actions-actions = إجراءات
actions-add-new = إضافة جديدة
actions-added-to-frequent-actions = أضيفت إلى الإجراءات المتكررة.
actions-all-actions = كل الإجراءات
actions-already-in-frequent-actions = موجود فعلًا في الإجراءات المتكررة.
actions-an-error-occurred = حدث خطأ: { $error }
actions-answer-again = الإجابة بـ«مجددًا»
actions-answer-easy = الإجابة بـ«سهل»
actions-answer-good = الإجابة بـ«جيد»
actions-answer-hard = الإجابة بـ«صعب»
actions-are-you-sure = هل أنت متأكد؟
actions-auto-advance = تقديم تلقائي
actions-bottom-bar = الشريط السفلي
actions-browse = تصفح
actions-card-buried = دُفِنت البطاقة
actions-card-info = معلومات البطاقة
actions-card-suspended = عُلِّقت البطاقة
actions-card-template = قالب البطاقة
actions-confirm-delete = تأكيد الحذف
actions-create = إنشاء
actions-current-audio-minus-5s = -5 ث للصوت الحالي
actions-current-audio-plus-5s = +5 ث للصوت الحالي
actions-custom-study-cant-be-used-on = لا يمكن استخدام ميزة الدراسة المخصصة في رزمة مفلترة.
actions-deck-statistics = إحصائيات الرزمة
actions-delete-note-and-its-cards = هل تريد حذف الملحوظة وبطاقاتها؟
actions-discard-changes = تجاهل التغييرات
actions-done = تم
actions-downloading = تنزيل...
actions-drag-here-to-remove = اسحب هنا للحذف
actions-draw = رسم
actions-file-invalid-or-corrupt = ملف تالف أو غير صالح.
actions-filtercram = فلترة/دراسة مكثفة
actions-filtered-deck = رزمة مفلترة { $num }
actions-flag-1 = مؤشر 1
actions-flag-1-red = مؤشر 1 (أحمر)
actions-flag-2 = مؤشر 2
actions-flag-2-orange = مؤشر 2 (برتقالي)
actions-flag-3 = مؤشر 3
actions-flag-3-green = مؤشر 3 (أخضر)
actions-flag-4 = مؤشر 4
actions-flag-4-blue = مؤشر 4 (أزرق)
actions-forgot-card = نسيت البطاقة
actions-frequent-actions = إجراءات متكررة
actions-leave-without-saving = هل تريد الخروج بدون الحفظ؟
actions-long-press-on-an-item-to = اضغط ضغطة مطولة على عنصر لتخصيصه.
actions-mark = تعليم
actions-mark-and-bury = تعليم ودفن
actions-mark-and-suspend = تعليم وتعليق
actions-marked = مُعلَّمة
actions-no-current-card = لا بطاقة حالية.
actions-no-load-restore-backup = لا يمكن تحميل مجموعتك. الرجاء استرجاع نسخة احتياطية من خلال نافذة التفضيلات.
# (http://example.com) does not appear to be...
actions-not-valid-link = لا يبدو رابط http/https صالحًا.
actions-note-and-its-cards-deleted = حُذفِت الملحوظة وبطاقاتها الـ { $count }.
actions-note-and-its-cards-suspended = عُلِّقت الملحوظة وبطاقاتها الـ{ $count }
actions-note-buried = دُفِنت الملحوظة
actions-note-marked-and-buried = عُلِّمت الملحوظة ودُفِنت
actions-nothing-to-undo = لا يوجد أي إجراء للتراجع عنه
actions-nothing-to-redo = لا يوجد أي إجراء لإعادة تطبيقه
actions-off = غير مفعل
actions-please-tap-the-in-the = الرجاء النقر على '?' في أعلى اليسار للبدء.
actions-processing = معالجة...
actions-record-voice = تسجيل صوت
actions-record-voice-menu = قائمة تسجيل الصوت
actions-reset-card = أعيد تعيين البطاقة
actions-revert = استرجاع
actions-review-undone = مراجعة البطاقات غير المكتملة
actions-scratchpad = المسودة
actions-scratchpad-size = حجم المسودة
actions-select-deck = تحديد الرزمة
actions-select-note-type = تحديد نوع الملحوظة
actions-show-answeranswer-good = إظهار الجواب/الإجابة بـ«جيد»
actions-study-options = خيارات الدراسة
actions-tools = أدوات
actions-tools-overlay = خلفية الأدوات
actions-top-bar = الشريط العلوي
actions-unbury-deck = نكش الرزمة
actions-undo = تراجع
actions-unmarked = غير مُعلَّم
actions-you-can-only-empty-a-filtered = تستطيع إفراغ رزمة مفلترة فقط.
actions-you-can-only-rebuild-a-filtered = تستطيع إعادة إنشاء رزمة مفلترة فقط.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = إفراغ
# create a filtered deck
actions-filter-short = فلترة
actions-add-short = إضافة
actions-answer-again-short = جواب م.
actions-answer-easy-short = جواب س.
actions-answer-good-short = جواب ج.
actions-answer-hard-short = جواب ص.
actions-auto-advance-short = تقديم تلقائي
actions-bottom-bar-short = شريط سفلي
actions-browse-short = تصفح
actions-bury-card-short = دفن بطاقة
actions-bury-note-short = دفن ملحوظة
actions-card-info-short = معلومات بطاقة
actions-card-template-short = قالب
actions-current-audio-minus-5s-short = -5 ث
actions-current-audio-plus-5s-short = +5 ث
actions-custom-study-short = مخصصة
actions-deck-statistics-short = إحصائيات الرزمة
actions-decks-short = رزم
actions-delete-note-short = حذف ملحوظة
actions-edit-short = تحرير
actions-mark-and-bury-short = تعليم ودفن
actions-mark-and-suspend-short = تعليم وتعليق
actions-mark-short = تعليم
actions-night-mode-short = ليلي
actions-off-short = غير مفعل
actions-pause-audio-short = إيقاف
actions-rebuild-short = إعادة إنشاء
actions-record-voice-short = تسجيل
actions-replay-voice-short = تشغيل صوت
actions-replay-audio-short = إعادة تشغيل
actions-reset-card-short = إعادة تعيين بطاقة
actions-scratchpad-short = المسودة
actions-scratchpad-size-short = حجم المسودة
actions-set-due-date-short = ضبط تاريخ الاستحقاق
actions-show-answer-short = إظهار الجواب
actions-show-answeranswer-good-short = إظهار/جيد
actions-study-options-short = خيارات الدراسة
actions-suspend-card-short = تعليق البطاقة
actions-suspend-note-short = تعليق الملحوظة
actions-tools-short = أدوات
actions-top-bar-short = شريط أ.
actions-unbury-deck-short = نكش
actions-undo-short = تراجع
actions-redo-short = إعادة تطبيق
