browsing-append = إلحاق
browsing-append-negated = إلحاق بصيغة منفية
browsing-card-updated = تم تحديث البطاقة
browsing-change-flag = تغيير المؤشر
browsing-clear-flag = مسح المؤشر
browsing-column-1 = عمود 1
browsing-column-2 = عمود 2
browsing-confirm-reset = تأكيد إعادة التعيين
browsing-dd-selected = { $part }/{ $total } محددة
browsing-due-dateorder = تاريخ/ترتيب الاستحقاق
browsing-due-reviews = مراجعات مستحقة
browsing-learning-cards = بطاقات التعلم
browsing-no-cards-are-selected = لم تحدد أي بطاقة.
browsing-note-created = أُنشئت الملحوظة
browsing-note-updated = حُدِّثت الملحوظة
browsing-note2 = ملحوظة:
browsing-questionandanswer = سؤال+جواب
browsing-repetitions = تكرارات
browsing-reset-cards = أعيد تعيين البطاقات
browsing-searching = بحث...
browsing-second-column-19 = العمود الثاني (1->9)
browsing-second-column-91 = العمود الثاني (9->1)
browsing-select-all = تحديد الكل
browsing-sort = فرز:
browsing-sort-order = ترتيب الفرز
browsing-tag = وسم:
