decks-a-deck-must-be-provided = يجب توفير رزمة.
decks-a-deck-named-already-exists = هناك رزمة باسم '%@' بالفعل.
decks-a-deck-with-that-name-already = هناك رزمة لها ذلك الاسم بالفعل.
decks-add-deck = إضافة رزمة
decks-add-empty-deck = إضافة رزمة فارغة
decks-addexport = إضافة/تصدير
decks-cannot-delete = تعذر الحذف
decks-card-limit = حد البطاقات
decks-cards-in-a-filtered-deck-cant = لا يمكن نقل البطاقات من رزمة مفلترة.
decks-custom-steps = خطوات مخصصة
decks-deck-exists = الرزمة موجودة
decks-deck-label = رزمة:
decks-deck-name = اسم الرزمة
decks-deck-options = خيارات الرزمة
decks-download-link = رابط التنزيل
decks-export-collection = تصدير المجموعة
decks-filtered-deck = رزمة مفلترة
decks-import-from-itunes = استيراد من iTunes
decks-invalid-deck-name = اسم رزمة غير صالح.
decks-link-to-apkg-file-to-import = رابط ملف .apkg الذي تريد استيراده:
decks-no-matches = لم يعثر على أي شيء
decks-return-by-delete = لإعادة كل البطاقات في الوقت نفسه، اسحب أعلى الرزمة الزرقاء في قائمة الرزم، أو احذفها.
decks-shared-deck-list = قائمة الرزم المشتركة
decks-sync = مزامنة
decks-synchronize = مزامنة
decks-the-default-deck-cannot-be-deleted = لا يمكن حذف الرزمة الافتراضية.
decks-the-provided-deck-does-not-exist = لا توجد الرزمة الموفرة.
decks-the-search-you-provided-did-not = لا تطابق عبارة بحثك أي بطاقات.
decks-will-be-returned = ستعود البطاقات إلى رزمها الأصلية عندما تجيب عنها.
