deck-options-add-options-group = إضافة مجموعة خيارات
deck-options-answer-time-cap = حد وقت الإجابة
deck-options-bury-related-new-cards = دفن البطاقات الجديدة ذات الصلة
deck-options-bury-related-reviews = دفن المراجعات ذات الصلة
deck-options-defaults = افتراضيات
deck-options-delete-options-full-sync = سيمنع حذف مجموعة الخيارات هذه أي تغييرات من أن تُدمج من أجهزة أخرى عند المزامنة التالية. هل تريد الاستكمال؟
deck-options-display-in-order-added = عرض حسب تاريخ الإضافة
deck-options-display-in-random-order = عرض بترتيب عشوائي
deck-options-full-sync-required = تلزم مزامنة كاملة
deck-options-group-name = اسم المجموعة
deck-options-max-new-per-day = عدد البطاقات الجديدة الأقصى في اليوم
deck-options-max-reviews-per-day = عدد المراجعات الأقصى في اليوم
deck-options-new-cards = البطاقات الجديدة
deck-options-options-group = مجموعة الخيارات
deck-options-replay-q-audio-in-answer = إعادة تشغيل أصوات السؤال في جانب الجواب
deck-options-reset-all-settings-to-defaults = هل تريد إعادة تعيين كل الإعدادات إلى الإعدادات الافتراضية؟
deck-options-restore-defaults = استعادة الافتراضيات
deck-options-steps = الخطوات
