preferences-about = حول
preferences-always-duck-and-ignore-mute = إضعاف وتجاهل الوضع الصامت دائمًا
preferences-answer-keeps-zoom = تبقي الإجابة على مستوى التكبير
preferences-answer-side = جانب السؤال
preferences-audio-buttons = أزرار الصوت
preferences-auto-advance-answer-action = إجراء الإجابة
preferences-auto-advance-answer-seconds = وقت الإجابة بالثانية
preferences-auto-advance-auto-advance-to-start = لبدء التقديم التلقائي، استخدم إجراء «التقديم التلقائي».
preferences-auto-advance-do-nothing = لا تفعل شيئًا
preferences-auto-advance-question-seconds = مدة عرض السؤال بالثانية
preferences-auto-advance-show-reminder = إظهار المُذكّر
preferences-auto-advance-wait-for-audio = انتظار الصوت
preferences-backup-available-backups = النسخ الاحتياطية المتاحة
preferences-backup-create-now = إنشاء الآن
preferences-backup-maximum-backups = عدد النسخ الاحتياطية الأقصى
preferences-backup-minutes-between-backups = الدقائق بين النسخ الاحتياطية
preferences-backup-revert-to-backup = استرجاع نسخة احتياطية
preferences-backup-revert-to-backup-confirm = هل تريد استرجاع { $backup }؟ ستفقد أي تغييرات أجريتها منذ هذه النسخة الاحتياطية.
preferences-backup-reverted-to-backup = استرجعت النسخة الاحتياطية.
preferences-bottom-bar-size = حجم الشريط السفلي
preferences-bottom-center = منتصف الأسفل
preferences-bottom-left = يسار الأسفل
preferences-bottom-right = يمين الأسفل
preferences-button-d = زر { $num }
preferences-collection-day-starts = يبدأ اليوم
preferences-collection-learn-ahead-minutes = دقائق التعلم المبكر
preferences-collection-mix = خلط
preferences-collection-new-first = الجديد أولًا
preferences-collection-newreview-order = ترتيب البطاقات الجديدة/المراجعات
preferences-collection-reviews-first = المراجعات أولًا
preferences-double-tap-prevention = منع النقر المزدوج
preferences-drawing-screen-ignores-fingers = تتجاهل نقرات الأصابع في شاشة الرسم
preferences-feedback-ticks = إشارات رد الفعل
preferences-fine = جيد
preferences-force-sync-confirm = هل تريد فرض مزامنة باتجاه واحد؟ ستفقد كل التغييرات في جانب واحد.
preferences-full-sync = مزامنة كاملة
preferences-gamepad-button-mapping = توزيع الأزرار
preferences-gamepad-menu-button = قائمة
preferences-gamepads = لوحات التحكم بالألعاب
preferences-height = ارتفاع
preferences-huge = ضخم
preferences-ignore-fingers = تجاهل نقرات الأصابع
preferences-interrupt-current-audio = مقاطعة الصوت الحالي
preferences-large = كبير
preferences-left = يسار
# gamepad
preferences-left-shoulder = أزرار التحكم الخلفي اليسرى
# gamepad
preferences-left-thumbstick-button = عصا الإبهام اليسرى
# gamepad
preferences-left-trigger = المفتاح الأيسر
preferences-logged-in-as = مسجل كـ:
preferences-long = طويل
preferences-mid-center = منتصف المركز
preferences-mid-left = منتصف اليسار
preferences-mid-right = منتصف اليمين
preferences-never-type-answer = لا تدخل الجواب أبدًا
preferences-never-show-scratchpad = عدم إظهار المسودة
preferences-never-show-scratchpad-enabled = خيار عدم إظهار المسودة مفعل من شاشة التفضيلات.
preferences-next-times = الأزمنة التالية
preferences-normal = عادي
preferences-notifications = تنبيهات
preferences-notifications-alert-time = وقت التنبيه
preferences-notifications-alert-when-due = تنبيه عند الاستحقاق
preferences-notifications-app-icon-shows-due-count = تظهر أيقونة التطبيق عدد البطاقات المستحقة
preferences-notifications-settings-app-enable-notifications = اذهب إلى إعدادات iOS، وابحث عن قسم أنكي، وفعّل التنبيهات، والوسوم، والإنذارات.
preferences-pen-size = حجم القلم
preferences-question-side = جانب السؤال
preferences-remaining-count = عدد البطاقات المتبقية
preferences-right = يمين
# gamepad
preferences-right-shoulder = أزرار التحكم الخلفي اليمنى
# gamepad
preferences-right-thumbstick-button = عصا الإبهام اليمنى
# gamepad
preferences-right-trigger = المفتاح الأيمن
preferences-scratchpad-below-buttons = المسودة أسفل الأزرار
preferences-scratchpad-transparency = شفافية المسودة
preferences-scratchpad-transparency-full = كامل
preferences-scratchpad-transparency-medium = متوسط
preferences-scratchpad-transparency-none = لا شيء
preferences-scratchpad-transparency-slight = صغير
preferences-shake-action = إجراء الهز
preferences-short = قصير
preferences-show-bottom-bar = إظهار الشريط السفلي
preferences-show-grid = إظهار الشبكة
preferences-show-top-bar = أظهار الشريط العلوي
preferences-small = صغير
preferences-swipe-down = سحب للأسفل
preferences-swipe-left = سحب لليسار
preferences-swipe-right = سحب لليمين
preferences-swipe-up = سحب للأعلى
preferences-swipes = سحبات
preferences-swipes-must-begin-from-the-far = يجب أن تبدأ السحبات من أقصى يسار أو يمين الشاشة.
preferences-sync-sounds-images = مزامنة الأصوات والصور
preferences-syncing = مزامنة
preferences-tap-to-sync = لتفعيل المزامنة، انقر زر مزامنة في شاشة قائمة الرزم.
preferences-taps = نقرات
preferences-theme-bar-style = تنسيق الشريط
preferences-theme-black = أسود

preferences-theme-dark-translucent = داكن وشفاف
preferences-theme-force-off = إيقاف إجباري
preferences-theme-force-on = تفعيل إجباري
preferences-theme-light-translucent = فاتح وشفاف
preferences-theme-night-mode-desc = يغمق الوضع الليلي الواجهة، ويعرض البطاقات كأبيض على أسود.
preferences-theme-night-mode-same-as-system = مثل النظام
preferences-theme-slate = رمادي داكن
preferences-thick = ثخين
preferences-tools-overlay-button = زر خلفية الأدوات
preferences-tools-overlay-position = موضع خلفية الأدوات
preferences-top-center = أعلى الوسط
preferences-top-left = أعلى اليسار
preferences-top-right = أعلى اليمين
preferences-undo-clears-all = تراجع عن مسح الكل
preferences-when-answer-shown = عند إظهار الجواب
preferences-when-question-shown = عند إظهار السؤال
preferences-you-have-been-logged-out = لقد سجلت الخروج.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = حجم الصورة الأقصى (الجانب الأطول)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = تغيير حجم الصور عند اللصق
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = تحويل علامات الاقتباس الذكية والشرطات
preferences-editing-crop-camera-photos = قص صور الكاميرا
