profiles-a-profile-with-that-name-already = هناك ملف شخصي له ذلك الاسم بالفعل.
profiles-add-profile = إضافة ملف شخصي
profiles-creating-backup = إنشاء نسخة احتياطية...
profiles-finishing-backup = إنهاء النسخ الاحتياطي...
profiles-please-provide-some-text-avoiding-symbols = الرجاء إدخال نص ما، مع تجنب الرموز والشرطات التحتية.
profiles-please-select-another-profile-first = الرجاء تحديد ملف شخصي آخر أولًا.
profiles-profile-name = اسم الملف الشخصي
profiles-rename-profile = تغيير اسم الملف الشخصي
profiles-unable-to-open-safari-please = تعذر فتح سفاري - تحقق من إعدادات الرقابة الأبوية.
profiles-welcome = مرحبًا!
