actions-actions = 動作
actions-add-new = 新增
actions-added-to-frequent-actions = 已新增到常用動作。
actions-all-actions = 所有動作
actions-already-in-frequent-actions = 已在常用動作中。
actions-an-error-occurred = 發生錯誤: %@
actions-answer-again = 回答「重來」
actions-answer-easy = 回答「簡單」
actions-answer-good = 回答「良好」
actions-answer-hard = 回答「困難」
actions-are-you-sure = 您確定嗎？
actions-auto-advance = 自動前進
actions-auto-advance-short = 自動前進
actions-bottom-bar = 底部列
actions-bottom-bar-short = 底列
actions-browse = 瀏覽
actions-bury-card-short = 暫停卡片
actions-bury-note-short = 暫停筆記
actions-card-buried = 已暫停卡片
actions-card-info = 卡片資訊
actions-card-info-short = 卡片資訊
actions-card-suspended = 已擱置卡片
actions-card-template = 卡片模板
actions-confirm-delete = 確定刪除
actions-create = 建立
actions-current-audio-minus-5s = 倒轉當前音訊 5 秒
actions-current-audio-minus-5s-short = -5 秒
actions-current-audio-plus-5s = 快轉當前音訊 5 秒
actions-current-audio-plus-5s-short = +5 秒
actions-custom-study-cant-be-used-on = 篩選牌組無法使用自訂學習功能。
actions-custom-study-short = 自訂
actions-deck-statistics = 牌組統計資料
actions-deck-statistics-short = 牌組統計
actions-delete-note-and-its-cards = 刪除筆記和其卡片？
actions-delete-note-short = 刪除
actions-discard-changes = 捨棄變更
actions-done = 完成
actions-downloading = 下載中...
actions-drag-here-to-remove = 拖曳到這裡來移除。
actions-draw = 繪製
actions-file-invalid-or-corrupt = 檔案無效或損毀。
actions-filtercram = 篩選/填鴨式學習
actions-filtered-deck = 篩選牌組%i
actions-flag-1 = 旗標 1
actions-flag-1-red = 旗標 1 (紅色)
actions-flag-2 = 旗標 2
actions-flag-2-orange = 旗標 2 (橙色)
actions-flag-3 = 旗標 3
actions-flag-3-green = 旗標 3 (綠色)
actions-flag-4 = 旗標 4
actions-flag-4-blue = 旗標 4 (藍色)
actions-forgot-card = 忘記卡片
actions-frequent-actions = 常用動作
actions-how-many-days-in-the-future = 今後幾天？
actions-invalid-number-of-days = 無效天數。
actions-leave-without-saving = 離開而不儲存？
actions-long-press-on-an-item-to = 長按項目來自訂
actions-mark = 標記
actions-mark-and-bury = 標記+暫停
actions-mark-and-bury-short = 標&暫
actions-mark-and-suspend = 標記+擱置
actions-mark-and-suspend-short = 標&擱
actions-marked = 已標記
actions-night-mode-short = 夜晚
actions-no-current-card = 沒有當前卡片。
actions-no-load-restore-backup = 無法載入您的集合。請在「偏好設定」>「備份」中恢復備份。
actions-not-valid-link = 似乎不是有效的http或https連結。
actions-note-and-its-cards-deleted = 已刪除筆記和與其關聯的%i張卡片
actions-note-and-its-cards-suspended = 已擱置的筆記和與其關聯的 %i 張卡片
actions-note-buried = 已暫停筆記
actions-note-marked-and-buried = 已標記並暫停筆記
actions-nothing-to-undo = 沒有可復原的動作
actions-off = 關閉
actions-pause-audio-short = 暫停
actions-please-tap-the-in-the = 請按一下左上的「？」來開始。
actions-processing = 處理中...
actions-record-voice = 錄製聲音
actions-record-voice-short = 錄製
actions-replay-audio-short = 重播
actions-reset-card = 重設卡片
actions-reset-card-short = 重設卡片
actions-revert = 還原
actions-review-undone = 已復原複習
actions-scratchpad = 速記本
actions-scratchpad-short = 速記本
actions-scratchpad-size = 速記本大小
actions-scratchpad-size-short = 速記本大小
actions-select-deck = 選取牌組
actions-select-note-type = 選取筆記類型
actions-set-due-date = 設定到期日
actions-set-due-date-short = 到期日
actions-show-answer-short = 答案
actions-show-answeranswer-good = 顯示答案/回答「良好」
actions-show-answeranswer-good-short = 顯示/「良好」
actions-study-options = 學習選項
actions-study-options-short = 學習選項
actions-suspend-card-short = 擱置卡片
actions-suspend-note-short = 擱置筆記
actions-tools = 工具
actions-tools-overlay = 工具視窗
actions-top-bar = 頂端列
actions-unbury-deck = 取消暫停牌組
actions-unbury-deck-short = 取消暫停
actions-undo = 復原
actions-unmarked = 取消標記
actions-you-can-only-empty-a-filtered = 您只能清空篩選牌組。
actions-you-can-only-rebuild-a-filtered = 您只能重建篩選牌組。
