custom-study-any-tag = 任何
custom-study-available = { $num }可用
custom-study-cant-extend-limits-no-extra = 無法擴展限制——沒有額外的卡片可用。
custom-study-cram-seen-cards-with-certain-tags = 對貼有特定標籤的卡片進行填鴨式學習
custom-study-days-to-look-ahead = 提前天數
custom-study-days-to-look-back = 延後天數
custom-study-exclude-cards-with-tag = 排除貼有標籤的卡片
custom-study-extra-new-cards = 額外的新卡片
custom-study-extra-review-cards = 額外的待複習卡片
custom-study-include-cards-with-tag = 包含貼有標籤的卡片
custom-study-learn-new-cards-with-certain-tags = 學習貼有特定標籤的新卡片
custom-study-loading = 讀取中...
custom-study-max-cards-to-gather = 堆積卡片上限
custom-study-no-tags = 無
custom-study-no-tags-available = 沒有可用的標籤
custom-study-preview-all-cards-with-certain-tags = 預覽所有貼有特定標籤的卡片
custom-study-review-due-cards-with-certain-tags = 複習貼有特定標籤的到期卡片
custom-study-search-matches = { $num }符合搜尋
custom-study-study-type = 學習類型
custom-study-the-selected-options-did-not-match = 沒有任何卡片符合已選取的選項。
