editing-bold = 粗體
editing-cancel-and-lose-any-unsaved-changes = 取消並捨棄所有未儲存更動
editing-cant-edit-original-image-data = 無法編輯——找不到原始圖像資料。
editing-card-returned-to-new-card-queue = 卡片已回到新卡片佇列。
editing-card-unsuspended = 已取消擱置卡片
editing-from-camera = 來自相機
editing-from-file = 來自檔案
editing-from-photos = 來自照片
editing-italic = 斜體
# keyboard shortcut description
editing-next-cloze = 下一個克漏字
editing-next-field = 下一個欄位
editing-note-deleted = 已刪除筆記
editing-note-suspended = 已擱置筆記
# (Note) type: 
editing-note-type-prompt = 類型：
editing-note-unsuspended = 已取消擱置筆記
# keyboard shortcut description
editing-same-cloze = 相同的克漏字
editing-the-first-field-must-not-be = 第一個欄位不能是空的。
editing-unable-to-obtain-image = 無法取得圖像
editing-unable-to-read-file = 無法讀取檔案
editing-underline = 底線
editing-unexpected-file-extension = 非預期的副檔名：
editing-unexpected-rich-text-format-please = 未預期的RTF格式——請嘗試複製貼上。
editing-unexpected-status-code = 未預期的狀態代碼：
editing-unsuspend-card = 取消擱置卡片
editing-unsuspend-note = 取消擱置筆記
editing-discard-changes-question = 捨棄所作更動
editing-discard = 捨棄
editing-keep-editing = 繼續編輯
