exporting-collection-saved-to-itunes = 已將集合儲存到iTunes。
exporting-export-to-itunes = 匯出到iTunes
exporting-export-to-share-sheet = 匯出到...
exporting-exporting = 匯出中...
exporting-include-media2 = 包含媒體檔
exporting-media-files-exported-d = 已匯出媒體檔：{ $count }...
