importing-delete-imported-file = 要刪除已匯入的檔案嗎？
importing-import-complete = 匯入完成。
importing-importing = 匯入中...
importing-no-apkg-or-colpkg-files-were = iTunes中找不到.apkg或.colpkg檔
importing-overwrite-via-import = 要使用匯入的檔案覆寫整個集合嗎？此動作無法復原。
importing-please-choose-a-file = 請選擇一個檔案。
importing-processed-media-files-d = 已處理媒體檔：{ $count }...
importing-replace-collection = 取代集合
importing-file-not-downloaded = 請從 iCloud 下載檔案後重新嘗試匯入檔案。
