preferences-about = 關於
preferences-always-duck-and-ignore-mute = 總是弱化背景音量並忽略系統靜音
preferences-answer-keeps-zoom = 答案保持縮放
preferences-answer-side = 答案面
preferences-audio-buttons = 音訊按鈕
preferences-auto-advance-answer-action = 答案顯示後動作
preferences-auto-advance-answer-seconds = 答案顯示時間
preferences-auto-advance-auto-advance-to-start = 要開始自動前進到下一張卡片，請使用「自動前進」動作。
preferences-auto-advance-do-nothing = 不進行動作
preferences-auto-advance-question-seconds = 問題顯示時間
preferences-auto-advance-show-reminder = 顯示提醒
preferences-auto-advance-wait-for-audio = 等待音訊播放
preferences-backup-available-backups = 可用備份
preferences-backup-create-now = 立即備份
preferences-backup-maximum-backups = 備份數量上限
preferences-backup-minutes-between-backups = 備份間隔（分鐘）
preferences-backup-revert-to-backup = 還原備份
preferences-backup-revert-to-backup-confirm = 是否還原到「{ $backup }」？備份後的任何更動都將遺失。
preferences-backup-reverted-to-backup = 已還原到備份。
preferences-bottom-bar-size = 底部列大小
preferences-bottom-center = 正下方
preferences-bottom-left = 左下方
preferences-bottom-right = 右下方
preferences-button-d = 按鈕{ $num }
preferences-collection-day-starts = 每日起始時間
preferences-collection-learn-ahead-minutes = 提前學習（分鐘）
preferences-collection-mix = 混合
preferences-collection-new-first = 新卡片優先
preferences-collection-newreview-order = 新卡片/複習卡順序
preferences-collection-reviews-first = 複習卡優先
preferences-double-tap-prevention = 防止誤觸間隔
preferences-drawing-screen-ignores-fingers = 繪製畫面忽略手指
preferences-feedback-ticks = 顯示回答勾號
preferences-fine = 細
preferences-force-sync-confirm = 是否強制單向同步？其中一方所作的更動將全部遺失。
preferences-full-sync = 完整同步
preferences-gamepad-button-mapping = 按鈕對應
preferences-gamepad-menu-button = 選單
preferences-gamepads = 遊戲手把控制
preferences-height = 高度
preferences-huge = 巨大
preferences-ignore-fingers = 忽略手指
preferences-interrupt-current-audio = 中斷正在播放的音訊
preferences-large = 大
preferences-left = 左對齊
# gamepad
preferences-left-shoulder = LS
# gamepad
preferences-left-thumbstick-button = 左搖桿按鈕
# gamepad
preferences-left-trigger = LT
preferences-logged-in-as = 已登入帳號：
preferences-long = 長
preferences-mid-center = 正中央
preferences-mid-left = 左中央
preferences-mid-right = 右中央
preferences-never-type-answer = 永不輸入答案
preferences-never-show-scratchpad = 永不顯示速記本
preferences-never-show-scratchpad-enabled = 「永不顯示速記本」已在偏好設定中啟用。
preferences-next-times = 下次答題時間
preferences-normal = 正常
preferences-notifications = 通知
preferences-notifications-alert-time = 通知時間
preferences-notifications-alert-when-due = 到期時通知
preferences-notifications-app-icon-shows-due-count = 在 App 圖示上顯示到期卡片數量
preferences-notifications-settings-app-enable-notifications = 請前往 iOS 設定，找到「Anki」，並啟用允許通知、標記和提示。
preferences-pen-size = 筆跡大小
preferences-question-side = 問題面
preferences-remaining-count = 剩餘數量
preferences-right = 右對齊
# gamepad
preferences-right-shoulder = RS
# gamepad
preferences-right-thumbstick-button = 右搖桿按鈕
# gamepad
preferences-right-trigger = RT
preferences-scratchpad-below-buttons = 速記本置於按鈕下方
preferences-scratchpad-transparency = 速記本透明度
preferences-scratchpad-transparency-full = 完整
preferences-scratchpad-transparency-medium = 中等
preferences-scratchpad-transparency-none = 無
preferences-scratchpad-transparency-slight = 輕微
preferences-shake-action = 搖動手機動作
preferences-short = 短
preferences-show-bottom-bar = 顯示底部列
preferences-show-grid = 顯示格線
preferences-show-top-bar = 顯示頂端列
preferences-small = 小
preferences-swipe-down = 下滑
preferences-swipe-left = 左滑
preferences-swipe-right = 右滑
preferences-swipe-up = 上滑
preferences-swipes = 滑動手勢
preferences-swipes-must-begin-from-the-far = 必須從螢幕最左或最右側開始滑動手勢。
preferences-sync-sounds-images = 同步音訊和圖像
preferences-syncing = 同步
preferences-tap-to-sync = 在牌組清單畫面按一下「同步」按鈕來啟用同步。
preferences-taps = 點按手勢
preferences-theme = 佈景主題
preferences-theme-bar-style = 列樣式
preferences-theme-black = 黑色
preferences-theme-dark-translucent = 深色半透明
preferences-theme-force-off = 總是關閉
preferences-theme-force-on = 總是啟用
preferences-theme-light-translucent = 淺色半透明
preferences-theme-night-mode-desc = 夜間模式會使介面變暗，卡片將顯示為黑底白字。
preferences-theme-night-mode-same-as-system = 跟隨系統
preferences-theme-slate = 深灰
preferences-thick = 粗
preferences-tools-overlay-button = 工具視窗按鈕
preferences-tools-overlay-position = 工具視窗位置
preferences-top-center = 正上方
preferences-top-left = 左上方
preferences-top-right = 右上方
preferences-undo-clears-all = 復原按鈕將清除所有筆跡
preferences-when-answer-shown = 顯示答案面時
preferences-when-question-shown = 顯示問題面時
preferences-you-have-been-logged-out = 已登出。
preferences-editing = 編輯
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = 圖像最大尺寸（長邊）
# whether to shrink images when pasting
preferences-editing-resize-on-paste = 貼上時調整圖像大小
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = 轉換智慧型引號和破折號
preferences-editing-crop-camera-photos = 裁切相機照片
