profiles-a-profile-with-that-name-already = 已存在名稱相同的設定檔。
profiles-add-profile = 新增設定檔
profiles-finishing-backup = 正在完成備份...
profiles-please-provide-some-text-avoiding-symbols = 請輸入一些文字，避免輸入標點符號和底線。
profiles-please-select-another-profile-first = 請先選取另一個設定檔。
profiles-profile-name = 設定檔名稱
profiles-rename-profile = 重新命名設定檔
profiles-unable-to-open-safari-please = 無法打開Safari - 請檢查分級保護控制。
profiles-welcome = 歡迎！
