studying-answer-time-elapsed = 已過回答時間
studying-auto-advance-starting = 正在開始自動前進
studying-auto-advance-stopped = 已停止自動前進
studying-have-ready-to-study = 您有 %@可以來學習。
studying-please-run-empty-cards-on-the = 請在電腦版執行「空白卡片」。
studying-replay-card = 重播卡片
studying-replay-voice = 重播聲音
studying-rescheduled-card = 將卡片重新排程。
studying-type-in-the-answer = 輸入答案
