actions-actions = Действия
actions-add-new = Добавить новую
actions-added-to-frequent-actions = Добавлено в частые действия.
actions-all-actions = Все действия
actions-already-in-frequent-actions = Уже находится в частых действиях.
actions-an-error-occurred = Произошла ошибка: { $error }
actions-answer-again = Ответить «снова»
actions-answer-easy = Ответить «легко»
actions-answer-good = Ответить «хорошо»
actions-answer-hard = Ответить «трудно»
actions-are-you-sure = Вы уверены?
actions-auto-advance = Автопросмотр
actions-bottom-bar = Нижняя панель
actions-browse = Список
actions-card-buried = Карточка отложена
actions-card-suspended = Карточка исключена
actions-card-template = Шаблон карточки
actions-confirm-delete = Подтверждение удаления
actions-create = Создать
actions-current-audio-minus-5s = Текущее аудио -5с
actions-current-audio-plus-5s = Текущее аудио +5с
actions-custom-study-cant-be-used-on = Пользовательская учеба не может быть использована на отфильтрованной колоде.
actions-deck-statistics = Статистика колоды
actions-delete-note-and-its-cards = Удалить записи и ее карточки?
actions-discard-changes = Отменить изменения
actions-done = Готово
actions-downloading = Скачивание...
actions-drag-here-to-remove = Перетащите сюда для удаления
actions-draw = Рисовать
actions-file-invalid-or-corrupt = Файл неверен или поврежден.
actions-filtercram = Фильтр/Зубрить
actions-filtered-deck = Отсортированная колода { $num }
actions-forgot-card = Карточка забыта
actions-frequent-actions = Частые действия
actions-leave-without-saving = Выйти без сохранения?
actions-long-press-on-an-item-to = Удерживайте на объекте для кастомизации.
actions-mark = Пометить
actions-mark-and-bury = Пометить и отложить
actions-mark-and-suspend = Пометить и исключить
actions-marked = Помеченные
actions-no-current-card = Текущая карточка отсутствует.
actions-no-load-restore-backup = Вашу коллекцию загрузить не удалось. Восстановите резервную копию с помощью меню настроек,
# (http://example.com) does not appear to be...
actions-not-valid-link = не является действительной ссылкой http/https.
actions-note-and-its-cards-deleted = Запись вместе с ее { $count } карточками удалена
actions-note-and-its-cards-suspended = Запись вместе с ее { $count } карточками исключена
actions-note-buried = Запись отложена
actions-note-marked-and-buried = Запись помечена и отложена
actions-nothing-to-undo = Нечего отменять
actions-nothing-to-redo = Нечего повторять
actions-off = Выкл.
actions-please-tap-the-in-the = Коснитесь '?' в левом верху для того, чтобы начать.
actions-processing = Обрабатывается...
actions-record-voice = Записать голос
actions-record-voice-menu = Меню записи голоса
actions-reset-card = Сбросить карточку
actions-revert = Вернуть
actions-review-undone = Просмотр отменен
actions-scratchpad = Блокнот
actions-scratchpad-size = Размер блокнота
actions-select-deck = Выбрать колоду
actions-select-note-type = Выбрать тип записи
actions-show-answeranswer-good = Показать ответ/ответить «хорошо»
actions-study-options = Настройки учебы
actions-tools = Инструменты
actions-tools-overlay = Оверлей инструментов
actions-top-bar = Верхняя панель
actions-unbury-deck = Вернуть колоду
actions-undo = Отмена
actions-unmarked = Выделение отменено
actions-you-can-only-empty-a-filtered = Можно очищать только отфильтрованную колоду.
actions-you-can-only-rebuild-a-filtered = Можно реконструировать только отфильтрованную колоду.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Очистить
# create a filtered deck
actions-filter-short = Фильтр
actions-add-short = Добавить
actions-answer-again-short = Ans.A
actions-answer-easy-short = Ans.E
actions-answer-good-short = Ans.G
actions-answer-hard-short = Ans.H
actions-auto-advance-short = Автопросм.
actions-bottom-bar-short = Ниж.П
actions-browse-short = Список
actions-bury-card-short = Отл.К
actions-bury-note-short = Отл.З
actions-card-info-short = Свед.К
actions-card-template-short = Шаблон
actions-current-audio-minus-5s-short = -5с
actions-current-audio-plus-5s-short = +5с
actions-custom-study-short = Своя
actions-deck-statistics-short = Стат.К
actions-decks-short = Колоды
actions-delete-note-short = Удал
actions-edit-short = Править
actions-mark-and-bury-short = Пом&Отл
actions-mark-and-suspend-short = Пом&Искл
actions-mark-short = Пометить
actions-night-mode-short = Ночь
actions-off-short = Выкл.
actions-pause-audio-short = Приостановить
actions-rebuild-short = Перестроить
actions-record-voice-short = Записать
actions-replay-voice-short = Воспр.Г
actions-replay-audio-short = Перевоспроизведение
actions-reset-card-short = Сбр.К
actions-scratchpad-short = Блок.
actions-scratchpad-size-short = Разм. блок.
actions-set-due-date-short = Уст.Дату
actions-show-answer-short = Пок.Отв.
actions-show-answeranswer-good-short = Показать/«хорошо»
actions-study-options-short = Нас.уч.
actions-suspend-card-short = Искл.К
actions-suspend-note-short = Искл.З
actions-tools-short = Инструменты
actions-top-bar-short = T.Bar
actions-unbury-deck-short = Вернуть
actions-undo-short = Отмена
actions-redo-short = Повторить
