decks-a-deck-must-be-provided = Должна быть предоставлена колода.
decks-a-deck-named-already-exists = Колода с именем '{ $name }' уже существует.
decks-a-deck-with-that-name-already = Колода с этим именем уже существует.
decks-add-deck = Добавить колоду
decks-add-empty-deck = Добавить пустую колоду
decks-addexport = Добав./экспорт.
decks-cannot-delete = Невозможно удалить
decks-card-limit = Лимит карточек
decks-cards-in-a-filtered-deck-cant = Карточки отсортированной колоды нельзя переместить.
decks-custom-steps = Свои шаги
decks-deck-exists = Колода существует
decks-deck-label = Колода:
decks-deck-name = Название колоды
decks-deck-options = Настройки колоды
decks-download-link = Прямая ссылка
decks-export-collection = Экспортировать коллекцию
decks-filtered-deck = Отсортированная колода
decks-import-from-itunes = Импортировать из iTunes
decks-invalid-deck-name = Неверное название колоды.
decks-link-to-apkg-file-to-import = Ссылка на .apkg файл для импорта:
decks-no-matches = Нет совпадений
decks-return-by-delete = Чтобы вернуть все карточки разом, смахните налево над синей колодой в списке, и удалите ее.
decks-shared-deck-list = Список общих колод
decks-sync = Синхронизация
decks-synchronize = Синхронизировать
decks-the-default-deck-cannot-be-deleted = Колода «По умолчанию» не может быть удалена.
decks-the-provided-deck-does-not-exist = Такая колода не существует.
decks-the-search-you-provided-did-not = Карточек по данному запросу найдено не было.
decks-will-be-returned = После ответа карточки будут возвращены в изначальную колоду.
