deck-options-add-options-group = Добавить набор настроек
deck-options-answer-time-cap = Времени на ответ
deck-options-bury-related-new-cards = Отложить связанные новые карты
deck-options-bury-related-reviews = Отложить связанные повторения
deck-options-defaults = По умолчанию
deck-options-delete-options-full-sync = Удаление этого набора настроек предотвратит слияние изменений с других устройств при следующей синхронизации. Продолжить?
deck-options-display-in-order-added = Показывать по порядку добавления
deck-options-display-in-random-order = Показывать в случайном порядке
deck-options-full-sync-required = Требуется полная синхронизация
deck-options-group-name = Название набора
deck-options-max-new-per-day = Макс. новых за день
deck-options-max-reviews-per-day = Макс. повторений за день
deck-options-new-cards = Новые карточки
deck-options-options-group = Набор настроек
deck-options-replay-q-audio-in-answer = Повторить аудио в ответе
deck-options-reset-all-settings-to-defaults = Сбросить все настройки до значений по умолчанию?
deck-options-restore-defaults = Восстановить значения по умолчанию
deck-options-steps = Шаги
