exporting-collection-saved-to-itunes = Коллекция сохранена в iTunes.
exporting-export-to-itunes = Экспортировать в iTunes
exporting-export-to-share-sheet = Поделиться
exporting-exporting = Идет экспорт...
exporting-include-media2 = Включить медиафайлы
exporting-media-files-exported-d = Медиафайлов экспортировано: %d...
