importing-delete-imported-file = Удалить импортированный файл?
importing-import-complete = Импортирование завершено.
importing-importing = Идет импорт...
importing-no-apkg-or-colpkg-files-were = .apkg или .colpkg файлы не были найдены в iTunes
importing-overwrite-via-import = Перезаписать всю коллекцию импортированным файлом? Это действие нельзя отменить.
importing-please-choose-a-file = Выберите файл.
importing-processed-media-files-d = Обработано медиафайлов: { $count }...
importing-replace-collection = Заменить коллекцию
importing-file-not-downloaded = Загрузите файл из iCloud, а затем ипортируйте его снова
