preferences-about = О приложении
preferences-always-duck-and-ignore-mute = Игнорировать бесшумный режим
preferences-answer-keeps-zoom = Ответ сохраняет приближ.
preferences-answer-side = Сторона ответа
preferences-audio-buttons = Кнопки звука
preferences-auto-advance-answer-action = Действие
preferences-auto-advance-answer-seconds = Секунд для ответа
preferences-auto-advance-auto-advance-to-start = Для автоматического просмотра карточек используйте 'Автопросмотр'.
preferences-auto-advance-do-nothing = Бездействовать
preferences-auto-advance-question-seconds = Секунд для вопроса
preferences-auto-advance-show-reminder = Показать напоминание
preferences-auto-advance-wait-for-audio = Ждать аудио
preferences-backup-available-backups = Доступные резервные копии
preferences-backup-create-now = Создать сейчас
preferences-backup-maximum-backups = Макс. число копий
preferences-backup-minutes-between-backups = Минут между копиями
preferences-backup-revert-to-backup = Вернуть до копии
preferences-backup-revert-to-backup-confirm = Вернуться к { $backup }? Все изменения с последней резервной копии будут утеряны.
preferences-backup-reverted-to-backup = Возвращено к копии.
preferences-bottom-bar-size = Размер нижней панели
preferences-bottom-center = Снизу по середине
preferences-bottom-left = Снизу слева
preferences-bottom-right = Снизу справа
preferences-button-d = Кнопка { $num }
preferences-collection-day-starts = День начинается в
preferences-collection-learn-ahead-minutes = Минут изучения наперед
preferences-collection-mix = Перемешать
preferences-collection-new-first = Сначала новые
preferences-collection-newreview-order = Порядок новых/просмотров
preferences-collection-reviews-first = Сначала просмотры
preferences-double-tap-prevention = Предотвращение двойного касания
preferences-drawing-screen-ignores-fingers = Игнорирование пальцев на экране рисования
preferences-feedback-ticks = Галочка при ответе
preferences-fine = Тонкий
preferences-force-sync-confirm = Принудительно синхронизировать в одну сторону? Все изменения с одной из сторон будут потеряны.
preferences-full-sync = Полная синхронизация
preferences-gamepad-button-mapping = Назначение кнопок
preferences-gamepad-menu-button = Меню
preferences-gamepads = Геймпады
preferences-height = Высота
preferences-huge = Огромный
preferences-ignore-fingers = Игнорировать пальцы
preferences-interrupt-current-audio = Прерывать текущее аудио
preferences-large = Большой
preferences-left = Слева
preferences-left-shoulder = Левый бампер
preferences-left-thumbstick-button = Кнопка левого стика
preferences-left-trigger = Левый триггер
preferences-logged-in-as = Выполнен вход как:
preferences-long = Долгое
preferences-mid-center = По середине
preferences-mid-left = Слева по середине
preferences-mid-right = Справа по середине
preferences-never-type-answer = Никогда не вписывать ответ
preferences-next-times = Время до следующего раза
preferences-normal = По умолчанию
preferences-notifications = Уведомления
preferences-notifications-alert-time = Время оповещения
preferences-notifications-alert-when-due = Опов., когда наст. время просм.
preferences-notifications-app-icon-shows-due-count = Число повтор. на значке
preferences-notifications-settings-app-enable-notifications = Пожалуйста, откройте настройки системы iOS, найдите там раздел с Anki и включите уведомления, наклейки и предупреждения.
preferences-pen-size = Размер пера
preferences-question-side = Сторона вопроса
preferences-remaining-count = Оставшееся количество
preferences-right = Справа
preferences-right-shoulder = Правый бампер
preferences-right-thumbstick-button = Кнопка правого стика
preferences-right-trigger = Правый триггер
preferences-scratchpad-below-buttons = Кнопки под блокнотом
preferences-scratchpad-transparency = Прозрачность блокнота
preferences-scratchpad-transparency-full = Полный
preferences-scratchpad-transparency-medium = Средняя
preferences-scratchpad-transparency-none = Нет
preferences-scratchpad-transparency-slight = Небольшая
preferences-shake-action = Действие встряхивания
preferences-short = Короткое
preferences-show-bottom-bar = Показать нижнюю панель
preferences-show-grid = Показать сетку
preferences-show-top-bar = Показать верхнюю панель
preferences-small = Маленький
preferences-swipe-down = Смахивание вниз
preferences-swipe-left = Смахивание влево
preferences-swipe-right = Смахивание вправо
preferences-swipe-up = Смахивание вверх
preferences-swipes = Жесты
preferences-swipes-must-begin-from-the-far = Жесты должны начинаться с дальнего левого или правого края экрана.
preferences-sync-sounds-images = Синхр. звуки и изображения
preferences-syncing = Синхронизация
preferences-tap-to-sync = Для включения синхронизации, коснитесь кнопки синхронизации в списке колод.
preferences-taps = Касания
preferences-theme = Тема
preferences-theme-bar-style = Стиль панели
preferences-theme-black = Черный
preferences-theme-dark = Темный
preferences-theme-dark-translucent = Темный и прозрачный
preferences-theme-force-off = Принудительно выключить
preferences-theme-force-on = Принудительно включить
preferences-theme-light-translucent = Светлый и прозрачный
preferences-theme-night-mode-desc = Темный режим затемняет интерфейс и карточки становятся белыми на черном фоне.
preferences-theme-night-mode-same-as-system = Использовать системную тему
preferences-theme-slate = Серый
preferences-thick = Толстый
preferences-tools-overlay-button = Кнопка оверлея инструментов
preferences-tools-overlay-position = Расположение оверлея инструментов
preferences-top-center = Сверху по середине
preferences-top-left = Сверху слева
preferences-top-right = Сверху справа
preferences-undo-clears-all = Отмена очищает все
preferences-when-answer-shown = Когда показан ответ
preferences-when-question-shown = Когда показан вопрос
preferences-you-have-been-logged-out = Выход выполнен.
