profiles-a-profile-with-that-name-already = Профиль с этим именем уже существует.
profiles-add-profile = Добавить профиль
profiles-creating-backup = Создание резервной копии...
profiles-finishing-backup = Завершение создания копии...
profiles-please-provide-some-text-avoiding-symbols = Впишите текст, избегая символов и знаков подчеркивания.
profiles-please-select-another-profile-first = Сначала выберите другой профиль.
profiles-profile-name = Название профиля
profiles-rename-profile = Переименовать профиль
profiles-unable-to-open-safari-please = Не удалось открыть Safari - проверьте настройки родительского контроля.
profiles-welcome = Добро пожаловать!
