actions-actions = Azioni
actions-all-actions = Tutte le azioni
actions-an-error-occurred = Si è verificato un errore: { $error }
actions-are-you-sure = Sei sicuro?
actions-browse = Sfoglia
actions-card-buried = Carta seppellita
actions-card-suspended = Carta sospesa
actions-create = Crea
actions-custom-study-cant-be-used-on = Lo studio personalizzato non si può usare su un mazzo filtrato.
actions-deck-statistics = Statistiche del mazzo
actions-delete-note-and-its-cards = Cancellare la nota e le sue carte?
actions-downloading = Download in corso...
actions-drag-here-to-remove = Trascinare qui per rimuovere
actions-file-invalid-or-corrupt = File invalido o corrotto.
actions-frequent-actions = Azioni frequenti
actions-invalid-number-of-days = Numero di giorni non valido.
actions-leave-without-saving = Uscire senza salvare?
actions-no-load-restore-backup = Non è stato possibile caricare la tua collezione. Ripristinala da un backup automatico attraverso la schermata delle preferenze.
# (http://example.com) does not appear to be...
actions-not-valid-link = Non sembra essere un link http/https valido.
actions-note-and-its-cards-deleted = Nota e { $count } sue carte eliminate
actions-note-buried = Nota seppellita
actions-pause-audio-short = Pausa
actions-please-tap-the-in-the = Fa click su '?' in alto a sinistra per iniziare.
actions-processing = Elaborazione...
actions-record-voice = Registra la voce
actions-record-voice-short = Registrare
actions-replay-audio-short = Replay
actions-select-deck = Seleziona il mazzo
actions-select-note-type = Seleziona il tipo di nota
actions-study-options = Opzioni di studio
actions-tools = Strumenti
actions-you-can-only-empty-a-filtered = Puoi svuotare solo un mazzo filtrato.
