actions-actions = Azioni
actions-all-actions = Tutte le azioni
actions-an-error-occurred = Si è verificato un errore: { $error }
actions-are-you-sure = Sei sicuro?
actions-browse = Sfoglia
actions-card-buried = Carta seppellita
actions-card-suspended = Carta sospesa
actions-create = Crea
actions-deck-statistics = Statistiche del mazzo
actions-delete-note-and-its-cards = Cancellare la nota e le sue carte?
actions-file-invalid-or-corrupt = File invalido o corrotto.
actions-frequent-actions = Azioni frequenti
actions-leave-without-saving = Uscire senza salvare?
actions-no-load-restore-backup = Non è stato possibile caricare la tua collezione. Per favore, ripristinala da un backup automatico attraverso la schermata delle preferenze.
# (http://example.com) does not appear to be...
actions-not-valid-link = Non sembra essere un link http/https valido.
actions-note-buried = Nota seppellita
actions-pause-audio-short = Pausa
actions-please-tap-the-in-the = Per favore, fa click su '?' in alto a sinistra per iniziare.
actions-record-voice-short = Registrare
actions-replay-audio-short = Replay
actions-select-deck = Seleziona il mazzo
actions-study-options = Opzioni di studio
actions-tools = Strumenti
