actions-actions = Azioni
actions-add-new = Aggiungi nuovo
actions-added-to-frequent-actions = Aggiunto alle azioni frequenti.
actions-all-actions = Tutte le azioni
actions-already-in-frequent-actions = Già in azioni frequenti.
actions-an-error-occurred = Si è verificato un errore: { $error }
actions-answer-again = Rispondi Ripeti
actions-answer-easy = Rispondi Facile
actions-answer-good = Rispondi Normale
actions-answer-hard = Rispondi Difficile
actions-are-you-sure = Sei sicuro?
actions-auto-advance = Avanzamento Automatico
actions-bottom-bar = Barra Inferiore
actions-browse = Sfoglia
actions-card-buried = Carta seppellita
actions-card-suspended = Carta sospesa
actions-card-template = Modello di Carta
actions-confirm-delete = Conferma Elimina
actions-create = Crea
actions-current-audio-minus-5s = Audio Corrente -5s
actions-current-audio-plus-5s = Audio Corrente +5s
actions-custom-study-cant-be-used-on = Lo studio personalizzato non si può usare su un mazzo filtrato.
actions-deck-statistics = Statistiche del mazzo
actions-delete-note-and-its-cards = Cancellare la nota e le sue carte?
actions-discard-changes = Scarta le Modifiche
actions-done = Fatto
actions-downloading = Download in corso...
actions-drag-here-to-remove = Trascinare qui per rimuovere
actions-draw = Disegna
actions-file-invalid-or-corrupt = File invalido o corrotto.
actions-filtercram = Filtra/Raggruppa
actions-filtered-deck = Mazzo FIltrato { $num }
actions-forgot-card = Dimentica carta
actions-frequent-actions = Azioni frequenti
actions-leave-without-saving = Uscire senza salvare?
actions-long-press-on-an-item-to = Tieni premuto su un elemento per modificarlo
actions-mark = Contrassegna
actions-mark-and-bury = Contrassegna + Seppellisci
actions-mark-and-suspend = Contrassegna + Sospendi
actions-marked = Contrassegnato
actions-no-current-card = Nessuna carta per adesso.
actions-no-load-restore-backup = Non è stato possibile caricare la tua collezione. Ripristinala da un backup automatico attraverso la schermata delle preferenze.
# (http://example.com) does not appear to be...
actions-not-valid-link = Non sembra essere un link http/https valido.
actions-note-and-its-cards-deleted = Nota e { $count } sue carte eliminate
actions-note-and-its-cards-suspended = La nota e la sua { $count } carta(e) sono state sospese.
actions-note-buried = Nota seppellita
actions-note-marked-and-buried = Nota contrassegnata e seppellita.
actions-nothing-to-undo = Niente da annullare.
actions-nothing-to-redo = Niente da ripristinare
actions-off = Disattiva
actions-please-tap-the-in-the = Fa click su '?' in alto a sinistra per iniziare.
actions-processing = Elaborazione...
actions-record-voice = Registra la voce
actions-record-voice-menu = Menu di registrazione della voce
actions-reset-card = Resetta Carta
actions-revert = Ripristina
actions-review-undone = Ripasso annullato
actions-scratchpad = Scratchpad
actions-scratchpad-size = Dimensione dello Scratchpad
actions-select-deck = Seleziona il mazzo
actions-select-note-type = Seleziona il tipo di nota
actions-show-answeranswer-good = Mostra Risponsta/Risposta Corretta
actions-study-options = Opzioni di studio
actions-tools = Strumenti
actions-tools-overlay = Overlay degli Strumenti
actions-top-bar = Barra Superiore
actions-unbury-deck = Disseppellisci Mazzo
actions-undo = Annulla
actions-unmarked = Non contrassegnato
actions-you-can-only-empty-a-filtered = Puoi svuotare solo un mazzo filtrato.
actions-you-can-only-rebuild-a-filtered = Puoi solo ricostruire un mazzo filtrato

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Vuoto
# create a filtered deck
actions-filter-short = Filtro
actions-add-short = Aggiungi
actions-answer-again-short = Risp. R
actions-answer-easy-short = Risp. F
actions-answer-good-short = Risp. B
actions-answer-hard-short = Risp. D
actions-auto-advance-short = Av. Auto.
actions-bottom-bar-short = BarraInf.
actions-browse-short = Browse
actions-bury-card-short = Sepp.C.
actions-bury-note-short = Sepp.N.
actions-card-info-short = Info C.
actions-card-template-short = Modello
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Custom
actions-deck-statistics-short = Stat.M.
actions-decks-short = Mazzi
actions-delete-note-short = Elimina
actions-edit-short = Mod.
actions-mark-and-bury-short = Co&Sep
actions-mark-and-suspend-short = Co&So
actions-mark-short = Contr.
actions-night-mode-short = Scuro
actions-off-short = Off
actions-pause-audio-short = Pausa
actions-rebuild-short = Ricostr.
actions-record-voice-short = Registrare
actions-replay-voice-short = Riasc.V.
actions-replay-audio-short = Replay
actions-reset-card-short = Reset.C
actions-scratchpad-short = Pad
actions-scratchpad-size-short = Dim.Pad
actions-set-due-date-short = Imp.Date
actions-show-answer-short = Mo.Risp
actions-show-answeranswer-good-short = Mo/Risp
actions-study-options-short = Opz.Stud.
actions-suspend-card-short = Sosp.C.
actions-suspend-note-short = Sosp.N.
actions-tools-short = Strum.
actions-top-bar-short = B.Sup.
actions-unbury-deck-short = Dissepp.
actions-undo-short = Annulla
actions-redo-short = Riprist.
