decks-a-deck-must-be-provided = Deve essere fornito un mazzo.
decks-a-deck-named-already-exists = Esiste già un mazzo chiamato '{ $name }'.
decks-a-deck-with-that-name-already = Esiste già un mazzo con questo nome.
decks-add-deck = Aggiungi Mazzo
decks-add-empty-deck = Aggiungi Mazzo Vuoto
decks-addexport = Aggiungi/Esporta
decks-cannot-delete = Impossibile Eliminare
decks-card-limit = Limite Carte
decks-cards-in-a-filtered-deck-cant = Le carte in un mazzo filtrato non possono essere spostate.
decks-custom-steps = Passi Personalizzati
decks-deck-exists = Il Mazzo Esiste
decks-deck-label = Mazzo:
decks-deck-name = Nome del mazzo
decks-deck-options = Opzioni del mazzo
decks-download-link = Download Link
decks-export-collection = Esporta Collezione
decks-filtered-deck = Mazzo filtrato
decks-import-from-itunes = Importa da iTunes
decks-invalid-deck-name = Nome del mazzo non valido.
decks-link-to-apkg-file-to-import = Link al file .apkg da importare:
decks-no-matches = Nessun Risultato
decks-return-by-delete = Per far tornare tutte le carte nel mazzo originale, scorri sul mazzo blu nell'elenco dei mazzi, e cancellalo.
decks-shared-deck-list = Lista dei Mazzi Condivisi
decks-sync = Sincronizza
decks-synchronize = Sincronizza
decks-the-default-deck-cannot-be-deleted = Il mazzo predefinito non può essere eliminato.
decks-the-provided-deck-does-not-exist = Il mazzo fornito non esiste.
decks-the-search-you-provided-did-not = La ricerca fornita non corrisponde a nessuna carta.
decks-will-be-returned = Le carte torneranno nel loro mazzo originale man mano che rispondi.
