deck-options-add-options-group = Aggiungi gruppo di opzioni
deck-options-answer-time-cap = Tempo massimo di risposta
deck-options-bury-related-new-cards = Seppellisci nuove carte collegate
deck-options-bury-related-reviews = Seppellisci carte collegate da ripassare
deck-options-defaults = Defaults
deck-options-delete-options-full-sync = Eliminare questo gruppo di opzioni impedirà di incorporare qualsiasi cambiamento da altri dispositivi alla prossima sincronizzazione. Procedere?
deck-options-display-in-order-added = Mostra in ordine di aggiunta
deck-options-display-in-random-order = Mostra in ordine casuale
deck-options-full-sync-required = Sincronizzazione Completa Richiesta
deck-options-group-name = Nome del gruppo
deck-options-max-new-per-day = Numero massimo di nuove carte giornaliere
deck-options-max-reviews-per-day = Numero massimo di ripetizioni giornaliere
deck-options-new-cards = Carte nuove
deck-options-options-group = Gruppo di opzioni
deck-options-replay-q-audio-in-answer = Riproduci di nuovo l'audio della domanda nella risposta
deck-options-reset-all-settings-to-defaults = Riportare tutte le impostazioni ai valori predefiniti?
deck-options-restore-defaults = Ripristina Defaults
deck-options-steps = Passi
