exporting-collection-saved-to-itunes = Collezione salvata su iTunes
exporting-export-to-itunes = Esporta su iTunes
exporting-export-to-share-sheet = Esporta su Share Sheet
exporting-exporting = Esportazione in corso...
exporting-include-media2 = Includi file multimediali
exporting-media-files-exported-d = File multimediali esportati: { $count }...
