importing-delete-imported-file = Cancellare il file importato?
importing-import-complete = Importazione completata.
importing-importing = Importazione in corso...
importing-no-apkg-or-colpkg-files-were = Nessun .apkg o .colpkg file trovato in iTunes.
importing-overwrite-via-import = Sovrascrivere l'intera collezione con il file importato? Quest'azione non può essere annullata.
importing-please-choose-a-file = Scegli un file.
importing-processed-media-files-d = Processando i file: { $count }...
importing-replace-collection = Sostituisci collezione
importing-file-not-downloaded = Per favore, scarica il file da iCloud e poi importalo nuovamente.
