preferences-about = Chi siamo
preferences-answer-side = Lato della risposta
preferences-audio-buttons = Pulsanti audio
preferences-auto-advance-answer-action = Azione di risposta
preferences-auto-advance-do-nothing = Non fare niente
preferences-auto-advance-wait-for-audio = Attendi audio
preferences-bottom-left = Pulsante a sinistra
preferences-bottom-right = Pulsante a destra
preferences-collection-day-starts = Statistiche giornaliere
preferences-collection-mix = Mix
preferences-collection-new-first = Prima le nuove
preferences-collection-reviews-first = Prima le revisionate
preferences-full-sync = Sincronizzazione completa
preferences-gamepad-menu-button = Menu
preferences-left = Sinistra
preferences-normal = Normale
preferences-notifications = Notifiche
preferences-right = Destra
preferences-scratchpad-transparency-none = Nessuno/a
preferences-sync-sounds-images = Sincronizza suono e immagine
preferences-syncing = Sincronizzazione
preferences-theme = Tema
preferences-theme-black = Nero
