preferences-about = Chi siamo
preferences-answer-side = Lato della risposta
preferences-audio-buttons = Pulsanti audio
preferences-auto-advance-answer-action = Azione di risposta
preferences-auto-advance-answer-seconds = Secondi Risposta
preferences-auto-advance-do-nothing = Non fare niente
preferences-auto-advance-question-seconds = Secondi Domanda
preferences-auto-advance-wait-for-audio = Attendi audio
preferences-backup-available-backups = Backup disponibili
preferences-backup-create-now = Crea Ora
preferences-backup-maximum-backups = Massimo n° di backup
preferences-backup-minutes-between-backups = Minuti tra i backup
preferences-backup-revert-to-backup = Ripristina backup
preferences-backup-revert-to-backup-confirm = Ripristinare { $backup }? Tutte le modifiche successive alla creazione del backup andranno perse.
preferences-backup-reverted-to-backup = Backup ripristinato.
preferences-bottom-left = Pulsante a sinistra
preferences-bottom-right = Pulsante a destra
preferences-button-d = Pulsante { $num }
preferences-collection-day-starts = Statistiche giornaliere
preferences-collection-learn-ahead-minutes = Mostra in anticipo - Minuti
preferences-collection-mix = Mix
preferences-collection-new-first = Prima le nuove
preferences-collection-newreview-order = Ordine Nuove/Da ripetere
preferences-collection-reviews-first = Prima le revisionate
preferences-full-sync = Sincronizzazione completa
preferences-gamepad-button-mapping = Mapping dei pulsanti
preferences-gamepad-menu-button = Menu
preferences-height = Altezza
preferences-interrupt-current-audio = Interrompi audio corrente
preferences-left = Sinistra
preferences-normal = Normale
preferences-notifications = Notifiche
preferences-right = Destra
preferences-scratchpad-transparency-none = Nessuno/a
preferences-sync-sounds-images = Sincronizza suono e immagine
preferences-syncing = Sincronizzazione
preferences-theme-black = Nero
