preferences-about = Chi siamo
preferences-autoplay-in-silent-mode = Riproduzione automatica in modalità silenziosa
preferences-always-duck = Disattiva sempre i suoni di sottofondo
preferences-answer-keeps-zoom = Mantieni Zoom nella risposta
preferences-answer-side = Lato della risposta
preferences-audio-buttons = Pulsanti audio
preferences-auto-advance-answer-action = Azione di risposta
preferences-auto-advance-answer-seconds = Secondi Risposta
preferences-auto-advance-auto-advance-to-start = Per avviare l'avanzamento automatico, utilizza l'azione 'Avanzamento Automatico'
preferences-auto-advance-do-nothing = Non fare niente
preferences-auto-advance-question-seconds = Secondi Domanda
preferences-backup-available-backups = Backup disponibili
preferences-backup-create-now = Crea Adesso
preferences-backup-maximum-backups = Massimo n° di backup
preferences-backup-minutes-between-backups = Minuti tra i backup
preferences-backup-revert-to-backup = Ripristina backup
preferences-backup-revert-to-backup-confirm = Ripristinare { $backup }? Tutte le modifiche successive alla creazione del backup andranno perse.
preferences-backup-reverted-to-backup = Backup ripristinato.
preferences-bottom-bar-size = Dimensione della barra inferiore
preferences-bottom-center = In basso al centro
preferences-bottom-left = In basso a sinistra
preferences-bottom-right = In basso a destra
preferences-button-d = Pulsante { $num }
preferences-collection-day-starts = Il giorno inizia alle ore
preferences-collection-learn-ahead-minutes = Studio anticipato in minuti
preferences-collection-mix = Mix
preferences-collection-new-first = Prima le nuove
preferences-collection-newreview-order = Ordine Nuove/Da ripassare
preferences-collection-reviews-first = Prima le ripetizioni
preferences-double-tap-prevention = Previeni doppio tocco
preferences-open-links-externally = Apri collegamenti in una finestra esterna
preferences-drawing-screen-ignores-fingers = La schermata di disegno ignora le dita
preferences-feedback-ticks = Indicatori di conferma
preferences-spread-ticks = Distanzia indicatori di conferma
preferences-fine = Fine
preferences-force-sync-confirm = Forzare una sincronizzazione a senso unico? Tutte le modifiche effettuate sull'altro versante verranno perse.
preferences-full-sync = Sincronizzazione unidirezionale
preferences-gamepad-button-mapping = Mapping dei pulsanti
preferences-gamepad-menu-button = Menu
preferences-gamepads = Gamepad
preferences-gamepad-thumbpad-deadzone = Zona morta del thumbpad %
preferences-height = Altezza
preferences-huge = Gigante
preferences-ignore-fingers = Ignora le dita
preferences-interrupt-current-audio = Interrompi l'audio attuale
preferences-large = Grande
preferences-left = Sinistra
# gamepad
preferences-left-shoulder = Spalla sinistra
# gamepad
preferences-left-thumbstick-button = Pulsante sinistro del joystick
# gamepad
preferences-left-trigger = Trigger sinistro
preferences-logged-in-as = Connesso come:
preferences-long = Lungo
preferences-mid-center = Centro, in mezzo
preferences-mid-left = Centro, a sinistra
preferences-mid-right = Centro, a destra
preferences-never-type-answer = Non digitare mai la risposta
preferences-never-show-scratchpad = Non mostrare mai il Blocchetto appunti
preferences-never-show-scratchpad-enabled = 'Non mostrare mai il Blocchetto appunti' è abilitato nella schermata delle preferenze.
preferences-next-times = Prossime volte
preferences-normal = Normale
preferences-notifications = Notifiche
preferences-notifications-alert-time = Orario di notifica
preferences-notifications-alert-when-due = Notifica scadenza
preferences-notifications-app-icon-shows-due-count = L'icona dell'app mostra il conteggio delle carte da ripetere
preferences-notifications-settings-app-enable-notifications = Accedere all'app Impostazioni di iOS, cercare la sezione Anki e abilitare le notifiche, le icone e gli avvisi.
preferences-pen-size = Dimensione del pennello
preferences-question-side = Lato della domanda
preferences-remaining-count = Conteggio rimanenti
preferences-right = Destra
# gamepad
preferences-right-shoulder = Spalla destra
# gamepad
preferences-right-thumbstick-button = Pulsante destro del joystick
# gamepad
preferences-right-trigger = Trigger destro
preferences-scratchpad-below-buttons = Blocchetto appunti sotto i pulsanti
preferences-scratchpad-transparency = Trasparenza del Blocchetto appunti
preferences-scratchpad-transparency-full = Completa
preferences-scratchpad-transparency-medium = Media
preferences-scratchpad-transparency-none = Nessuna
preferences-scratchpad-transparency-slight = Leggera
preferences-shake-action = Azione allo scuotimento
preferences-short = Corto
preferences-show-bottom-bar = Mostra barra inferiore
preferences-show-grid = Mostra griglia
preferences-show-top-bar = Mostra barra superiore
preferences-small = Piccolo
preferences-swipe-down = Swipe in basso
preferences-swipe-left = Swipe a sinistra
preferences-swipe-right = Swipe a destra
preferences-swipe-up = Swipe in alto
preferences-swipes = Movimenti di swipe
preferences-swipes-must-begin-from-the-far = Inizia i movimenti di swipe dal margine sinistro o destro dello schermo.
preferences-sync-sounds-images = Sincronizza file audio e immagini
preferences-syncing = Sincronizzazione
preferences-tap-to-sync = Per attivare la sincronizzazione, tocca il pulsante di sincronizzazione nella schermata dell'elenco dei mazzi.
preferences-taps = Tocchi
preferences-theme-bar-style = Stile della Barra
preferences-theme-black = Nero
preferences-theme-dark-translucent = Scuro e Traslucido
preferences-theme-force-off = Forza spento
preferences-theme-force-on = Forza acceso
preferences-theme-light-translucent = Chiaro e Traslucido
preferences-theme-night-mode-desc = La modalità notturna scurisce l'interfaccia e mostra le carte con sfondo nero e testo bianco.
preferences-theme-night-mode-same-as-system = Segui impostazioni del dispositivo
preferences-theme-slate = Ardesia
preferences-thick = Spesso
preferences-tools-overlay-button = Pulsante Finestra degli Strumenti
preferences-tools-overlay-position = Posizione Finestra degli Strumenti
preferences-top-center = In alto al centro
preferences-top-left = In alto a sinistra
preferences-top-right = In alto a destra
preferences-undo-clears-all = "Annulla" cancella tutto
preferences-when-answer-shown = Quando viene mostrata la risposta
preferences-when-question-shown = Quando viene mostrata la domanda
preferences-you-have-been-logged-out = Sei stato disconnesso.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Dimensione massima dell'immagine (bordo lungo)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Ridimensiona quando si incolla
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Converti virgolette curve e trattini
preferences-editing-crop-camera-photos = Ritaglia immagini della fotocamera
preferences-loop-video = Ripeti video
preferences-show-video-controls = Mostra controlli video
preferences-high-quality-video = Video di alta qualità
preferences-auto-capitalize = Maiuscole automatiche
preferences-auto-correct = Correzione automatica
preferences-strip-hebrew-vowels = Rimuovi le vocali ebraiche
