profiles-a-profile-with-that-name-already = Esiste già un profilo con questo nome.
profiles-add-profile = Aggiungi profilo
profiles-finishing-backup = Completamento del backup...
profiles-please-provide-some-text-avoiding-symbols = Per favore fornisci del testo, evitando simboli e trattini bassi.
profiles-please-select-another-profile-first = Per favore, seleziona prima un altro profilo.
profiles-profile-name = Nome del profilo
profiles-rename-profile = Rinomina il profilo
profiles-unable-to-open-safari-please = Impossibile aprire Safari; verifica le impostazioni del parental control.
profiles-welcome = Ti do il benvenuto!
