actions-actions = Amallar
actions-add-new = Yangi qoʻshish
actions-all-actions = Barcha amallar
actions-an-error-occurred = Xatolik yuz berdi: { $error }
actions-answer-easy = Javobi oson
actions-are-you-sure = Ishonchingiz komilmi?
actions-bottom-bar = Pastki panel
actions-browse = Koʻrib chiqish
actions-card-buried = Karta koʻmildi
actions-card-suspended = Karta toʻxtatildi
actions-card-template = Karta shabloni
actions-confirm-delete = Oʻchirishni tasdiqlash
actions-create = Yaratish
actions-current-audio-minus-5s = Joriy audio -5 s
actions-current-audio-plus-5s = Joriy audio +5 s
actions-custom-study-cant-be-used-on = Filtrlangan dastaga maxsus oʻrganishni qoʻllab boʻlmaydi.
actions-deck-statistics = Dasta statistikasi
actions-delete-note-and-its-cards = Qayd va uni kartalari oʻchirilsinmi?
actions-discard-changes = Oʻzgarishlarni bekor qilish
actions-done = Bajarildi
actions-downloading = Yuklab olinmoqda...
actions-draw = Chizish
actions-file-invalid-or-corrupt = Fayl yaroqsiz yoki buzilgan.
actions-filtered-deck = Filtrlangan dasta { $num }
actions-leave-without-saving = Saqlamasdan chiqilsinmi?
actions-long-press-on-an-item-to = Moslashtirish uchun elementni ustiga uzoq bosib turing.
actions-mark = Belgilash
actions-mark-and-bury = Belgilash va koʻmish
actions-mark-and-suspend = Belgilash va toʻxtatish
actions-marked = Belgilangan
actions-no-current-card = Joriy karta yoʻq.
actions-no-load-restore-backup = Toʻplamingizni yuklab boʻlmadi. Sozlamalar ekrani yordamida avtomatik zahiradan tiklang.
# (http://example.com) does not appear to be...
actions-not-valid-link = yaroqli http/https havolasi emas.
actions-note-and-its-cards-deleted = Qayd va uni { $count } ta kartasi oʻchirildi
actions-note-and-its-cards-suspended = Qayd va uni { $count } ta kartasi toʻxtatildi
actions-note-buried = Qayd koʻmildi
actions-note-marked-and-buried = Qayd belgilandi va koʻmildi
actions-off = Oʻchiq
actions-please-tap-the-in-the = Boshlash uchun yuqoridagi chapdagi '?' tugmasini bosing.
actions-record-voice = Ovozni yozib olish
actions-record-voice-menu = Ovozni yozib olish menyusi
actions-reset-card = Kartani qayta tiklash
actions-select-deck = Dastani tanlash
actions-select-note-type = Qayd turini tanlash
actions-show-answeranswer-good = Javobni koʻrsatish/javobi yaxshi
actions-study-options = Oʻrganish parametrlari
actions-tools = Asboblar
actions-top-bar = Yuqoridagi panel
actions-unbury-deck = Dastani koʻmishdan chiqarish
actions-undo = Bekor qilish
actions-unmarked = Belgilanmagan
actions-you-can-only-empty-a-filtered = Faqat filtrlangan dastani boʻshata olasiz.
actions-you-can-only-rebuild-a-filtered = Faqat filtrlangan dastani qayta qura olasiz.
actions-scroll-up = Tepaga aylantirish
actions-scroll-down = Pastga aylantirish

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Boʻshat.
# create a filtered deck
actions-filter-short = Filtrlash
actions-add-short = Qoʻshish
actions-answer-again-short = Qaytadan
actions-answer-easy-short = Oson
actions-answer-good-short = Yaxshi
actions-answer-hard-short = Qiyin
actions-auto-advance-short = Avto-ilg.
actions-bottom-bar-short = Past.P.
actions-browse-short = Koʻrib ch.
actions-bury-card-short = K.koʻm.
actions-bury-note-short = Q.koʻm.
actions-card-info-short = K.maʼl.
actions-card-template-short = Shablon
actions-current-audio-minus-5s-short = -5 s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-short = Maxsus
actions-deck-statistics-short = D.stat.
actions-decks-short = Dastalar
actions-delete-note-short = Oʻch.
actions-edit-short = Tahr.
actions-mark-and-bury-short = B&K
actions-mark-and-suspend-short = B&T
actions-mark-short = Belgi.
actions-night-mode-short = Tun
actions-off-short = Oʻchiq
actions-pause-audio-short = Pauza
actions-rebuild-short = Q. qurish
actions-record-voice-short = Ovoz y.
actions-replay-voice-short = O. ijro
actions-replay-audio-short = Ijro
actions-reset-card-short = K.tik.
actions-show-answer-short = Javobi
actions-show-answeranswer-good-short = Koʻr./Yaxshi
actions-suspend-card-short = K.toʻx.
actions-suspend-note-short = Q.toʻx.
actions-tools-short = Asboblar
actions-top-bar-short = Y.panel
