decks-a-deck-must-be-provided = Dasta berilishi kerak.
decks-a-deck-named-already-exists = '{ $name }' nomli dasta allaqachon mavjud
decks-a-deck-with-that-name-already = Ushbu nomli dasta allaqachon mavjud.
decks-add-deck = Dasta qoʻshish
decks-add-empty-deck = Boʻsh dasta qoʻshish
decks-addexport = Qoʻshish/eksport
decks-cannot-delete = Oʻchirib boʻlmaydi
decks-card-limit = Karta limiti
decks-cards-in-a-filtered-deck-cant = Filtrlangan dastadagi kartalarni koʻchirib boʻlmaydi.
decks-custom-steps = Maxsus bosqichlar
decks-deck-exists = Dasta mavjud
decks-deck-label = Dasta:
decks-deck-name = Dasta nomi
decks-deck-options = Dasta parametrlari
decks-download-link = Yuklab olish havolasi
decks-export-collection = Toʻplamni eksport qilish
decks-filtered-deck = Filtrlangan dasta
decks-import-from-itunes = iTunesʼdan import qilish
decks-invalid-deck-name = Dasta nomi yaroqsiz.
decks-link-to-apkg-file-to-import = Import qilinadigan .apkg fayl havolasi:
decks-no-matches = Mosliklar yoʻq
decks-return-by-delete = Barcha kartalarni bir vaqtning oʻzida qaytarish uchun dasta roʻyxatdagi koʻk dasta ustidan suring va uni oʻchiring.
decks-shared-deck-list = Ulashilgan dastalar roʻyxati
decks-sync = Sinxronlash
decks-synchronize = Sinxronlash
decks-the-default-deck-cannot-be-deleted = Birlamchi dastani oʻchirib boʻlmaydi.
decks-the-provided-deck-does-not-exist = Berilgan dasta mavjud emas.
decks-the-search-you-provided-did-not = Siz kiritgan qidiruv hech qanday kartaga mos kelmadi.
decks-will-be-returned = Siz ularga javob berganingizda kartalar asl dastalariga qaytariladi.
