deck-options-add-options-group = Parametrlar guruhini qoʻshish
deck-options-answer-time-cap = Javob berish chegarasi
deck-options-bury-related-new-cards = Aloqador yangi kartalarni koʻmish
deck-options-bury-related-reviews = Aloqador takrorlashlarni koʻmish
deck-options-defaults = Birlamchilar
deck-options-delete-options-full-sync = Ushbu parametrlar guruhini oʻchirsangiz keyingi sinxronlashda boshqa qurilmalardagi oʻzgarishlarni birlashtira olmaysiz. Davom etasizmi?
deck-options-display-in-order-added = Qoʻshilgan tartibi boʻyicha koʻrsatish
deck-options-display-in-random-order = Tasodifiy tartibda koʻrsatish
deck-options-full-sync-required = Toʻliq sinxronlash talab qilinadi
deck-options-group-name = Guruh nomi
deck-options-max-new-per-day = Kunlik eng koʻp yangi kartalar
deck-options-max-reviews-per-day = Kunlik eng koʻp takrorlashlar
deck-options-new-cards = Yangi kartalar
deck-options-options-group = Parametrlar guruhi
deck-options-replay-q-audio-in-answer = Savol audiosini javobda qayta ijro etish
deck-options-reset-all-settings-to-defaults = Barcha sozlamalarni birlamchiga qaytarilsinmi?
deck-options-restore-defaults = Birlamchiga qaytarish
deck-options-steps = Boshqichlar
