media-error-initializing-recorder = Diktofonni ishga tushurishda xatolik yuz berdi.
media-error-playing-audio-full = Audioni ijro etishda xatolik yuz berdi. Bunga buzilgan fayl, iOS qoʻllab-quvvatlamaydigan fayl turi (masalan, .ogg) yoki mp3 fayl .wav sifatida notoʻgʻri nomlanganligi sabab boʻlishi mumkin.
media-recording = Yozib olinmoqda...
