preferences-about = Haqida
preferences-answer-side = Javob tarafi
preferences-audio-buttons = Audio tugmalari
preferences-auto-advance-do-nothing = Hechnima qilma
preferences-backup-available-backups = Mavjud zaxira nusxalari
preferences-backup-create-now = Hozir yaratish
preferences-gamepad-menu-button = Menyu
preferences-gamepads = Geympad
preferences-left = Chap
