preferences-about = Haqida
preferences-autoplay-in-silent-mode = "Silent Mode"da avtomatik ijro etish
preferences-always-duck = Orqa fondagi tovushlarni har doim pasaytirish
preferences-answer-keeps-zoom = Javob masshtabni saqlaydi
preferences-answer-side = Javob tarafi
preferences-audio-buttons = Audio tugmalari
preferences-auto-advance-answer-action = Javobdan keyingi amal
preferences-auto-advance-answer-seconds = Javob koʻrsatish vaqti (soniyalarda)
preferences-auto-advance-auto-advance-to-start = Avtomatik tarzda ilgarilashni boshlash uchun "Avtomatik ilgarilash" amalidan foydalaning.
preferences-auto-advance-do-nothing = Hechnima qilma
preferences-auto-advance-question-seconds = Savolni koʻrsatish vaqti (soniyalarda)
preferences-backup-available-backups = Mavjud zaxira nusxalari
preferences-backup-create-now = Hozir yaratish
preferences-backup-maximum-backups = Eng koʻp zaxiralar soni
preferences-backup-minutes-between-backups = Zaxiralashlar orasidagi vaqt (daqiqalarda)
preferences-backup-revert-to-backup = Zaxiraga qaytarish
preferences-backup-revert-to-backup-confirm = { $backup }ga qaytarilsinmi? Zaxiradan keyin qilingan barcha oʻzgarishlar yoʻqoladi.
preferences-backup-reverted-to-backup = Zaxira nusxasiga qaytarildi.
preferences-bottom-bar-size = Pastki panel oʻlchami
preferences-bottom-center = Pastki markaz
preferences-bottom-left = Pastki chap
preferences-bottom-right = Pastki oʻng
preferences-button-d = Tugma { $num }
preferences-collection-day-starts = Kun boshlanishi
preferences-collection-learn-ahead-minutes = Oldindan oʻrganish (daqiqalarda)
preferences-collection-mix = Aralashtirish
preferences-collection-new-first = Avval yangilari
preferences-collection-newreview-order = Yangilar/takrorlashlar tartibi
preferences-collection-reviews-first = Avval takrorlashlar
preferences-double-tap-prevention = Ikki marta bosishni oldini olish
preferences-open-links-externally = Havolalarni tashqi ilovalarda ochish
preferences-drawing-screen-ignores-fingers = Chizish ekrani barmoq bilan kiritishni qabul qilmaydi
preferences-feedback-ticks = Toʻgʻri javob belgisi
preferences-spread-ticks = Belgilarni joylashtirish
preferences-fine = Ingichka
preferences-force-sync-confirm = Bir tomonlama sinxronlashni majburiy qilinsinmi? Tomonlardan biridagi barcha oʻzgarishlar yoʻqoladi.
preferences-full-sync = Bir tomonlama sinxronlash
preferences-gamepad-button-mapping = Tugmalarni moslash
preferences-gamepad-menu-button = Menyu
preferences-gamepads = Geympad
preferences-gamepad-thumbpad-deadzone = Bosh barmoq yetadigan maydon nisbati %
preferences-height = Balandligi
preferences-huge = Ulkan
preferences-ignore-fingers = Barmoqlarni qabul qilinmasin
preferences-interrupt-current-audio = Joriy audioni uzmoq
preferences-large = Katta
preferences-left = Chap
# gamepad
preferences-left-shoulder = Chap yelka
# gamepad
preferences-left-thumbstick-button = Chap bosh barmoq tugmasi
# gamepad
preferences-left-trigger = Chap trigger
preferences-logged-in-as = Tizimga kirgan:
preferences-long = Uzun
preferences-mid-center = Oʻrta markaz
preferences-mid-left = Oʻrta chap
preferences-mid-right = Oʻrta oʻng
preferences-never-type-answer = Javob hech qachon kiritilmasin
preferences-never-show-scratchpad = Skretchpad hechqachon koʻrsatilmasin
preferences-never-show-scratchpad-enabled = Skretchpad hechqachon koʻrsatilmasin sozlamalar ekranida yoqilgan.
preferences-next-times = Keyingi vaqt
preferences-normal = Normal
preferences-notifications = Bildirishnomalar
preferences-notifications-alert-time = Ogohlantirish vaqti
preferences-notifications-alert-when-due = Muddati kelganda ogohlantirish
preferences-notifications-app-icon-shows-due-count = Ilova belgisi muddatli kartalar sonini koʻrsatadi
preferences-notifications-settings-app-enable-notifications = iOS sozlamalari oʻting, Anki boʻlimini toping va bildirishnomalar, nishonlar va ogohlantirishlarni yoqing.
preferences-pen-size = Qalam oʻlchami
preferences-question-side = Savol tomoni
preferences-remaining-count = Qolgan kartalar soni
preferences-right = Oʻng
# gamepad
preferences-right-shoulder = Oʻng yelka
# gamepad
preferences-right-thumbstick-button = Oʻng bosh barmoq tugmasi
# gamepad
preferences-right-trigger = Oʻng trigger
preferences-scratchpad-below-buttons = Skretchpad tugmalar ostida
preferences-scratchpad-transparency = Skretchpad shaffofligi
preferences-scratchpad-transparency-full = Toʻliq
preferences-scratchpad-transparency-medium = Oʻrta
preferences-scratchpad-transparency-none = Yoʻq
preferences-scratchpad-transparency-slight = Biroz
preferences-shake-action = Silkitish amali
preferences-short = Qisqa
preferences-show-bottom-bar = Pastki panelni koʻrsatish
preferences-show-grid = Panjarani koʻrsatish
preferences-show-top-bar = Yuqori panelni koʻrsatish
preferences-small = Kichik
preferences-swipe-down = Pastga surish
preferences-swipe-left = Chapga surish
preferences-swipe-right = Oʻngga surish
preferences-swipe-up = Yuqoriga surish
preferences-swipes = Surishlar
preferences-swipes-must-begin-from-the-far = Surish ekranning chap chetidan yoki oʻng chetidan boshlanishi kerak.
preferences-sync-sounds-images = Tovushlar va rasmlarni sinxronlash
preferences-syncing = Sinxronlashmoqda
preferences-tap-to-sync = Sinxronizatsiyani faollashtirish uchun dasta roʻyxat ekranidagi sinxronizatsiya tugmasini bosing.
preferences-taps = Bosishlar
preferences-theme-bar-style = Panel stili
preferences-theme-black = Qora
preferences-theme-dark-translucent = Qorongʻu va shaffof
preferences-theme-force-off = Majburlab oʻchirish
preferences-theme-force-on = Majburlab yoqish
preferences-theme-light-translucent = Yoriq va shaffof
preferences-theme-night-mode-desc = Tungi rejim interfeysni qoraytiradi va kartalarni qora ustida oq rangda koʻrsatadi.
preferences-theme-night-mode-same-as-system = Tizimga rioya qilish
preferences-theme-slate = Kulrang
preferences-thick = Qalin
preferences-tools-overlay-button = Asboblar overleyi tugmasi
preferences-tools-overlay-position = Asboblar overleyi oʻrni
preferences-top-center = Yuqori markaz
preferences-top-left = Yuqori chap
preferences-top-right = Yuqori oʻng
preferences-undo-clears-all = Bekor qilish barchasini tozalaydi
preferences-when-answer-shown = Javob koʻrsatilganda
preferences-when-question-shown = Savol koʻrsatilganda
preferences-you-have-been-logged-out = Tizimdan chiqarildingiz.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Maksimal rasm oʻlchami (uzun cheti)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Qoʻyganda oʻlchamini oʻzgartirish
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Aqlli iqtiboslar va chiziqchalarni almashtirish
preferences-editing-crop-camera-photos = Kamera rasmlarini kesish
preferences-loop-video = Videoni takrorlash
preferences-show-video-controls = Video boshqaruvlarini koʻrsatish
preferences-high-quality-video = Yuqori sifatli video
preferences-auto-capitalize = Avtomatik tarzda bosh harf bilan yozilsin
preferences-auto-correct = Avtomatik tuzatish
preferences-strip-hebrew-vowels = Ibroniy unlilarni olib tashlash
