actions-actions = Eylemler
actions-add-new = Yeni Ekle
actions-added-to-frequent-actions = Sık eylemlere eklendi.
actions-all-actions = Tüm Eylemler
actions-already-in-frequent-actions = Zaten sık eylemlerde.
actions-an-error-occurred = Bir hata oluştu: { $error }
actions-answer-again = Tekrar Cevapla
actions-answer-easy = Kolay
actions-answer-good = İyi
actions-answer-hard = Zor
actions-are-you-sure = Emin misin?
actions-auto-advance = Otomatik İlerleme
actions-bottom-bar = Alt Bar
actions-browse = Gözat
actions-card-buried = Kart gizlendi.
actions-card-suspended = Kart askıya alındı
actions-card-template = Kart Şablonu
actions-confirm-delete = Silmeyi Onayla
actions-create = Oluştur
actions-current-audio-minus-5s = Mevcut Ses -5s
actions-current-audio-plus-5s = Mevcut Ses +5s
actions-custom-study-cant-be-used-on = Filtrelenmiş destelerde özel çalışma kullanılamaz.
actions-deck-statistics = Deste İstatistikleri
actions-delete-note-and-its-cards = Not ve kartları silinsin mi?
actions-discard-changes = Değişiklikleri İptal Et
actions-done = Oldu
actions-downloading = İndiriliyor...
actions-drag-here-to-remove = Kaldırmak için buraya sürükle
actions-draw = Çiz
actions-file-invalid-or-corrupt = Dosya geçersiz ya da bozuk.
actions-filtercram = Filtrele/İnekle
actions-filtered-deck = Filtrelenmiş Deste { $num }
actions-forgot-card = Kart unutuldu
actions-frequent-actions = Sık yapılan işlemler
actions-leave-without-saving = Kaydetmeden çıkılsın mı?
actions-long-press-on-an-item-to = Özelleştirmek için bir öğeye uzun basın.
actions-mark = İşaretle
actions-mark-and-bury = İşaretle + Göm
actions-mark-and-suspend = İşaretle + Askıya al
actions-marked = İşaretlenmiş
actions-no-current-card = Geçerli kart yok.
actions-no-load-restore-backup = Koleksiyonunuz yüklenemedi. Lütfen tercihler ekranını kullanarak otomatik bir yedekten geri yükleyin.
actions-note-and-its-cards-deleted = Not ve ona ait { $count } kart(lar) silindi.
actions-note-and-its-cards-suspended = Not ve ona ait { $count } kart askıya alındı
actions-note-buried = Not gizlendi.
actions-note-marked-and-buried = Not işaretlendi ve gizlendi
actions-nothing-to-undo = Geri alınacak bir şey yok
actions-nothing-to-redo = Yeniden yapılacak bir şey yok.
actions-off = Kapalı
actions-please-tap-the-in-the = Lütfen başlamak için sol üstteki '?' simgesine dokunun.
actions-processing = İşleniyor...
actions-record-voice = Ses Kaydet
actions-reset-card = Kartı Sıfırla
actions-revert = Eski haline döndür
actions-review-undone = Gözden geçirme geri alındı
actions-scratchpad = Çalışma defteri
actions-scratchpad-size = Çalışma defteri boyutu
actions-select-deck = Desteyi Seç
actions-select-note-type = Not Tipini Seç
actions-show-answeranswer-good = Cevabı Göster/Cevabı İyi
actions-study-options = Çalışma Seçenekleri
actions-undo = Geri al
actions-you-can-only-rebuild-a-filtered = Sadece filtrelenmiş bir deste yeniden oluşturulabilir.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

actions-auto-advance-short = Oto İlerle.
actions-bottom-bar-short = Alt B.
actions-bury-card-short = KrtGzl.
actions-bury-note-short = NotGzl.
actions-card-info-short = Krt.B.
actions-current-audio-minus-5s-short = -5 sn
actions-current-audio-plus-5s-short = +5 sn
actions-deck-statistics-short = D.İstatistikleri
actions-delete-note-short = Sil
actions-mark-and-bury-short = İ&G
actions-mark-and-suspend-short = İ&A
actions-night-mode-short = Gece
actions-pause-audio-short = Duraklat
actions-rebuild-short = Yeniden oluş
actions-record-voice-short = Kayıt
actions-reset-card-short = K.Sıfırla
actions-scratchpad-short = Defter
actions-scratchpad-size-short = Defter Boyutu
actions-set-due-date-short = S.Tarihi Ayarla
actions-show-answer-short = Cv.Gstr
actions-show-answeranswer-good-short = Göster/İyi
actions-study-options-short = Ç.Sçnk
actions-undo-short = Geri al
actions-redo-short = Yeniden yap
