actions-actions = Eylemler
actions-add-new = Yeni Ekle
actions-added-to-frequent-actions = Sık eylemlere eklendi.
actions-all-actions = Tüm Eylemler
actions-already-in-frequent-actions = Zaten sık eylemlerde.
actions-an-error-occurred = Bir hata oluştu: { $error }
actions-answer-easy = Kolay
actions-are-you-sure = Emin misin?
actions-bottom-bar = Alt Çubuk
actions-browse = Göz At
actions-card-buried = Kart gizlendi.
actions-card-suspended = Kart askıya alındı
actions-card-template = Kart Şablonu
actions-confirm-delete = Silmeyi Onayla
actions-create = Oluştur
actions-current-audio-minus-5s = Geçerli Ses -5s
actions-current-audio-plus-5s = Geçerli Ses +5s
actions-custom-study-cant-be-used-on = Filtrelenmiş destelerde özel çalışma kullanılamaz.
actions-deck-statistics = Deste İstatistikleri
actions-delete-note-and-its-cards = Not ve kartları silinsin mi?
actions-discard-changes = Değişiklikleri İptal Et
actions-done = Oldu
actions-downloading = İndiriliyor...
actions-drag-here-to-remove = Kaldırmak için buraya sürükle
actions-draw = Çiz
actions-file-invalid-or-corrupt = Dosya geçersiz ya da bozuk.
actions-filtercram = Filtrele/İnekle
actions-filtered-deck = Filtrelenmiş Deste { $num }
actions-frequent-actions = Sık yapılan işlemler
actions-leave-without-saving = Kaydetmeden çıkılsın mı?
actions-long-press-on-an-item-to = Özelleştirmek için bir öğeye uzun basın.
actions-mark = İşaretle
actions-mark-and-bury = İşaretle + Gizle
actions-mark-and-suspend = İşaretle + Askıya al
actions-marked = İşaretli
actions-no-current-card = Geçerli kart yok.
actions-no-load-restore-backup = Koleksiyonunuz yüklenemedi. Lütfen tercihler ekranını kullanarak otomatik bir yedekten geri yükleyin.
# (http://example.com) does not appear to be...
actions-not-valid-link = geçerli http/https bir linki olmak gibi görünmüyor.
actions-note-and-its-cards-deleted = Not ve { $count } kart(lar)ı silindi.
actions-note-and-its-cards-suspended = Not ve { $count } kart(lar)ı askıya alındı
actions-note-buried = Not gizlendi.
actions-note-marked-and-buried = Not işaretlendi ve gizlendi
actions-off = Kapalı
actions-please-tap-the-in-the = Lütfen başlamak için sol üstteki '?' simgesine dokunun.
actions-processing = İşleniyor...
actions-record-voice = Ses Kaydet
actions-record-voice-menu = Ses Kaydetme Menüsü
actions-reset-card = Kartı Sıfırla
actions-revert = Eski haline döndür
actions-review-undone = Gözden geçirme geri alındı
actions-scratchpad = Çalışma defteri
actions-scratchpad-size = Çalışma defteri boyutu
actions-select-deck = Desteyi Seç
actions-select-note-type = Not Türü Seç
actions-show-answeranswer-good = Cevabı Göster/Cevabı İyi
actions-study-options = Çalışma Seçenekleri
actions-tools = Araçlar
actions-tools-overlay = Araçlar Bindirmesi
actions-top-bar = Üst Çubuk
actions-unbury-deck = Deste Gizlenmeyi Geri Al
actions-undo = Geri al
actions-unmarked = İşaretsiz
actions-you-can-only-empty-a-filtered = Sadece filtrelenmiş bir deste boşaltılabilir.
actions-you-can-only-rebuild-a-filtered = Sadece filtrelenmiş bir deste yeniden oluşturulabilir.
actions-scroll-up = Yukarı Kaydır
actions-scroll-down = Aşağı Kaydır

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Boşalt
# create a filtered deck
actions-filter-short = Filtre
actions-add-short = Ekle
actions-answer-again-short = Tekrar
actions-answer-easy-short = Kolay
actions-answer-good-short = İyi
actions-answer-hard-short = Zor
actions-auto-advance-short = Oto İlerle.
actions-bottom-bar-short = Alt Ç.
actions-browse-short = Göz At
actions-bury-card-short = KrtGzl.
actions-bury-note-short = NotGzl.
actions-card-info-short = Krt.B.
actions-card-template-short = Şablon
actions-current-audio-minus-5s-short = -5 sn
actions-current-audio-plus-5s-short = +5 sn
actions-custom-study-short = Özel
actions-deck-statistics-short = D.İstatistikleri
actions-decks-short = Desteler
actions-delete-note-short = Sil
actions-edit-short = Düzenle
actions-mark-and-bury-short = İ&G
actions-mark-and-suspend-short = İ&A
actions-mark-short = İşaretle
actions-night-mode-short = Gece
actions-off-short = Kapalı
actions-pause-audio-short = Duraklat
actions-rebuild-short = Yeniden oluş
actions-record-voice-short = Kayıt
actions-replay-voice-short = S.Oynat
actions-replay-audio-short = Tekrar Oynat
actions-reset-card-short = K.Sıfırla
actions-scratchpad-short = Defter
actions-scratchpad-size-short = Defter Boyutu
actions-set-due-date-short = S.Tarihi Ayarla
actions-show-answer-short = Cv.Gstr
actions-show-answeranswer-good-short = Göster/İyi
actions-study-options-short = Ç.Sçnk
actions-suspend-card-short = K.AskAl
actions-suspend-note-short = N.AskAl
actions-tools-short = Araçlar
actions-top-bar-short = Üst.Çbk
actions-unbury-deck-short = GzlGrAl
actions-undo-short = Geri al
actions-redo-short = Yeniden yap
actions-scroll-up-short = Yukarı
actions-scroll-down-short = Aşağı
