actions-actions = Eylemler
actions-add-new = Yeni Ekle
actions-added-to-frequent-actions = Sık eylemlere eklendi.
actions-all-actions = Bütün Eylemler
actions-already-in-frequent-actions = Zaten Sık Eylemlerde var.
actions-an-error-occurred = Bir hata oluştu: %@
actions-answer-again = Tekrar Cevapla
actions-answer-easy = Kolay
actions-answer-good = İyi
actions-answer-hard = Zor
actions-are-you-sure = Emin misin?
actions-auto-advance = Otomatik İlerleme
actions-auto-advance-short = Oto İlerle.
actions-bottom-bar = Alt Bar
actions-bottom-bar-short = Alt B.
actions-browse = Gözat
actions-bury-card-short = KrtGzl.
actions-bury-note-short = NotGzl.
actions-card-buried = Kart gizlendi.
actions-card-info = Kart Bilgisi
actions-card-info-short = Krt.B.
actions-card-suspended = Kart askıya alındı
actions-card-template = Kart Şablonu
actions-confirm-delete = Silmeyi Onayla
actions-create = Oluştur
actions-current-audio-minus-5s = Mevcut Ses -5s
actions-current-audio-minus-5s-short = -5 sn
actions-current-audio-plus-5s = Mevcut Ses +5s
actions-current-audio-plus-5s-short = +5 sn
actions-custom-study-cant-be-used-on = Filtrelenmiş destelerde özel çalışma kullanılamaz.
actions-deck-statistics = Deste İstatistikleri
actions-deck-statistics-short = D.İstatistikleri
actions-delete-note-and-its-cards = Not ve kartları silinsin mi?
actions-delete-note-short = Sil
actions-discard-changes = Değişiklikleri İptal Et
actions-done = Oldu
actions-downloading = İndiriliyor...
actions-drag-here-to-remove = Kaldırmak için buraya sürükle
actions-draw = Çiz
actions-file-invalid-or-corrupt = Dosya geçersiz ya da bozuk.
actions-filtered-deck = Filtrelenmiş Deste %i
actions-flag-1 = Bayrak 1
actions-flag-1-red = Bayrak 1 (Kırmızı)
actions-flag-2 = Bayrak 2
actions-flag-2-orange = Bayrak (Turuncu)
actions-flag-3 = Bayrak 3
actions-flag-3-green = Bayrak 3 (Yeşil)
actions-flag-4 = Bayrak 4
actions-flag-4-blue = Bayrak 4 (Mavi)
actions-forgot-card = Unutulan kart
actions-frequent-actions = Sık yapılan işlemler
actions-how-many-days-in-the-future = Gelecekte kaç gün var?
actions-invalid-number-of-days = Geçersin gün sayısı.
actions-leave-without-saving = Kaydetmeden çıkılsın mı?
actions-long-press-on-an-item-to = Özelleştirmek için bir öğeye uzun basın.
actions-mark = İşaretle
actions-mark-and-bury = İşaretle + Göm
actions-mark-and-bury-short = İ&G
actions-mark-and-suspend = İşaretle + Askıya al
actions-mark-and-suspend-short = İ&A
actions-marked = İşaretlenmiş
actions-night-mode-short = Gece
actions-no-current-card = Geçerli kart yok.
actions-note-and-its-cards-deleted = Not ve ona ait %d kart(lar) silindi.
actions-note-and-its-cards-suspended = Not ve ona ait %i kart askıya alındı
actions-note-buried = Not saklandı.
actions-note-marked-and-buried = Not işaretlendi ve saklandı
actions-nothing-to-undo = Geri alınacak bir şey yok
actions-off = Kapalı
actions-pause-audio-short = Duraklat
actions-please-tap-the-in-the = Lütfen başlamak için sol üstteki '?' simgesine dokunun.
actions-processing = İşleniyor...
actions-record-voice = Ses Kaydet
actions-record-voice-short = Kayıt
actions-replay-audio-short = Yeniden Oynat
actions-reset-card = Kartı Sıfırla
actions-reset-card-short = K.Sıfırla
actions-revert = Eski haline döndür
actions-review-undone = Bitirilmemiş kartları gözden geçir
actions-scratchpad = Çalışma defteri
actions-scratchpad-short = Defter
actions-scratchpad-size = Çalışma defteri boyutu
actions-scratchpad-size-short = Defter Boyutu
actions-select-deck = Desteyi Seç
actions-select-note-type = Not Tipini Seç
actions-set-due-date = Son Tarihi Ayarla
actions-set-due-date-short = S.Tarihi Ayarla
actions-show-answer-short = Cv.Gstr
actions-show-answeranswer-good = Cevabı Göster/Cevabı İyi
actions-show-answeranswer-good-short = Göster/İyi
actions-study-options = Çalışma Ayarları
actions-study-options-short = Ç.Ayarları
