browsing-append = Sonuna Ekle
browsing-card-updated = Kart Güncellendi
browsing-change-flag = Bayrağı Değiştir
browsing-clear-flag = Bayrağı Kaldır
browsing-confirm-reset = Sıfırlamayı Onayla
browsing-dd-selected = { $part }/{ $total } seçili
browsing-due-dateorder = Bitiş Tarihi/Sırası
browsing-due-reviews = Beklenen Gözden Geçirmeler
browsing-learning-cards = Öğrenme Kartları
browsing-no-cards-are-selected = Kart seçilmedi.
browsing-note-created = Not Oluşturuldu
browsing-note-updated = Not Güncellendi
browsing-note2 = Not:
browsing-questionandanswer = Soru+Cevap
browsing-repetitions = Tekrarlar
browsing-reset-cards = Kartları sıfırla
browsing-searching = Aranıyor...
browsing-second-column-19 = İkinci Sütün (1->9)
browsing-second-column-91 = İkinci Sütün (9->1)
browsing-select-all = Tümünü Seç
browsing-sort = Sırala:
browsing-sort-order = Sıralama düzeni
