decks-a-deck-must-be-provided = Bir deste sağlanmalıdır.
decks-a-deck-named-already-exists = '{ $name }' isimli bir deste zaten var.
decks-a-deck-with-that-name-already = Bu isimde bir deste zaten var.
decks-add-deck = Deste Ekle
decks-add-empty-deck = Boş Deste Ekle
decks-addexport = Ekle/Dışa Aktar
decks-cannot-delete = Silinemiyor
decks-card-limit = Kart limiti
decks-cards-in-a-filtered-deck-cant = Filtrelenmiş destedeki kartlar taşınamaz.
decks-deck-exists = Deste Var
decks-deck-label = Deste:
decks-deck-name = Deste İsmi
decks-deck-options = Deste Ayarları
decks-download-link = İndirme Linki
decks-export-collection = Koleksiyonu dışa aktar
decks-filtered-deck = Filtrelenmiş Deste
decks-import-from-itunes = ITunes'dan içe aktar
decks-invalid-deck-name = Geçersiz deste ismi.
decks-no-matches = Eşleşme Yok
decks-shared-deck-list = Paylaşılan Deste Listesi
