decks-a-deck-must-be-provided = Bir deste girilmelidir.
decks-a-deck-named-already-exists = '{ $name }' isimli bir deste zaten var.
decks-a-deck-with-that-name-already = Bu isimde bir deste zaten var.
decks-add-deck = Deste Ekle
decks-add-empty-deck = Boş Deste Ekle
decks-addexport = Ekle/Dışa Aktar
decks-cannot-delete = Silinemiyor
decks-card-limit = Kart sınırı
decks-cards-in-a-filtered-deck-cant = Filtrelenmiş destedeki kartlar taşınamaz.
decks-custom-steps = Özel Adımlar
decks-deck-exists = Deste Mevcut
decks-deck-label = Deste:
decks-deck-name = Deste İsmi
decks-deck-options = Deste Secenekleri
decks-download-link = İndirme Linki
decks-export-collection = Koleksiyonu dışa aktar
decks-filtered-deck = Filtrelenmiş Deste
decks-import-from-itunes = iTunes'dan içe aktar
decks-invalid-deck-name = Geçersiz deste ismi.
decks-link-to-apkg-file-to-import = İçeri aktarılacak .apkg dosyası için bağlantı:
decks-no-matches = Eşleşme Yok
decks-shared-deck-list = Paylaşılan Deste Listesi
decks-the-default-deck-cannot-be-deleted = Varsayılan deste silinemez.
decks-the-provided-deck-does-not-exist = Girdiğiniz deste mevcut değil.
decks-the-search-you-provided-did-not = Girdiğiniz arama hiçbir kartla eşleşmedi.
