importing-delete-imported-file = İçe aktarılan dosya silinsin mi?
importing-import-complete = İçe aktarma tamamlandı.
importing-importing = İçe aktarılıyor...
importing-no-apkg-or-colpkg-files-were = İTunes'da .apkg veya .colpkg dosyası bulunamadı
importing-overwrite-via-import = İçe aktarılan dosya bütün koleksiyonun üzerine yazılsın mı? Bu eylem geri alınamaz.
importing-please-choose-a-file = Lütfen bir dosya seçin.
importing-processed-media-files-d = İşlenen ortam dosyaları: { $count }...
importing-replace-collection = Koleksiyonun yerini değiştir
importing-file-not-downloaded = Lütfen dosyayı iCloud'dan indirin, sonra tekrar içe aktarın.
