preferences-about = Hakkında
preferences-answer-keeps-zoom = Cevap Yakınlaştırmayı Korur
preferences-answer-side = Cevap Tarafı
preferences-audio-buttons = Ses Düğmeleri
preferences-auto-advance-answer-action = Cevaplama Eylemi
preferences-auto-advance-answer-seconds = Cevap Saniyesi
preferences-auto-advance-do-nothing = Hiçbir şey yapma
preferences-auto-advance-question-seconds = Soru Saniyeleri
preferences-backup-available-backups = Mevcut yedekler
preferences-backup-create-now = Şu an Oluştur
preferences-backup-maximum-backups = Maksimum Yedek
preferences-backup-minutes-between-backups = Yedeklemeler Arası Dakikalar
preferences-backup-revert-to-backup = Yedeğe Geri Dön
preferences-backup-reverted-to-backup = Yedeğe geri döndü.
preferences-bottom-bar-size = Alt Çubuk Boyutu
preferences-bottom-center = Alt Orta
preferences-bottom-left = Sol Alt
preferences-bottom-right = Sağ Alt
preferences-button-d = { $num } Düğmesi
preferences-collection-learn-ahead-minutes = Önümüzdeki Dakikaları Öğren
preferences-collection-mix = Karma
preferences-collection-new-first = Önce yeni
preferences-collection-newreview-order = Yeni/Gözden geçirme Sırası
preferences-collection-reviews-first = Önce gözden geçirmeler
preferences-double-tap-prevention = Çift Dokunuş Önleme
preferences-drawing-screen-ignores-fingers = Çizim ekranı parmakları yok sayar
preferences-feedback-ticks = Geri bildirim işaretleri
preferences-fine = İyi
preferences-force-sync-confirm = Tek yönlü senkronizasyonu zorla? Bir taraftaki tüm değişiklikler kaybolacak.
preferences-full-sync = Tam Senkronizasyon
preferences-gamepads = Oyun kumandaları
preferences-height = Yükseklik
preferences-huge = Kocaman
preferences-ignore-fingers = Parmakları Yoksay
preferences-interrupt-current-audio = Geçerli Sesi Kes
preferences-large = Büyük
# gamepad
preferences-left-shoulder = Sol Omuz
# gamepad
preferences-left-thumbstick-button = Sol Parmak Çubuğu Düğmesi
# gamepad
preferences-left-trigger = Sol Tetik
preferences-logged-in-as = Olarak giriş yaptı:
preferences-long = Uzun
preferences-mid-center = Orta Merkez
preferences-mid-left = Orta Sol
preferences-mid-right = Orta Sağ
preferences-never-type-answer = Asla Cevap Yazma
preferences-next-times = Sıradaki Zamanlar
preferences-normal = Normal
preferences-notifications = Bildirimler
preferences-notifications-alert-time = Uyarı Zamanı
preferences-notifications-alert-when-due = Süresi Dolduğunda Uyar
preferences-notifications-app-icon-shows-due-count = Simgede Bekleyen Not Sayısını Gösterir
preferences-pen-size = Kalem Boyutu
preferences-question-side = Soru Tarafı
preferences-remaining-count = Kalan Sayım
preferences-right = Sağ
# gamepad
preferences-right-shoulder = Sağ omuz
# gamepad
preferences-right-thumbstick-button = Sağ Parmak Çubuğu Düğmesi
# gamepad
preferences-right-trigger = Sağ tetik
preferences-scratchpad-below-buttons = Çalışma defteri alt düğmeleri
preferences-scratchpad-transparency = Çalışma defteri saydamlığı
preferences-scratchpad-transparency-full = Tam
preferences-scratchpad-transparency-medium = Orta
preferences-scratchpad-transparency-none = Yok
preferences-scratchpad-transparency-slight = Hafif
preferences-short = Kısa
preferences-show-bottom-bar = Alt Çubuğu Göster
preferences-show-grid = Sistemi Göster
preferences-show-top-bar = Üst Çubuğu Göster
preferences-small = Küçük
preferences-theme-bar-style = Bar Sitili
preferences-theme-black = Siyah
preferences-theme-dark-translucent = Karanlık & Yarı Saydam
preferences-theme-light-translucent = Parlak ve Yarı Saydam
preferences-theme-night-mode-same-as-system = Sisteme Uy
preferences-theme-slate = Barut rengi
preferences-tools-overlay-button = Araçlar Bindirmesi Düğmesi
preferences-tools-overlay-position = Araçlar Bindirmesi Konumu
preferences-undo-clears-all = Geri Alma Her Şeyi Temizler
preferences-when-question-shown = Soru gösterildiğinde
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Maksimum Resim Boyutu (Uzun Kenar)
