preferences-about = Hakkında
preferences-autoplay-in-silent-mode = Sessiz Mod'da Otomatik Oynat
preferences-always-duck = Arka Plandaki Sesi Daima Azalt
preferences-answer-keeps-zoom = Cevap Yakınlaştırmayı Korur
preferences-answer-side = Cevap Tarafı
preferences-audio-buttons = Ses Düğmeleri
preferences-auto-advance-answer-action = Cevaplama Eylemi
preferences-auto-advance-answer-seconds = Cevap Saniyesi
preferences-auto-advance-auto-advance-to-start = Otomatik ilerlemeyi başlatmak için 'Otomatik İlerle' eylemini kullanın.
preferences-auto-advance-do-nothing = Hiçbir şey yapma
preferences-auto-advance-question-seconds = Soru Saniyeleri
preferences-backup-available-backups = Mevcut yedekler
preferences-backup-create-now = Şu an Oluştur
preferences-backup-maximum-backups = Maksimum Yedek
preferences-backup-minutes-between-backups = Yedeklemeler Arası Dakikalar
preferences-backup-revert-to-backup = Yedeğe Geri Dön
preferences-backup-revert-to-backup-confirm = { $backup } yedeğine geri dönülsün mü? Bu yedekten sonra yapılan tüm değişiklikler kaybedilecektir.
preferences-backup-reverted-to-backup = Yedeğe geri döndü.
preferences-bottom-bar-size = Alt Çubuk Boyutu
preferences-bottom-center = Alt Orta
preferences-bottom-left = Sol Alt
preferences-bottom-right = Sağ Alt
preferences-button-d = { $num } Düğmesi
preferences-collection-day-starts = Gün Başlangıcı
preferences-collection-learn-ahead-minutes = Önümüzdeki Dakikaları Öğren
preferences-collection-mix = Karma
preferences-collection-new-first = Önce yeni
preferences-collection-newreview-order = Yeni/Gözden geçirme Sırası
preferences-collection-reviews-first = Önce gözden geçirmeler
preferences-double-tap-prevention = Çift Dokunuş Önleme
preferences-open-links-externally = Bağlantıları Harici Olarak Aç
preferences-drawing-screen-ignores-fingers = Çizim ekranı parmakları yok sayar
preferences-feedback-ticks = Geri bildirim işaretleri
preferences-spread-ticks = Onay işaretlerini ayır
preferences-fine = İyi
preferences-force-sync-confirm = Tek yönlü senkronizasyonu zorla? Bir taraftaki tüm değişiklikler kaybolacak.
preferences-full-sync = Tam Senkronizasyon
preferences-gamepad-button-mapping = Düğmelerin Konumlandırması
preferences-gamepad-menu-button = Menü
preferences-gamepads = Oyun kumandaları
preferences-gamepad-thumbpad-deadzone = Başparmak pad'i ölü alan yüzdesi
preferences-height = Yükseklik
preferences-huge = Kocaman
preferences-ignore-fingers = Parmakları Yoksay
preferences-interrupt-current-audio = Geçerli Sesi Kes
preferences-large = Büyük
preferences-left = Sol
# gamepad
preferences-left-shoulder = Sol Omuz
# gamepad
preferences-left-thumbstick-button = Sol Parmak Çubuğu Düğmesi
# gamepad
preferences-left-trigger = Sol Tetik
preferences-logged-in-as = Olarak giriş yaptı:
preferences-long = Uzun
preferences-mid-center = Orta Merkez
preferences-mid-left = Orta Sol
preferences-mid-right = Orta Sağ
preferences-never-type-answer = Asla Cevap Yazma
preferences-never-show-scratchpad = Karalama defterini asla gösterme
preferences-never-show-scratchpad-enabled = Tercihler ekranında "Karalama defterini asla gösterme" seçeneği etkinleştirildi.
preferences-next-times = Sıradaki Zamanlar
preferences-normal = Normal
preferences-notifications = Bildirimler
preferences-notifications-alert-time = Uyarı Zamanı
preferences-notifications-alert-when-due = Süresi Dolduğunda Uyar
preferences-notifications-app-icon-shows-due-count = Simgede Bekleyen Not Sayısını Gösterir
preferences-notifications-settings-app-enable-notifications = Lütfen iOS Ayarlar uygulamasına gidin, Anki bölümünü bulun ve bildirimleri, rozetleri ve uyarıları etkinleştirin.
preferences-pen-size = Kalem Boyutu
preferences-question-side = Soru Tarafı
preferences-remaining-count = Kalan Sayım
preferences-right = Sağ
# gamepad
preferences-right-shoulder = Sağ omuz
# gamepad
preferences-right-thumbstick-button = Sağ Parmak Çubuğu Düğmesi
# gamepad
preferences-right-trigger = Sağ tetik
preferences-scratchpad-below-buttons = Çalışma defteri alt düğmeleri
preferences-scratchpad-transparency = Çalışma defteri saydamlığı
preferences-scratchpad-transparency-full = Tam
preferences-scratchpad-transparency-medium = Orta
preferences-scratchpad-transparency-none = Yok
preferences-scratchpad-transparency-slight = Hafif
preferences-shake-action = Sallama Eylemi
preferences-short = Kısa
preferences-show-bottom-bar = Alt Çubuğu Göster
preferences-show-grid = Sistemi Göster
preferences-show-top-bar = Üst Çubuğu Göster
preferences-small = Küçük
preferences-swipe-down = Aşağı Kaydırma
preferences-swipe-left = Sola Kaydırma
preferences-swipe-right = Sağa Kaydırma
preferences-swipe-up = Yukarı Kaydırma
preferences-swipes = Kaydırma
preferences-swipes-must-begin-from-the-far = Kaydırma işlemleri ekranın sağından veya solundan başlamalıdır.
preferences-sync-sounds-images = Senkronize Etme Ses & Görselleri
preferences-syncing = Senkronize Ediliyor
preferences-tap-to-sync = Senkronize etmek için destelerin listelendiği ekranda "Senkronize Et" tuşuna basın.
preferences-taps = Dokunuşlar
preferences-theme-bar-style = Bar Sitili
preferences-theme-black = Siyah
preferences-theme-dark-translucent = Karanlık & Yarı Saydam
preferences-theme-force-off = Zorla Kapat
preferences-theme-force-on = Zorla Aç
preferences-theme-light-translucent = Parlak ve Yarı Saydam
preferences-theme-night-mode-desc = Gece modu arayüzü karartır ve kartları siyah üzerinde beyaz olarak gösterir.
preferences-theme-night-mode-same-as-system = Sisteme Uy
preferences-theme-slate = Barut rengi
preferences-thick = Kalın
preferences-tools-overlay-button = Araçlar Bindirmesi Düğmesi
preferences-tools-overlay-position = Araçlar Bindirmesi Konumu
preferences-top-center = Üst Orta
preferences-top-left = Sol Üst
preferences-top-right = Sağ Üst
preferences-undo-clears-all = Geri Alma Her Şeyi Temizler
preferences-when-answer-shown = Yanıt görüntülendiğinde
preferences-when-question-shown = Soru gösterildiğinde
preferences-you-have-been-logged-out = Çıkış yaptınız.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Maksimum Resim Boyutu (Uzun Kenar)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Yapıştırırken Yeniden Boyutlandır
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Akıllı Tırnakları ve Tireleri Dönüştür
preferences-editing-crop-camera-photos = Kamera Fotoğrafını Kırp
preferences-loop-video = Videoyu Döngüye Al
preferences-show-video-controls = Video Kontrollerini Göster
preferences-high-quality-video = Yükesk Kaliteli Video
preferences-auto-capitalize = Otomatik Altyazı
preferences-auto-correct = Otomatik Düzeltme
preferences-strip-hebrew-vowels = İbranice Sesli Harfleri Kaldır (örn. אָ yerine א)
