actions-actions = Acțiuni
actions-add-new = Adaugă nou
actions-added-to-frequent-actions = Adăugat la acțiunile frecvente.
actions-all-actions = Toate acțiunile
actions-already-in-frequent-actions = Este deja în acțiunile frecvente.
actions-an-error-occurred = S-a produs o eroare: { $error }
actions-answer-easy = Răspuns ușor
actions-are-you-sure = Ești sigur?
actions-bottom-bar = Bara de jos
actions-browse = Răsfoiește
actions-card-buried = Card îngropat
actions-card-suspended = Card suspendat
actions-card-template = Șablon de card
actions-confirm-delete = Confirmă ștergerea
actions-create = Crează
actions-current-audio-minus-5s = Audio curent -5s
actions-current-audio-plus-5s = Audio curent +5s
actions-custom-study-cant-be-used-on = Studiul personalizat nu poate fi folosit pe un pachet filtrat.
actions-deck-statistics = Statisticile pachetului
actions-delete-note-and-its-cards = Ștergi notița și cardurile sale?
actions-discard-changes = Renunță la modificări
actions-done = Efectuat
actions-downloading = Se descarcă
actions-drag-here-to-remove = Trage aici pentru a elimina
actions-draw = Desenează
actions-file-invalid-or-corrupt = Fișier invalid sau corupt.
actions-filtercram = Filtru / Înghesuire
actions-filtered-deck = Pachet filtrat { $num }
actions-forgot-card = Uită cardul
actions-frequent-actions = Acțiuni frecvente
actions-leave-without-saving = Ieși fără a salva?
actions-long-press-on-an-item-to = Apăsă lung pe un articol pentru a personaliza.
actions-mark = Marchează
actions-mark-and-bury = Marchează + Îngroapă
actions-mark-and-suspend = Marchează + Suspendă
actions-marked = Marcat
actions-no-current-card = Fără card curent.
actions-no-load-restore-backup = Colecția ta nu a putut fi încărcată. Restaurează dintr-o copie de rezervă automată prin ecranul de preferințe.
# (http://example.com) does not appear to be...
actions-not-valid-link = nu pare a fi un link http/https valid.
actions-note-and-its-cards-deleted = Notița și cardurile sale { $count } au fost șterse
actions-note-and-its-cards-suspended = Notă și cardurile sale { $count } au fost suspendate
actions-note-buried = Notiță îngropată
actions-note-marked-and-buried = Notiță marcată și îngropată
actions-off = Oprit
actions-please-tap-the-in-the = e rog să atingi „?” în stânga sus pentru a începe.
actions-processing = Se procesează...
actions-record-voice = Înregistrează voce
actions-record-voice-menu = Meniu înregistrare voce
actions-reset-card = Resetează card
actions-revert = Revenire
actions-review-undone = Recenzia anulată
actions-scratchpad = Carnet pentru notițe
actions-scratchpad-size = Dimensiunea carnetului pentru notițe
actions-select-deck = Selectează pachetul
actions-select-note-type = Selectează tipul notiței
actions-show-answeranswer-good = Arată răspunsul /Răspuns bun
actions-study-options = Opțiuni de studiu
actions-tools = Instrumente
actions-tools-overlay = Strat intrumente
actions-top-bar = Bara de sus
actions-unbury-deck = Dezgroapă pachet
actions-undo = Anulează
actions-unmarked = Nemarcat
actions-you-can-only-empty-a-filtered = Poți goli doar un pachet filtrat.
actions-you-can-only-rebuild-a-filtered = Poți reconstrui doar un pachet filtrat.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Golește
# create a filtered deck
actions-filter-short = Filtrează
actions-add-short = Adaugă
actions-answer-again-short = Încă o dată
actions-answer-easy-short = Ușor
actions-answer-good-short = Bine
actions-answer-hard-short = Dificil
actions-auto-advance-short = Autoavans
actions-bottom-bar-short = Bară.but.
actions-browse-short = Răsfoiește
actions-bury-card-short = Îngroapă.c
actions-bury-note-short = Îngroapă.N
actions-card-info-short = C.Info
actions-card-template-short = Șablon
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Personalizat
actions-deck-statistics-short = P.stat.
actions-decks-short = Pachete
actions-delete-note-short = Șterg
actions-edit-short = Edit
actions-mark-and-bury-short = M&Î.
actions-mark-and-suspend-short = M&S
actions-mark-short = Marc
actions-night-mode-short = Noapte
actions-off-short = Oprit
actions-pause-audio-short = Pauză
actions-rebuild-short = Reconstr
actions-record-voice-short = Înreg.V.
actions-replay-voice-short = Redă.V.
actions-replay-audio-short = Redă
actions-reset-card-short = Reset.C.
actions-scratchpad-short = Pad
actions-scratchpad-size-short = D.Pad
actions-set-due-date-short = S.Dată
actions-show-answer-short = Ar.Răsp
actions-show-answeranswer-good-short = Ar/Răs.B
actions-study-options-short = Ar.Opt
actions-suspend-card-short = Susp.C
actions-suspend-note-short = Susp.N
actions-tools-short = Instr
actions-top-bar-short = BaraS
actions-unbury-deck-short = Dezgr
actions-undo-short = Anul
actions-redo-short = Refă
