decks-a-deck-must-be-provided = Trebuie furnizat un pachet
decks-a-deck-named-already-exists = Un pachet numit „{ $name }” există deja.
decks-a-deck-with-that-name-already = Un pachet cu acest nume există deja.
decks-add-deck = Adaugă pachet
decks-add-empty-deck = Adaugă pachet gol
decks-addexport = Adaugă/Exportă
decks-cannot-delete = Nu se poate șterge
decks-card-limit = Limită card
decks-cards-in-a-filtered-deck-cant = Cardurile dintr-un pachet filtrat nu pot fi mutate.
decks-custom-steps = Pași personalizați
decks-deck-exists = Pachetul există
decks-deck-label = Pachet:
decks-deck-name = Numele pachetului
decks-deck-options = Opțiuni pachet
decks-download-link = Descarcă link
decks-export-collection = Exportă colectia
decks-filtered-deck = Pachet filtrat
decks-import-from-itunes = Importă din  iTunes
decks-invalid-deck-name = Nume pachet invalid.
decks-link-to-apkg-file-to-import = Link către fișierul .apkg de importat:
decks-no-matches = Nu sunt potriviri
decks-return-by-delete = Pentru a returna toate cardurile simultan, glisează peste pachetul albastru din lista de pachete și șterge-l.
decks-shared-deck-list = Listă de pachete partajată
decks-sync = Sincronizare
decks-synchronize = Sincronizează
decks-the-default-deck-cannot-be-deleted = Pachetul implicit nu poate fi șters.
decks-the-provided-deck-does-not-exist = Pachetul furnizat nu există.
decks-the-search-you-provided-did-not = Căutarea pe care ai furnizat-o nu s-a potrivit cu niciun card.
decks-will-be-returned = Cardurile vor fi returnate în pachetul original pe măsură ce răspunzi la ele.
