deck-options-add-options-group = Adaugă grup de opțiuni
deck-options-answer-time-cap = Limita timpului de răspuns
deck-options-bury-related-new-cards = Îngroapă carduri noi înrudite
deck-options-bury-related-reviews = Îngroapă carduri de revăzut înrudite
deck-options-defaults = Implicite
deck-options-delete-options-full-sync = Ștergerea acestui grup de opțiuni va împiedica îmbinarea oricăror modificări de la alte dispozitive la următoarea sincronizare. Continui?
deck-options-display-in-order-added = Afișare în ordine adăugării
deck-options-display-in-random-order = Afișare în ordine aleatorie
deck-options-full-sync-required = Sincronizarea completă este necesară
deck-options-group-name = Numele grupului
deck-options-max-new-per-day = Număr noi maxim pe zi
deck-options-max-reviews-per-day = Maxim carduri de repatat pe zi
deck-options-new-cards = Carduri noi
deck-options-options-group = Grup de opțiuni
deck-options-replay-q-audio-in-answer = Reluare audio ca răspuns
deck-options-reset-all-settings-to-defaults = Resetezi toate setările la valorile implicite?
deck-options-restore-defaults = Restabilire setări implicite
deck-options-steps = Pași
