exporting-collection-saved-to-itunes = Colecția a fost salvată îniTunes.
exporting-export-to-itunes = Exportați îniTunes
exporting-export-to-share-sheet = Exportă în Share Sheet
exporting-exporting = Se exportă...
exporting-include-media2 = Include media
exporting-media-files-exported-d = Fișiere media exportate: { $count }...
