preferences-about = Despre
preferences-answer-keeps-zoom = Răspunsul păstrează zoomul
preferences-answer-side = Partea de răspuns
preferences-audio-buttons = Butoane audio
preferences-auto-advance-answer-action = Actiune răspuns
preferences-auto-advance-answer-seconds = Secunde răspuns
preferences-auto-advance-auto-advance-to-start = Pentru a începe automat avansarea, utilizați acțiunea „Avansare automată”.
preferences-auto-advance-do-nothing = Nu fă nimic
preferences-auto-advance-question-seconds = Secunde întrebare
preferences-backup-available-backups = Copii de rezervă disponibile
preferences-backup-create-now = Crează acum
preferences-backup-maximum-backups = Nr, maxim de copii de rezervă
preferences-backup-minutes-between-backups = Minute între copii de rezervă
preferences-backup-revert-to-backup = Reveniți la copie de rezervă
preferences-backup-revert-to-backup-confirm = Reveniți la { $backup }? Orice modificare făcută dincolo de copia de rezervă se va pierde.
preferences-backup-reverted-to-backup = S-a revenit la copia de rezervă.
preferences-bottom-bar-size = Dimensiunea barei de jos
preferences-bottom-center = Centru jos
preferences-bottom-left = Stânga jos
preferences-bottom-right = Dreapta jos
preferences-button-d = Buton { $num }
preferences-collection-day-starts = Ziua începe la
preferences-collection-learn-ahead-minutes = Minute învață înainte
preferences-collection-mix = Mix
preferences-collection-new-first = Noi primele
preferences-collection-newreview-order = Noi/Ordine Repetare
preferences-collection-reviews-first = De repetat primele
preferences-double-tap-prevention = Prevenirea atingerii duble
preferences-drawing-screen-ignores-fingers = Ecranul de desen ignoră degetele
preferences-feedback-ticks = Răspuns tactil selecție
preferences-fine = Fin
preferences-force-sync-confirm = Forțați o sincronizare unidirecțională? Toate modificările de pe o parte se vor pierde.
preferences-full-sync = Sincronizare totală
preferences-gamepad-button-mapping = Atribuire butoane
preferences-gamepad-menu-button = Meniu
preferences-gamepads = Gamepad-uri
preferences-height = Înălțime
preferences-huge = Uriaș
preferences-ignore-fingers = Ignoră degetele
preferences-interrupt-current-audio = Întreruperea sunetului curent
preferences-large = Mare
preferences-left = Stânga
# gamepad
preferences-left-shoulder = Umăr stâng
# gamepad
preferences-left-thumbstick-button = Butonul stick-ului din stânga
# gamepad
preferences-left-trigger = Trăgaci stâng
preferences-logged-in-as = Conectat ca:
preferences-long = Lung
preferences-mid-center = Centru mijloc
preferences-mid-left = Centru stanga
preferences-mid-right = Mijloc dreapta
preferences-never-type-answer = Nu tasta niciodată răspuns
preferences-never-show-scratchpad = Nu afișa niciodată carnetul de notițe
preferences-never-show-scratchpad-enabled = Nu se afișează niciodată ”carnetul de notițe” este activat în ecranul Preferințe.
preferences-next-times = Dățile viitoare
preferences-normal = Normal
preferences-notifications = Notificări
preferences-notifications-alert-time = Timpul alertei
preferences-notifications-alert-when-due = Alertează când vine scadența
preferences-notifications-app-icon-shows-due-count = Pictograma aplicației arată numărul cardurilor scadente
preferences-notifications-settings-app-enable-notifications = Accesați aplicația Setări iOS, localizați secțiunea Anki și activați notificările, insignele și alertele.
preferences-pen-size = Grosimea stiloului
preferences-question-side = Partea pentru întrebări
preferences-remaining-count = Numărul rămas
preferences-right = Dreapta
# gamepad
preferences-right-shoulder = Umărul drept
# gamepad
preferences-right-thumbstick-button = Butonul stick-ului dreapta
# gamepad
preferences-right-trigger = Trăgaciul drept
preferences-scratchpad-below-buttons = Butoanele de sub ”Carnetul pentru notițe”
preferences-scratchpad-transparency = Transparența ”Carnetului pentru notițe”
preferences-scratchpad-transparency-full = Plin
preferences-scratchpad-transparency-medium = Mediu
preferences-scratchpad-transparency-none = Deloc
preferences-scratchpad-transparency-slight = Ușor
preferences-shake-action = Acțiune șarpe
preferences-short = Scurt
preferences-show-bottom-bar = Arată bara de butoane
preferences-show-grid = Arată grila
preferences-show-top-bar = Arată bara de sus
preferences-small = Mic
preferences-swipe-down = Glisați în jos
preferences-swipe-left = Glisați la stânga
preferences-swipe-right = Glisați la dreapta
preferences-swipe-up = Glisați în sus
preferences-swipes = Glisări
preferences-swipes-must-begin-from-the-far = Glisările trebuie să înceapă din extrema stângă sau dreapta a ecranului.
preferences-sync-sounds-images = Sincronizați sunete și imagini
preferences-syncing = Sincronizare
preferences-tap-to-sync = Pentru a activa sincronizarea, atingeți butonul de sincronizare de pe ecranul listei de deck.
preferences-taps = Apăsări
preferences-theme-bar-style = Stilul barei
preferences-theme-black = Negru
preferences-theme-dark-translucent = Întunecat și transparent
preferences-theme-force-off = Dezactivare forțată
preferences-theme-force-on = Activare forțată
preferences-theme-light-translucent = Luminos și transparent
preferences-theme-night-mode-desc = Modul noapte întunecă interfața și afișează cardurile ca alb pe negru.
preferences-theme-night-mode-same-as-system = Urmează sistemul
preferences-theme-slate = Ardezie
preferences-thick = Gros
preferences-tools-overlay-button = Strat butoane pentru Instrumente
preferences-tools-overlay-position = Pozitia stratului cu instrumente
preferences-top-center = Centru sus
preferences-top-left = Stânga sus
preferences-top-right = Dreapta sus
preferences-undo-clears-all = Anulare Șterge toate
preferences-when-answer-shown = Când se afișează răspunsul
preferences-when-question-shown = Când întrebarea este afișată
preferences-you-have-been-logged-out = Ai fost deconectat.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Dimensiunea maximă a imaginii (latura lungă)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Redimensionați la lipire
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Convertiți citate și liniuțe inteligente
preferences-editing-crop-camera-photos = Decupați fotografiile camerei
