profiles-a-profile-with-that-name-already = Un profil cu acest nume există deja.
profiles-add-profile = Adaugă profil
profiles-creating-backup = Se crează copie de rezervă...
profiles-finishing-backup = Se finalizează copia de rezervă...
profiles-please-provide-some-text-avoiding-symbols = Vă rugăm să furnizați ceva text, evitând simbolurile și liniutele de subliniere.
profiles-please-select-another-profile-first = Vă rugăm să selectați mai întâi alt profil.
profiles-profile-name = Numele profilului
profiles-rename-profile = Redenumește profilul
profiles-unable-to-open-safari-please = Nu se poate deschide Safari - vă rugăm să verificați controlul parental.
profiles-welcome = Bun venit!
