actions-actions = Дії
actions-add-new = Додати нову
actions-added-to-frequent-actions = Додано до частих дій.
actions-all-actions = Усі дії
actions-already-in-frequent-actions = Вже в частих діях
actions-an-error-occurred = Сталася помилка: { $error }
actions-answer-easy = Відповідь легка
actions-are-you-sure = Впевнені?
actions-bottom-bar = Нижня панель
actions-browse = Навігатор
actions-card-buried = Картку сховано
actions-card-suspended = Картку призупинено
actions-card-template = Шаблон картки
actions-confirm-delete = Підтвердьте видалення
actions-create = Створити
actions-current-audio-minus-5s = Поточне аудіо -5 с
actions-current-audio-plus-5s = Поточне аудіо +5 с
actions-custom-study-cant-be-used-on = Спеціальне навчання не можна використовувати для відфільтрованої колоди.
actions-deck-statistics = Статистика колоди
actions-delete-note-and-its-cards = Видалити нотатку та її картки?
actions-discard-changes = Скасувати зміни
actions-done = Зроблено
actions-downloading = Завантаження...
actions-drag-here-to-remove = Перетягніть сюди, щоб видалити
actions-draw = Тягти
actions-file-invalid-or-corrupt = Файл недійсний або пошкоджений.
actions-filtercram = Фільтр/Виповнити
actions-filtered-deck = Відфільтрована колода { $num }
actions-frequent-actions = Часті дії
actions-leave-without-saving = Вийти без збереження?
actions-long-press-on-an-item-to = Натисніть і утримуйте елемент, щоб налаштувати.
actions-mark = Позначка
actions-mark-and-bury = Позначити + Сховати
actions-mark-and-suspend = Позначити + призупинити
actions-marked = Позначено
actions-no-current-card = Немає актуальної картки.
actions-no-load-restore-backup = Не вдалося завантажити вашу колекцію. Відновіть із автоматичної резервної копії на екрані налаштувань.
# (http://example.com) does not appear to be...
actions-not-valid-link = не є дійсним посиланням http/https.
actions-note-and-its-cards-deleted = Нотатка і її { $count } карток видалено
actions-note-and-its-cards-suspended = Нотатка і її { $count } картка/картки/карток призупинено
actions-note-buried = Нотатку сховано
actions-note-marked-and-buried = Нотатку позначено та сховано
actions-off = Вимикнено
actions-please-tap-the-in-the = Торкніться «?» у верхньому лівому куті, щоб почати.
actions-processing = Обробка даних...
actions-record-voice = Запис голосу
actions-record-voice-menu = Меню запису голоса
actions-reset-card = Скинути картку
actions-revert = Повернути
actions-review-undone = Перевірку скасовано
actions-scratchpad = Блокнот
actions-scratchpad-size = Розмір блокнота
actions-select-deck = Вибрати колоду
actions-select-note-type = Вибрати тип нотатки
actions-show-answeranswer-good = Показати відповідь/Відповідь добра
actions-study-options = Опції навчання
actions-tools = Інструменти
actions-tools-overlay = Накладання інструментів
actions-top-bar = Верхня панель
actions-unbury-deck = Показати колоду
actions-undo = Скасувати
actions-unmarked = Відмітку знято
actions-you-can-only-empty-a-filtered = Ви можете спорожнити лише відфільтровану колоду.
actions-you-can-only-rebuild-a-filtered = Ви можете відновити лише відфільтровану колоду.
actions-scroll-up = Прокрутити вгору
actions-scroll-down = Прокрутити вниз

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Порожньо
# create a filtered deck
actions-filter-short = Фільтр
actions-add-short = Додати
actions-answer-again-short = Знову
actions-answer-easy-short = Легко
actions-answer-good-short = Добре
actions-answer-hard-short = Складно
actions-auto-advance-short = Автопер.
actions-bottom-bar-short = Ниж. Пан.
actions-browse-short = Перегляд
actions-bury-card-short = Відкл.К.
actions-bury-note-short = Відкл.Н.
actions-card-info-short = К.Інфо
actions-card-template-short = Шаблон
actions-current-audio-minus-5s-short = -5с
actions-current-audio-plus-5s-short = +5с
actions-custom-study-short = Власна
actions-deck-statistics-short = Ко.Стат.
actions-decks-short = Колоди
actions-delete-note-short = Вид
actions-edit-short = Ред.
actions-mark-and-bury-short = M&B
actions-mark-and-suspend-short = M&S
actions-mark-short = Позначка
actions-night-mode-short = Нічний
actions-off-short = Вимикнено
actions-pause-audio-short = Пауза
actions-rebuild-short = Перебудувати
actions-record-voice-short = Запис.V
actions-replay-voice-short = Повт.V
actions-replay-audio-short = Повторити
actions-reset-card-short = Скинути.С
actions-scratchpad-short = Блок
actions-scratchpad-size-short = Блок.Кор
actions-set-due-date-short = К.Дата
actions-show-answer-short = К.Відп
actions-show-answeranswer-good-short = Показати/Відп
actions-study-options-short = С.Опц
actions-suspend-card-short = Пз.К
actions-suspend-note-short = Пз.Н
actions-tools-short = Інструменти
actions-top-bar-short = В.Панель
actions-unbury-deck-short = Показати
actions-undo-short = Скасувати
actions-redo-short = Повернути
actions-scroll-up-short = Вгору
actions-scroll-down-short = Вниз
actions-back = Назад
