deck-options-add-options-group = Додати групу параметрів
deck-options-answer-time-cap = Обмеження часу відповіді
deck-options-bury-related-new-cards = Сховати пов'язані нові картки
deck-options-bury-related-reviews = Сховати відповідні перегляди
deck-options-defaults = За замовчуванням
deck-options-delete-options-full-sync = Видалення цієї групи параметрів запобіжить об’єднанню будь-яких змін з інших пристроїв під час наступної синхронізації. Продовжити?
deck-options-display-in-order-added = Показати в порядку додавання
deck-options-display-in-random-order = Відображення в довільному порядку
deck-options-full-sync-required = Потрібна повна синхронізація
deck-options-group-name = Назва групи
deck-options-max-new-per-day = Макс нових за день
deck-options-max-reviews-per-day = Макс. переглядів на день
deck-options-new-cards = Нові картки
deck-options-options-group = Група параметрів
deck-options-replay-q-audio-in-answer = Повторити шв. аудіо у відповіді
deck-options-reset-all-settings-to-defaults = Відновити всі налаштування до значень за замовчуванням?
deck-options-restore-defaults = Відновити значення за замовчуванням
deck-options-steps = Кроки
