decks-a-deck-must-be-provided = Необхідно додати колоду.
decks-a-deck-named-already-exists = Колода із назвою '{ $name }' вже існує.
decks-a-deck-with-that-name-already = Колода з такою назвою вже існує.
decks-add-deck = Додати колоду
decks-add-empty-deck = Додати порожню колоду
decks-addexport = Додати/Експорт
decks-cannot-delete = Неможливо видалити
decks-card-limit = Ліміт картки
decks-cards-in-a-filtered-deck-cant = Карти у відфільтрованій колоді не можна переміщати.
decks-custom-steps = Спеціальні кроки
decks-deck-exists = Колода існує
decks-deck-label = Колода:
decks-deck-name = Назва колоди
decks-deck-options = Налаштування колоди
decks-download-link = Посилання для завантаження
decks-export-collection = Експорт колекції
decks-filtered-deck = Відфільтрована колода
decks-import-from-itunes = Імпортувати з iTunes
decks-invalid-deck-name = Недійсна назва колоди.
decks-link-to-apkg-file-to-import = Посилання на файл .apkg для імпорту:
decks-no-matches = Немає збігів
decks-return-by-delete = Щоб повернути всі картки одночасно, проведіть пальцем по синій колоді в списку колод і видаліть її.
decks-shared-deck-list = Спільний список колод
decks-sync = Синхронізація
decks-synchronize = Синхронизація
decks-the-default-deck-cannot-be-deleted = Колоду за замовчуванням не можна видалити.
decks-the-provided-deck-does-not-exist = Наданої колоди не існує.
decks-the-search-you-provided-did-not = З даним пошуковим запитом не знайдено жодної картки.
decks-will-be-returned = Після перегляду картки повернуться до своєї колоди
