decks-a-deck-must-be-provided = Необхідно вказати колоду.
decks-a-deck-named-already-exists = Колода '{ $name }' вже існує.
decks-a-deck-with-that-name-already = Колода з таким іменем вже існує.
decks-add-deck = Додати колоду
decks-add-empty-deck = Додати порожню колоду
decks-addexport = Додати/Експортувати
decks-cannot-delete = Неможливо видалити
decks-card-limit = Ліміт картки
decks-cards-in-a-filtered-deck-cant = Карти у відфільтрованій колоді не можна переміщати.
decks-custom-steps = Спеціальні кроки
decks-deck-exists = Колода існує
decks-deck-label = Колода:
decks-deck-name = Назва колоди
decks-deck-options = Налаштування колоди
decks-download-link = Покликання для завантаження
decks-export-collection = Експорт колекції
decks-filtered-deck = Відфільтрована колода
decks-import-from-itunes = Імпортувати з iTunes
decks-invalid-deck-name = Неправильна назва колоди.
decks-link-to-apkg-file-to-import = Покликання на файл .apkg для імпорту:
decks-no-matches = Немає збігів
decks-return-by-delete = Щоб повернути всі картки одночасно, проведіть пальцем по синій колоді в списку колод і видаліть її.
decks-shared-deck-list = Список спільних колод
decks-sync = Синхронізація
decks-synchronize = Синхронізувати
decks-the-default-deck-cannot-be-deleted = Типову колоду не можна видалити.
decks-the-provided-deck-does-not-exist = Вказаної колоди не існує.
decks-the-search-you-provided-did-not = За Вашим пошуковим запитом немає жодної картки.
decks-will-be-returned = Після відповіді картки повертатимуться до своїх колод.
