deck-options-add-options-group = Додати групу налаштувань
deck-options-answer-time-cap = Обмеження часу відповіді
deck-options-bury-related-new-cards = Відкладати пов'язані нові картки
deck-options-bury-related-reviews = Відкладати пов'язані пригадування
deck-options-defaults = Типово
deck-options-delete-options-full-sync = Видалення цієї групи налаштувань унеможливить об’єднання змін з інших пристроїв при наступній синхронізації. Продовжити?
deck-options-display-in-order-added = Показати в порядку додавання
deck-options-display-in-random-order = Показати в довільному порядку
deck-options-full-sync-required = Потрібна повна синхронізація
deck-options-group-name = Назва групи
deck-options-max-new-per-day = Макс нових за день
deck-options-max-reviews-per-day = Макс. переглядів на день
deck-options-new-cards = Нові картки
deck-options-options-group = Група параметрів
deck-options-replay-q-audio-in-answer = Повторити шв. аудіо у відповіді
deck-options-reset-all-settings-to-defaults = Скинути всі налаштування до типових значень?
deck-options-restore-defaults = Відновити типові значення
deck-options-steps = Кроки
