exporting-collection-saved-to-itunes = Колекція збережена в iTunes.
exporting-export-to-itunes = Експортувати в iTunes
exporting-export-to-share-sheet = Експорт на аркуш спільного доступу
exporting-exporting = Експорт...
exporting-include-media2 = Включити Медіа
exporting-media-files-exported-d = Експортовано мультимедіа файлів: { $count }...
