preferences-about = Про опції
preferences-autoplay-in-silent-mode = Автовідтворення в беззвучному режимі
preferences-always-duck = Завжди фон качки
preferences-answer-keeps-zoom = Відповідь Зберігати масштаб
preferences-answer-side = Сторона відповіді
preferences-audio-buttons = Аудіо кнопки
preferences-auto-advance-answer-action = Відповідь Дія
preferences-auto-advance-answer-seconds = Секунди відповіді
preferences-auto-advance-auto-advance-to-start = Щоб почати автоматичний перехід, скористайтеся дією «Автоматичний перехід».
preferences-auto-advance-do-nothing = Нічого не робити
preferences-auto-advance-question-seconds = Секунди питання
preferences-backup-available-backups = Доступні резервні копії
preferences-backup-create-now = Створити зараз
preferences-backup-maximum-backups = Максимальна кількість резервних копій
preferences-backup-minutes-between-backups = Хвилини між резервними копіями
preferences-backup-revert-to-backup = Повернути резервну копію
preferences-backup-revert-to-backup-confirm = Повернути { $backup }? Будь-які зміни, внесені після створення резервної копії, буде втрачено.
preferences-backup-reverted-to-backup = Повернуто до резервної копії.
preferences-bottom-bar-size = Розмір нижньої панелі
preferences-bottom-center = Внизу в центрі
preferences-bottom-left = Внизу ліворуч
preferences-bottom-right = Внизу праворуч
preferences-button-d = Кнопка { $num }
preferences-collection-day-starts = Початок
preferences-collection-learn-ahead-minutes = Хвилин вивчати
preferences-collection-mix = Мікс
preferences-collection-new-first = Спершу нове
preferences-collection-newreview-order = Нове/Переглянути порядок
preferences-collection-reviews-first = Спочатку переглянуте
preferences-double-tap-prevention = Запобігання подвійному натисканню
preferences-drawing-screen-ignores-fingers = Ігнорувати малювання по екрану
preferences-feedback-ticks = Тики зворотного зв'язку
preferences-spread-ticks = Тики поширення
preferences-fine = Точно
preferences-force-sync-confirm = Примусова одностороння синхронізація? Усі зміни з одного боку буде втрачено.
preferences-full-sync = Одностороння синхронізація
preferences-gamepad-button-mapping = Відображення кнопок
preferences-gamepad-menu-button = Меню
preferences-gamepads = Джойстики
preferences-gamepad-thumbpad-deadzone = Мертва зона для великого пальця %
preferences-height = Висота
preferences-huge = Великість
preferences-ignore-fingers = Ігнорувати пальці
preferences-interrupt-current-audio = Переривання поточного аудіо
preferences-large = Великий
preferences-left = Ліворуч
# gamepad
preferences-left-shoulder = Ліве плече
# gamepad
preferences-left-thumbstick-button = Ліва кнопка великого пальця
# gamepad
preferences-left-trigger = Лівий тригер
preferences-logged-in-as = Ви увійшли як:
preferences-long = Довжина
preferences-mid-center = Посередині
preferences-mid-left = Посередині зліва
preferences-mid-right = Посередині справа
preferences-never-type-answer = Ніколи не вводити відповідь
preferences-never-show-scratchpad = Ніколи не показувати Scratchpad
preferences-never-show-scratchpad-enabled = Ніколи не показувати Scratchpad якщо увімкнено на екрані налаштувань.
preferences-next-times = Наступні рази
preferences-normal = Звичайний
preferences-notifications = Повідомлення
preferences-notifications-alert-time = Час сповіщення
preferences-notifications-alert-when-due = Термін сповіщення
preferences-notifications-app-icon-shows-due-count = Іконка програми показує належний підрахунок
preferences-notifications-settings-app-enable-notifications = Перейдіть у програму налаштувань iOS, знайдіть розділ Anki та ввімкніть сповіщення, значки та попередження.
preferences-pen-size = Розмір пера
preferences-question-side = Сторона питання
preferences-remaining-count = Підрахунок Залишилось
preferences-right = Праворуч
# gamepad
preferences-right-shoulder = Праве плече
# gamepad
preferences-right-thumbstick-button = Права кнопка великого пальця
# gamepad
preferences-right-trigger = Правий тригер
preferences-scratchpad-below-buttons = Блокнот під кнопками
preferences-scratchpad-transparency = Прозорість блокнота
preferences-scratchpad-transparency-full = Повне
preferences-scratchpad-transparency-medium = Середнє
preferences-scratchpad-transparency-none = Ні
preferences-scratchpad-transparency-slight = Незначне
