preferences-about = Про опції
preferences-autoplay-in-silent-mode = Автовідтворення в беззвучному режимі
preferences-always-duck = Завжди фон качки
preferences-answer-keeps-zoom = Відповідь зберігає масштаб
preferences-answer-side = Сторона відповіді
preferences-audio-buttons = Аудіо кнопки
preferences-auto-advance-answer-action = Дія при відповіді
preferences-auto-advance-answer-seconds = Секунд на відповідь
preferences-auto-advance-auto-advance-to-start = Щоб почати автоматичний перехід, скористайтеся дією «Автоматичний перехід».
preferences-auto-advance-do-nothing = Нічого не робити
preferences-auto-advance-question-seconds = Секунд на запитання
preferences-backup-available-backups = Доступні резервні копії
preferences-backup-create-now = Створити зараз
preferences-backup-maximum-backups = Максимум резервних копій
preferences-backup-minutes-between-backups = Хвилин між резервними копіями
preferences-backup-revert-to-backup = Відновити з резервної копії
preferences-backup-revert-to-backup-confirm = Відновити з { $backup }? Зміни, внесені після створення резервної копії, буде втрачено.
preferences-backup-reverted-to-backup = Відновлено з резервної копії.
preferences-bottom-bar-size = Розмір нижньої панелі
preferences-bottom-center = Внизу в центрі
preferences-bottom-left = Внизу ліворуч
preferences-bottom-right = Внизу праворуч
preferences-button-d = Кнопка { $num }
preferences-collection-day-starts = Початок дня
preferences-collection-learn-ahead-minutes = Вчити хвилин наперед
preferences-collection-mix = Мікс
preferences-collection-new-first = Спершу нове
preferences-collection-newreview-order = Порядок нових/пригадувальних
preferences-collection-reviews-first = Спочатку пригадувальні
preferences-double-tap-prevention = Запобігати подвійному натисканню
preferences-open-links-externally = Відкрити у браузері
preferences-drawing-screen-ignores-fingers = Ігнорувати пальці на екрані малювання
preferences-feedback-ticks = Вібрація при натиску
preferences-spread-ticks = Тики поширення
preferences-fine = Точно
preferences-force-sync-confirm = Примусова одностороння синхронізація? Усі зміни з одного боку буде втрачено.
preferences-full-sync = Одностороння синхронізація
preferences-gamepad-button-mapping = Відображення кнопок
preferences-gamepad-menu-button = Меню
preferences-gamepads = Джойстики
preferences-gamepad-thumbpad-deadzone = Мертва зона для великого пальця %
preferences-height = Висота
preferences-huge = Великість
preferences-ignore-fingers = Ігнорувати пальці
preferences-interrupt-current-audio = Переривання поточного аудіо
preferences-large = Великий
preferences-left = Ліворуч
# gamepad
preferences-left-shoulder = Ліве плече
# gamepad
preferences-left-thumbstick-button = Ліва кнопка великого пальця
# gamepad
preferences-left-trigger = Лівий тригер
preferences-logged-in-as = Ви увійшли як:
preferences-long = Довжина
preferences-mid-center = Посередині
preferences-mid-left = Посередині зліва
preferences-mid-right = Посередині справа
preferences-never-type-answer = Ніколи не вводити відповідь
preferences-never-show-scratchpad = Ніколи не показувати Scratchpad
preferences-never-show-scratchpad-enabled = Ніколи не показувати Scratchpad якщо увімкнено на екрані налаштувань.
preferences-next-times = Наступні рази
preferences-normal = Звичайний
preferences-notifications = Повідомлення
preferences-notifications-alert-time = Час сповіщення
preferences-notifications-alert-when-due = Термін сповіщення
preferences-notifications-app-icon-shows-due-count = Іконка програми показує належний підрахунок
preferences-notifications-settings-app-enable-notifications = Перейдіть у програму налаштувань iOS, знайдіть розділ Anki та ввімкніть сповіщення, значки та попередження.
preferences-pen-size = Розмір пера
preferences-question-side = Сторона питання
preferences-remaining-count = Підрахунок Залишилось
preferences-right = Праворуч
# gamepad
preferences-right-shoulder = Праве плече
# gamepad
preferences-right-thumbstick-button = Права кнопка великого пальця
# gamepad
preferences-right-trigger = Правий тригер
preferences-scratchpad-below-buttons = Блокнот під кнопками
preferences-scratchpad-transparency = Прозорість блокнота
preferences-scratchpad-transparency-full = Повне
preferences-scratchpad-transparency-medium = Середнє
preferences-scratchpad-transparency-none = Ні
preferences-scratchpad-transparency-slight = Незначне
preferences-shake-action = Дія при струсі
preferences-short = Коротке
preferences-show-bottom-bar = Показати нижню панель
preferences-show-grid = Показати сітку
preferences-show-top-bar = Показати верхню панель
preferences-small = Маленьке
preferences-swipe-down = Проведіть пальцем вниз
preferences-swipe-left = Проведіть пальцем вліво
preferences-swipe-right = Проведіть праворуч
preferences-swipe-up = Проведіть пальцем вгору
preferences-swipes = Свайпи
preferences-swipes-must-begin-from-the-far = Гортання потрібно починати з крайнього лівого або правого краю екрана.
preferences-sync-sounds-images = Синхронізація звуків і зображень
preferences-syncing = Синхронізація
preferences-tap-to-sync = Щоб активувати синхронізацію, торкніться кнопки синхронізації на екрані списку колод.
preferences-taps = Тапи
preferences-theme-bar-style = Стиль панелі
preferences-theme-black = Чорний
preferences-theme-dark-translucent = Темний і напівпрозорий
preferences-theme-force-off = Примусово вимкнути
preferences-theme-force-on = Примусово ввімкнути
preferences-theme-light-translucent = Світлий і напівпрозорий
preferences-theme-night-mode-desc = Нічний режим затемнює інтерфейс і відображає картки білим на чорному.
preferences-theme-night-mode-same-as-system = Згідно із системними
preferences-theme-slate = Висувати
preferences-thick = Товстий
preferences-tools-overlay-button = Кнопка накладання інструментів
preferences-tools-overlay-position = Інструменти накладання позиції
preferences-top-center = Верх центр
preferences-top-left = Верх ліворуч
preferences-top-right = Верх праворуч
preferences-undo-clears-all = Скасувати Очищає все
preferences-when-answer-shown = Коли показано відповідь
preferences-when-question-shown = Коли показано запитання
preferences-you-have-been-logged-out = Ви вийшли з системи.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Максимальний розмір зображення (довгий край)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Змінити розмір під час вставлення
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Перетворення розумних лапок і тире
preferences-editing-crop-camera-photos = Обрізати фото з камери
preferences-loop-video = Зациклити відео
preferences-show-video-controls = Показати елементи керування відео
preferences-high-quality-video = Відео високої якості
preferences-auto-capitalize = Автоматичне використання великих літер
preferences-auto-correct = Автовиправлення
preferences-strip-hebrew-vowels = Видалення голосних івриту
