actions-actions = Ak­tio­nen
actions-add-new = Neue hinzufügen
actions-added-to-frequent-actions = Zu den häu­fi­gen Ak­tio­nen hin­zu­ge­fügt.
actions-all-actions = Alle Aktionen
actions-already-in-frequent-actions = Be­rei­ts in häu­fi­ge Ak­tio­nen.
actions-an-error-occurred = Ein Feh­ler ist auf­ge­tre­ten: { $error }
actions-answer-again = \"Er­neut\" ant­wor­ten
actions-answer-easy = \"Einfach\" antworten
actions-answer-good = \"Gut\" ant­wor­ten
actions-answer-hard = \"Schwer\" ant­wor­ten
actions-are-you-sure = Sind Sie sich sich­er?
actions-auto-advance = Au­to­ma­ti­sches Fort­schrei­ten
actions-bottom-bar = Unterer Balken
actions-browse = Kartenübersicht
actions-card-buried = Karte zurückgestellt
actions-card-suspended = Karte ausgesetzt
actions-card-template = Kartenvorlage
actions-confirm-delete = Löschen bestätigen
actions-create = Erstellen
actions-current-audio-minus-5s = Audiowiedergabe zurückspulen -5s
actions-current-audio-plus-5s = Audiowiedergabe vorspulen +5s
actions-custom-study-cant-be-used-on = Benutzerdefiniertes Lernen kann nicht bei einem Auswahlstapel verwendet werden.
actions-deck-statistics = Sta­pel­sta­tis­tiken
actions-delete-note-and-its-cards = Notiz und ihre Karten löschen?
actions-discard-changes = Änderungen verwerfen
actions-done = Erledigt
actions-downloading = Es wird heruntergeladen...
actions-drag-here-to-remove = Zum Entfernen hierhin ziehen
actions-draw = Zeichnen
actions-file-invalid-or-corrupt = Datei ist ungültig oder beschädigt.
actions-filtercram = Filter/Pauken
actions-filtered-deck = Auswahlstapel { $num }
actions-forgot-card = Vergessene Karte
actions-frequent-actions = Häufige Aktionen
actions-leave-without-saving = Ohne zu speichern verlassen?
actions-long-press-on-an-item-to = Langes Drücken auf einen Eintrag zum Anpassen.
actions-mark = Kennzeichnen
actions-mark-and-bury = Kennzeichnen + zurückstellen
actions-mark-and-suspend = Kennzeichnen + aussetzen
actions-marked = Gekennzeichnet
actions-no-current-card = Keine aktuelle Karte.
actions-no-load-restore-backup = Ihre Sammlung konnte nicht geladen werden. Bitte stellen Sie eine Sicherungskopie über die Einstellungen wieder her.
# (http://example.com) does not appear to be...
actions-not-valid-link = scheint kein gültiger http/https-Link zu sein.
actions-note-and-its-cards-deleted = Notiz und ihre { $count } Karten gelöscht
actions-note-and-its-cards-suspended = Notiz und ihre { $count } Karte(n) ausgesetzt
actions-note-buried = Notiz zurückgestellt
actions-note-marked-and-buried = Notiz gekennzeichnet und zurückgestellt
actions-nothing-to-undo = Nichts zum Zurücknehmen
actions-nothing-to-redo = Nichts zum Wiederherstellen
actions-off = Aus
actions-please-tap-the-in-the = Bitte tippen Sie das '?' oben links an, um loszulegen.
actions-processing = Verarbeitung läuft …
actions-record-voice = Stimme aufnehmen
actions-record-voice-menu = Stimmaufnahme-Menü
actions-reset-card = Karte resetten
actions-revert = Zurücknehmen
actions-review-undone = Wiederholung unvollständig
actions-scratchpad = Notizblack
actions-scratchpad-size = Notizblock-Größe
actions-select-deck = Stapel auswählen
actions-select-note-type = Notiztyp auswählen
actions-show-answeranswer-good = Antwort anzeigen/\"Gut\" antworten
actions-study-options = Lern­op­tio­nen
actions-tools = Werkzeuge
actions-tools-overlay = Werkzeugeinblendung
actions-top-bar = Oberer Balken
actions-unbury-deck = Zurückstellung des Stapels aufheben
actions-undo = Rück­gängig
actions-unmarked = Nicht gekennzeichnet
actions-you-can-only-empty-a-filtered = Sie können nur einen Auswahlstapel leeren.
actions-you-can-only-rebuild-a-filtered = Sie können nur einen Auswahlstapel erneut aufbauen.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Leeren
# create a filtered deck
actions-filter-short = Auswahl
actions-add-short = Neu
actions-answer-again-short = N.antw.
actions-answer-easy-short = E.antw.
actions-answer-good-short = G.antw.
actions-answer-hard-short = S.antw.
actions-auto-advance-short = Autom. Forts.
actions-bottom-bar-short = Bot.B
actions-browse-short = Stöbern
actions-bury-card-short = K. zurückst
actions-bury-note-short = N. zurückst
actions-card-info-short = K.Info
actions-card-template-short = Vorlage
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Be­nut­zer­de­fi­niert
actions-deck-statistics-short = S.Stat.
actions-decks-short = Stapel
actions-delete-note-short = Entf
actions-edit-short = Ändern
actions-mark-and-bury-short = K&Z
actions-mark-and-suspend-short = K&A
actions-mark-short = Mark.
actions-night-mode-short = Nacht
actions-off-short = Aus
actions-pause-audio-short = Pause
actions-rebuild-short = Erneuern
actions-record-voice-short = Aufnehmen
actions-replay-voice-short = S. ern. abspl.
actions-replay-audio-short = Erneut abspielen
actions-reset-card-short = C. resetten
actions-scratchpad-short = Pad
actions-scratchpad-size-short = Padgröße
actions-set-due-date-short = S.Datum
actions-show-answer-short = S.Ant.
actions-show-answeranswer-good-short = Zeigen/Gut
actions-study-options-short = S.Opt
actions-suspend-card-short = K.auss.
actions-suspend-note-short = N.auss.
actions-tools-short = Extras
actions-top-bar-short = Leiste
actions-unbury-deck-short = AufhZurücks
actions-undo-short = Rückg.
actions-redo-short = Wiederherstellen
