actions-actions = Ak­tio­nen
actions-add-new = Neue hinzufügen
actions-added-to-frequent-actions = Zu häu­fi­gen Ak­tio­nen hin­zu­ge­fügt.
actions-all-actions = Alle Aktionen
actions-already-in-frequent-actions = Be­rei­ts in häu­fi­ge Ak­tio­nen.
actions-an-error-occurred = Ein Feh­ler ist auf­ge­tre­ten: { $error }
actions-answer-easy = mit „Einfach“ antworten
actions-are-you-sure = Bist du sich­er?
actions-bottom-bar = Unterer Balken
actions-browse = Kartenübersicht
actions-card-buried = Karte aufgeschoben
actions-card-suspended = Karte ausgeschlossen
actions-card-template = Kartenvorlage
actions-confirm-delete = Löschen bestätigen
actions-create = Erstellen
actions-current-audio-minus-5s = Audiowiedergabe zurückspulen -5s
actions-current-audio-plus-5s = Audiowiedergabe vorspulen +5s
actions-custom-study-cant-be-used-on = Benutzerdefiniertes Lernen kann nicht bei einem Auswahlstapel verwendet werden.
actions-deck-statistics = Sta­pel­sta­tis­tiken
actions-delete-note-and-its-cards = Notiz und Karten löschen?
actions-discard-changes = Änderungen verwerfen
actions-done = Erledigt
actions-downloading = Herunterladen...
actions-drag-here-to-remove = Zum Entfernen hierhin ziehen
actions-draw = Zeichnen
actions-file-invalid-or-corrupt = Datei ist ungültig oder beschädigt.
actions-filtercram = Filter/Pauken
actions-filtered-deck = Auswahlstapel { $num }
actions-frequent-actions = Häufige Aktionen
actions-leave-without-saving = Ohne zu speichern verlassen?
actions-long-press-on-an-item-to = Langes Drücken auf einen Eintrag zum Anpassen.
actions-mark = Markieren
actions-mark-and-bury = Markieren und zurückstellen
actions-mark-and-suspend = Markieren und ausschließen
actions-marked = Markiert
actions-no-current-card = Keine aktuelle Karte.
actions-no-load-restore-backup = Deine Sammlung konnte nicht geladen werden. Bitte stelle sie von einem automatischen Backup in den Einstellungen wieder her.
# (http://example.com) does not appear to be...
actions-not-valid-link = scheint kein gültiger http/https-Link zu sein.
actions-note-and-its-cards-deleted = Notiz und { $count } Karten gelöscht
actions-note-and-its-cards-suspended = Notiz und { $count } Karte(n) ausgeschlossen
actions-note-buried = Notiz zurückgestellt
actions-note-marked-and-buried = Notiz markiert und zurückgestellt
actions-off = Aus
actions-please-tap-the-in-the = Bitte tippe auf das Fragezeichen (?) oben links, um loszulegen.
actions-processing = Verarbeiten...
actions-record-voice = Sprachaufzeichnung starten
actions-record-voice-menu = Sprachaufzeichnungsmenü
actions-reset-card = Karte zurücksetzen
actions-revert = Zurücknehmen
actions-review-undone = Wiederholung unvollständig
actions-scratchpad = Notizblock
actions-scratchpad-size = Notizblock-Größe
actions-select-deck = Stapel auswählen
actions-select-note-type = Notiztyp auswählen
actions-show-answeranswer-good = Antwort anzeigen/"Gut" antworten
actions-study-options = Lern­einstellungen
actions-tools = Werkzeuge
actions-tools-overlay = Werkzeuge einblenden
actions-top-bar = Oberer Balken
actions-unbury-deck = Zurückstellung des Stapels aufheben
actions-undo = Rück­gängig
actions-unmarked = Nicht markiert
actions-you-can-only-empty-a-filtered = Du kannst nur einen Auswahlstapel leeren.
actions-you-can-only-rebuild-a-filtered = Du kannst nur einen Auswahlstapel erneut aufbauen.
actions-scroll-up = Hochscrollen
actions-scroll-down = Herunterscrollen

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Leeren
# create a filtered deck
actions-filter-short = Auswahl
actions-add-short = Neu
actions-answer-again-short = Nochmal
actions-answer-easy-short = Einfach
actions-answer-good-short = Gut
actions-answer-hard-short = Schwer
actions-auto-advance-short = Aut. Fort.
actions-bottom-bar-short = U. Blk.
actions-browse-short = Suchen
actions-bury-card-short = Kt. zurSt.
actions-bury-note-short = Nt. zurSt.
actions-card-info-short = KtSt.
actions-card-template-short = Vorl.
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Be­nut­zer­de­f.
actions-deck-statistics-short = StplStat.
actions-decks-short = Stpl.
actions-delete-note-short = Entf.
actions-edit-short = Bearb.
actions-mark-and-bury-short = M. & z.
actions-mark-and-suspend-short = M. & a.
actions-mark-short = Mark.
actions-night-mode-short = Nacht
actions-off-short = Aus
actions-pause-audio-short = Pause
actions-rebuild-short = Erneuern
actions-record-voice-short = Aufnehmen
actions-replay-voice-short = S. ern. abspl.
actions-replay-audio-short = Erneut abspielen
actions-reset-card-short = K.zurücksetzen
actions-scratchpad-short = Pad
actions-scratchpad-size-short = Padgröße
actions-set-due-date-short = S.Datum
actions-show-answer-short = Antw.anz.
actions-show-answeranswer-good-short = Anz./Gut
actions-study-options-short = S.Opt
actions-suspend-card-short = K.auss.
actions-suspend-note-short = N.auss.
actions-tools-short = Extras
actions-top-bar-short = Leiste
actions-unbury-deck-short = AufhAufsch
actions-undo-short = Rückg.
actions-redo-short = Wiederh.
actions-scroll-up-short = Hoch
actions-scroll-down-short = Runter
actions-back = Zurück
