browsing-append = An­fügen
browsing-append-negated = An­fü­gen und um­keh­ren
browsing-card-updated = Karte aktualisiert
browsing-change-flag = Markierung ändern
browsing-clear-flag = Markierung aufheben
browsing-column-1 = Spalte 1
browsing-column-2 = Spalte 2
browsing-confirm-reset = Reset bestätigen
browsing-dd-selected = %d/%d aus­ge­wählt
browsing-due-dateorder = Fälligkeitsdatum/-reihenfolge
browsing-due-reviews = Fällige Wiederholungen
browsing-learning-cards = Lernkarten
browsing-no-cards-are-selected = Keine Karte wurde ausgewählt.
browsing-note-created = Notiz erstellt
browsing-note-updated = Notiz aktualisiert
browsing-note2 = Notiz:
browsing-questionandanswer = Frage+Antwort
browsing-repetitions = Wiederholungen
browsing-reset-cards = Karten resetten
browsing-searching = Suche läuft...
browsing-second-column-19 = Zweite Spalte (1->9)
browsing-second-column-91 = Zweite Spalte (9->1)
browsing-select-all = Alles auswählen
browsing-sort = Sortieren
browsing-sort-order = Sortierreihenfolge
browsing-tag = Schlagwort:
