deck-options-add-options-group = Stapelprofil hin­zu­fü­gen
deck-options-answer-time-cap = Ant­wort­zeit­be­gren­zung
deck-options-bury-related-new-cards = Geschwisterkarten mit Status „Neu“ aufschieben
deck-options-bury-related-reviews = Geschwisterkarten mit Status „Wiederholung“ aufschieben
deck-options-defaults = Standardeinstellungen
deck-options-delete-options-full-sync = Das Löschen dieses Stapelprofils wird verhindern, dass Änderungen von anderen Geräten bei der Synchronisierung zusammengeführt werden können. Möchten Sie fortfahren?
deck-options-display-in-order-added = In der Reihenfolge anzeigen, wie sie hinzufügt wurden
deck-options-display-in-random-order = In zufälliger Reihenfolge anzeigen
deck-options-full-sync-required = Vollständige Synchronisierung erforderlich
deck-options-group-name = Gruppenname
deck-options-max-new-per-day = Max. neue Karten pro Tag
deck-options-max-reviews-per-day = Tageshöchstwert für Wiederholungskarten
deck-options-new-cards = Neue Karten
deck-options-options-group = Stapelprofil
deck-options-replay-q-audio-in-answer = Fr.-Audio in der Antwort erneut abspielen
deck-options-reset-all-settings-to-defaults = Alle Einstellungen auf die Standardeinstellungen zurücksetzen?
deck-options-restore-defaults = Standardeinstellungen wiederherstellen
deck-options-steps = Lernstufen
