decks-a-deck-must-be-provided = Bit­te Sta­pel aus­wäh­len.
decks-a-deck-named-already-exists = Ein Sta­pel na­mens '{ $name }' ex­ist­iert be­rei­ts.
decks-a-deck-with-that-name-already = Ein Sta­pel die­ses Na­mens ex­is­tiert be­rei­ts.
decks-add-deck = Sta­pel hin­zu­fü­gen
decks-add-empty-deck = Lee­ren Sta­pel hin­zu­fü­gen
decks-addexport = Hin­zu­fü­gen/Ex­por­tier­en
decks-cannot-delete = Löschen fehlgeschlagen
decks-card-limit = Tageshöchstwert
decks-cards-in-a-filtered-deck-cant = Karten in Auswahlstapeln können nicht verschoben werden.
decks-custom-steps = Be­nut­zer­de­fi­nier­te Lern­stu­fen
decks-deck-exists = Existierende Stapel
decks-deck-label = Stapel:
decks-deck-name = Stapelname
decks-deck-options = Stapelprofile
decks-download-link = Link zum Herunterladen
decks-export-collection = Sammlung exportieren
decks-filtered-deck = Auswahlstapel
decks-import-from-itunes = Aus iTunes importieren
decks-invalid-deck-name = Ungültiger Stapelname.
decks-link-to-apkg-file-to-import = Link zur .apkg-Datei für Import:
decks-no-matches = Keine Übereinstimmungen
decks-return-by-delete = Um alle Karten auf einmal zurückkehren zu lassen, einfach über den blauen Stapel in der Stapelliste wischen und anschließend löschen.
decks-shared-deck-list = Geteilte Stapellisten
decks-sync = Synchro
decks-synchronize = Synchronisieren
decks-the-default-deck-cannot-be-deleted = Der Standardstapel kann nicht gelöscht werden.
decks-the-provided-deck-does-not-exist = Der bereitgestellte Stapel existiert nicht.
decks-the-search-you-provided-did-not = Die Suche, die Sie zur bereitgestellt haben, hat keine Übereinstimmung mit irgendeiner Karte.
decks-will-be-returned = Karten kehren in ihren ursprünglichen Stapel zurück, wenn sie beantwortet werden.
