editing-bold = Fett
editing-cancel-and-lose-any-unsaved-changes = Abbrechen und alle nicht gespeicherten Änderungen verlieren?
editing-cant-edit-original-image-data = Bearbeitung fehlgeschlagen - Ursprungsbilddaten konnten nicht gefunden werden.
editing-card-returned-to-new-card-queue = Karte zu den neuen Karten zurück verschoben.
editing-card-unsuspended = Karte eingesetzt
editing-from-camera = Von der Kamera
editing-from-file = Von Datei
editing-from-photos = Von Fotos
editing-italic = Kursiv
editing-next-cloze = Nächster Lückentext
editing-next-field = Nächstes Feld
editing-note-deleted = Notiz gelöscht
editing-note-suspended = Notiz ausgesetzt
editing-note-type-prompt = Typ:
editing-note-unsuspended = Notiz eingesetzt
editing-same-cloze = Gleicher Lückentext
editing-the-first-field-must-not-be = Das erste Feld darf nicht leer sein.
editing-unable-to-obtain-image = Bild konnte nicht abgerufen werden
editing-unable-to-read-file = Datei konnte nicht gelesen werden
editing-underline = Unterstreichen
editing-unexpected-file-extension = Unerwartete Dateierweiterung:
editing-unexpected-rich-text-format-please = Unerwartetes Rich-Text-Format - bitte versuchen Sie es mit Kopieren & Einfügen
editing-unexpected-status-code = Unerwarteter Statuscode:
editing-unsuspend-card = Karte wieder einsetzen
editing-unsuspend-note = Notiz wieder einsetzen
