importing-delete-imported-file = Importierte Datei löschen?
importing-import-complete = Import fertiggestellt.
importing-importing = Import läuft …
importing-no-apkg-or-colpkg-files-were = Keine .apkg- oder .colpkg-Dateien in iTunes gefunden
importing-overwrite-via-import = Gesamte Sammlung mit importierter Datei überschreiben? Diese Aktion kann nicht rückgängig gemacht werden.
importing-please-choose-a-file = Bitte wählen Sie eine Datei aus.
importing-processed-media-files-d = Mediendateien werden verarbeitet: { $count } …
importing-replace-collection = Sammlung ersetzen
importing-file-not-downloaded = Bitte die Datei aus iCloud herunterladen und erneut importieren.
