preferences-about = Ü­ber
preferences-always-duck-and-ignore-mute = Im­mer au­srei­ßen + Stumm­schal­tung i­gno­rier­en
preferences-answer-keeps-zoom = Ant­wort be­hält Zoom bei
preferences-answer-side = Ant­wort­sei­te
preferences-audio-buttons = Au­dio­knö­pfe
preferences-auto-advance-answer-action = Ant­wort­ak­tion
preferences-auto-advance-answer-seconds = Ant­wort­se­kun­den
preferences-auto-advance-auto-advance-to-start = Um automatisch fortzuschreiten, benutzen Sie bitte die Aktion 'Autom. Fortschreiten'.
preferences-auto-advance-do-nothing = Nichts machen
preferences-auto-advance-question-seconds = Sekunden zum Fragen
preferences-auto-advance-show-reminder = Erinnerung anzeigen
preferences-auto-advance-wait-for-audio = Auf Audio warten
preferences-backup-available-backups = Ver­füg­ba­re Sich­er­ungs­kop­ien
preferences-backup-create-now = Jetzt erstellen
preferences-backup-maximum-backups = Maximale Sicherungskopien
preferences-backup-minutes-between-backups = Minuten zwischen Sicherungskopien
preferences-backup-revert-to-backup = Auf den Stand der Sicherungskopie zurücksetzen
preferences-backup-revert-to-backup-confirm = Zu { $backup } zurückkehren? Alle Änderungen, die nach dieser Sicherheitskopie erfolgt sind, werden verloren gehen.
preferences-backup-reverted-to-backup = Auf den Stand der Sicherungskopie zurückgesetzt.
preferences-bottom-bar-size = Größe des unteren Balkens
preferences-bottom-center = Unten mittig
preferences-bottom-left = Unten links
preferences-bottom-right = Unten rechts
preferences-button-d = Knopf { $num }
preferences-collection-day-starts = Tag beginnt
preferences-collection-learn-ahead-minutes = Um Minuten vorauslernen
preferences-collection-mix = Mischen
preferences-collection-new-first = Neue zuerst
preferences-collection-newreview-order = Neu/Wiederholung-Reihenfolge
preferences-collection-reviews-first = Wiederholungen zuerst
preferences-double-tap-prevention = Verhinderung von Doppeltipp
preferences-drawing-screen-ignores-fingers = Zeichenbildschirm ignoriert Finger
preferences-feedback-ticks = Feedbackzeichen
preferences-fine = Strafe
preferences-force-sync-confirm = Möchten Sie eine einseitig gerichtete Synchronisation erzwingen? Alle Änderungen auf einer Seite werden verloren gehen.
preferences-full-sync = Vollständige Synchronisation
preferences-gamepad-button-mapping = Knöpfeanordnung
preferences-gamepad-menu-button = Menü
preferences-gamepads = Gamepads
preferences-height = Höhe
preferences-huge = Groß
preferences-ignore-fingers = Finger ignorieren
preferences-interrupt-current-audio = Aktuelle Audiowiedergabe unterbrechen
preferences-large = Groß
preferences-left = Links
preferences-left-shoulder = Linke Schulter
preferences-left-thumbstick-button = Linker Knopf für Daumen
preferences-left-trigger = Links Auslöser
preferences-logged-in-as = Angemeldet als:
preferences-long = Lang
preferences-mid-center = mittig
preferences-mid-left = Mitte links
preferences-mid-right = Mitte rechts
preferences-never-type-answer = Niemals Antwort eintippen
preferences-next-times = Nächste Male
preferences-normal = Normal
preferences-notifications = Benachrichtigungen
preferences-notifications-alert-time = Alarmzeit
preferences-notifications-alert-when-due = Bei Fäll­ig­keit a­lar­mier­en
preferences-notifications-app-icon-shows-due-count = App-Symbol zeigt An­zahl fäl­li­ger Kar­ten
preferences-notifications-settings-app-enable-notifications = Bitte gehen Sie in den iOS-Einstellungen zum Abschnitt für Anki und aktivieren Sie dort Benachrichtigungen/Mitteilungen, Badges und Warnhinweise.
preferences-pen-size = Stiftgröße
preferences-question-side = Frageseite
preferences-remaining-count = Zähler für verbleibend
preferences-right = Rechts
preferences-right-shoulder = Rechte Schulter
preferences-right-thumbstick-button = Rechter Knopf für Daumen
preferences-right-trigger = Rechts Auslöser
preferences-scratchpad-below-buttons = Notizblock unter den Knöpfen
preferences-scratchpad-transparency = Notizblock-Transparenz
preferences-scratchpad-transparency-full = Voll
preferences-scratchpad-transparency-medium = Mittel
preferences-scratchpad-transparency-none = Nichts
preferences-scratchpad-transparency-slight = Gering
preferences-shake-action = Schüttelaktion
preferences-short = Kurz
preferences-show-bottom-bar = Unteren Balkan anzeigen
preferences-show-grid = Gitter anzeigen
preferences-show-top-bar = Oberen Balken anzeigen
preferences-small = Klein
preferences-swipe-down = Nach unten wischen
preferences-swipe-left = Nach links wischen
preferences-swipe-right = Nach rechts wischen
preferences-swipe-up = Nach oben wischen
preferences-swipes = Wischgesten
preferences-swipes-must-begin-from-the-far = Wischgesten müssen von weit links oder rechts auf dem Bildschirm beginnen.
preferences-sync-sounds-images = Audio & Bilder sync.
preferences-syncing = Synchronisierung
preferences-tap-to-sync = Um die Synchronisation zu aktivieren, tippen Sie bitte auf den Synchronisieren-Knopf auf dem Bildschirm für die Stapelliste.
preferences-taps = Tippen
preferences-theme = Theme
preferences-theme-bar-style = Bal­ken­stil
preferences-theme-black = Schwarz
preferences-theme-dark = Dunkel
preferences-theme-dark-translucent = Dunkel & durchsichtig
preferences-theme-force-off = Aus erzwingen
preferences-theme-force-on = An erzwingen
preferences-theme-light-translucent = Hell & durchlässig
preferences-theme-night-mode-desc = Der Nachtmodus dunkelt die Benutzeroberfläche ab und zeigt Karten mit weißem Text auf schwarzem Hintergrund an.
preferences-theme-night-mode-same-as-system = System folgen
preferences-theme-slate = Schiefer
preferences-thick = Dick
preferences-tools-overlay-button = Werkzeugeinblendungsknopf
preferences-tools-overlay-position = Werkzeugeinblendungsposition
preferences-top-center = Oben mittig
preferences-top-left = Oben links
preferences-top-right = Oben rechts
preferences-undo-clears-all = \"Alles aufräumen\" rückgängig machen
preferences-when-answer-shown = Wenn Antwort angezeigt wird
preferences-when-question-shown = Wenn Frage angezeigt wird
preferences-you-have-been-logged-out = Sie wurden abgemeldet.
