profiles-a-profile-with-that-name-already = Es ex­is­tie­rt be­rei­ts ein Pro­fil mit die­sem Na­men.
profiles-add-profile = Pro­fil er­stel­len
profiles-creating-backup = Sicherungskopie wird erstellt...
profiles-finishing-backup = Sicherungskopie wird fertiggestellt...
profiles-please-provide-some-text-avoiding-symbols = Bitte stellen Sie etwas Text zur Verfügung und vermeiden Sie dabei Symbole und Unterstriche.
profiles-please-select-another-profile-first = Bitte wählen Sie zunächst ein anderes Profil aus.
profiles-profile-name = Profilname
profiles-rename-profile = Profil umbenennen
profiles-unable-to-open-safari-please = Safari konnte nicht geöffnet werden - bitte überprüfen Sie die Kinderschutzeinstellungen
profiles-welcome = Willkommen!
