profiles-a-profile-with-that-name-already = Es ex­is­tie­rt be­rei­ts ein Benutzerprofil mit die­sem Na­men.
profiles-add-profile = Benutzerprofil er­stel­len
profiles-finishing-backup = Sicherungskopie wird fertiggestellt...
profiles-please-provide-some-text-avoiding-symbols = Bitte schreiben Sie etwas Text und vermeiden Sie dabei Symbole und Unterstriche.
profiles-please-select-another-profile-first = Bitte wählen Sie zunächst ein anderes Benutzerprofil aus.
profiles-profile-name = Benutzerprofilname
profiles-rename-profile = Benutzerprofil umbenennen
profiles-unable-to-open-safari-please = Safari konnte nicht geöffnet werden - bitte überprüfen Sie die Kinderschutzeinstellungen
profiles-welcome = Willkommen!
