studying-answer-time-elapsed = Ant­wort­zeit ab­ge­lau­fen
studying-auto-advance-starting = Au­to­ma­ti­sches Fort­schrei­ten star­tet
studying-auto-advance-stopped = Au­to­ma­ti­sches Fort­schrei­ten ge­stop­pt
studying-have-ready-to-study = Sie haben { $numCards } bereit zum Lernen.
studying-please-run-empty-cards-on-the = Bitte führen Sie die Aktion \"Leere Karten\" in der Computer-Version von Anki aus.
studying-replay-card = Karte erneut abspielen
studying-replay-voice = Stimme erneut abspielen
studying-rescheduled-card = Karte zeitlich neu geplant.
studying-type-in-the-answer = Antwort eintippen
