actions-actions = Mga Kilos
actions-add-new = Magdagdag ng panibago
actions-added-to-frequent-actions = Nadagdag sa mga madalas na kilos.
actions-all-actions = Lahat ng mga kilos
actions-already-in-frequent-actions = Nasa mga madalas na kilos na.
actions-an-error-occurred = Nagkaroon ng error: { $error }
actions-answer-easy = Magsagot nang Madali
actions-are-you-sure = Sigurado ka ba?
actions-bottom-bar = Bottom Bar
actions-browse = Mag-browse
actions-card-buried = Naka-bury ang card
actions-card-suspended = Na-suspend ang card
actions-card-template = Template ng Card
actions-confirm-delete = I-confirm delete
actions-create = Gumawa
actions-current-audio-minus-5s = Kasalukuyang Audio -5s
actions-current-audio-plus-5s = Kasalukuyang Audio +5s
actions-custom-study-cant-be-used-on = Hindi magagamit ang Custom study sa isang filtered deck.
actions-deck-statistics = Mga Statistics ng Deck
actions-delete-note-and-its-cards = I-delete ang note at ang mga card nito?
actions-discard-changes = I-discard ang mga pagbabago
actions-done = Tapos na
actions-downloading = Dina-download...
actions-drag-here-to-remove = Hilahin dito para tanggalin
actions-draw = Mag-drawing
actions-file-invalid-or-corrupt = Invalid o corrupt ang file.
actions-filtercram = I-filter o i-cram
actions-filtered-deck = Naka-filter na deck { $num }
actions-forgot-card = Nakalimutan na card
actions-frequent-actions = Mga madalas na kilos
actions-leave-without-saving = Umalis nang hindi nase-save?
actions-long-press-on-an-item-to = Mag-long press sa isang item para i-customize.
actions-mark = Mag-mark
actions-mark-and-bury = Mag-mark + mag-bury
actions-mark-and-suspend = Mag-mark + mag-suspend
actions-marked = Namarkahan
actions-no-current-card = Walang kasalukuyang card.
actions-no-load-restore-backup = Hindi ma-load ang collection mo. Paki-restore mula sa isang automatic backup sa preferences screen.
# (http://example.com) does not appear to be...
actions-not-valid-link = mukhang hindi valid na http/https link.
actions-note-and-its-cards-deleted = Na-delete na ang note at { $count } (na) card nito.
actions-note-and-its-cards-suspended = Na-suspend na ang note at { $count } (na) card nito.
actions-note-buried = Na-bury ang note
actions-note-marked-and-buried = Namarkahan at na-bury ang note
actions-off = I-off
actions-please-tap-the-in-the = Pakipindot ng '?' sa kaliwang taas upang magsimula.
actions-record-voice = Mag-record ng boses
actions-record-voice-menu = Menu ng pag-record ng boses
actions-reset-card = I-reset ang card
actions-revert = Mag-revert
actions-review-undone = Hindi pa tapos ang review
actions-scratchpad = Scratchpad
actions-scratchpad-size = Laki ng scratchpad
actions-select-deck = Pumili ng deck
actions-select-note-type = Pumili ng Note Type
actions-show-answeranswer-good = Ipakita ang sagot/magsagot ng 'tama'
actions-study-options = Mga Option sa Pag-aaral
actions-tools = Mga Tool
actions-tools-overlay = Overlay ng mga Tool
actions-top-bar = Top Bar
actions-unbury-deck = I-unbury ang deck
actions-undo = I-undo
actions-unmarked = Naka-unmark
actions-you-can-only-empty-a-filtered = Filtered deck lang ang puwedeng ma-empty.
actions-you-can-only-rebuild-a-filtered = Filtered deck lang ang puwedeng ma-rebuild.
actions-scroll-up = Mag-scroll pataas
actions-scroll-down = Mag-scroll pababa

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = I-empty
# create a filtered deck
actions-filter-short = I-filter
actions-add-short = Magdagdag
actions-answer-again-short = Ulit
actions-answer-easy-short = Madali
actions-answer-good-short = Tama
actions-answer-hard-short = Mahirap
actions-auto-advance-short = Auto Adv.
actions-bottom-bar-short = Bot.B
actions-browse-short = Mag-browse
actions-bury-card-short = Bury.C
actions-bury-note-short = Bury.N
actions-card-info-short = C.Info
actions-card-template-short = Template
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Custom
actions-deck-statistics-short = D.Stats
actions-decks-short = Mga Deck
actions-delete-note-short = I-del
actions-edit-short = I-edit
actions-mark-and-bury-short = M&B
actions-mark-and-suspend-short = M&S
actions-mark-short = Mark
actions-night-mode-short = Gabi
actions-off-short = I-off
actions-pause-audio-short = I-pause
actions-rebuild-short = I-rebuild
actions-record-voice-short = Mag-rec
actions-replay-voice-short = I-replay
actions-replay-audio-short = I-replay
actions-reset-card-short = I-reset
actions-scratchpad-short = Pad
actions-scratchpad-size-short = Laki ng pad
actions-set-due-date-short = Tingnan date
actions-show-answer-short = Tingnan sagot
actions-show-answeranswer-good-short = Tingnan sagot
actions-study-options-short = S.Opt
actions-suspend-card-short = Sus.C
actions-suspend-note-short = Sus.N
actions-tools-short = Mga Tool
actions-top-bar-short = T.Bar
actions-unbury-deck-short = UBury
actions-undo-short = I-undo
actions-redo-short = I-redo
actions-scroll-up-short = Taas
actions-scroll-down-short = Babâ
