actions-actions = Accions
actions-add-new = Afegeix-ne un de nou
actions-added-to-frequent-actions = S'ha afegit a les accions freqüents.
actions-all-actions = Totes les accions
actions-already-in-frequent-actions = Ja es troba en les accions freqüents.
actions-an-error-occurred = S'ha produït un error: { $error }
actions-answer-easy = Resposta fàcil
actions-are-you-sure = Segur que voleu continuar?
actions-bottom-bar = Barra inferior
actions-browse = Navega
actions-card-buried = Targeta enterrada
actions-card-suspended = S’ha suspès la targeta
actions-card-template = Plantilla de targeta
actions-confirm-delete = Confirma la supressió
actions-create = Crea
actions-current-audio-minus-5s = So actual −5 s
actions-current-audio-plus-5s = So actual +5 s
actions-custom-study-cant-be-used-on = No podeu fer servir la funció d’estudi personalitzat amb una baralla filtrada.
actions-deck-statistics = Estadístiques de la baralla
actions-delete-note-and-its-cards = Voleu eliminar aquesta nota i les seves targetes?
actions-discard-changes = Anul·la els canvis
actions-done = Fet
actions-downloading = S'està baixant…
actions-drag-here-to-remove = Arrossegueu ací per a eliminar
actions-draw = Dibuixa
actions-file-invalid-or-corrupt = Fitxer invàlid o malmès
actions-filtercram = Filtra/empolla
actions-filtered-deck = Baralla filtrada { $num }
actions-frequent-actions = Accions freqüents
actions-leave-without-saving = Voleu sortir sense guardar?
actions-long-press-on-an-item-to = Manteniu premut un ítem per a personalitzar-lo.
actions-mark = Marca
actions-mark-and-bury = Marca i enterra
actions-mark-and-suspend = Marca i suspèn
actions-marked = Marcada
actions-no-current-card = No hi ha cap targeta actual.
actions-no-load-restore-backup = No s'ha pogut carregar la vostra col·lecció. Restaureu-la des d'una còpia de seguretat automàtica mitjançant el menú de preferències.
# (http://example.com) does not appear to be...
actions-not-valid-link = no sembla un enllaç http/https vàlid
actions-note-and-its-cards-deleted = S'ha esborrat la nota i les seves { $count } targetes.
actions-note-and-its-cards-suspended = S'ha suspès aquesta nota i la o les seves { $count } targetes.
actions-note-buried = Nota enterrada
actions-note-marked-and-buried = Nota marcada i enterrada
actions-off = Desactivat
actions-please-tap-the-in-the = Feu toc sobre el botó «?» de la part superior esquerra per a començar.
actions-record-voice = Enregistra la veu
actions-record-voice-menu = Menú d'enregistrament de veu
actions-reset-card = Inicialitza la targeta
actions-revert = Reverteix
actions-review-undone = Repàs desfet
actions-scratchpad = Bloc de notes
actions-scratchpad-size = Mida del bloc de notes
actions-select-deck = Tria la baralla
actions-select-note-type = Tria un tipus de nota
actions-show-answeranswer-good = Mostra la resposta/resposta correcta
actions-study-options = Opcions d’estudi
actions-tools = Eines
actions-tools-overlay = Superposició d'eines
actions-top-bar = Barra superior
actions-unbury-deck = Desenterra la baralla
actions-undo = Desfés
actions-unmarked = No marcada
actions-you-can-only-empty-a-filtered = Només podeu buidar una baralla filtrada.
actions-you-can-only-rebuild-a-filtered = Només podeu reestablir una baralla filtrada.
actions-scroll-up = Llisca cap amunt
actions-scroll-down = Llisca cap avall

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Buida
# create a filtered deck
actions-filter-short = Filtre
actions-add-short = Afegeix
actions-answer-again-short = De nou
actions-answer-easy-short = Fàcil
actions-answer-good-short = Correcte
actions-answer-hard-short = Difícil
actions-auto-advance-short = Av. auto.
actions-bottom-bar-short = B. inf.
actions-browse-short = Navega
actions-bury-card-short = Ent. t.
actions-bury-note-short = Ent. n.
actions-card-info-short = Info.
actions-card-template-short = Plantilla
actions-current-audio-minus-5s-short = –5 s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-short = Personalitzat
actions-deck-statistics-short = Estad.
actions-decks-short = Baralles
actions-delete-note-short = Supr
actions-edit-short = Edita
actions-mark-and-bury-short = M. i e.
actions-mark-and-suspend-short = M. i s.
actions-mark-short = Marca
actions-night-mode-short = Fosc
actions-off-short = Desact.
actions-pause-audio-short = Pausa
actions-rebuild-short = Recons.
actions-record-voice-short = Enreg.
actions-replay-voice-short = Subst.
actions-replay-audio-short = Repeteix
actions-reset-card-short = Inicialitza
actions-scratchpad-short = Bloc
actions-scratchpad-size-short = M. del bloc
actions-set-due-date-short = Est. data
actions-show-answer-short = Resposta
actions-show-answeranswer-good-short = Correcte
actions-study-options-short = Opc. estudi
actions-suspend-card-short = Sus. t.
actions-suspend-note-short = Sus. n.
actions-tools-short = Eines
actions-top-bar-short = Bar. sup.
actions-unbury-deck-short = Desent.
actions-undo-short = Desfés
actions-redo-short = Refés
actions-scroll-up-short = Amunt
actions-scroll-down-short = Avall
actions-back = Enrere
