decks-a-deck-must-be-provided = Heu de proporcionar un mall.
decks-a-deck-named-already-exists = Ja existeix un mall amb el nom «{ $name }».
decks-a-deck-with-that-name-already = Ja existeix un mall amb aquest nom.
decks-add-deck = Afegeix un mall
decks-add-empty-deck = Afegeix un mall buit
decks-addexport = Afegeix/exporta
decks-cannot-delete = No s'ha pogut eliminar
decks-card-limit = Límit de targetes
decks-cards-in-a-filtered-deck-cant = No és possible moure les targetes d'un mall filtrat.
decks-custom-steps = Passos personalitzats
decks-deck-exists = Aquest mall ja existeix
decks-deck-label = Mall:
decks-deck-name = Nom del mall
decks-deck-options = Opcions del mall
decks-download-link = Enllaç de descàrrega
decks-export-collection = Exporta la col·lecció
decks-filtered-deck = Mall filtrat
decks-import-from-itunes = Importa des d'iTunes
decks-invalid-deck-name = El nom del mall no és vàlid.
decks-link-to-apkg-file-to-import = Introduïu l'enllaç del fitxer .apkg que voleu importar:
decks-no-matches = No hi ha coincidències
decks-return-by-delete = Per a retornar totes les targetes alhora, llisqueu el dit sobre el mall blau en la llista de malls i suprimiu-lo.
decks-shared-deck-list = Llista de malls compartits
decks-sync = Sincronitza
decks-synchronize = Sincronitza
decks-the-default-deck-cannot-be-deleted = No podeu eliminar el mall per defecte.
decks-the-provided-deck-does-not-exist = El mall que heu proporcionat no existeix.
decks-the-search-you-provided-did-not = La cerca que heu proporcionat no correspon a cap targeta.
decks-will-be-returned = Les targetes retornaran al seu mall original a mesura que les respongueu.
