decks-a-deck-must-be-provided = Selecciona una baralla.
decks-a-deck-named-already-exists = Ja existeix una baralla amb el nom «{ $name }».
decks-a-deck-with-that-name-already = Ja existeix una baralla amb aquest nom.
decks-add-deck = Afegeix una baralla
decks-add-empty-deck = Afegeix una baralla buida
decks-addexport = Afegeix/exporta
decks-cannot-delete = No s’ha pogut suprimir
decks-card-limit = Límit de targetes
decks-cards-in-a-filtered-deck-cant = No pots moure les targetes d’una baralla filtrada.
decks-custom-steps = Passos personalitzats
decks-deck-exists = Aquesta baralla ja existeix
decks-deck-label = Baralla:
decks-deck-name = Nom de la baralla
decks-deck-options = Opcions de la baralla
decks-download-link = Enllaç de descàrrega
decks-export-collection = Exporta la col·lecció
decks-filtered-deck = Baralla filtrada
decks-import-from-itunes = Importa des d’iTunes
decks-invalid-deck-name = El nom de la baralla no és vàlid.
decks-link-to-apkg-file-to-import = Introdueix l’enllaç del fitxer .apkg que vols importar:
decks-no-matches = No hi ha coincidències
decks-return-by-delete = Per a retornar totes les targetes alhora, llisca el dit sobre la baralla blava de la llista i elimina-la.
decks-shared-deck-list = Llista de baralles compartides
decks-sync = Sincronitza
decks-synchronize = Sincronitza
decks-the-default-deck-cannot-be-deleted = No pots eliminar la baralla per defecte.
decks-the-provided-deck-does-not-exist = La baralla que has seleccionat no existeix.
decks-the-search-you-provided-did-not = No s’ha trobat cap targeta amb aquestes condicions.
decks-will-be-returned = Les targetes tornaran a la baralla original a mesura que les responguis.
