exporting-collection-saved-to-itunes = S’ha guardat la col·lecció en iTunes.
exporting-export-to-itunes = Exporta a iTunes
exporting-export-to-share-sheet = Exporta al full de compartir
exporting-exporting = S'està exportant…
exporting-include-media2 = Inclou els fitxers multimèdia
exporting-media-files-exported-d = Fitxers multimèdia exportats: { $count }…
