preferences-about = Quant a
preferences-answer-side = Costat de la resposta
preferences-audio-buttons = Botons de so
preferences-auto-advance-answer-action = Acció de resposta
preferences-auto-advance-answer-seconds = Segons de resposta
preferences-auto-advance-do-nothing = No facis res
preferences-auto-advance-question-seconds = Segons per pregunta
preferences-auto-advance-show-reminder = Mostra un recordatori
preferences-auto-advance-wait-for-audio = Espera el so
preferences-backup-available-backups = Còpies de seguretat disponibles
preferences-backup-create-now = Crea'n ara
preferences-backup-maximum-backups = Nombre màxim de còpies de seguretat
preferences-backup-minutes-between-backups = Minuts entre còpies de seguretat
preferences-backup-revert-to-backup = Restaura una còpia de seguretat
preferences-backup-reverted-to-backup = S'ha restaurat una còpia de seguretat.
preferences-bottom-bar-size = Mida de la barra inferior
preferences-button-d = Botó { $num }
preferences-collection-day-starts = Començament del dia
preferences-collection-mix = Barreja
preferences-collection-new-first = Les noves primer
preferences-feedback-ticks = Quadre de comentaris
preferences-fine = Fi
preferences-full-sync = Sincronització completa
preferences-gamepad-button-mapping = Assignació dels botons
preferences-gamepad-menu-button = Menú
preferences-gamepads = Comandaments
preferences-height = Altura
preferences-huge = Enorme
preferences-ignore-fingers = Ignora els dits
preferences-interrupt-current-audio = Interromp el so actual
preferences-large = Gran
preferences-left = Esquerra
preferences-logged-in-as = Connectat com a:
preferences-long = Llarg
preferences-normal = Normal
preferences-notifications = Notificacions
preferences-pen-size = Mida del llapis
preferences-right = Dreta
preferences-scratchpad-transparency-full = Completa
preferences-scratchpad-transparency-medium = Mitjana
preferences-scratchpad-transparency-none = Cap
preferences-scratchpad-transparency-slight = Subtil
preferences-short = Curt
preferences-small = Petit
preferences-syncing = Sincronització
preferences-taps = Tocs
preferences-theme = Tema
preferences-theme-bar-style = Estil de la barra
preferences-theme-black = Negre
preferences-theme-dark-translucent = Fosc i translúcid
preferences-theme-light-translucent = Clar i translúcid
preferences-theme-night-mode-same-as-system = Segons el sistema
preferences-theme-slate = Pissarra
preferences-thick = Gros
preferences-editing = Edició
