preferences-about = Quant a
preferences-answer-side = Costat de la resposta
preferences-audio-buttons = Botons de so
preferences-auto-advance-answer-action = Acció de resposta
preferences-auto-advance-answer-seconds = Segons de resposta
preferences-auto-advance-do-nothing = No facis res
preferences-backup-create-now = Crea'n ara
preferences-backup-maximum-backups = Nombre màxim de còpies de seguretat
preferences-collection-mix = Barreja
preferences-collection-new-first = Les noves primer
preferences-full-sync = Sincronització completa
preferences-gamepad-button-mapping = Assignació dels botons
preferences-gamepad-menu-button = Menú
preferences-gamepads = Comandaments
preferences-height = Altura
preferences-huge = Enorme
preferences-ignore-fingers = Ignora els dits
preferences-left = Esquerra
preferences-long = Llarg
preferences-normal = Normal
preferences-notifications = Notificacions
preferences-right = Dreta
preferences-scratchpad-transparency-full = Completa
preferences-scratchpad-transparency-medium = Mitjana
preferences-scratchpad-transparency-none = Cap
preferences-scratchpad-transparency-slight = Subtil
preferences-short = Curt
preferences-small = Petit
preferences-syncing = Sincronització
preferences-taps = Tocs
preferences-theme = Tema
preferences-theme-bar-style = Estil de la barra
preferences-theme-black = Negre
preferences-theme-dark-translucent = Fosc i translúcid
