profiles-a-profile-with-that-name-already = Ja existeix una foto amb aquest nom.
profiles-add-profile = Afegeix un perfil
profiles-finishing-backup = S’està acabant la còpia de seguretat…
profiles-please-provide-some-text-avoiding-symbols = Introdueix un text sense símbols o ratlles baixes.
profiles-please-select-another-profile-first = Primer, selecciona un altre perfil.
profiles-profile-name = Nom del perfil
profiles-rename-profile = Reanomena el perfil
profiles-unable-to-open-safari-please = No s’ha pogut obrir el Safari. Comprova les restriccions parentals.
profiles-welcome = Us donem la benvinguda!
