actions-actions = טוּונגען
actions-add-new = שאַפֿן נײַ
actions-added-to-frequent-actions = צוגעשטעלט אין אָפֿטלעכע טוּונגען.
actions-all-actions = אַלע טוּונגען
actions-already-in-frequent-actions = שוין אין אָפֿטלעכע טוּונגען.
actions-an-error-occurred = ס׳איז פֿאָרגעקומען אַ גרײַז: { $error }
actions-answer-easy = ענטפֿערן גרינג
actions-are-you-sure = זיכער?
actions-bottom-bar = אונטנבאַלקן
actions-browse = דורכקוקן
actions-card-buried = קאַרטל אָפּגעהאַלטן
actions-card-suspended = קאַרטל אָפּגעשטעלט
actions-card-template = מוסטער-קאַרטל
actions-confirm-delete = באַשטעטיקן אויסמעק
actions-create = שאַפֿן
actions-current-audio-minus-5s = יעצטיקע אוידיאָ -5ס
actions-current-audio-plus-5s = יעצטיקע אוידיאָ +5ס
actions-custom-study-cant-be-used-on = מע טאָר נישט אײַנ׳חזר׳ן צוגעפּאַסט אַ פֿילטרירט טעשל.
actions-deck-statistics = טעשל-סטאַטיסטיק
actions-delete-note-and-its-cards = אויסמעקן נאָטיץ און אירע קאַרטלעך?
actions-discard-changes = אַוועקוואַרפֿן טוישונגען
actions-done = געמאַכט
actions-downloading = אַראָפּלאָדנט זיך…
actions-drag-here-to-remove = צושלעפּ אַהער אויף אָפּצונעמען
actions-draw = סקיצירן
actions-file-invalid-or-corrupt = טעקע איז פּסול אָדער געשעדיקט.
actions-filtercram = פֿילטרירן/זוברעווען
actions-filtered-deck = פֿילטרירטע טעשל { $num }
actions-frequent-actions = אָפֿטלעכע אַקציעס
actions-leave-without-saving = וועקגיין אָן דעם אויפֿהיטן?
actions-long-press-on-an-item-to = לאַנג-דרוק אויף אַ שטיק עס צוצופּאַסן.
actions-mark = באַצייכענען
actions-mark-and-bury = באַצייכענען + אָפּהאַלטן
actions-mark-and-suspend = באַצייכענען + אָפּשטעלן
actions-marked = באַצייכענט
actions-no-current-card = קיין יעצטיק קאַרטל.
actions-no-load-restore-backup = אײַער זאַמלונג האָט נישט געקענט לאָדירט ווערן. ביטע צוריקציט פֿון אַן אויטאָמאַטיש רעזערוו-קאָפּיע דורך די אויסוואַלן עקראַן.
# (http://example.com) does not appear to be...
actions-not-valid-link = ס׳זעט אויס, אַז ס׳איז נישט קיין גילטיק http/https לינקל.
actions-note-and-its-cards-deleted = נאָטיץ אין זײַנע { $count } קאַרטל(עך) אָפּגעמעקט
actions-note-and-its-cards-suspended = נאָטיץ אין זײַנע { $count } קאַרטל(עך) אָפּגעשטעלט
actions-note-buried = נאָטיץ אָפּגעלייגט
actions-note-marked-and-buried = נאָטיץ באַצייכנט און אָפּגעלייגט
actions-off = אויס
actions-please-tap-the-in-the = געב ביטע אַ טאַפּ די '?' אויף אויבן-לינקס כּדי אָנצוהייבן.
actions-record-voice = רעקאָרדירן קול
actions-record-voice-menu = רעקאָרדירן-קול-מעניו
actions-reset-card = פֿאַרגעסן קאַרטל
actions-revert = צוריקציִען
actions-review-undone = איבער׳חזר׳ונג אַנולירט
actions-scratchpad = בלאָקנאָט
actions-scratchpad-size = בלאָקנאָט-גרייס
actions-select-deck = אויסקלײַבן טעשל
actions-select-note-type = איבערקלײַבן מין-נאָטיץ
actions-show-answeranswer-good = באַווײַזן ענטפֿער/גוט ענטפֿער
actions-study-options = אײַנ׳חזר-ברירות
actions-tools = מכשירים
actions-tools-overlay = מכשירים-איבערלאָג
actions-top-bar = אויבנבאַלקן
actions-unbury-deck = צוריקנעמען טעשל
actions-undo = אַנולירן
actions-unmarked = אומבאַצייכענט
actions-you-can-only-empty-a-filtered = מען קען אויסליידיקן נאָר אַ פֿילטרירט טעשל.
actions-you-can-only-rebuild-a-filtered = מען קען צוריקבויען נאָר אַ פֿילטרירט טעשל.
actions-scroll-up = אַרויפֿבלעטערן
actions-scroll-down = אַראָפּבלעטערן

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = אויסליידיקן
# create a filtered deck
actions-filter-short = פֿילטרירן
actions-add-short = צולייגן
actions-answer-again-short = ווידער
actions-answer-easy-short = גרינג
actions-answer-good-short = גוט
actions-answer-hard-short = שווער
actions-auto-advance-short = אויטאָ-אַדוו
actions-bottom-bar-short = אונט.באַל
actions-browse-short = דורכקוקן
actions-bury-card-short = אָפּהאַל.ק
actions-bury-note-short = אָפּהאַל.נ
actions-card-info-short = ק.אינפֿאָ
actions-card-template-short = מוטסער
actions-current-audio-minus-5s-short = -5ס
actions-current-audio-plus-5s-short = +5ס
actions-custom-study-short = צוגעפּאַסט
actions-deck-statistics-short = ט.סטאַט
actions-decks-short = טעשלעך
actions-delete-note-short = אָפּמעק.
actions-edit-short = צופּאַסן
actions-mark-and-bury-short = בצ+אָ-ל
actions-mark-and-suspend-short = בצ+אָ-ש
actions-mark-short = צײַכ.
actions-night-mode-short = נאַכט
actions-off-short = אויס
actions-pause-audio-short = מפֿסיק
actions-rebuild-short = צ-בוי
actions-record-voice-short = רעק.ק
actions-replay-voice-short = א-ש.ק
actions-replay-audio-short = איברשפּ.
actions-reset-card-short = אײַנשט.ק
actions-scratchpad-short = בלאָקנ.
actions-scratchpad-size-short = בלאָק.גר
actions-set-due-date-short = בשט.טער.
actions-show-answer-short = ווז.ענ
actions-show-answeranswer-good-short = וו.גוט.ע
actions-study-options-short = ווז.ברי
actions-suspend-card-short = אָפּשט.ק
actions-suspend-note-short = אָפּשט.נאָ
actions-tools-short = מכשירים
actions-top-bar-short = אויבנ.ב
actions-unbury-deck-short = צ.נעמ
actions-undo-short = אַנולירן
actions-redo-short = איבערמאַכן
actions-scroll-up-short = אַרויף
actions-scroll-down-short = אַראָפּ
actions-back = הינטן
