actions-actions = טוּונגען
actions-add-new = שאַפֿן נײַ
actions-added-to-frequent-actions = צוגעשטעלט אין אָפֿטלעכע טוּונגען.
actions-all-actions = אַלע טוּונגען
actions-already-in-frequent-actions = שוין אין אָפֿטלעכע טוּונגען.
actions-an-error-occurred = ס׳איז פֿאָרגעקומען אַ גרײַז: { $error }
actions-answer-easy = ענטפֿערן גרינג
actions-are-you-sure = זיכער?
actions-bottom-bar = אונטנבאַלקן
actions-browse = דורכקוקן
actions-card-buried = קאַרטל אָפּגעהאַלטן
actions-card-suspended = קאַרטל אָפּגעשטעלט
actions-card-template = מוסטער-קאַרטל
actions-confirm-delete = באַשטעטיקן אויסמעק
actions-create = שאַפֿן
actions-current-audio-minus-5s = יעצטיקע אוידיאָ -5ס
actions-current-audio-plus-5s = יעצטיקע אוידיאָ +5ס
actions-custom-study-cant-be-used-on = מע טאָר נישט אײַנ׳חזר׳ן צוגעפּאַסט אַ פֿילטרירט טעשל.
actions-deck-statistics = טעשל-סטאַטיסטיקס
actions-delete-note-and-its-cards = אויסמעקן נאָטיץ און אירע קאַרטלעך?
actions-discard-changes = אַוועקוואַרפֿן טוישונגען
actions-done = געמאַכט
actions-downloading = אַראָפּלאָדנט זיך…
actions-drag-here-to-remove = צושלעפּ אַהער אויף אָפּצונעמען
actions-draw = סקיצירן
actions-file-invalid-or-corrupt = טעקע איז פּסול אָדער געשעדיקט.
actions-no-load-restore-backup = אײַער זאַמלונג האָט נישט געקענט לאָדירט ווערן. ביטע צוריקציט פֿון אַן אויטאָמאַטיש רעזערוו-קאָפּיע דורך די אויסוואַלן עקראַן.
actions-revert = צוריקציִען

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

actions-auto-advance-short = אויטאָ-אַדוו
actions-bottom-bar-short = אונט.באַל
actions-browse-short = דורכקוקן
actions-bury-card-short = אָפּהאַל.ק
actions-bury-note-short = אָפּהאַל.נ
actions-card-info-short = ק.אינפֿאָ
actions-card-template-short = מוטסער
actions-current-audio-minus-5s-short = -5ס
actions-current-audio-plus-5s-short = +5ס
actions-custom-study-short = צוגעפּאַסט
actions-deck-statistics-short = ט.סטאַט
actions-decks-short = טעשלעך
actions-delete-note-short = אָפּמעק.
actions-edit-short = צופּאַסן
actions-mark-short = צײַכ.
actions-night-mode-short = נאַכט
actions-off-short = אויס
actions-tools-short = מכשירים
actions-undo-short = אַנולירן
actions-redo-short = איבערמאַכן
actions-scroll-up-short = אַרויף
actions-scroll-down-short = אַראָפּ
actions-back = הינטן
