deck-options-add-options-group = צולייגן ברירות-גרופּע
deck-options-answer-time-cap = ענטפֿער-צײַט גרענעץ
deck-options-bury-related-new-cards = אָפּהאַלטן שײַכותדיקע נײַע קאַרטלעך
deck-options-bury-related-reviews = אָפּהאַלטן שײַכותדיקע חזר-קאַרטלעך
deck-options-defaults = דורך פֿעליקייט
deck-options-delete-options-full-sync = דאָס סויסמעקן די ברירות-גרופּע וועט פֿאַרהיטן, אַז יעדער טויש פֿון אַנדערע מכּשירים קען זיך נישט צונויפֿגיסן אויפֿן קומעדיקן סינכראָנירן. ממשיך זײַן?
deck-options-display-in-order-added = אָנווײַזן אין סדר וואָס צוגעלייגט
deck-options-display-in-random-order = אָנווײַזן אויף טראַף
deck-options-full-sync-required = פֿול סינכראָנירן נייטיק
deck-options-group-name = נאָמען פֿון גרופּע
deck-options-max-new-per-day = מאַקס. נײַ לויט מעת-לעת
deck-options-max-reviews-per-day = מאַקס. חזר-קאַרטלעך לויט מעת-לעת
deck-options-new-cards = נײַע קאַרטלעך
deck-options-options-group = ברירות-גרופּע
deck-options-replay-q-audio-in-answer = איבערשפּילן פֿ. אוידיאָ בײַ ענטפֿער
deck-options-reset-all-settings-to-defaults = אײַנשטעלן אַלע פֿיקסוריונגען ווי אויף לכתּחילה?
deck-options-restore-defaults = אויפֿריכטן ווי לכתּחילה
deck-options-steps = שטאַפּלען
