decks-a-deck-must-be-provided = מע מוז צולייגן אַ טעשל.
decks-a-deck-named-already-exists = ס׳איז שוין פֿאַראַן אַזאַ טעשל בײַם נאָמען '{ $name }'.
decks-a-deck-with-that-name-already = ס׳ איז שוין פֿאַראַן אַ טעשל פֿון אַזאַ נאָמען.
decks-add-deck = צושטעלן טעשל
decks-add-empty-deck = צולייגן ליידיק טעשל
decks-addexport = צושטעלן/אַרויספֿירן
decks-cannot-delete = מע קען נישט אָפּמעקן
decks-card-limit = קאַרטל-גרענעץ
decks-cards-in-a-filtered-deck-cant = קאַרטלעך וואָס אין אַ פֿילטרירט טעשל קען מען נישט איבעררוקן.
decks-custom-steps = צוגעפּאַסטע שטאַפּלען
decks-deck-exists = טעשל איז פֿאַראַן
decks-deck-label = טעשל:
decks-deck-name = טעשל-נאָמען
decks-deck-options = טעשל-ברירות
decks-download-link = אראָפּלאָד-לינקל
decks-export-collection = אַרויספֿירן זאַמלונג
decks-filtered-deck = פֿילטרירט טעשל
decks-import-from-itunes = אַרײַנפֿירן פֿון אײַ-טונז (iTunes)
decks-invalid-deck-name = טעשל-נאָמען גילט נישט.
decks-link-to-apkg-file-to-import = לינקל צו .apkg טעקע פֿאַרן אַרײַנפֿירן:
decks-no-matches = קיין גלײַכנס
decks-return-by-delete = כּדי צוריקצורוקן אַלע קאַרטלעך אין איינעם, טאָ אַ פֿיר איבער׳ן בלויע טעשל אין טעשל-רשימה, דערנאָך מעק עס אָפּ.
decks-shared-deck-list = בשותּפֿותדיקע-טעשל-רשימה
decks-sync = סינכ.
decks-synchronize = סיכראָניזירן
decks-the-default-deck-cannot-be-deleted = דאָס טעשל דורך פֿעליקייט קען נישט אָפּגעמעקט ווערן.
decks-the-provided-deck-does-not-exist = אַזאַ טעשל איז נישט פֿאַראַן.
decks-the-search-you-provided-did-not = די זוך וואָס איר האָט צוגעשטעלט איז נישט גלײַך מיט קיין קאַרטל.
decks-will-be-returned = קאַטלעך וועלן צוריקגעלייגט ווערן אין זייער עיקר-טעשל בײַם זיי פֿאַרענטפֿערן.
