preferences-about = מכּוח
preferences-autoplay-in-silent-mode = שפּילן אויטאָמאַטיש בשעת שטוממאָדוס
preferences-always-duck = פֿאַרשטילן הינטערגרונד תּמיד
preferences-answer-keeps-zoom = ענטפֿער האַלט זום
preferences-answer-side = ענטפֿער-זײַט
preferences-audio-buttons = אוידיאָ-קנעפּלעך
preferences-auto-advance-answer-action = ענטפֿער טוּונג
preferences-auto-advance-answer-seconds = ענטפֿער סעקונדעס
preferences-auto-advance-auto-advance-to-start = כּדי אָנצוהייבן פֿאָרויסגיין אויטאָמאַטיק, ניץ די 'אויטאָ-פֿאָראויסגיין' טוּונג.
preferences-auto-advance-do-nothing = גאָרנישט מאַכן
preferences-auto-advance-question-seconds = פֿראַגע סעקונדעס
preferences-backup-available-backups = רעזערוו-קאָפּיעס בנימצא
preferences-backup-create-now = באַשאַפֿן יעצט
preferences-backup-maximum-backups = מאַקסימאַל צאָל רעזערוו-קאָפּיעס
preferences-backup-minutes-between-backups = מינוטן צווישן רעזערוו-קאָפּיעס
preferences-backup-revert-to-backup = צוריקציִען אין אַ רעזערוו-קאָפּיע
preferences-backup-revert-to-backup-confirm = צוריקציִען אין { $backup }? יעדער טוישונג זינט דער רעזערוו-קאָפּיע וועט פֿאַרלוירן ווערן.
preferences-backup-reverted-to-backup = צוריקגעצויגן אין דער רעזערוו-קאָפּיע.
preferences-bottom-bar-size = אונטנבאַלקן-גרייס
preferences-bottom-center = אונטן-צענטער
preferences-bottom-left = אונטן-לינקס
preferences-bottom-right = אונטן-רעכטס
preferences-button-d = קנעפּל { $num }
preferences-collection-day-starts = טאָג הייבט זיך אָן
preferences-collection-learn-ahead-minutes = מינוטן פון לערנען זיך אין פֿאָראויס
preferences-collection-mix = געמיש
preferences-collection-new-first = נײַע קודם
preferences-collection-newreview-order = נײַ/אײַנ׳חזר-סדר
preferences-collection-reviews-first = איבער׳חזר׳ונגען קודם
preferences-double-tap-prevention = פֿאַרהיטן טאָפּל-טאַפּן
preferences-open-links-externally = עפֿענען לינקלעך אויסנווייניק
preferences-drawing-screen-ignores-fingers = סקיציר-עקראַן איגנאָרירט פֿינגער
preferences-feedback-ticks = אָפּרוף-טיקענען
preferences-spread-ticks = אויסשפּרייט-טיקענען
preferences-fine = דין
preferences-force-sync-confirm = צווינגען אַן אַהינסיכראָנירונג? ס׳וועלן אַלע בײַטן אויף איין זײַט פֿאַרלוירן ווערן.
preferences-full-sync = אַהינסינכראָניזירן
preferences-gamepad-button-mapping = קנעפּל-מאַפּירונג
preferences-gamepad-menu-button = מעניו
preferences-gamepads = שפּיל-קאָנטראָלערס
preferences-height = הייך
preferences-huge = ריזיק
preferences-ignore-fingers = איגנאָרירן פֿינגער
preferences-interrupt-current-audio = איבעררײַסן גייי‎ִקע קלאַנג
preferences-large = גרויס
preferences-left = לינקס
# gamepad
preferences-left-shoulder = לינקער אַקסל
# gamepad
preferences-left-trigger = לינקע צינגל
preferences-logged-in-as = אַרײַנגעשריבן ווי:
preferences-long = לאַנג
preferences-mid-center = מיטל-צענטער
preferences-mid-left = מיטל-לינקס
preferences-mid-right = מיטל-רעכטס
preferences-never-type-answer = קײנמאָל נישט אײַנקלאַפּן ענטפֿער
preferences-never-show-scratchpad = קײנמאָל נישט ווײַזן בלאָקנאָט
preferences-never-show-scratchpad-enabled = „נישט ווײַזן קיין מאָל בלאָקנאָט״ איז אַקטיווירט אין די אויסוואַלן-עקראַן.
preferences-next-times = נעקסטיקע מאָלן
preferences-normal = סתּם
preferences-notifications = הודעות
preferences-notifications-alert-time = הודעה-צײַט
preferences-notifications-alert-when-due = מודיע זײַן ווען טערמיניק
preferences-pen-size = פֿעדער-גרייס
preferences-question-side = פֿראַגע-גרייס
preferences-remaining-count = חשבון פֿון געבליבענע קאַרטלעך
preferences-right = רעכטס
# gamepad
preferences-right-shoulder = רעכטער אַקסל
# gamepad
preferences-right-trigger = רעכטע צינגל
preferences-scratchpad-transparency = בלאָקנאָט דורכזעיִקײט
preferences-scratchpad-transparency-full = פֿול
preferences-scratchpad-transparency-medium = מעדיום
preferences-scratchpad-transparency-none = קיין איינער
preferences-scratchpad-transparency-slight = קנאַפּ
preferences-shake-action = שאָקל-אַקציע
preferences-short = קורץ
preferences-show-bottom-bar = באַווײַזן אונטנבאַלקן
preferences-show-grid = ווײַזן געפֿלעכט
preferences-show-top-bar = ווײַזן אויבנבאַלקן
preferences-small = קליין
preferences-swipe-down = אַ פֿיר טאָן אַראָפּ
preferences-swipe-left = אַ פֿיר טאָן אויף לינקס
preferences-swipe-right = אַ פֿיר טאָן אויף רעכטס
preferences-swipe-up = אַ פֿיר טאָן אַרויף
preferences-swipes = פֿירן טאָן
preferences-swipes-must-begin-from-the-far = פֿירן מוזן אָנהייבן פֿון ווײַט-לינקס אָדער -רעכטס פֿון עקראַן
preferences-sync-sounds-images = סינכראָניזירן קלאַנג און בילדער
preferences-syncing = סיכראָניזירן
preferences-taps = טאַפּן
preferences-theme-bar-style = באַלקן-שטײגער
preferences-theme-black = שוואַרץ
preferences-theme-dark-translucent = טונקל און דורכלײַכטיק
preferences-theme-force-off = צווינגען אָפּ
preferences-theme-force-on = צווינגען אָן
preferences-theme-light-translucent = ליכטיק און דורכלײַכטיק
preferences-theme-night-mode-desc = נאַכט-מאָדוס פֿאַרטונקלט דעם צווישנבינד, און ווײַזט קאַרטלעך אַלס ווײַס אויף שוואַרץ.
preferences-theme-night-mode-same-as-system = לויט דער סיסטעם
preferences-thick = דיק
preferences-tools-overlay-button = מכשירים-איבערלאָג קנעפּל
preferences-tools-overlay-position = מכשירים-איבערלאָג פּאָזיציע
preferences-top-center = אויבן-צענטער
preferences-top-left = אויבן-לינקס
preferences-top-right = אויבן-רעכטס
preferences-undo-clears-all = אַנולירן רייניקט אַלץ אָפּ
preferences-when-answer-shown = אויפֿן באַווײַזן דער ענטפֿער
preferences-when-question-shown = אויפֿן באַוויזן די פֿראַגע
preferences-you-have-been-logged-out = האָסט זיך אַרויסגעשריבן.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = מאַקסימאַל בילד-גרייס (לאַנגער ראַנד)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = בײַטן גרייס בײַם קלעפּן
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = איבערמאַכן קלוג-גענזעל-פֿיסלעך און טירעען
preferences-editing-crop-camera-photos = צושנײַדן קאַמערע-בילדער
preferences-loop-video = שפּילן ווידעאָ אויף פּעטליע
preferences-show-video-controls = באַווײַזן ווידעאָ-קאָנטראָלן
preferences-high-quality-video = ווידעאָ פֿון איכות
preferences-auto-capitalize = שטעלן אויטאָמאַטיש מיט גרױסע אותיות
preferences-auto-correct = אויטאָ-פֿאַרריכטן
preferences-strip-hebrew-vowels = אַרויסוואַרפֿן נקודים
