profiles-a-profile-with-that-name-already = ס׳ איז שוין פֿאַראַן אַ פּראָפֿיל פֿון אַזאַ נאָמען.
profiles-add-profile = צושטעלן פּראָפֿיל
profiles-finishing-backup = ס׳ווערט פֿאַרענדיקט רעזערוו-קאָפּיע…
profiles-please-provide-some-text-avoiding-symbols = ביטע שטעל צו עפּעס טעקסט, אָן קיין סימבאָל אָדער אונטערשטריך.
profiles-please-select-another-profile-first = קודם קלײַב אויס אַן אַנדער פּראָפֿיל.
profiles-profile-name = פּראָפֿיל-נאָמען
profiles-rename-profile = איבעררופֿן פּראָפֿיל
profiles-unable-to-open-safari-please = 'Safari' ווערט נישט געעפֿענט - ביטע גיב אַ קוק איבער עלטער-קאָנטראָל.
profiles-welcome = ברוך-הבאָ!
