preferences-answer-side = ଉତ୍ତର ପାର୍ଶ୍ୱ
preferences-auto-advance-do-nothing = କିଛି କରନ୍ତୁନି
preferences-collection-new-first = ପ୍ରଥମେ ନୂଆ
preferences-collection-newreview-order = ନୂଆ/ସମୀକ୍ଷା କ୍ରମ
preferences-collection-reviews-first = ପ୍ରଥମେ ସମୀକ୍ଷା
preferences-fine = ସୂକ୍ଷ୍ମ
preferences-full-sync = ପୂର୍ଣ୍ଣ ସିଙ୍କ୍
preferences-gamepad-menu-button = ମେନୁ
preferences-height = ଉଚ୍ଚତା
preferences-left = ବାମ
# gamepad
preferences-left-shoulder = ବାମ କାନ୍ଧ
preferences-normal = ସାଧାରଣ
preferences-notifications = ବିଜ୍ଞପ୍ତି
preferences-pen-size = କଲମ ଆକାର
preferences-question-side = ପ୍ରଶ୍ନ ପାର୍ଶ୍ୱ
preferences-remaining-count = ବଳକା ଗଣନା
preferences-right = ଡାହାଣ
# gamepad
preferences-right-shoulder = ଡାହାଣ କାନ୍ଧ
preferences-scratchpad-transparency-full = ପୁରା
preferences-shake-action = ଦୋହଲାଇଲେ
preferences-swipe-down = ତଳକୁ ସ୍ଵାଇପ୍ କଲେ
preferences-swipe-left = ବାମକୁ ସ୍ଵାଇପ୍ କଲେ
preferences-swipe-right = ଡାହାଣକୁ ସ୍ଵାଇପ୍ କଲେ
preferences-swipe-up = ଉପରକୁ ସ୍ଵାଇପ୍ କଲେ
preferences-theme = ଥିମ୍
preferences-theme-bar-style = ଦଣ୍ଡିକାର ଶୈଳୀ
preferences-theme-black = କଳା
preferences-theme-dark-translucent = ଗାଢ଼ ଓ ଆବରଣଯୁକ୍ତ
preferences-theme-force-off = ବଳପୂର୍ବକ ବନ୍ଦ କରନ୍ତୁ
preferences-theme-force-on = ବଳପୂର୍ବକ ଚାଲୁ କରନ୍ତୁ
preferences-theme-light-translucent = ହାଲୁକା ଓ ଆବରଣଯୁକ୍ତ
preferences-theme-night-mode-desc = ରାତ୍ରି ମୋଡ୍ ଇଣ୍ଟରଫେସ୍ କୁ ଅନ୍ଧାର କରେ, ଏବଂ କଳା ଉପରେ ଧଳା ଥିଲାଭଳି ପତ୍ରଗୁଡ଼ିକ ପ୍ରଦର୍ଶନ କରେ।
preferences-theme-night-mode-same-as-system = ସିଷ୍ଟମ୍ କୁ ଅନୁସରଣ କରିବା
preferences-theme-slate = ପାଉଁସିଆ
