actions-actions = Әрекеттер
actions-add-new = Жаңа Қосу
actions-added-to-frequent-actions = Жиі әрекеттерге қосылды.
actions-all-actions = Барлық Әрекет
actions-already-in-frequent-actions = Онсыз да жиі әрекеттерге қосылған.
actions-an-error-occurred = Қате шықты: { $error }
actions-answer-easy = Оңай Деу
actions-are-you-sure = Расымен бе?
actions-bottom-bar = Төменгі Жолақ
actions-browse = Шолып Көру
actions-card-buried = Карта тығылды
actions-card-suspended = Карта кідіртілді
actions-card-template = Карта Үлгісі
actions-confirm-delete = Жоюды Растау
actions-create = Жасау
actions-current-audio-minus-5s = Ағымдағы Аудио -5с
actions-current-audio-plus-5s = Ағымдағы Аудио +5с
actions-deck-statistics = Колода Санағы
actions-delete-note-and-its-cards = Жазба мен оның карталарын жою?
actions-discard-changes = Өзгерістерді Тастау
actions-done = Дайын
actions-downloading = Жүктеп алу...
actions-drag-here-to-remove = Жою үшін осы жерге апарыңыз
actions-draw = Сурет Салу
actions-file-invalid-or-corrupt = Файл жарамсыз не бұзылған.
actions-filtercram = Сүзу/Нықтау
actions-filtered-deck = Сүзілген Колода { $num }
actions-frequent-actions = Жиі Әрекеттер
actions-leave-without-saving = Сақтамай шығу?
actions-mark = Белгілеу
actions-mark-and-bury = Белгілеу + Тығу
actions-mark-and-suspend = Белгілеу + Кідірту
actions-marked = Белгіленген
actions-no-current-card = Ағымда карта жоқ.
actions-note-buried = Жазба тығылды
actions-note-marked-and-buried = Жазба белгіленіп тығылды
actions-off = Өшірулі
actions-record-voice = Дауысты Жазу
actions-record-voice-menu = Дауыс Жазу Мәзірі
actions-reset-card = Картаны Ысыру
actions-revert = Қайтару
actions-review-undone = Шолым Болдырылмады
actions-scratchpad = Блокнот
actions-scratchpad-size = Блокноттың Өлшемі
actions-select-deck = Колоданы Таңдау
actions-select-note-type = Жазба Түрін Таңдау
actions-show-answeranswer-good = Жауапты Көрсету/Жақсы Деу
actions-study-options = Оқу Баптаулары
actions-tools = Құралдар
actions-tools-overlay = Құралдар Аражабыны
actions-top-bar = Үстінгі Жолақ
actions-unbury-deck = Колоданы Ақтару
actions-undo = Болдырмау
actions-unmarked = Белгіленбеген
actions-you-can-only-empty-a-filtered = Сүзілген колоданы ғана босата аласыз.
actions-you-can-only-rebuild-a-filtered = Сүзілген колоданы ғана қайта құра аласыз.
actions-scroll-up = Үстіге Қарай Жылжу
actions-scroll-down = Төмен Қарай Жылжу

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Бос
# create a filtered deck
actions-filter-short = Сүзгі
actions-add-short = Қосу
actions-answer-again-short = Қайта
actions-answer-easy-short = Оңай
actions-answer-good-short = Жақсы
actions-answer-hard-short = Қиын
actions-auto-advance-short = Өз-Ілг.
actions-bottom-bar-short = Төм.Ж
actions-browse-short = Шолу
actions-bury-card-short = К.Тығу
actions-bury-note-short = Ж.Тығу
actions-card-info-short = К.Ақпар
actions-card-template-short = Үлгі
actions-current-audio-minus-5s-short = -5с
actions-current-audio-plus-5s-short = +5с
actions-custom-study-short = Өзгертп
actions-deck-statistics-short = К.Санақ
actions-decks-short = Колод.
actions-delete-note-short = Жою
actions-edit-short = Өңдеу
actions-mark-and-bury-short = Бел&Тығ
actions-mark-and-suspend-short = Бел&Кід
actions-mark-short = Белгі
actions-night-mode-short = Түн
actions-off-short = Өш.
actions-pause-audio-short = Іркіліс
actions-rebuild-short = Қ.Құру
actions-record-voice-short = Д.Жазу
actions-replay-voice-short = Д.Қайта
actions-replay-audio-short = Қайтала
actions-reset-card-short = К.Ысыру
actions-scratchpad-short = Блокнот
actions-scratchpad-size-short = Блок.Ө
actions-set-due-date-short = Меріз.О
actions-show-answer-short = Жау.Көр
actions-show-answeranswer-good-short = Көр/Жау
actions-study-options-short = Оқу.Бап
actions-suspend-card-short = К.Кідір
actions-suspend-note-short = Ж.Кідір
actions-tools-short = Құрал
actions-top-bar-short = Ү.Жолақ
actions-unbury-deck-short = Ақтару
actions-undo-short = Болдырм
actions-redo-short = Қайтару
actions-scroll-up-short = Үсті
actions-scroll-down-short = Асты
actions-back = Арты
