deck-options-add-options-group = Баптаулар Тобын Қосу
deck-options-answer-time-cap = Жауап уақытының шегі
deck-options-defaults = Әдепкілер
deck-options-display-in-random-order = Кездейсоқ ретте көрсету
deck-options-full-sync-required = Толық Үйлесім Қажет
deck-options-group-name = Топ атауы
deck-options-max-new-per-day = Күндік жаңа карта шегі
deck-options-max-reviews-per-day = Күндік шолу шегі
deck-options-new-cards = Жаңа карталар
deck-options-options-group = Баптаулар тобы
deck-options-reset-all-settings-to-defaults = Барлық баптауды қалпына келтіру?
deck-options-restore-defaults = Қалпына Келтіру
deck-options-steps = Қадамдар
