decks-a-deck-must-be-provided = Колода ұсыну керек.
decks-a-deck-named-already-exists = '{ $name }' атаулы колода онсыз да бар.
decks-a-deck-with-that-name-already = Осындай атаулы колода онсыз да бар.
decks-add-deck = Колода Қосу
decks-add-empty-deck = Бос Колода Қосу
decks-addexport = Қосу/Шығару
decks-cannot-delete = Жоя Алмайды
decks-card-limit = Карталар шегі
decks-deck-exists = Колода Бар
decks-deck-label = Колода:
decks-deck-name = Колода Атауы
decks-deck-options = Колода Баптаулары
decks-download-link = Жүктеу Сілтемесі
decks-export-collection = Жинақты Экспорттау
decks-filtered-deck = Сүзілген Колода
decks-import-from-itunes = iTunes-тен импорттау
decks-invalid-deck-name = Жарамсыз колода атауы.
decks-link-to-apkg-file-to-import = .apkg файлын импорттау сілтемесі:
decks-no-matches = Сәйкестік Жоқ
decks-return-by-delete = Барлық картаны бірден қайтару үшін, тізімдегі көк колоданы сырғытып, өшіріңіз.
decks-shared-deck-list = Отрақ Колодалар Тізімі
decks-sync = Үйлестіру
decks-synchronize = Үйлестеру
decks-the-default-deck-cannot-be-deleted = Әдепкі колоданы жоюға болмайды.
decks-the-provided-deck-does-not-exist = Ұсынылған колода жоқ.
decks-the-search-you-provided-did-not = Сіздің іздеуіңіз бойынша карта табылмады.
decks-will-be-returned = Карталар жауап берген сайын бастапқы колодасына қайтарылады.
