editing-bold = Қалың
editing-cancel-and-lose-any-unsaved-changes = Доғарып, сақталмаған өзгерістерді жоғалту?
editing-cant-edit-original-image-data = Өңдеу мүмкін емес – бастапқы сурет деректері табылмады.
editing-card-returned-to-new-card-queue = Карта жаңа карталар кезегіне оралды.
editing-card-unsuspended = Карта кідіртілді
editing-from-camera = Камерадан
editing-from-file = Файлдан
editing-from-photos = Фотолардан
editing-italic = Көлбеу
editing-next-field = Келесі Өріс
editing-note-deleted = Жазба жойылды
editing-note-suspended = Жазба кідірді
# (Note) type: 
editing-note-type-prompt = Түр:
editing-note-unsuspended = Жазба тірілді
editing-underline = Астын Сызу
editing-unexpected-status-code = Күтпеген күй коды:
editing-discard-changes-question = Өзгерістерді тастау?
editing-discard = Тастау
editing-keep-editing = Өңдеуді Жалғастыру
