importing-delete-imported-file = Импортталған файлды жою?
importing-import-complete = Импорт аяқталды.
importing-importing = Импорттау...
importing-no-apkg-or-colpkg-files-were = iTunes-тен .apkg не .colpkg файлдары таблмады
importing-overwrite-via-import = Бүкіл жинақты импортталған файлмен қайта жазу? Бұл әрекетті болдырмауға болмайды.
importing-please-choose-a-file = Файл таңдаңыз.
importing-processed-media-files-d = Өңделген медиа файлдар: { $count }...
importing-replace-collection = Жинақты Ауыстыру
importing-file-not-downloaded = Файлды iCloud-тан жүктеп алып, қайталап көріңіз.
