preferences-about = Жайлы
preferences-autoplay-in-silent-mode = Тыныш Режимде Өзойнау
preferences-always-duck = Өң Дыбысын Әрдайым Бәсеңдету
preferences-answer-keeps-zoom = Жауап Өлшемді Сақтайды
preferences-answer-side = Жауап Жағы
preferences-audio-buttons = Ауидо Батырмалары
preferences-auto-advance-answer-action = Жауап Әрекеті
preferences-auto-advance-answer-seconds = Жауап Секундары
preferences-auto-advance-auto-advance-to-start = Өзінен-өзі ілгеріле бастау үшін, 'Өзілгерілеу' әрекетін қолданыңыз.
preferences-auto-advance-do-nothing = Ештеңе Істемеу
preferences-auto-advance-question-seconds = Сұрақ Секундары
preferences-backup-available-backups = Қолжетімді сақтық көшірмелер
preferences-backup-create-now = Қазір Жасау
preferences-backup-maximum-backups = Сақтық Көшірмелер Шектеуі
preferences-backup-minutes-between-backups = Көшірмелер Аралығы (Мин)
preferences-backup-revert-to-backup = Қалпына Келтіру
preferences-backup-revert-to-backup-confirm = { $backup } қайтару? Сақтық көшірмеден кейін жасалған өзгерістер жоғалады.
preferences-backup-reverted-to-backup = Қалпына келтірілді.
preferences-bottom-bar-size = Төменгі Жолақ Өлшемі
preferences-bottom-center = Төменгі Орта
preferences-bottom-left = Төменгі Сол
preferences-bottom-right = Төменгі Оң
preferences-button-d = Батырма { $num }
preferences-collection-day-starts = Күннің Басталуы
preferences-collection-learn-ahead-minutes = Озып Оқу (Минут)
preferences-collection-mix = Араластыру
preferences-collection-new-first = Алдымен жаңа
preferences-collection-newreview-order = Жаңа/Шолу Реті
preferences-collection-reviews-first = Алдамен шолу
preferences-double-tap-prevention = Қос Түртуді Болғызбау
preferences-open-links-externally = Сілтемелерді Сыртта Ашу
preferences-drawing-screen-ignores-fingers = Сызу Бейнебеті Саусақты Елемейді
preferences-fine = Жұқа
preferences-full-sync = Толық Үйлесім
preferences-gamepad-menu-button = Мәзір
preferences-gamepads = Геймпад
preferences-height = Биіктік
preferences-huge = Алып
preferences-ignore-fingers = Саусақты Елемеу
preferences-interrupt-current-audio = Ағымдағы Аудионы Үзу
preferences-large = Үлкен
preferences-left = Сол
# gamepad
preferences-left-shoulder = Сол Иық
# gamepad
preferences-left-thumbstick-button = Сол Стик Батырмасы
# gamepad
preferences-left-trigger = Сол Триггер
preferences-logged-in-as = Кірген:
preferences-long = Ұзын
preferences-mid-center = Орта
preferences-mid-left = Орта Сол
preferences-mid-right = Орта Оң
preferences-never-type-answer = Жауапты Ешқашан Термеу
preferences-never-show-scratchpad = Блокнотты Ешқашан Көрсетпеу
preferences-next-times = Келесі Реттер
preferences-normal = Қалыпты
preferences-notifications = Ескертпелер
preferences-notifications-alert-time = Ескерту Уақыты
preferences-pen-size = Қалам Өлшемі
preferences-right = Оң
# gamepad
preferences-right-shoulder = Оң Иық
# gamepad
preferences-right-thumbstick-button = Оң Стик Батырмасы
# gamepad
preferences-right-trigger = Оң Триггер
preferences-scratchpad-transparency-none = Ештеңе
preferences-short = Қысқа
preferences-small = Кішкентай
preferences-thick = Қалың
preferences-top-center = Үстінгі Орта
preferences-top-left = Үстінгі Сол
preferences-top-right = Үстінгі Оң
preferences-undo-clears-all = Болдырмау Бәрін Ысырады
preferences-auto-correct = Өзтүзету
