preferences-about = Жайлы
preferences-autoplay-in-silent-mode = Тыныш Режимде Өзойнау
preferences-always-duck = Өң Дыбысын Әрдайым Бәсеңдету
preferences-answer-keeps-zoom = Жауап Өлшемді Сақтайды
preferences-answer-side = Жауап Жағы
preferences-audio-buttons = Ауидо Түймелері
preferences-auto-advance-answer-action = Жауап Әрекеті
preferences-auto-advance-answer-seconds = Жауап Секундары
preferences-auto-advance-auto-advance-to-start = Өзінен-өзі ілгеріле бастау үшін, 'Өзілгерілеу' әрекетін қолданыңыз.
preferences-auto-advance-do-nothing = Ештеңе Істемеу
preferences-auto-advance-question-seconds = Сұрақ Секундары
preferences-backup-available-backups = Қолжетімді сақтық көшірмелер
preferences-backup-create-now = Қазір Жасау
preferences-backup-maximum-backups = Сақтық Көшірмелер Шектеуі
preferences-backup-minutes-between-backups = Көшірмелер Аралығы (Мин)
preferences-backup-revert-to-backup = Қалпына Келтіру
preferences-backup-revert-to-backup-confirm = { $backup } қайтару? Сақтық көшірмеден кейін жасалған өзгерістер жоғалады.
preferences-backup-reverted-to-backup = Қалпына келтірілді.
preferences-bottom-bar-size = Төменгі Жолақ Өлшемі
preferences-bottom-center = Төменгі Орта
preferences-bottom-left = Төменгі Сол
preferences-bottom-right = Төменгі Оң
preferences-button-d = Түйме { $num }
preferences-collection-day-starts = Күннің Басталуы
preferences-collection-learn-ahead-minutes = Озып Оқу (Минут)
preferences-collection-mix = Араластыру
preferences-collection-new-first = Алдымен жаңа
preferences-collection-newreview-order = Жаңа/Шолым Реті
preferences-collection-reviews-first = Алдымен шолымдар
preferences-double-tap-prevention = Қос Түртуді Болғызбау
preferences-open-links-externally = Сілтемелерді Сыртта Ашу
preferences-drawing-screen-ignores-fingers = Сызу Бейнебеті Саусақты Елемейді
preferences-feedback-ticks = Кері Байланыс Белгілері
preferences-spread-ticks = Белгілерді Жаю
preferences-fine = Жұқа
preferences-full-sync = Толық Үйлесім
preferences-gamepad-button-mapping = Түймелерді Бейнелеу
preferences-gamepad-menu-button = Мәзір
preferences-gamepads = Геймпад
preferences-height = Биіктік
preferences-huge = Алып
preferences-ignore-fingers = Саусақты Елемеу
preferences-interrupt-current-audio = Ағымдағы Аудионы Үзу
preferences-large = Үлкен
preferences-left = Сол
# gamepad
preferences-left-shoulder = Сол Иық
# gamepad
preferences-left-thumbstick-button = Сол Стик Түймесі
# gamepad
preferences-left-trigger = Сол Триггер
preferences-logged-in-as = Кірген:
preferences-long = Ұзын
preferences-mid-center = Орта
preferences-mid-left = Орта Сол
preferences-mid-right = Орта Оң
preferences-never-type-answer = Жауапты Ешқашан Термеу
preferences-never-show-scratchpad = Блокнотты Ешқашан Көрсетпеу
preferences-next-times = Келесі Реттер
preferences-normal = Қалыпты
preferences-notifications = Ескертпелер
preferences-notifications-alert-time = Ескерту Уақыты
preferences-notifications-alert-when-due = Мерізімінде Ескерту
preferences-notifications-app-icon-shows-due-count = Белгіше Дайын Карта Санын Көрсетеді
preferences-pen-size = Қалам Өлшемі
preferences-right = Оң
# gamepad
preferences-right-shoulder = Оң Иық
# gamepad
preferences-right-thumbstick-button = Оң Стик Түймесі
# gamepad
preferences-right-trigger = Оң Триггер
preferences-scratchpad-below-buttons = Шимай Парағы Түйменің Астында
preferences-scratchpad-transparency = Шимай Парағының Мөлдірлігі
preferences-scratchpad-transparency-full = Толық
preferences-scratchpad-transparency-medium = Орташа
preferences-scratchpad-transparency-none = Ештеңе
preferences-scratchpad-transparency-slight = Шағын
preferences-shake-action = Сілку Әрекеті
preferences-short = Қысқа
preferences-show-bottom-bar = Төменгі Жолақты Көрсету
preferences-show-grid = Торды Көрсету
preferences-show-top-bar = Үстінгі Жолақты Көрсету
preferences-small = Кішкентай
preferences-swipe-down = Төменге Сығырту
preferences-swipe-left = Солға Сығырту
preferences-swipe-right = Оңға Сығырту
preferences-swipe-up = Үстіге Сығырту
preferences-swipes = Сығыртулар
preferences-sync-sounds-images = Дыбыстар мен Суреттерді Үйлестіру
preferences-syncing = Үйлестіру
preferences-taps = Түртулер
preferences-theme-bar-style = Жолақ Стилі
preferences-theme-black = Қара
preferences-theme-dark-translucent = Күңгірт & Мөлдір
preferences-theme-force-off = Күштеп Өшіру
preferences-theme-force-on = Күштеп Қосу
preferences-theme-light-translucent = Жарық & Мөлдір
preferences-theme-night-mode-same-as-system = Жүйеге Сүйену
preferences-theme-slate = Сұр
preferences-thick = Қалың
preferences-tools-overlay-button = Құралдар Аражабыны Батырмасы
preferences-tools-overlay-position = Құралдар Аражабынының Орны
preferences-top-center = Үстінгі Орта
preferences-top-left = Үстінгі Сол
preferences-top-right = Үстінгі Оң
preferences-undo-clears-all = Болдырмау Бәрін Ысырады
preferences-when-answer-shown = Жауап көрсетілгенде
preferences-when-question-shown = Сұрақ көрсетілгенде
preferences-you-have-been-logged-out = Жүйеден шығарылдыңыз.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Суреттің Шекті Өлшемі (Ұзын Шеті)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Қойғанда Өлшемді Өзгерту
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Жұп Тырнақша & Сызқшаны Түрлендіру
preferences-editing-crop-camera-photos = Камера Суреттерін Қиып Алу
preferences-loop-video = Бейнені Тұйықтау
preferences-show-video-controls = Бейне Басқаруын Көрсету
preferences-high-quality-video = Сапасы Жоғары Бейне
preferences-auto-capitalize = Ауто Бас Әріптер
preferences-auto-correct = Өзтүзету
preferences-strip-hebrew-vowels = Иурит Дауыстыларын Сыдыру
