profiles-a-profile-with-that-name-already = Атауы осындай бейін онсыз да бар.
profiles-add-profile = Бейін Қосу
profiles-finishing-backup = Сақтық Көшіруді Аяқтау...
profiles-please-provide-some-text-avoiding-symbols = Таңбалар мен астыңғы сызықтар қоспай, біршама мәтін беріңіз.
profiles-please-select-another-profile-first = Алдымен басқа бейін таңдаңыз.
profiles-profile-name = Бейін атауы
profiles-rename-profile = Бейінді Қайта Атау
profiles-unable-to-open-safari-please = Safari ашылмайды - ата-ана бақылауын тексеріңіз.
profiles-welcome = Қош келдіңіз!
