actions-actions = Actions
actions-add-new = Add New
actions-added-to-frequent-actions = Added to frequent actions.
actions-all-actions = All Actions
actions-already-in-frequent-actions = Already in frequent actions.
actions-an-error-occurred = An error occurred: { $error }
actions-answer-again = Answer Again
actions-answer-easy = Answer Easy
actions-answer-good = Answer Good
actions-answer-hard = Answer Hard
actions-are-you-sure = Are you sure?
actions-auto-advance = Auto Advance
actions-auto-advance-short = Auto Adv.
actions-bottom-bar = Bottom Bar
actions-bottom-bar-short = Bot.B
actions-browse = Browse
actions-bury-card-short = Bury.C
actions-bury-note-short = Bury.N
actions-card-buried = Card buried
actions-card-info = Card Info
actions-card-info-short = C.Info
actions-card-suspended = Card suspended
actions-card-template = Card Template
actions-confirm-delete = Confirm Delete
actions-create = Create
actions-current-audio-minus-5s = Current Audio -5s
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s = Current Audio +5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-cant-be-used-on = Custom study can't be used on a filtered deck.
actions-custom-study-short = Custom
actions-deck-statistics = Deck Statistics
actions-deck-statistics-short = D.Stats
actions-delete-note-and-its-cards = Delete note and its cards?
actions-delete-note-short = Del
actions-discard-changes = Discard Changes
actions-done = Done
actions-downloading = Downloading...
actions-drag-here-to-remove = Drag here to remove
actions-draw = Draw
actions-file-invalid-or-corrupt = File invalid or corrupt.
actions-filtercram = Filter/Cram
actions-filtered-deck = Filtered Deck { $num }
actions-flag-1 = Flag 1
actions-flag-1-red = Flag 1 (Red)
actions-flag-2 = Flag 2
actions-flag-2-orange = Flag 2 (Orange)
actions-flag-3 = Flag 3
actions-flag-3-green = Flag 3 (Green)
actions-flag-4 = Flag 4
actions-flag-4-blue = Flag 4 (Blue)
actions-forgot-card = Forgot card
actions-frequent-actions = Frequent Actions
actions-how-many-days-in-the-future = How many days in the future?
actions-invalid-number-of-days = Invalid number of days.
actions-leave-without-saving = Leave without saving?
actions-long-press-on-an-item-to = Long press on an item to customize.
actions-mark = Mark
actions-mark-and-bury = Mark + Bury
actions-mark-and-bury-short = M&B
actions-mark-and-suspend = Mark + Suspend
actions-mark-and-suspend-short = M&S
actions-marked = Marked
actions-night-mode-short = Night
actions-no-current-card = No current card.
actions-no-load-restore-backup = Your collection couldn't be loaded. Please restore from an automatic backup via the preferences screen.
# (http://example.com) does not appear to be...
actions-not-valid-link = does not appear to be a valid http/https link.
actions-note-and-its-cards-deleted = Note and its { $count } cards deleted
actions-note-and-its-cards-suspended = Note and its { $count } card(s) suspended
actions-note-buried = Note buried
actions-note-marked-and-buried = Note marked and buried
actions-nothing-to-undo = Nothing to undo
actions-off = Off
actions-pause-audio-short = Pause
actions-please-tap-the-in-the = Please tap the '?' in the top left to get started.
actions-processing = Processing...
actions-record-voice = Record Voice
actions-record-voice-short = Record
actions-replay-audio-short = Replay
actions-reset-card = Reset Card
actions-reset-card-short = Reset.C
actions-revert = Revert
actions-review-undone = Review undone
actions-scratchpad = Scratchpad
actions-scratchpad-short = Pad
actions-scratchpad-size = Scratchpad Size
actions-scratchpad-size-short = Pad Size
actions-select-deck = Select Deck
actions-select-note-type = Select Note Type
actions-set-due-date = Set Due Date
actions-set-due-date-short = S.Date
actions-show-answer-short = S.Ans
actions-show-answeranswer-good = Show Answer/Answer Good
actions-show-answeranswer-good-short = Show/Good
actions-study-options = Study Options
actions-study-options-short = S.Opt
actions-suspend-card-short = Sus.C
actions-suspend-note-short = Sus.N
actions-tools = Tools
actions-tools-overlay = Tools Overlay
actions-top-bar = Top Bar
actions-unbury-deck = Unbury Deck
actions-unbury-deck-short = UBury
actions-undo = Undo
actions-unmarked = Unmarked
actions-you-can-only-empty-a-filtered = You can only empty a filtered deck.
actions-you-can-only-rebuild-a-filtered = You can only rebuild a filtered deck.
