actions-actions = Actions
actions-add-new = Add New
actions-added-to-frequent-actions = Added to frequent actions.
actions-all-actions = All Actions
actions-already-in-frequent-actions = Already in frequent actions.
actions-an-error-occurred = An error occurred: { $error }
actions-answer-easy = Answer Easy
actions-are-you-sure = Are you sure?
actions-bottom-bar = Bottom Bar
actions-browse = Browse
actions-card-buried = Card buried
actions-card-suspended = Card suspended
actions-card-template = Card Template
actions-confirm-delete = Confirm Delete
actions-create = Create
actions-current-audio-minus-5s = Current Audio -5s
actions-current-audio-plus-5s = Current Audio +5s
actions-custom-study-cant-be-used-on = Custom study can't be used on a filtered deck.
actions-deck-statistics = Deck Statistics
actions-delete-note-and-its-cards = Delete note and its cards?
actions-discard-changes = Discard Changes
actions-done = Done
actions-downloading = Downloading...
actions-drag-here-to-remove = Drag here to remove
actions-draw = Draw
actions-file-invalid-or-corrupt = File invalid or corrupt.
actions-filtercram = Filter/Cram
actions-filtered-deck = Filtered Deck { $num }
actions-frequent-actions = Frequent Actions
actions-leave-without-saving = Leave without saving?
actions-long-press-on-an-item-to = Long press on an item to customize.
actions-mark = Mark
actions-mark-and-bury = Mark + Bury
actions-mark-and-suspend = Mark + Suspend
actions-marked = Marked
actions-no-current-card = No current card.
actions-no-load-restore-backup = Your collection couldn't be loaded. Please restore from an automatic backup via the preferences screen.
# (http://example.com) does not appear to be...
actions-not-valid-link = does not appear to be a valid http/https link.
actions-note-and-its-cards-deleted = Note and its { $count } cards deleted
actions-note-and-its-cards-suspended = Note and its { $count } card(s) suspended
actions-note-buried = Note buried
actions-note-marked-and-buried = Note marked and buried
actions-off = Off
actions-please-tap-the-in-the = Please tap the '?' in the top left to get started.
actions-processing = Processing...
actions-record-voice = Record Voice
actions-record-voice-menu = Record Voice Menu
actions-reset-card = Reset Card
actions-revert = Revert
actions-review-undone = Review undone
actions-scratchpad = Scratchpad
actions-scratchpad-size = Scratchpad Size
actions-select-deck = Select Deck
actions-select-note-type = Select Note Type
actions-show-answeranswer-good = Show Answer/Answer Good
actions-study-options = Study Options
actions-tools = Tools
actions-tools-overlay = Tools Overlay
actions-top-bar = Top Bar
actions-unbury-deck = Unbury Deck
actions-undo = Undo
actions-unmarked = Unmarked
actions-you-can-only-empty-a-filtered = You can only empty a filtered deck.
actions-you-can-only-rebuild-a-filtered = You can only rebuild a filtered deck.
actions-scroll-up = Scroll Up
actions-scroll-down = Scroll Down

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Empty
# create a filtered deck
actions-filter-short = Filter
actions-add-short = Add
actions-answer-again-short = Again
actions-answer-easy-short = Easy
actions-answer-good-short = Good
actions-answer-hard-short = Hard
actions-auto-advance-short = Auto Adv.
actions-bottom-bar-short = Bot.B
actions-browse-short = Browse
actions-bury-card-short = Bury.C
actions-bury-note-short = Bury.N
actions-card-info-short = C.Info
actions-card-template-short = Template
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Custom
actions-deck-statistics-short = D.Stats
actions-decks-short = Decks
actions-delete-note-short = Del
actions-edit-short = Edit
actions-mark-and-bury-short = M&B
actions-mark-and-suspend-short = M&S
actions-mark-short = Mark
actions-night-mode-short = Night
actions-off-short = Off
actions-pause-audio-short = Pause
actions-rebuild-short = Rebuild
actions-record-voice-short = Rec.V
actions-replay-voice-short = Repl.V
actions-replay-audio-short = Replay
actions-reset-card-short = Reset.C
actions-scratchpad-short = Pad
actions-scratchpad-size-short = Pad.S
actions-set-due-date-short = S.Date
actions-show-answer-short = S.Ans
actions-show-answeranswer-good-short = Show/Ans
actions-study-options-short = S.Opt
actions-suspend-card-short = Sus.C
actions-suspend-note-short = Sus.N
actions-tools-short = Tools
actions-top-bar-short = T.Bar
actions-unbury-deck-short = UBury
actions-undo-short = Undo
actions-redo-short = Redo
actions-scroll-up-short = Up
actions-scroll-down-short = Down
