decks-a-deck-must-be-provided = A deck must be provided.
decks-a-deck-named-already-exists = A deck named '{ $name }' already exists.
decks-a-deck-with-that-name-already = A deck with that name already exists.
decks-add-deck = Add Deck
decks-add-empty-deck = Add Empty Deck
decks-addexport = Add/Export
decks-cannot-delete = Cannot Delete
decks-card-limit = Card limit
decks-cards-in-a-filtered-deck-cant = Cards in a filtered deck can't be moved.
decks-custom-steps = Custom Steps
decks-deck-exists = Deck Exists
decks-deck-label = Deck:
decks-deck-name = Deck Name
decks-deck-options = Deck Options
decks-download-link = Download Link
decks-export-collection = Export Collection
decks-filtered-deck = Filtered Deck
decks-import-from-itunes = Import from iTunes
decks-invalid-deck-name = Invalid deck name.
decks-link-to-apkg-file-to-import = Link to .apkg file to import:
decks-no-matches = No Matches
decks-return-by-delete = To return all cards at once, swipe over the blue deck in the deck list, and delete it.
decks-shared-deck-list = Shared Deck List
decks-sync = Sync
decks-synchronize = Synchronize
decks-the-default-deck-cannot-be-deleted = The default deck cannot be deleted.
decks-the-provided-deck-does-not-exist = The provided deck does not exist.
decks-the-search-you-provided-did-not = The search you provided did not match any cards.
decks-will-be-returned = Cards will be returned to their original deck as you answer them.
