deck-options-add-options-group = Add Options Group
deck-options-answer-time-cap = Answer time cap
deck-options-bury-related-new-cards = Bury related new cards
deck-options-bury-related-reviews = Bury related reviews
deck-options-defaults = Defaults
deck-options-delete-options-full-sync = Deleting this options group will prevent any changes from being merged from other devices on the next sync. Proceed?
deck-options-display-in-order-added = Display in order added
deck-options-display-in-random-order = Display in random order
deck-options-full-sync-required = Full Sync Required
deck-options-group-name = Group name
deck-options-max-new-per-day = Max new per day
deck-options-max-reviews-per-day = Max reviews per day
deck-options-new-cards = New cards
deck-options-options-group = Options group
deck-options-replay-q-audio-in-answer = Replay q. audio in answer
deck-options-reset-all-settings-to-defaults = Reset all settings to defaults?
deck-options-restore-defaults = Restore Defaults
deck-options-steps = Steps
