exporting-collection-saved-to-itunes = Collection saved to iTunes.
exporting-export-to-itunes = Export to iTunes
exporting-export-to-share-sheet = Export to Share Sheet
exporting-exporting = Exporting...
exporting-include-media2 = Include Media
exporting-media-files-exported-d = Media files exported: { $count }...
