preferences-about = About
preferences-always-duck-and-ignore-mute = Always Duck + Ignore Mute
preferences-answer-keeps-zoom = Answer Keeps Zoom
preferences-answer-side = Answer Side
preferences-audio-buttons = Audio Buttons
preferences-auto-advance-answer-action = Answer Action
preferences-auto-advance-answer-seconds = Answer Seconds
preferences-auto-advance-auto-advance-to-start = To start automatically advancing, use the 'Auto Advance' action.
preferences-auto-advance-do-nothing = Do Nothing
preferences-auto-advance-question-seconds = Question Seconds
preferences-auto-advance-show-reminder = Show Reminder
preferences-auto-advance-wait-for-audio = Wait for Audio
preferences-backup-available-backups = Available backups
preferences-backup-create-now = Create Now
preferences-backup-maximum-backups = Maximum Backups
preferences-backup-minutes-between-backups = Minutes Between Backups
preferences-backup-revert-to-backup = Revert to Backup
preferences-backup-revert-to-backup-confirm = Revert to { $backup }? Any changes made since the backup will be lost.
preferences-backup-reverted-to-backup = Reverted to backup.
preferences-bottom-bar-size = Bottom Bar Size
preferences-bottom-center = Bottom Center
preferences-bottom-left = Bottom Left
preferences-bottom-right = Bottom Right
preferences-button-d = Button { $num }
preferences-collection-day-starts = Day Starts
preferences-collection-learn-ahead-minutes = Learn Ahead Minutes
preferences-collection-mix = Mix
preferences-collection-new-first = New first
preferences-collection-newreview-order = New/Review Order
preferences-collection-reviews-first = Reviews first
preferences-double-tap-prevention = Double Tap Prevention
preferences-drawing-screen-ignores-fingers = Drawing Screen Ignores Fingers
preferences-feedback-ticks = Feedback Ticks
preferences-fine = Fine
preferences-force-sync-confirm = Force a one way sync? All changes on one side will be lost.
preferences-full-sync = Full Sync
preferences-gamepad-button-mapping = Button Mapping
preferences-gamepad-menu-button = Menu
preferences-gamepads = Gamepads
preferences-height = Height
preferences-huge = Huge
preferences-ignore-fingers = Ignore Fingers
preferences-interrupt-current-audio = Interrupt Current Audio
preferences-large = Large
preferences-left = Left
# gamepad
preferences-left-shoulder = Left Shoulder
# gamepad
preferences-left-thumbstick-button = Left Thumbstick Button
# gamepad
preferences-left-trigger = Left Trigger
preferences-logged-in-as = Logged in as:
preferences-long = Long
preferences-mid-center = Mid Center
preferences-mid-left = Mid Left
preferences-mid-right = Mid Right
preferences-never-type-answer = Never Type Answer
preferences-never-show-scratchpad = Never Show Scratchpad
preferences-never-show-scratchpad-enabled = Never Show Scratchpad is enabled in the Preferences screen.
preferences-next-times = Next Times
preferences-normal = Normal
preferences-notifications = Notifications
preferences-notifications-alert-time = Alert Time
preferences-notifications-alert-when-due = Alert When Due
preferences-notifications-app-icon-shows-due-count = App Icon Shows Due Count
preferences-notifications-settings-app-enable-notifications = Please go the iOS Settings app, locate the Anki section, and enable notifications, badges and alerts.
preferences-pen-size = Pen Size
preferences-question-side = Question Side
preferences-remaining-count = Remaining Count
preferences-right = Right
# gamepad
preferences-right-shoulder = Right Shoulder
# gamepad
preferences-right-thumbstick-button = Right Thumbstick Button
# gamepad
preferences-right-trigger = Right Trigger
preferences-scratchpad-below-buttons = Scratchpad Below Buttons
preferences-scratchpad-transparency = Scratchpad Transparency
preferences-scratchpad-transparency-full = Full
preferences-scratchpad-transparency-medium = Medium
preferences-scratchpad-transparency-none = None
preferences-scratchpad-transparency-slight = Slight
preferences-shake-action = Shake Action
preferences-short = Short
preferences-show-bottom-bar = Show Bottom Bar
preferences-show-grid = Show Grid
preferences-show-top-bar = Show Top Bar
preferences-small = Small
preferences-swipe-down = Swipe Down
preferences-swipe-left = Swipe Left
preferences-swipe-right = Swipe Right
preferences-swipe-up = Swipe Up
preferences-swipes = Swipes
preferences-swipes-must-begin-from-the-far = Swipes must begin from the far left or right of the screen.
preferences-sync-sounds-images = Sync Sounds & Images
preferences-syncing = Syncing
preferences-tap-to-sync = To activate syncing, tap the synchronize button on the deck list screen.
preferences-taps = Taps
preferences-theme = Theme
preferences-theme-bar-style = Bar Style
preferences-theme-black = Black
preferences-theme-dark = Dark
preferences-theme-dark-translucent = Dark & Translucent
preferences-theme-force-off = Force Off
preferences-theme-force-on = Force On
preferences-theme-light-translucent = Light & Translucent
preferences-theme-night-mode-desc = Night mode darkens the interface, and displays cards as white on black.
preferences-theme-night-mode-same-as-system = Follow System
preferences-theme-slate = Slate
preferences-thick = Thick
preferences-tools-overlay-button = Tools Overlay Button
preferences-tools-overlay-position = Tools Overlay Position
preferences-top-center = Top Center
preferences-top-left = Top Left
preferences-top-right = Top Right
preferences-undo-clears-all = Undo Clears All
preferences-when-answer-shown = When answer shown
preferences-when-question-shown = When question shown
preferences-you-have-been-logged-out = You have been logged out.

preferences-editing = Editing
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Max Image Size (Long Edge)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Resize When Pasting
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Convert Smart Quotes & Dashes
preferences-editing-crop-camera-photos = Crop Camera Photos
