actions-actions = مەشغۇلات
actions-add-new = يېڭىدىن قوش
actions-added-to-frequent-actions = كۆپ ئىشلىتىدىغان مەشغۇلاتقا قوشۇلدى.
actions-all-actions = بارلىق مەشغۇلات
actions-already-in-frequent-actions = كۆپ ئىشلىتىدىغان مەشغۇلات قاتارىدا بار.
actions-an-error-occurred = خاتالىق كۆرۈلدى: { $error }
actions-answer-easy = جاۋابى «ئاسان»
actions-are-you-sure = راستمۇ؟
actions-bottom-bar = ئاستى بالداق
actions-browse = كۆز يۈگۈرت
actions-card-buried = كارتا يوشۇرۇلدى
actions-card-suspended = كارتا كېچىكتۈرۈلدى
actions-card-template = كارتا قېلىپى
actions-confirm-delete = ئۆچۈرۈشنى جەزملە
actions-create = قۇر
actions-current-audio-minus-5s = نۆۋەتتىكى ئۈن 5- سېكۇنت
actions-current-audio-plus-5s = نۆۋەتتىكى ئۈن 5+ سېكۇنت
actions-custom-study-cant-be-used-on = سۈزۈلگەن دەستەگە ئىختىيارى ئۆگىنىش قىلغىلى بولمايدۇ.
actions-deck-statistics = دەستە ئىستاتىستىكىسى
actions-delete-note-and-its-cards = خاتىرە ۋە ئۇنىڭ كارتىسىنى ئۆچۈرەمدۇ؟
actions-discard-changes = ئۆزگىرىشنى تاشلىۋەت
actions-done = تامام
actions-downloading = چۈشۈرۈۋاتىدۇ…
actions-drag-here-to-remove = بۇ جايغا سۆرەلسە چىقىرىۋېتىدۇ
actions-draw = سىز
actions-file-invalid-or-corrupt = ھۆججەت ئىناۋەتسىز ياكى بۇزۇلغان.
actions-filtercram = سۈزگۈچ/ئىمتىھان تەييارلىق
actions-filtered-deck = سۈزۈلگەن دەستە { $num }
actions-frequent-actions = كۆپ ئىشلىتىدىغان مەشغۇلات
actions-leave-without-saving = ساقلىماي ئايرىلامدۇ؟
actions-long-press-on-an-item-to = خاسلاشتۇرۇشتا تۈر ئۇزۇن بېسىلىدۇ.
actions-mark = بەلگە
actions-mark-and-bury = بەلگە+يوشۇر
actions-mark-and-suspend = بەلگە+كېچىكتۈر
actions-marked = بەلگە سېلىندى
actions-no-current-card = نۆۋەتتە كارتا يوق.
actions-no-load-restore-backup = توپلىمىڭىزنى يۈكلىيەلمەيدۇ. تەڭشەك › زاپاستىن سانلىق مەلۇماتنى ئەسلىگە كەلتۈرۈڭ.
# (http://example.com) does not appear to be...
actions-not-valid-link = ئىناۋەتلىك http/https ئۇلانمىسى ئەمەستەك قىلىدۇ.
actions-note-and-its-cards-deleted = خاتىرە ۋە ئۇنىڭ { $count } كارتىسى ئۆچۈرۈلدى
actions-note-and-its-cards-suspended = خاتىرە ۋە ئۇنىڭ { $count } كارتىسى كېچىكتۈرۈلدى
actions-note-buried = خاتىرە يوشۇرۇلدى
actions-note-marked-and-buried = خاتىرىگە بەلگە سېلىنىپ يوشۇرۇلدى
actions-off = تاقاق
actions-please-tap-the-in-the = سول چوققىدىكى «?» نى چېكىپ باشلاڭ.
actions-processing = بىر تەرەپ قىلىۋاتىدۇ…
actions-record-voice = ئۈنگە ئال
actions-record-voice-menu = ئۈنگە ئېلىش تىزىملىكى
actions-reset-card = كارتىنى ئەسلىگە قايتۇر
actions-revert = ئەسلىگە كەلتۈر
actions-review-undone = تەكرارلاشتىن يېنىۋالدى
actions-scratchpad = تېز خاتىرە دەپتەر
actions-scratchpad-size = تېز خاتىرە دەپتەر چوڭلۇقى
actions-select-deck = دەستە تاللا
actions-select-note-type = خاتىرە تۈرى تاللا
actions-show-answeranswer-good = جاۋاب كۆرسەت/جاۋابى ياخشى
actions-study-options = ئۆگىنىش تاللانمىسى
actions-tools = قورال
actions-tools-overlay = قورال قاپلاش
actions-top-bar = چوققا بالداق
actions-unbury-deck = دەستە يوشۇرما
actions-undo = يېنىۋال
actions-unmarked = بەلگە سالما
actions-you-can-only-empty-a-filtered = پەقەت سۈزگۈچ دەستىنى بوشىتالايسىز.
actions-you-can-only-rebuild-a-filtered = پەقەت سۈزۈلگەن دەستىنى قايتا قۇرالايسىز.
actions-scroll-up = ئۈستىگە دومىلات
actions-scroll-down = ئاستىغا دومىلات

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = بوش
# create a filtered deck
actions-filter-short = سۈزگۈچ
actions-add-short = قوش
actions-answer-again-short = تەكرار
actions-answer-easy-short = ئاسان
actions-answer-good-short = ياخشى
actions-answer-hard-short = تەس
actions-auto-advance-short = ئۆزلۈكىدىن كۆرسەت
actions-bottom-bar-short = ئاستى بالداق
actions-browse-short = كۆز يۈگۈرت
actions-bury-card-short = كارتا يوشۇر
actions-bury-note-short = خاتىرە يوشۇر
actions-card-info-short = كارتا ئۇچۇرى
actions-card-template-short = قېلىپ
actions-current-audio-minus-5s-short = -5سېكۇنت
actions-current-audio-plus-5s-short = +5سېكۇنت
actions-custom-study-short = ئىختىيارى
actions-deck-statistics-short = دەستە ئىستاتىستىكا
actions-decks-short = دەستە
actions-delete-note-short = ئۆچۈر
actions-edit-short = تەھرىر
actions-mark-and-bury-short = بەلگە سېلىپ يوشۇر
actions-mark-and-suspend-short = بەلگە سېلىپ كېچىكتۈر
actions-mark-short = بەلگە
actions-night-mode-short = كېچە
actions-off-short = تاقاق
actions-pause-audio-short = ۋاقىتلىق توختات
actions-rebuild-short = قايتا قۇر
actions-record-voice-short = ئۈنگە ئال
actions-replay-voice-short = قايتا قوي
actions-replay-audio-short = قايتا قوي
actions-reset-card-short = كارتىنى ئەسلىگە قايتۇر
actions-scratchpad-short = تېز خاتىرە دەپتەر
actions-scratchpad-size-short = تېز خاتىرە دەپتەر چوڭلۇقى
actions-set-due-date-short = مۆھلەت تەڭشەك
actions-show-answer-short = جاۋاب
actions-show-answeranswer-good-short = كۆرسەت/جاۋاب
actions-study-options-short = تاللانما
actions-suspend-card-short = كارتا كېچىكتۈر
actions-suspend-note-short = خاتىرە كېچىكتۈر
actions-tools-short = قورال
actions-top-bar-short = قورال بالداق
actions-unbury-deck-short = يوشۇرما
actions-undo-short = يېنىۋال
actions-redo-short = قايتىلا
actions-scroll-up-short = ئۈستى
actions-scroll-down-short = ئاستى
actions-back = قايت
