decks-a-deck-must-be-provided = كەم دېگەندە بىر دەستە تەمىنلىنىدۇ.
decks-a-deck-named-already-exists = «{ $name }» ئاتلىق دەستە مەۋجۇت.
decks-a-deck-with-that-name-already = ئۇ ئاتتىكى دەستە مەۋجۇت.
decks-add-deck = دەستە قوش
decks-add-empty-deck = بوش دەستە قوش
decks-addexport = قوش/چىقار
decks-cannot-delete = ئۆچۈرەلمەيدۇ
decks-card-limit = كارتا چېكى
decks-cards-in-a-filtered-deck-cant = سۈزۈلگەن دەستەدىكى كارتىنى يۆتكىگىلى بولمايدۇ.
decks-custom-steps = ئىختىيارى باسقۇچ
decks-deck-exists = دەستە مەۋجۇت
decks-deck-label = دەستە:
decks-deck-name = دەستە ئاتى
decks-deck-options = دەستە تاللانما
decks-download-link = چۈشۈرۈش ئۇلانمىسى
decks-export-collection = توپلامنى چىقار
decks-filtered-deck = سۈزۈلگەن دەستە
decks-import-from-itunes = iTunes دىن ئەكىر
decks-invalid-deck-name = ئىناۋەتسىز دەستە ئاتى.
decks-link-to-apkg-file-to-import = ئەكىرىشتە .apkg ھۆججەتكە ئۇلايدۇ:
decks-no-matches = ماس كېلىدىغىنى يوق
decks-return-by-delete = بىرلا ۋاقىتتا ھەممە كارتىنى ئەسلىگە قايتۇرىدۇ، دەستە تىزىمىدا كۆك دەستە ئۈستىدە سۈرۈلسە ئۆچۈرىدۇ.
decks-shared-deck-list = ھەمبەھىر دەستە تىزىمى
decks-sync = قەدەمداش
decks-synchronize = قەدەمداش توپلىمى
decks-the-default-deck-cannot-be-deleted = كۆڭۈلدىكى دەستەنى ئۆچۈرگىلى بولمايدۇ.
decks-the-provided-deck-does-not-exist = تەمىنلەنگەن دەستە مەۋجۇت ئەمەس.
