deck-options-add-options-group = تاللانما گۇرۇپپىسى قوش
deck-options-answer-time-cap = جاۋاب ۋاقىت چېكى
deck-options-bury-related-new-cards = مۇناسىۋەتلىك يېڭى كارتىنى يوشۇرىدۇ
deck-options-bury-related-reviews = مۇناسىۋەتلىك تەكرارلىغان كارتىنى يوشۇرىدۇ
deck-options-defaults = كۆڭۈلدىكى
deck-options-delete-options-full-sync = بۇ تاللانما گۇرۇپپىسى ئۆچۈرۈلسە كېيىنكى قېتىم قەدەمداشلىغاندا باشقا ئۈسكۈنە بىلەن ئۆزگىرىشنى بىرلەشتۈرگىلى بولمايدۇ. داۋاملاشتۇرسۇنمۇ؟
deck-options-display-in-order-added = كارتا قوشۇلغان تەرتىپتە كۆرسىتىدۇ
deck-options-display-in-random-order = خالىغان تەرتىپتە كۆرسىتىدۇ
deck-options-full-sync-required = تولۇق قەدەمداشلاش زۆرۈر
deck-options-group-name = گۇرۇپپا ئاتى
deck-options-max-new-per-day = كۈندىلىك يېڭى كارتا يۇقىرى چېكى
deck-options-max-reviews-per-day = كۈندىلىك تەكرارلاشنىڭ يۇقىرى چېكى
deck-options-new-cards = يېڭى كارتا
deck-options-options-group = تاللانما گۇرۇپپا
deck-options-replay-q-audio-in-answer = جاۋابىنى كۆرسەتكەندە ئاۋازىنى قويىدۇ
deck-options-reset-all-settings-to-defaults = ھەممە تەڭشەكنى كۆڭۈلدىكى قىممەتكە قايتۇرامدۇ؟
deck-options-restore-defaults = كۆڭۈلدىكىگە قايتۇر
deck-options-steps = باسقۇچ
