exporting-collection-saved-to-itunes = توپلام iTunes قا ساقلاندى.
exporting-export-to-itunes = iTunes قا چىقار
exporting-export-to-share-sheet = ھەمبەھىر ۋاراققا چىقار…
exporting-exporting = چىقىرىۋاتىدۇ…
exporting-include-media2 = ۋاسىتە ئىچىدە
exporting-media-files-exported-d = چىقىرىلغان ۋاسىتە ھۆججىتى:
