preferences-about = ھەققىدە
preferences-autoplay-in-silent-mode = ئۈنسىز ھالەتتە ئۆزلۈكىدىن قويىدۇ
preferences-always-duck = ھەمىشە تەگلىك ئاۋازىنى ئۈنسىزلەيدۇ
preferences-answer-keeps-zoom = جاۋابنىڭ چوڭلۇق نىسبىتىنى ساقلايدۇ
preferences-answer-side = جاۋاب تەرەپ
preferences-audio-buttons = ئۈن توپچە
preferences-auto-advance-answer-action = جاۋاب مەشغۇلاتى
preferences-auto-advance-answer-seconds = جاۋاب كۆرسىتىش سېكۇنت
preferences-auto-advance-auto-advance-to-start = جاۋابنى ئۆزلۈكىدىن كۆرسەتكەندە، جاۋاب بېرىپ كېيىنكى كارتىنى كۆرسىتىشتە «ئۆزلۈكىدىن كۆرسەت» مەشغۇلاتىنى ئىشلىتىش كېرەك.
preferences-auto-advance-do-nothing = مەشغۇلات قىلما
preferences-auto-advance-question-seconds = سوئال كۆرسىتىش سېكۇنت
preferences-backup-available-backups = باز زاپاس
preferences-backup-create-now = ھازىر قۇر
preferences-backup-maximum-backups = ئەڭ كۆپ زاپاس سانى
preferences-backup-minutes-between-backups = زاپاسلاش چاستوتىسى مىنۇت
preferences-backup-revert-to-backup = زاپاسنى ئەسلىگە كەلتۈر
preferences-backup-revert-to-backup-confirm = { $backup } غا ئەسلىگە كەلتۈرەمدۇ؟ مەزكۇر زاپاستىن كېيىنكى ئۆزگەرتىشلەرنىڭ ھەممىسى يوقىلىدۇ.
preferences-backup-reverted-to-backup = زاپاس ئەسلىگە كەلتۈرۈلدى.
preferences-bottom-bar-size = ئاستى بالداق چوڭلۇقى
preferences-bottom-center = ئاستى ئوتتۇرا
preferences-bottom-left = سول ئاستى
preferences-bottom-right = ئوڭ ئاستى
preferences-button-d = ئاستى { $num }
preferences-collection-day-starts = باشلاش ۋاقتى
preferences-collection-learn-ahead-minutes = ئالدىن ئۆگىنىش مىنۇت
preferences-collection-mix = ئارىلاش
preferences-collection-new-first = ئاۋۋال يېڭىسى
preferences-collection-newreview-order = يېڭى/تەكرارلاش كارتا تەرتىپى
preferences-collection-reviews-first = ئاۋۋال تەكرارلاش
preferences-double-tap-prevention = قوش چېكىشتىن مۇداپىئە
preferences-open-links-externally = ئۇلانمىنى سىرتتا ئاچىدۇ
preferences-drawing-screen-ignores-fingers = ئېكران سىزىپ بارماققا پەرۋا قىلمايدۇ
preferences-feedback-ticks = توغرا خاتا بەلگىسىنى كۆرسىتىدۇ
preferences-spread-ticks = جاۋاب تارقاق كۆرسىتىلىدۇ
preferences-fine = ئىنچىكە
preferences-force-sync-confirm = مەجبۇرىي يەككە يۆنىلىشتە قەدەمداشلامدۇ؟ بىر تەرەپتىكى ھەممە ئۆزگەرتىش قاپلىۋېتىلىدۇ.
preferences-full-sync = يەككە يۆنىلىش قەدەمداش
preferences-gamepad-button-mapping = توپچە تەسۋىرى
preferences-gamepad-menu-button = تىزىملىك
preferences-gamepads = ئويۇن تۇتقۇچى
preferences-gamepad-thumbpad-deadzone = باش بارماق يەتمەس رايون نىسبىتى %
preferences-height = ئېگىزلىكى
preferences-huge = زور
preferences-ignore-fingers = بارماققا پەرۋا قىلما
preferences-interrupt-current-audio = نۆۋەتتىكى ئۈننى ئۈز
preferences-large = چوڭ
preferences-left = سول
# gamepad
preferences-left-shoulder = سول مۈرە
# gamepad
preferences-left-thumbstick-button = سول باش بارماق توپچە
# gamepad
preferences-left-trigger = سول قوزغاتقۇچ
preferences-logged-in-as = تىزىمغا كىرگىنى:
preferences-long = ئۇزۇن
preferences-mid-center = دەل ئوتتۇرا
preferences-mid-left = سول ئوتتۇرا
preferences-mid-right = ئوڭ ئوتتۇرا
preferences-never-type-answer = ھەرگىز جاۋاب يېزىلماس
preferences-never-show-scratchpad = ھەرگىز تېز خاتىرە دەپتەر كۆرسەتمە
preferences-never-show-scratchpad-enabled = «ھەرگىز تېز خاتىرە دەپتەر كۆرسەتمە» مايىللىق ئېكرانىدا قوزغىتىلدى.
preferences-next-times = كېيىنكى جاۋاب ۋاقىت
preferences-normal = ئادەتتىكى
preferences-notifications = ئۇقتۇرۇش
preferences-notifications-alert-time = ئەسكەرتىش ۋاقتى
preferences-notifications-alert-when-due = مۆھلەت توشقاندا ئەسكەرت
preferences-notifications-app-icon-shows-due-count = ئەپ سىنبەلگىسىدە مۆھلىتى توشقان كارتا سانىنى كۆرسىتىدۇ
preferences-notifications-settings-app-enable-notifications = iOS نىڭ تەڭشىكىگە يۆتكىلىپ، Anki نى تېپىپ، ئۇقتۇرۇش، تارتۇق ۋە ئەسكەرتىشنى قوزغىتىڭ.
preferences-pen-size = قەلەم توملۇقى
preferences-question-side = سوئال تەرەپ
preferences-remaining-count = قالغان كارتا سانى
preferences-right = ئوڭ
# gamepad
preferences-right-shoulder = ئوڭ مۈرە
# gamepad
preferences-right-thumbstick-button = ئوڭ باش بارماق توپچە
# gamepad
preferences-right-trigger = ئوڭ قوزغاتقۇچ
preferences-scratchpad-below-buttons = تېز خاتىرە دەپتەر ئاستى توپچە
preferences-scratchpad-transparency = تېز خاتىرە دەپتەر سۈزۈكلۈكى
preferences-scratchpad-transparency-full = تولۇق
preferences-scratchpad-transparency-medium = ئوتتۇرا
preferences-scratchpad-transparency-none = يوق
preferences-scratchpad-transparency-slight = سەل
preferences-shake-action = قول ئېلىش مەشغۇلاتى
preferences-short = قىسقا
preferences-show-bottom-bar = ئاستى بالداقنى كۆرسەت
preferences-show-grid = تورنى كۆرسەت
preferences-show-top-bar = چوققا بالداقنى كۆرسەت
preferences-small = كىچىك
preferences-swipe-down = ئاستىغا سۈر
preferences-swipe-left = سولغا سۈر
preferences-swipe-right = ئوڭغا سۈر
preferences-swipe-up = ئۈستىگە سۈر
preferences-swipes = سۈرۈش قول ئىشارىتى
preferences-swipes-must-begin-from-the-far = چوقۇم ئېكرانىڭ ئەڭ سول ياكى ئەڭ ئوڭ تەرىپىدىن سۈرۈشنى باشلاڭ.
preferences-sync-sounds-images = ئۈن ۋە سۈرەتنى قەدەمداشلا
preferences-syncing = قەدەمداشلاۋاتىدۇ
preferences-tap-to-sync = قەدەمداشلاشنى ئاكتىپلاشتا، دەستە تىزىم ئېكرانىدا قەدەمداش توپچە چېكىلىدۇ.
preferences-taps = قول ئىشارىتى: چەك
preferences-theme-bar-style = بالداق ئۇسلۇبى
preferences-theme-black = قارا
preferences-theme-dark-translucent = قاراڭغۇ يېرىم سۈزۈك
preferences-theme-force-off = مەجبۇرىي تاقا
preferences-theme-force-on = مەجبۇرىي ئاچ
preferences-theme-light-translucent = يورۇق يېرىم سۈزۈك
preferences-theme-night-mode-desc = قاراڭغۇ ھالەتتە ئارايۈز قاراڭغۇلىشىدۇ، كارتا تەگلىكى قارا خېتى ئاق كۆرۈنىدۇ.
preferences-theme-night-mode-same-as-system = سىستېمىغا ئەگەش
preferences-theme-slate = توق كۈلرەڭ
preferences-thick = قېلىن
preferences-tools-overlay-button = قورال قاپلاش توپچە
preferences-tools-overlay-position = قورال قاپلاش ئورنى
preferences-top-center = چوققا ئوتتۇرا
preferences-top-left = سول چوققا
preferences-top-right = ئوڭ چوققا
preferences-undo-clears-all = يېنىۋال ھەممىنى تازىلا
preferences-when-answer-shown = جاۋابنى كۆرسەتكەندە
preferences-when-question-shown = سوئالنى كۆرسەتكەندە
preferences-you-have-been-logged-out = تىزىمدىن چىقتىڭىز.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = ئەڭ چوڭ سۈرەت چوڭلۇقى (ئۇزۇن تەرەپ)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = چاپلىغاندا سۈرەت چوڭلۇقىنى تەڭشە
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = تىرناق ۋە سىزىقنى ئۆزلۈكىدىن ئالماشتۇر
preferences-editing-crop-camera-photos = كامېرا سۈرىتىنى قايچىلا
preferences-loop-video = سىننى تەكرارلا
preferences-show-video-controls = سىن كونترولىنى كۆرسەت
preferences-high-quality-video = يۇقىرى سۈپەتلىك سىن
preferences-auto-capitalize = جۈملە بېشىدىكى ھەرپنى چوڭ ھەرپكە ئۆزلۈكىدىن ئالماشتۇرىدۇ
preferences-auto-correct = ئۆزلۈكىدىن تۈزەت
preferences-strip-hebrew-vowels = ئىبرانىيچە سوزۇق تاۋۇشنى چىقىرىۋەت
