preferences-about = ھەققىدە
preferences-autoplay-in-silent-mode = ئۈنسىز ھالەتتە ئۆزلۈكىدىن قويىدۇ
preferences-always-duck = ھەمىشە تەگلىك ئاۋازىنى ئۈنسىزلەيدۇ
preferences-answer-keeps-zoom = جاۋابنىڭ چوڭلۇق نىسبىتىنى ساقلايدۇ
preferences-answer-side = جاۋاب تەرەپ
preferences-audio-buttons = ئۈن توپچە
preferences-auto-advance-answer-action = جاۋاب مەشغۇلاتى
preferences-auto-advance-answer-seconds = جاۋاب كۆرسىتىش سېكۇنت
preferences-auto-advance-auto-advance-to-start = جاۋابنى ئۆزلۈكىدىن كۆرسەتكەندە، جاۋاب بېرىپ كېيىنكى كارتىنى كۆرسىتىشتە «ئۆزلۈكىدىن كۆرسەت» مەشغۇلاتىنى ئىشلىتىش كېرەك.
preferences-auto-advance-do-nothing = مەشغۇلات قىلما
preferences-auto-advance-question-seconds = سوئال كۆرسىتىش سېكۇنت
preferences-backup-available-backups = باز زاپاس
preferences-backup-create-now = ھازىر قۇر
preferences-backup-maximum-backups = ئەڭ كۆپ زاپاس سانى
preferences-backup-minutes-between-backups = زاپاسلاش چاستوتىسى مىنۇت
preferences-backup-revert-to-backup = زاپاسنى ئەسلىگە كەلتۈر
preferences-backup-revert-to-backup-confirm = { $backup } غا ئەسلىگە كەلتۈرەمدۇ؟ مەزكۇر زاپاستىن كېيىنكى ئۆزگەرتىشلەرنىڭ ھەممىسى يوقىلىدۇ.
preferences-backup-reverted-to-backup = زاپاس ئەسلىگە كەلتۈرۈلدى.
preferences-bottom-bar-size = ئاستى بالداق چوڭلۇقى
preferences-bottom-center = ئاستى ئوتتۇرا
preferences-bottom-left = سول ئاستى
preferences-bottom-right = ئوڭ ئاستى
preferences-button-d = ئاستى { $num }
preferences-collection-day-starts = باشلاش ۋاقتى
preferences-collection-learn-ahead-minutes = ئالدىن ئۆگىنىش مىنۇت
preferences-collection-mix = ئارىلاش
preferences-collection-new-first = ئاۋۋال يېڭىسى
preferences-collection-newreview-order = يېڭى/تەكرارلاش كارتا تەرتىپى
preferences-collection-reviews-first = ئاۋۋال تەكرارلاش
