decks-a-deck-must-be-provided = En kortlek måste anges.
decks-a-deck-named-already-exists = Det finns redan en kortlek med namnet '{ $name }'.
decks-a-deck-with-that-name-already = Det finns redan en kortlek med det namnet.
decks-add-deck = Lägg till kortlek
decks-add-empty-deck = Lägg till tom kortlek
decks-addexport = Lägg till/Exportera
decks-cannot-delete = Kan inte ta bort
decks-card-limit = Max antal kort
decks-cards-in-a-filtered-deck-cant = Kort i en filtrerad kortlek går inte att flytta.
decks-custom-steps = Egna steg
decks-deck-exists = Kortleken finns redan
decks-deck-label = Kortlek:
decks-deck-name = Namn på kortlek
decks-deck-options = Kortleksalternativ
decks-download-link = Nedladdningslänk
decks-export-collection = Exportera samlingen
decks-filtered-deck = Filtrerad kortlek
decks-import-from-itunes = Importera från iTunes
decks-invalid-deck-name = Ogiltigt kortleksnamn.
decks-link-to-apkg-file-to-import = Länk till .apkg-fil för import:
decks-no-matches = Inga träffar
decks-return-by-delete = För att återställa alla kort på en gång, svep över den blå kortleken i kortlekslistan och ta bort den.
decks-shared-deck-list = Delad kortlekslista
decks-sync = Synkronisera
decks-synchronize = Synkronisera
decks-the-default-deck-cannot-be-deleted = Standardkortleken kan inte tas bort.
decks-the-provided-deck-does-not-exist = Den angivna kortleken finns inte.
decks-the-search-you-provided-did-not = Sökningen du angav matchade inga kort.
decks-will-be-returned = Kort kommer att återföras till sin ursprungliga kortlek när du svarar på dem.
