deck-options-add-options-group = Lägg till Alternativgrupp
deck-options-answer-time-cap = Tidsgräns för svar
deck-options-bury-related-new-cards = Begräv relaterade nya kort
deck-options-bury-related-reviews = Begräv relaterade repetitioner
deck-options-defaults = Standardinställningar
deck-options-delete-options-full-sync = Om du tar bort den här alternativgruppen kommer inga ändringar från andra enheter att kunna slås samman vid nästa synk. Vill du fortsätta?
deck-options-display-in-order-added = Visa i tillagd ordning
deck-options-display-in-random-order = Visa i slumpordning
deck-options-full-sync-required = Full synkronisering krävs
deck-options-group-name = Namn på gruppen
deck-options-max-new-per-day = Max nya per dag
deck-options-max-reviews-per-day = Max antal repetitioner per dag
deck-options-new-cards = Nya kort
deck-options-options-group = Alternativgrupp
deck-options-replay-q-audio-in-answer = Spela upp fråga och svar i ljud
deck-options-reset-all-settings-to-defaults = Återställ alla inställningar till standard?
deck-options-restore-defaults = Återställ till standardvärden
deck-options-steps = Steg
