decks-a-deck-must-be-provided = En kortlek måste anges.
decks-a-deck-named-already-exists = Det finns redan en kortlek med namnet '{ $name }'.
decks-add-deck = Lägg till kortlek
decks-deck-label = Kortlek:
decks-deck-name = Kortlek namn
decks-deck-options = Kortleksalternativ
decks-export-collection = Exportera samlingen
decks-import-from-itunes = Importera från iTunes
decks-sync = Synkronisera
decks-synchronize = Synkronisera
