decks-a-deck-must-be-provided = Карталар топтому көрсөтүлүшү керек.
decks-a-deck-named-already-exists = '{ $name }' аттуу карталар топтому мурунтан эле бар.
decks-a-deck-with-that-name-already = Мындай аталыштагы карталар топтому мурунтан эле бар.
decks-add-deck = Топтом кошуу
decks-add-empty-deck = Бош топтом кошуу
decks-addexport = Кошуу/Экспорттоо
decks-cannot-delete = Өчүрүү мүмкүн эмес
decks-card-limit = Карталардын лимити
decks-cards-in-a-filtered-deck-cant = Фильтрленген топтомдогу карталарды жылдырууга болбойт.
decks-custom-steps = Жекече кадамдар
decks-deck-exists = Топтом мурунтан эле бар
decks-deck-label = Топтом:
decks-deck-name = Топтомдун аталышы
decks-deck-options = Топтомдун жөндөөлөрү
decks-download-link = Жүктөө шилтемеси
decks-export-collection = Коллекцияны экспорттоо
decks-filtered-deck = Фильтрленген топтом
decks-import-from-itunes = iTunes'тан импорттоо
decks-invalid-deck-name = Топтомдун аталышы жараксыз.
decks-link-to-apkg-file-to-import = Импорттоо үчүн .apkg файлына шилтеме:
decks-no-matches = Дал келүүлөр жок
decks-return-by-delete = Бардык карталарды дароо кайтаруу үчүн, топтомдордун тизмесиндеги көк топтомдун үстүнөн сыдырып, аны өчүрүңүз.
decks-shared-deck-list = Бөлүшүлгөн топтомдордун тизмеси
decks-sync = Шайкештештирүү
decks-synchronize = Шайкештештирүү
decks-the-default-deck-cannot-be-deleted = Баштапкы топтомду өчүрүүгө болбойт.
decks-the-provided-deck-does-not-exist = Көрсөтүлгөн топтом жок.
decks-the-search-you-provided-did-not = Сиздин издөөңүз эч бир картага дал келген жок.
decks-will-be-returned = Сиз жооп берген сайын карталар өздөрүнүн баштапкы топтомуна кайтарылат.
