deck-options-add-options-group = Жөндөөлөр тобун кошуу
deck-options-answer-time-cap = Жооп берүү убактысынын чеги
deck-options-bury-related-new-cards = Байланышкан жаңы карталарды көмүү
deck-options-bury-related-reviews = Байланышкан кайталоолорду көмүү
deck-options-defaults = Демейкилер
deck-options-delete-options-full-sync = Бул жөндөөлөр тобун өчүрүү кийинки шайкештештирүүдө башка түзмөктөрдөгү өзгөртүүлөрдүн биригишине жол бербейт. Улантасызбы?
deck-options-display-in-order-added = Кошулган ирети менен көрсөтүү
deck-options-display-in-random-order = Кокус тартипте көрсөтүү
deck-options-full-sync-required = Толук шайкештештирүү талап кылынат
deck-options-group-name = Топтун аты
deck-options-max-new-per-day = Күнүнө жаңы карталардын эң көп саны
deck-options-max-reviews-per-day = Күнүмдүк кайталоолордун эң көп саны
deck-options-new-cards = Жаңы карталар
deck-options-options-group = Жөндөөлөр тобу
deck-options-replay-q-audio-in-answer = Суроонун аудиосун жооп учурунда  кайталоо
deck-options-reset-all-settings-to-defaults = Бардык жөндөөлөрдү баштапкы абалына кайтарасызбы?
deck-options-restore-defaults = Баштапкы жөндөөлөрдү калыбына келтирүү
deck-options-steps = Кадамдар
