preferences-about = Тиркеме жөнүндө
preferences-autoplay-in-silent-mode = Үнсүз режимде авто-ойнотуу
preferences-always-duck = Фондогу үндү дайыма басаңдатуу
preferences-answer-keeps-zoom = Жооп масштабын сактайт
preferences-answer-side = Жооп жагы
preferences-audio-buttons = Аудио баскычтары
preferences-auto-advance-answer-action = Жооп берүү аракети
preferences-auto-advance-answer-seconds = Жооп секундасы
preferences-auto-advance-auto-advance-to-start = Автоматтык түрдө өтүүнү баштоо үчүн, 'Авто-өтүү' аракетин колдонуңуз.
preferences-auto-advance-do-nothing = Эч нерсе кылбоо
preferences-auto-advance-question-seconds = Суроо секундасы
preferences-backup-available-backups = Жеткиликтүү камдык көчүрмөлөр
preferences-backup-create-now = Азыр түзүү
preferences-backup-maximum-backups = Камдык көчүрмөлөрдүн эң көп саны
preferences-backup-minutes-between-backups = Камдык көчүрмөлөрдүн ортосундагы мүнөттөр
preferences-backup-revert-to-backup = Камдык көчүрмөгө кайтаруу
preferences-backup-revert-to-backup-confirm = { $backup } көчүрмөсүнө кайтарылсынбы? Андан берки бардык өзгөртүүлөр жоголот.
preferences-backup-reverted-to-backup = Камдык көчүрмөгө кайтарылды.
preferences-bottom-bar-size = Төмөнкү тилкенин өлчөмү
preferences-bottom-center = Төмөнкү борбор
preferences-bottom-left = Төмөнкү сол
preferences-bottom-right = Төмөнкү оң
preferences-button-d = Баскыч { $num }
preferences-collection-day-starts = Күн башталат
preferences-collection-learn-ahead-minutes = Алдын ала үйрөнүү мүнөттөрү
preferences-collection-mix = Аралаштыруу
preferences-collection-new-first = Адегенде жаңылар
preferences-collection-newreview-order = Жаңы/Кайталоо ирети
preferences-collection-reviews-first = Адегенде кайталоолор
preferences-double-tap-prevention = Эки жолу басуудан сактоо
preferences-open-links-externally = Шилтемелерди тыштан ачуу
preferences-drawing-screen-ignores-fingers = Сүрөт тартуу экраны манжаларды этибар албайт
preferences-feedback-ticks = Кайтарым байланыш белгилери
preferences-spread-ticks = Белгилерди жайылтуу
preferences-fine = Ичке
preferences-force-sync-confirm = Бир тараптуу шайкештештирүүгө мажбурлайсызбы? Бир тараптагы бардык өзгөртүүлөр жоголот.
preferences-full-sync = Бир тараптуу шайкештештирүү
preferences-gamepad-button-mapping = Баскычтарды дайындоо
preferences-gamepad-menu-button = Меню
preferences-gamepads = Геймпаддар
preferences-gamepad-thumbpad-deadzone = Джойстиктин сезгич эмес аймагы %
preferences-height = Бийиктиги
preferences-huge = Абдан чоң
preferences-ignore-fingers = Манжаларды этибар албоо
preferences-interrupt-current-audio = Учурдагы аудиолорду үзгүлтүккө учуратуу
preferences-large = Чоң
preferences-left = Сол
# gamepad
preferences-left-shoulder = Сол жак ийин (геймпад)
# gamepad
preferences-left-thumbstick-button = Сол джойстик баскычы
# gamepad
preferences-left-trigger = Сол триггер
