preferences-about = Тиркеме жөнүндө
preferences-autoplay-in-silent-mode = Үнсүз режимде авто-ойнотуу
preferences-always-duck = Фондогу үндү дайыма басаңдатуу
preferences-answer-keeps-zoom = Жооп масштабын сактайт
preferences-answer-side = Жооп жагы
preferences-audio-buttons = Аудио баскычтары
preferences-auto-advance-answer-action = Жооп берүү аракети
preferences-auto-advance-answer-seconds = Жооп секундасы
preferences-auto-advance-auto-advance-to-start = Автоматтык түрдө өтүүнү баштоо үчүн, 'Авто-өтүү' аракетин колдонуңуз.
preferences-auto-advance-do-nothing = Эч нерсе кылбоо
preferences-auto-advance-question-seconds = Суроо секундасы
preferences-backup-available-backups = Жеткиликтүү камдык көчүрмөлөр
preferences-backup-create-now = Азыр түзүү
preferences-backup-maximum-backups = Камдык көчүрмөлөрдүн эң көп саны
preferences-backup-minutes-between-backups = Камдык көчүрмөлөрдүн ортосундагы мүнөттөр
preferences-backup-revert-to-backup = Камдык көчүрмөгө кайтаруу
preferences-backup-revert-to-backup-confirm = { $backup } көчүрмөсүнө кайтарылсынбы? Андан берки бардык өзгөртүүлөр жоголот.
preferences-backup-reverted-to-backup = Камдык көчүрмөгө кайтарылды.
preferences-bottom-bar-size = Төмөнкү тилкенин өлчөмү
preferences-bottom-center = Төмөнкү борбор
preferences-bottom-left = Төмөнкү сол
preferences-bottom-right = Төмөнкү оң
preferences-button-d = Баскыч { $num }
preferences-collection-day-starts = Күн башталат
preferences-collection-learn-ahead-minutes = Алдын ала үйрөнүү мүнөттөрү
preferences-collection-mix = Аралаштыруу
preferences-collection-new-first = Адегенде жаңылар
preferences-collection-newreview-order = Жаңы/Кайталоо ирети
preferences-collection-reviews-first = Адегенде кайталоолор
preferences-double-tap-prevention = Эки жолу басуудан сактоо
preferences-open-links-externally = Шилтемелерди тыштан ачуу
preferences-drawing-screen-ignores-fingers = Сүрөт тартуу экраны манжаларды этибар албайт
preferences-feedback-ticks = Кайтарым байланыш белгилери
preferences-spread-ticks = Белгилерди жайылтуу
preferences-fine = Ичке
preferences-force-sync-confirm = Бир тараптуу шайкештештирүүгө мажбурлайсызбы? Бир тараптагы бардык өзгөртүүлөр жоголот.
preferences-full-sync = Бир тараптуу шайкештештирүү
preferences-gamepad-button-mapping = Баскычтарды дайындоо
preferences-gamepad-menu-button = Меню
preferences-gamepads = Геймпаддар
preferences-gamepad-thumbpad-deadzone = Джойстиктин сезгич эмес аймагы %
preferences-height = Бийиктиги
preferences-huge = Абдан чоң
preferences-ignore-fingers = Манжаларды этибар албоо
preferences-interrupt-current-audio = Учурдагы аудиолорду үзгүлтүккө учуратуу
preferences-large = Чоң
preferences-left = Сол
# gamepad
preferences-left-shoulder = Сол жак ийин (геймпад)
# gamepad
preferences-left-thumbstick-button = Сол джойстик баскычы
# gamepad
preferences-left-trigger = Сол триггер
preferences-logged-in-as = Каттоо эсеби:
preferences-long = Узун
preferences-mid-center = Ортоңку борбор
preferences-mid-left = Ортоңку сол
preferences-mid-right = Ортоңку оң
preferences-never-type-answer = Жоопту эч качан тербөө
preferences-never-show-scratchpad = Чийме тактасын эч качан көрсөтпөө
preferences-never-show-scratchpad-enabled = "Чийме тактасын эч качан көрсөтпөө" жөндөөлөр экранында иштетилген.
preferences-next-times = Кийинки жолу
preferences-normal = Кадимки
preferences-notifications = Билдирмелер
preferences-notifications-alert-time = Эскертүү убактысы
preferences-notifications-alert-when-due = Мөөнөтү келгенде эскертүү
preferences-notifications-app-icon-shows-due-count = Тиркеменин сүрөтчөсү мөөнөтү келгендердин санын көрсөтөт
preferences-notifications-settings-app-enable-notifications = Сураныч, iOS жөндөөлөрүнөн Anki бөлүмүн таап, билдирмелерди, белгилерди жана эскертүүлөрдү иштетиңиз.
preferences-pen-size = Калемдин өлчөмү
preferences-question-side = Суроо жагы
preferences-remaining-count = Калган сан
preferences-right = Оң
# gamepad
preferences-right-shoulder = Оң жак ийин (геймпад)
# gamepad
preferences-right-thumbstick-button = Оң джойстик баскычы
# gamepad
preferences-right-trigger = Оң триггер
preferences-scratchpad-below-buttons = Чийме тактасы баскычтардын астында
preferences-scratchpad-transparency = Чийме тактасынын тунуктугу
preferences-scratchpad-transparency-full = Толук
preferences-scratchpad-transparency-medium = Орто
preferences-scratchpad-transparency-none = Жок
preferences-scratchpad-transparency-slight = Бир аз
preferences-shake-action = Силкүү аракети
preferences-short = Кыска
preferences-show-bottom-bar = Төмөнкү тилкени көрсөтүү
preferences-show-grid = Торчону көрсөтүү
preferences-show-top-bar = Жогорку тилкени көрсөтүү
preferences-small = Кичине
preferences-swipe-down = Төмөн сыдыруу
preferences-swipe-left = Солго сыдыруу
preferences-swipe-right = Оңго сыдыруу
preferences-swipe-up = Жогору сыдыруу
preferences-swipes = Сыдыруулар
preferences-swipes-must-begin-from-the-far = Сыдыруу экрандын эң сол же оң четинен башталышы керек.
preferences-sync-sounds-images = Үндөрдү жана сүрөттөрдү шайкештештирүү
preferences-syncing = Шайкештештирилүүдө
preferences-tap-to-sync = Шайкештештирүүнү иштетүү үчүн, топтомдор тизмеси экранындагы шайкештештирүү баскычын басыңыз.
preferences-taps = Басуулар
preferences-theme-bar-style = Тилкенин стили
preferences-theme-black = Кара
preferences-theme-dark-translucent = Караңгы жана тунук
preferences-theme-force-off = Мажбурлап өчүрүү
preferences-theme-force-on = Мажбурлап күйгүзүү
preferences-theme-light-translucent = Ачык жана тунук
preferences-theme-night-mode-desc = Түнкү режим интерфейсти караңгылатат жана карталарды кара фондо ак менен көрсөтөт.
preferences-theme-night-mode-same-as-system = Системаны ээрчүү
preferences-theme-slate = Боз
preferences-thick = Калың
preferences-tools-overlay-button = Аспаптар катмарынын баскычы
preferences-tools-overlay-position = Аспаптар катмарынын жайгашуусу
preferences-top-center = Жогорку борбор
preferences-top-left = Жогорку сол
preferences-top-right = Жогорку оң
preferences-undo-clears-all = "Артка кайтаруу" баарын тазалайт
preferences-when-answer-shown = Жооп көрсөтүлгөндө
preferences-when-question-shown = Суроо көрсөтүлгөндө
preferences-you-have-been-logged-out = Сиз каттоо эсебиңизден чыктыңыз.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Сүрөттүн эң чоң өлчөмү (Узун жагы)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Чаптоодо өлчөмүн өзгөртүү
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = "Акылдуу" тырмакчаларды жана сызыкчаларды өзгөртүү
preferences-editing-crop-camera-photos = Камера сүрөттөрүн кесүү
preferences-loop-video = Видеону кайталоо
preferences-show-video-controls = Видеону башкаруу элементтерин көрсөтүү
preferences-high-quality-video = Жогорку сапаттагы видео
preferences-auto-capitalize = Автоматтык баш тамга
preferences-auto-correct = Авто-түзөтүү
preferences-strip-hebrew-vowels = Иврит үндүүлөрүн алып салуу
