actions-actions = Acciones
actions-add-new = Añadir Nuevo
actions-added-to-frequent-actions = Añadido a acciones frecuentes.
actions-all-actions = Todas las Acciones
actions-already-in-frequent-actions = Ya esta en acciones frecuentes.
actions-an-error-occurred = Se ha producido un error: %@
actions-answer-again = Otra Vez
actions-answer-easy = Fácil
actions-answer-good = Bien
actions-answer-hard = Difícil
actions-are-you-sure = ¿Estás seguro?
actions-auto-advance = Avance Automático
actions-auto-advance-short = Auto Av.
actions-bottom-bar = Barra Inferior
actions-bottom-bar-short = Inf.B
actions-browse = Explorar
actions-bury-card-short = Enterr.C
actions-bury-note-short = Enterr.N
actions-card-buried = Tarjeta enterrada
actions-card-info = Información de la tarjeta
actions-card-info-short = T.Info
actions-card-suspended = Tarjeta suspendida
actions-card-template = Plantillas de tarjetas
actions-confirm-delete = Confirmar eliminación
actions-create = Crear
actions-current-audio-minus-5s = Audio actual -5s
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s = Audio actual +5s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-cant-be-used-on = El estudio personalizado no se puede utilizar en un mazo filtrado.
actions-custom-study-short = Personalizado
actions-deck-statistics = Estadísticas
actions-deck-statistics-short = M.Estad
actions-delete-note-and-its-cards = ¿Eliminar nota y sus tarjetas?
actions-delete-note-short = Eliminar
actions-discard-changes = Descartar Cambios
actions-done = Hecho
actions-downloading = Descargando...
actions-drag-here-to-remove = Arrastra aquí para eliminar
actions-draw = Dibujar
actions-file-invalid-or-corrupt = Archivo no válido o corrupto.
actions-filtercram = Filtrar/Empollar
actions-filtered-deck = Mazo filtrado %i
actions-flag-1 = Marca 1
actions-flag-1-red = Marca 1 (roja)
actions-flag-2 = Marca 2
actions-flag-2-orange = Marca 2 (Naranja)
actions-flag-3 = Marca 3
actions-flag-3-green = Marca 3 (Verde)
actions-flag-4 = Marca 4
actions-flag-4-blue = Marca 4 (Azul)
actions-forgot-card = Tarjeta olvidada
actions-frequent-actions = Acciones frecuentes
actions-how-many-days-in-the-future = ¿Cuántos días en el futuro?
actions-invalid-number-of-days = Número de días inválido.
actions-leave-without-saving = ¿Salir sin guardar?
actions-long-press-on-an-item-to = Mantenga presionado un elemento para personalizarlo.
actions-mark = Marcar
actions-mark-and-bury = Marcar + Enterrar
actions-mark-and-bury-short = M&E
actions-mark-and-suspend = Marcar + Suspender
actions-mark-and-suspend-short = M&S
actions-marked = Marcada
actions-night-mode-short = Noche
actions-no-current-card = No hay tarjeta actual.
actions-no-load-restore-backup = No se pudo cargar tu colección. Por favor, restaura desde una copia de seguridad automática a través de la pantalla de preferencias.
actions-not-valid-link = no parece ser un enlace válido de http/https.
actions-note-and-its-cards-deleted = Nota y sus %i cartas han sido eliminadas
actions-note-and-its-cards-suspended = Nota y sus %i tarjetas suspendidas
actions-note-buried = Nota enterrada
actions-note-marked-and-buried = Nota marcada y enterrada
actions-nothing-to-undo = No hay nada que deshacer
actions-off = Desactivado
actions-pause-audio-short = Pausar
actions-please-tap-the-in-the = Por favor toca el '?' en la parte superior izquierda para empezar.
actions-processing = Procesando...
actions-record-voice = Grabar Voz
actions-record-voice-short = Grabar
actions-replay-audio-short = Repetir
actions-reset-card = Restablecer Tarjeta
actions-reset-card-short = Reset.T
actions-revert = Revertir
actions-review-undone = Revisión deshecha
actions-scratchpad = Bloc de Notas
actions-scratchpad-short = Blog
actions-scratchpad-size = Tamaño del bloc de notas
actions-scratchpad-size-short = Tamaño del bloc de notas
actions-select-deck = Seleccionar Mazo
actions-select-note-type = Seleccionar tipo de nota
actions-set-due-date = Establecer fecha de vencimiento
actions-set-due-date-short = S.Fecha
actions-show-answer-short = S.Res
actions-show-answeranswer-good = Mostrar Respuesta/Respuesta Correcta
actions-show-answeranswer-good-short = Muestra/Bien
actions-study-options = Opciones de Estudio
actions-study-options-short = E.Opt
actions-suspend-card-short = Sus.T
actions-suspend-note-short = Sus.N
actions-tools = Herramientas
actions-tools-overlay = Superposición de herramientas
actions-top-bar = Barra Superior
actions-unbury-deck = Desenterrar mazo
actions-unbury-deck-short = Des M
actions-undo = Deshacer
actions-unmarked = Sin marcas
actions-you-can-only-empty-a-filtered = Sólo puede vaciar un mazo filtrado.
actions-you-can-only-rebuild-a-filtered = Sólo puede reconstruir un mazo filtrado.
