actions-actions = Acciones
actions-add-new = Añadir Nuevo
actions-added-to-frequent-actions = Añadido a acciones frecuentes.
actions-all-actions = Todas las Acciones
actions-already-in-frequent-actions = Ya esta en acciones frecuentes.
actions-an-error-occurred = Se ha producido un error: { $error }
actions-answer-again = Otra Vez
actions-answer-easy = Fácil
actions-answer-good = Bien
actions-answer-hard = Difícil
actions-are-you-sure = ¿Estás seguro?
actions-auto-advance = Avance Automático
actions-bottom-bar = Barra Inferior
actions-browse = Explorar
actions-card-buried = Tarjeta enterrada
actions-card-suspended = Tarjeta suspendida
actions-card-template = Plantillas de tarjetas
actions-confirm-delete = Confirmar eliminación
actions-create = Crear
actions-current-audio-minus-5s = Audio actual -5s
actions-current-audio-plus-5s = Audio actual +5s
actions-custom-study-cant-be-used-on = El estudio personalizado no se puede utilizar en un mazo filtrado.
actions-deck-statistics = Estadísticas
actions-delete-note-and-its-cards = ¿Eliminar nota y sus tarjetas?
actions-discard-changes = Descartar Cambios
actions-done = Hecho
actions-downloading = Descargando...
actions-drag-here-to-remove = Arrastra aquí para eliminar
actions-draw = Dibujar
actions-file-invalid-or-corrupt = Archivo no válido o corrupto.
actions-filtercram = Filtrar/Empollar
actions-filtered-deck = Mazo filtrado { $num }
actions-forgot-card = Tarjeta olvidada
actions-frequent-actions = Acciones frecuentes
actions-leave-without-saving = ¿Salir sin guardar?
actions-long-press-on-an-item-to = Mantenga presionado un elemento para personalizarlo.
actions-mark = Marcar
actions-mark-and-bury = Marcar + Enterrar
actions-mark-and-suspend = Marcar + Suspender
actions-marked = Marcada
actions-no-current-card = No hay tarjeta actual.
actions-no-load-restore-backup = No se pudo cargar tu colección. Por favor, restaura desde una copia de seguridad automática a través de la pantalla de preferencias.
# (http://example.com) does not appear to be...
actions-not-valid-link = no parece ser un enlace válido de http/https.
actions-note-and-its-cards-deleted = Nota y sus { $count } cartas han sido eliminadas
actions-note-and-its-cards-suspended = Nota y sus { $count } tarjetas suspendidas
actions-note-buried = Nota enterrada
actions-note-marked-and-buried = Nota marcada y enterrada
actions-nothing-to-undo = No hay nada que deshacer
actions-nothing-to-redo = Nada que rehacer
actions-off = Desactivado
actions-please-tap-the-in-the = Por favor toca el '?' en la parte superior izquierda para empezar.
actions-processing = Procesando...
actions-record-voice = Grabar Voz
actions-record-voice-menu = Grabar menú de voz
actions-reset-card = Restablecer Tarjeta
actions-revert = Revertir
actions-review-undone = Revisión deshecha
actions-scratchpad = Bloc de Notas
actions-scratchpad-size = Tamaño del bloc de notas
actions-select-deck = Seleccionar Mazo
actions-select-note-type = Seleccionar tipo de nota
actions-show-answeranswer-good = Mostrar Respuesta/Respuesta Correcta
actions-study-options = Opciones de Estudio
actions-tools = Herramientas
actions-tools-overlay = Superposición de herramientas
actions-top-bar = Barra Superior
actions-unbury-deck = Desenterrar mazo
actions-undo = Deshacer
actions-unmarked = Sin marcas
actions-you-can-only-empty-a-filtered = Sólo puede vaciar un mazo filtrado.
actions-you-can-only-rebuild-a-filtered = Sólo puede reconstruir un mazo filtrado.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Vacío
# create a filtered deck
actions-filter-short = Filtrar
actions-add-short = Agregar
actions-answer-again-short = R:Otra
actions-answer-easy-short = R:Fácil
actions-answer-good-short = R:Bien
actions-answer-hard-short = R:Difíc
actions-auto-advance-short = Auto Av.
actions-bottom-bar-short = Inf.B
actions-browse-short = Navegar
actions-bury-card-short = Enterr.C
actions-bury-note-short = Enterr.N
actions-card-info-short = T.Info
actions-card-template-short = Plantilla
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-short = Personalizado
actions-deck-statistics-short = M.Estad
actions-decks-short = Mazos
actions-delete-note-short = Eliminar
actions-edit-short = Editar
actions-mark-and-bury-short = M&E
actions-mark-and-suspend-short = M&S
actions-mark-short = Marcar
actions-night-mode-short = Noche
actions-off-short = Apagado
actions-pause-audio-short = Pausar
actions-rebuild-short = Recons.
actions-record-voice-short = Grabar
actions-replay-audio-short = Repetir
actions-reset-card-short = Reset.T
actions-scratchpad-short = Blog
actions-scratchpad-size-short = Tamaño del bloc de notas
actions-set-due-date-short = S.Fecha
actions-show-answer-short = S.Res
actions-show-answeranswer-good-short = Muestra/Bien
actions-study-options-short = E.Opt
actions-suspend-card-short = Sus.T
actions-suspend-note-short = Sus.N
actions-unbury-deck-short = Des M
actions-undo-short = Deshacer
actions-redo-short = Listo
