browsing-append = Adjuntar
browsing-append-negated = Sustraer
browsing-card-updated = Tarjeta actualizada
browsing-change-flag = Cambiar Marca
browsing-clear-flag = Borrar Marca
browsing-column-1 = Columna 1
browsing-column-2 = Columna 2
browsing-confirm-reset = Confirmar reinicio
browsing-dd-selected = %d/%d seleccionados
browsing-due-dateorder = Fecha de Vencimiento/Orden
browsing-due-reviews = Repasos vencidos
browsing-learning-cards = Tarjetas en fase de aprendizaje
browsing-no-cards-are-selected = No hay tarjetas seleccionadas.
browsing-note-created = Nota creada
browsing-note-updated = Nota actualizada
browsing-note2 = Nota:
browsing-questionandanswer = Pregunta + Respuesta
browsing-repetitions = Repeticiones
browsing-reset-cards = Restablecer Tarjetas
browsing-searching = Buscando...
browsing-second-column-19 = Segunfa Columna (1->9)
browsing-second-column-91 = Segunda columna (9->1)
browsing-select-all = Seleccionar Todo
browsing-sort = Ordenar:
browsing-sort-order = Ordenar
browsing-tag = Etiqueta:
