custom-study-any-tag = cualquiera
custom-study-available = { $num } disponible
custom-study-cant-extend-limits-no-extra = No se pueden extender los límites - no hay tarjetas extra disponibles.
custom-study-cram-seen-cards-with-certain-tags = Empollar tarjetas vistas con ciertas etiquetas
custom-study-days-to-look-ahead = Días para mirar hacia adelante
custom-study-days-to-look-back = Días para volver a ver
custom-study-exclude-cards-with-tag = Excluir tarjetas con etiqueta
custom-study-extra-new-cards = Tarjetas nuevas adicionales
custom-study-extra-review-cards = Tarjetas repasadas adicionales
custom-study-include-cards-with-tag = Incluye tarjetas con etiqueta
custom-study-learn-new-cards-with-certain-tags = Aprender tarjetas nuevas con ciertas etiquetas
custom-study-loading = Cargando...
custom-study-max-cards-to-gather = Máximo de cartas a recolectar
custom-study-no-tags = ninguno
custom-study-no-tags-available = no hay etiquetas disponibles
custom-study-preview-all-cards-with-certain-tags = Previsualizar todas las tarjetas con ciertas etiquetas
custom-study-review-due-cards-with-certain-tags = Revisar las tarjetas de vencimiento con ciertas etiquetas
custom-study-search-matches = Buscar coincidencias { $num }
custom-study-study-type = Tipo de estudio
custom-study-the-selected-options-did-not-match = Las opciones seleccionadas no coinciden con ninguna tarjeta.
