decks-a-deck-must-be-provided = Debe proporcionarse un mazo.
decks-a-deck-named-already-exists = Un mazo llamado '{ $name }' ya existe.
decks-a-deck-with-that-name-already = Ya existe un mazo con ese nombre.
decks-add-deck = Añadir Mazo
decks-add-empty-deck = Añadir Mazo Vacío
decks-addexport = Añadir/Exportar
decks-cannot-delete = No se puede eliminar
decks-card-limit = Límite de tarjetas
decks-cards-in-a-filtered-deck-cant = Las tarjetas en un mazo filtrado no se pueden mover.
decks-custom-steps = Pasos personalizados
decks-deck-exists = El mazo ya existe
decks-deck-label = Mazo:
decks-deck-name = Nombre del Mazo
decks-deck-options = Opciones de Mazo
decks-download-link = Enlace de descarga
decks-export-collection = Exportar colección
decks-filtered-deck = Mazo filtrado
decks-import-from-itunes = Importar desde iTunes
decks-invalid-deck-name = Nombre de mazo inválido.
decks-link-to-apkg-file-to-import = Enlace al archivo .apkg para importar:
decks-no-matches = No hay coincidencias
decks-return-by-delete = Para devolver todas las cartas a la vez, desliza el dedo sobre el mazo azul en la lista de mazos y elimínelo.
decks-shared-deck-list = Lista de Mazos Compartidos
decks-sync = Sincronizar
decks-synchronize = Sincronizar
decks-the-default-deck-cannot-be-deleted = El mazo por defecto no puede ser eliminado.
decks-the-provided-deck-does-not-exist = El mazo proporcionado no existe.
decks-the-search-you-provided-did-not = La búsqueda que proporcionaste no coincide con ninguna tarjeta.
decks-will-be-returned = Las tarjetas serán devueltas a su mazo original a medida que las respondas.
