deck-options-add-options-group = Añadir Opciones de Grupo
deck-options-answer-time-cap = Tiempo límite para responder
deck-options-bury-related-new-cards = Enterrar nuevas targetas relacionadas
deck-options-bury-related-reviews = Enterrar repasos relacionados
deck-options-defaults = Predeterminado
deck-options-delete-options-full-sync = Eliminar este grupo de opciones evitará que cualquier cambio se fusione desde otros dispositivos en la próxima sincronización. ¿Continuar?
deck-options-display-in-order-added = Mostrar en orden añadido
deck-options-display-in-random-order = Mostrar en orden aleatorio
deck-options-full-sync-required = Sincronización completa requerida
deck-options-group-name = Nombre del grupo
deck-options-max-new-per-day = Máximo de nuevas por día
deck-options-max-reviews-per-day = Máximo de repasos por día
deck-options-new-cards = Nuevas tarjetas
deck-options-options-group = Opciones de grupo
deck-options-replay-q-audio-in-answer = Repetir q. audio en respuesta
deck-options-reset-all-settings-to-defaults = ¿Restablecer todos los ajustes a los predeterminados?
deck-options-restore-defaults = Restaurar valores por defecto
deck-options-steps = Pasos
