editing-bold = Negrita
editing-cancel-and-lose-any-unsaved-changes = ¿Quieres cancelar y perder cualquier cambio sin guardar?
editing-cant-edit-original-image-data = No se puede editar, no se ha encontrado la imagen original.
editing-card-returned-to-new-card-queue = La tarjeta regresó a la cola de tarjetas nuevas.
editing-card-unsuspended = Tarjeta sin sispender
editing-from-camera = Desde la Cámara
editing-from-file = Desde archivo
editing-from-photos = Desde Fotos
editing-italic = Cursiva
editing-next-cloze = Siguiente Hueco
editing-next-field = Siguiente Campo
editing-note-deleted = Nota borrada
editing-note-suspended = Nota suspendida
editing-note-type-prompt = Tipo:
editing-note-unsuspended = Nota sin suspender
editing-same-cloze = Misma Cloze
editing-the-first-field-must-not-be = El primer campo no debe estar vacío.
editing-unable-to-obtain-image = No se puede obtener la imagen
editing-unable-to-read-file = No se puede leer el archivo
editing-underline = Subrayar
editing-unexpected-file-extension = Extensión de archivo inesperada:
editing-unexpected-rich-text-format-please = Formato de texto enriquecido inesperado - por favor, intente copiar y pegar.
editing-unexpected-status-code = Código de estado inesperado:
editing-unsuspend-card = Reactivar tarjeta
editing-unsuspend-note = Reactivar nota
