importing-delete-imported-file = ¿Eliminar archivo importado?
importing-import-complete = Importación completada.
importing-importing = Importando…
importing-no-apkg-or-colpkg-files-were = No se ha encontrado ningún archivo .apkg o .colpkg en iTunes
importing-overwrite-via-import = ¿Quieres sobrescribir la colección completa con el archivo importado? Esta acción no se puede deshacer.
importing-please-choose-a-file = Por favor, elije un archivo.
importing-processed-media-files-d = Archivos multimedia procesados: { $count }…
importing-replace-collection = Reemplazar colección
importing-file-not-downloaded = Por favor, descarga el archivo desde iCloud, y luego impórtalo de nuevo.
