preferences-about = Acerca de
preferences-autoplay-in-silent-mode = reproducción automática en modo silencioso
preferences-always-duck = Atenuar música en segundo plano
preferences-answer-keeps-zoom = La respuesta manitene el zoom
preferences-answer-side = Anverso
preferences-audio-buttons = Botones de audio
preferences-auto-advance-answer-action = Acción de respuesta
preferences-auto-advance-answer-seconds = Número de Segundos
preferences-auto-advance-auto-advance-to-start = Para comenzar a avanzar automáticamente, utilice la acción 'Avance Automático'.
preferences-auto-advance-do-nothing = No hacer nada
preferences-auto-advance-question-seconds = Segundos en pregunta
preferences-backup-available-backups = Respaldos disponibles
preferences-backup-create-now = Crear Ahora
preferences-backup-maximum-backups = Máximo de copias de seguridad
preferences-backup-minutes-between-backups = Minutos entre copias de seguridad
preferences-backup-revert-to-backup = Revertir a una copia de seguridad
preferences-backup-revert-to-backup-confirm = Volver a { $backup }? Cualquier cambio realizado desde la copia de seguridad se perderá.
preferences-backup-reverted-to-backup = Revertido a la copia de seguridad.
preferences-bottom-bar-size = Tamaño de la barra inferior
preferences-bottom-center = Parte Inferior Central
preferences-bottom-left = Parte Inferior Izquierda
preferences-bottom-right = Parte Inferior Derecha
preferences-button-d = Botón { $num }
preferences-collection-day-starts = Inicio del día
preferences-collection-learn-ahead-minutes = Aprender Por Avanzado (minutos)
preferences-collection-mix = Mezcla
preferences-collection-new-first = Nuevas primero
preferences-collection-newreview-order = Orden Nuevo/Repaso
preferences-collection-reviews-first = Repasos primero
preferences-double-tap-prevention = Prevención de doble toque
preferences-open-links-externally = Abrir enlances externamente
preferences-drawing-screen-ignores-fingers = La pantalla de dibujo ignora los dedos
preferences-feedback-ticks = Cuadro de comentarios
preferences-fine = Fino
preferences-force-sync-confirm = ¿Forzar una sincronización unidireccional? Todos los cambios en un lado se perderán.
preferences-full-sync = Sincronización completa
preferences-gamepad-button-mapping = Asignación de botones
preferences-gamepad-menu-button = Menú
preferences-gamepads = Gamepads
preferences-height = Altura
preferences-huge = Enorme
preferences-ignore-fingers = Ignorar dedos
preferences-interrupt-current-audio = Interrumpir el Audio Actual
preferences-large = Grande
preferences-left = Izquierda
# gamepad
preferences-left-shoulder = Gatillo Izquierdo
# gamepad
preferences-left-thumbstick-button = Botón de palanca de izquierdo
# gamepad
preferences-left-trigger = Gatillo izquierdo
preferences-logged-in-as = Conectado como:
preferences-long = Largo
preferences-mid-center = Centro Medio
preferences-mid-left = Centro Izquierda
preferences-mid-right = Centro Derecha
preferences-never-type-answer = Nunca escriba la respuesta
preferences-never-show-scratchpad = Nunca mostrar Bloc de notas
preferences-never-show-scratchpad-enabled = 'Nunca mostrar Bloc de notas' está habilitado en la pantalla Preferencias.
preferences-next-times = Próximas veces
preferences-normal = Normal
preferences-notifications = Notificaciones
preferences-notifications-alert-time = Hora de alerta
preferences-notifications-alert-when-due = Alertar cuando haya repasos venzidos
preferences-notifications-app-icon-shows-due-count = El icono de la aplicación muestra el número de repasos pendientes
preferences-notifications-settings-app-enable-notifications = Por favor, vaya a configuración de aplicaciónes de iOS, localize la sección de Anki, y habilite las notificaciones, insignias y alertas.
preferences-pen-size = Tamaño del lápiz
preferences-question-side = Lado de la pregunta
preferences-remaining-count = Recuento Restante
preferences-right = Derecha
# gamepad
preferences-right-shoulder = Gatillo Derecho
# gamepad
preferences-right-thumbstick-button = Botón derecho del joystick
# gamepad
preferences-right-trigger = Gatillo derecho
preferences-scratchpad-below-buttons = Botones de abajo del bloc de notas
preferences-scratchpad-transparency = Transparencia del bloc de notas
preferences-scratchpad-transparency-full = Completa
preferences-scratchpad-transparency-medium = Medio
preferences-scratchpad-transparency-none = Ninguno
preferences-scratchpad-transparency-slight = Leve
preferences-shake-action = Acción de sacudida
preferences-short = Corto
preferences-show-bottom-bar = Mostrar Barra Inferior
preferences-show-grid = Mostrar Cuadrícula
preferences-show-top-bar = Mostrar barra superior
preferences-small = Pequeño
preferences-swipe-down = Deslizar abajo
preferences-swipe-left = Deslizar a la izquierda
preferences-swipe-right = Deslizar a la derecha
preferences-swipe-up = Deslizar hacia arriba
preferences-swipes = Deslizar
preferences-swipes-must-begin-from-the-far = Los deslizamientos deben comenzar desde la extrema izquierda o derecha de la pantalla.
preferences-sync-sounds-images = Sincronizar sonidos & Imágenes
preferences-syncing = Sincronizando
preferences-tap-to-sync = Para activar la sincronización, toque el botón de sincronización en la pantalla principal.
preferences-taps = Toques
preferences-theme-bar-style = Estilo de barra
preferences-theme-black = Negro
preferences-theme-dark-translucent = Oscuro & Translucido
preferences-theme-force-off = Forzar desactivación
preferences-theme-force-on = Forzar activación
preferences-theme-light-translucent = Luz & Translucido
preferences-theme-night-mode-desc = El modo nocturno oscurece la interfaz y muestra las tarjetas en blanco sobre negro.
preferences-theme-night-mode-same-as-system = Igual que el sistema
preferences-theme-slate = Pizarra
preferences-thick = Grosor
preferences-tools-overlay-button = Botón de superposición de herramientas
preferences-tools-overlay-position = Posición de superposición de herramientas
preferences-top-center = Parte Superior Central
preferences-top-left = Parte Superior Izquierda
preferences-top-right = Parte Superior Derecha
preferences-undo-clears-all = Deshacer lo borra todo
preferences-when-answer-shown = Cuando se muestra la respuesta
preferences-when-question-shown = Cuando se muestra la pregunta
preferences-you-have-been-logged-out = Has cerrado la sesión.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Tamaño máximo de imagen (borde largo)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Redimensionar al pegar
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Convertir comillas y guiones inteligentes
preferences-editing-crop-camera-photos = Recortar fotos de la cámara
preferences-loop-video = Vídeo en bucle
preferences-show-video-controls = Mostrar los controles de reproducción
preferences-high-quality-video = Video en alta calidad
preferences-auto-capitalize = Capitalizar automáticamente
preferences-auto-correct = Corrector ortográfico
