profiles-a-profile-with-that-name-already = Ya existe un perfil con ese nombre.
profiles-add-profile = Añadir Perfil
profiles-creating-backup = Creando copia de seguridad...
profiles-finishing-backup = Finalizando copia de seguridad...
profiles-please-provide-some-text-avoiding-symbols = Por favor escribe algún texto, evitando símbolos y guiones bajos.
profiles-please-select-another-profile-first = Por favor, selecciona otro perfil primero.
profiles-profile-name = Nombre del perfil
profiles-rename-profile = Renombrar perfil
profiles-unable-to-open-safari-please = No se puede abrir Safari - por favor comprueba los controles parentales.
profiles-welcome = ¡Bienvenid@!
