actions-actions = 操作
actions-add-new = 添加
actions-added-to-frequent-actions = 已添加至常用操作。
actions-all-actions = 全部操作
actions-already-in-frequent-actions = 已在常用操作中。
actions-an-error-occurred = 发生错误：{ $error }
actions-answer-easy = 回答「简单」
actions-are-you-sure = 确定？
actions-bottom-bar = 底部按钮
actions-browse = 浏览
actions-card-buried = 卡片已搁置
actions-card-suspended = 卡片已暂停
actions-card-template = 卡片模板
actions-confirm-delete = 确认删除
actions-create = 创建
actions-current-audio-minus-5s = 当前音频－5s
actions-current-audio-plus-5s = 当前音频＋5s
actions-custom-study-cant-be-used-on = 不能对筛选牌组进行自定义学习。
actions-deck-statistics = 牌组统计
actions-delete-note-and-its-cards = 删除笔记及其卡片？
actions-discard-changes = 放弃修改
actions-done = 完成
actions-downloading = 下载中…
actions-drag-here-to-remove = 拖动至此以移除。
actions-draw = 手写
actions-file-invalid-or-corrupt = 文件无效或损坏。
actions-filtercram = 筛选/突击
actions-filtered-deck = 筛选牌组 { $num }
actions-frequent-actions = 常用操作
actions-leave-without-saving = 不保存就离开？
actions-long-press-on-an-item-to = 长按一个项目以自定义。
actions-mark = 标记
actions-mark-and-bury = 标记 + 搁置
actions-mark-and-suspend = 标记 + 暂停
actions-marked = 已标记
actions-no-current-card = 当前牌组中没有卡片。
actions-no-load-restore-backup = 无法加载您的集合。请访问「设置」>「备份」以恢复数据。
# (http://example.com) does not appear to be...
actions-not-valid-link = 似乎不是有效的 http/https 链接。
actions-note-and-its-cards-deleted = 笔记及其 { $count } 张卡片已删除
actions-note-and-its-cards-suspended = 笔记及其 { $count } 张卡片已暂停
actions-note-buried = 笔记已搁置
actions-note-marked-and-buried = 笔记已被标记并搁置
actions-off = 禁用
actions-please-tap-the-in-the = 请点击左上角的「?」以开始。
actions-record-voice = 录制音频
actions-record-voice-menu = 录制声音菜单
actions-reset-card = 重置为新卡片
actions-revert = 还原
actions-review-undone = 复习已撤销
actions-scratchpad = 手写板
actions-scratchpad-size = 手写板大小
actions-select-deck = 选择牌组
actions-select-note-type = 选择笔记模板
actions-show-answeranswer-good = 显示答案/回答「良好」
actions-study-options = 学习选项
actions-tools = 工具
actions-tools-overlay = 快捷工具包
actions-top-bar = 顶栏
actions-unbury-deck = 取消该牌组的搁置
actions-undo = 撤销
actions-unmarked = 已取消标记
actions-you-can-only-empty-a-filtered = 您只可以清空筛选牌组。
actions-you-can-only-rebuild-a-filtered = 您只可以重建筛选牌组。
actions-scroll-up = 向上滚动
actions-scroll-down = 向下滚动

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = 清空
# create a filtered deck
actions-filter-short = 筛选
actions-add-short = 添加
actions-answer-again-short = 忘记
actions-answer-easy-short = 简单
actions-answer-good-short = 良好
actions-answer-hard-short = 困难
actions-auto-advance-short = 自动前进
actions-bottom-bar-short = 底栏
actions-browse-short = 浏览
actions-bury-card-short = 搁置卡片
actions-bury-note-short = 搁置笔记
actions-card-info-short = 卡片信息
actions-card-template-short = 模板
actions-current-audio-minus-5s-short = －5秒
actions-current-audio-plus-5s-short = ＋5秒
actions-custom-study-short = 自定义
actions-deck-statistics-short = 牌组统计
actions-decks-short = 牌组
actions-delete-note-short = 删除
actions-edit-short = 编辑
actions-mark-and-bury-short = 标记并搁置
actions-mark-and-suspend-short = 标记并暂停
actions-mark-short = 标记
actions-night-mode-short = 夜间模式
actions-off-short = 关闭
actions-pause-audio-short = 终止
actions-rebuild-short = 重建
actions-record-voice-short = 录音
actions-replay-voice-short = 重播
actions-replay-audio-short = 重播
actions-reset-card-short = 重置卡片
actions-scratchpad-short = 手写板
actions-scratchpad-size-short = 手写板大小
actions-set-due-date-short = 指定到期
actions-show-answer-short = 答案
actions-show-answeranswer-good-short = 显示/回答
actions-study-options-short = 选项
actions-suspend-card-short = 暂停卡片
actions-suspend-note-short = 暂停笔记
actions-tools-short = 工具
actions-top-bar-short = 工具栏
actions-unbury-deck-short = 取消搁置
actions-undo-short = 撤销
actions-redo-short = 恢复
actions-scroll-up-short = 向上
actions-scroll-down-short = 向下
actions-back = 返回
