actions-actions = 操作
actions-add-new = 新建
actions-added-to-frequent-actions = 已添加至常用操作。
actions-all-actions = 全部操作
actions-already-in-frequent-actions = 已在常用操作中。
actions-an-error-occurred = 发生错误：{ $error }
actions-answer-again = 回答“再来”
actions-answer-easy = 回答“简单”
actions-answer-good = 回答“良好”
actions-answer-hard = 回答“困难”
actions-are-you-sure = 确定？
actions-auto-advance = 自动播放卡片
actions-bottom-bar = 底部导航栏
actions-browse = 浏览
actions-card-buried = 卡片已延期
actions-card-info = 卡片信息
actions-card-suspended = 卡片已保留
actions-card-template = 卡片模板
actions-confirm-delete = 确认删除
actions-create = 创建
actions-current-audio-minus-5s = 当前音频－5s
actions-current-audio-plus-5s = 当前音频＋5s
actions-custom-study-cant-be-used-on = 不能对筛选卡组进行自定义学习。
actions-deck-statistics = 卡组统计
actions-delete-note-and-its-cards = 删除笔记及其卡片？
actions-discard-changes = 放弃修改
actions-done = 完成
actions-downloading = 下载中…
actions-drag-here-to-remove = 拖动至此以移除。
actions-draw = 绘制
actions-file-invalid-or-corrupt = 文件无效或损坏。
actions-filtercram = 筛选/死记硬背
actions-filtered-deck = 筛选卡组 { $num }
actions-flag-1 = 标注 1
actions-flag-1-red = 标注 1 (红)
actions-flag-2 = 标注 2
actions-flag-2-orange = 标注 2 (橙)
actions-flag-3 = 标注 3
actions-flag-3-green = 标注 3 (绿)
actions-flag-4 = 标注 4
actions-flag-4-blue = 标注 4 (蓝)
actions-forgot-card = 忘记卡片
actions-frequent-actions = 常用操作
actions-leave-without-saving = 不保存就离开？
actions-long-press-on-an-item-to = 长按一个项目以自定义。
actions-mark = 标记(快捷标签)
actions-mark-and-bury = 标记 + 延期
actions-mark-and-suspend = 标记 + 保留
actions-marked = 已标记
actions-no-current-card = 目前没有卡片。
actions-no-load-restore-backup = 无法加载您的卡组集合。请访问 偏好设置->备份 以恢复数据。
# (http://example.com) does not appear to be...
actions-not-valid-link = 似乎不是有效的 http/https链接。
actions-note-and-its-cards-deleted = 笔记及其 { $count } 张卡片已删除
actions-note-and-its-cards-suspended = 笔记及其 { $count } 张卡片已保留
actions-note-buried = 笔记已延期
actions-note-marked-and-buried = 笔记已标记并延期
actions-nothing-to-undo = 无可撤销
actions-off = 禁用
actions-please-tap-the-in-the = 请点击左上角的 ? 以开始。
actions-processing = 处理中...
actions-record-voice = 录制音频
actions-reset-card = 重置为新卡片
actions-revert = 还原
actions-review-undone = 复习已撤销
actions-scratchpad = 手写板
actions-scratchpad-size = 手写板大小
actions-select-deck = 选择卡组
actions-select-note-type = 选择笔记类型
actions-show-answeranswer-good = 显示答案/回答“良好”
actions-study-options = 学习选项
actions-tools = 工具包
actions-tools-overlay = 快捷工具包
actions-top-bar = 顶部快捷栏
actions-unbury-deck = 取消延期该卡组
actions-undo = 撤销
actions-unmarked = 已抹去标记
actions-you-can-only-empty-a-filtered = 您只可以清空筛选卡组。
actions-you-can-only-rebuild-a-filtered = 您只可以重建筛选卡组。

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = 清空
# create a filtered deck
actions-filter-short = 过滤
actions-add-short = 添加
actions-answer-again-short = 重来
actions-answer-easy-short = 简单
actions-answer-good-short = 良好
actions-answer-hard-short = 困难
actions-auto-advance-short = 自动播卡
actions-bottom-bar-short = 底栏
actions-browse-short = 浏览
actions-bury-card-short = 卡片延期
actions-bury-note-short = 笔记延期
actions-card-info-short = 信息
actions-card-template-short = 模板
actions-current-audio-minus-5s-short = －5s
actions-current-audio-plus-5s-short = ＋5s
actions-custom-study-short = 自定义
actions-deck-statistics-short = 卡组统计
actions-decks-short = 牌组
actions-delete-note-short = 删除
actions-edit-short = 编辑
actions-mark-and-bury-short = 标&延期
actions-mark-and-suspend-short = 标&保留
actions-mark-short = 标记
actions-night-mode-short = 夜间
actions-off-short = 关闭
actions-pause-audio-short = 暂停
actions-rebuild-short = 重建
actions-record-voice-short = 录音
actions-replay-audio-short = 重播
actions-reset-card-short = 重置卡片
actions-scratchpad-short = 手写板
actions-scratchpad-size-short = 手写板大小
actions-set-due-date-short = 指定到期
actions-show-answer-short = 答案
actions-show-answeranswer-good-short = 显示/“良好”
actions-study-options-short = 选项
actions-suspend-card-short = 保留卡片
actions-suspend-note-short = 保留笔记
actions-tools-short = 工具
actions-top-bar-short = 工具栏
actions-unbury-deck-short = 取消延期
actions-undo-short = 撤销
