decks-a-deck-must-be-provided = 至少需要保留一个牌组。
decks-a-deck-named-already-exists = 已存在名为 “{ $name }” 的牌组。
decks-a-deck-with-that-name-already = 已存在同名牌组。
decks-add-deck = 添加牌组
decks-add-empty-deck = 创建空牌组
decks-addexport = 添加/导出
decks-cannot-delete = 不能删除
decks-card-limit = 卡片上限
decks-cards-in-a-filtered-deck-cant = 不能移动筛选牌组内的卡片。
decks-custom-steps = 自定义步骤
decks-deck-exists = 牌组已存在
decks-deck-label = 牌组：
decks-deck-name = 牌组名称
decks-deck-options = 牌组学习计划
decks-download-link = 下载链接
decks-export-collection = 导出集合
decks-filtered-deck = 筛选牌组
decks-import-from-itunes = 从 iTunes 中导入
decks-invalid-deck-name = 无效的牌组名称。
decks-link-to-apkg-file-to-import = 链接到 .apkg文件以导入:
decks-no-matches = 没有找到匹配结果
decks-return-by-delete = 要把所有卡片放回原位，请在牌组列表中的蓝色牌组上滑动删除。
decks-shared-deck-list = 共享牌组列表
decks-sync = 同步
decks-synchronize = 同步
decks-the-default-deck-cannot-be-deleted = 系统预置牌组不能被删除。
decks-the-provided-deck-does-not-exist = 牌组不存在。
decks-the-search-you-provided-did-not = 您提供的搜索条件没有匹配到任何卡片。
decks-will-be-returned = 这些卡片会在您做出回答后被放回原牌组。
