deck-options-add-options-group = 添加学习计划组
deck-options-answer-time-cap = 回答时限(超出不计入统计)
deck-options-bury-related-new-cards = 同源新卡片延期至次日
deck-options-bury-related-reviews = 同源待复习卡片延期至次日
deck-options-defaults = 默认
deck-options-delete-options-full-sync = 删除此学习计划组将在下次同步时阻止来自其他设备的任何修改。继续吗？
deck-options-display-in-order-added = 卡片添加时间
deck-options-display-in-random-order = 随机
deck-options-full-sync-required = 需要完全同步
deck-options-group-name = 组名称
deck-options-max-new-per-day = 每天最多新卡数 (张)
deck-options-max-reviews-per-day = 每天最多复习数 (张)
deck-options-new-cards = 新卡片
deck-options-options-group = 学习计划组
deck-options-replay-q-audio-in-answer = 显示答案时重播问题音频
deck-options-reset-all-settings-to-defaults = 将所有设置重置为默认值？
deck-options-restore-defaults = 恢复默认值
deck-options-steps = 步骤 (分钟/步)
