deck-options-add-options-group = 添加学习计划组
deck-options-answer-time-cap = 回答时限(超出不计入统计)
deck-options-bury-related-new-cards = 搁置相关的新卡片
deck-options-bury-related-reviews = 搁置相关的复习卡片
deck-options-defaults = 默认
deck-options-delete-options-full-sync = 删除此计划组将导致下次同步时无法与其他设备合并改变，继续吗？
deck-options-display-in-order-added = 按卡片添加顺序显示
deck-options-display-in-random-order = 按随机顺序显示
deck-options-full-sync-required = 需要完全同步
deck-options-group-name = 组名称
deck-options-max-new-per-day = 每天最多新卡数 (张)
deck-options-max-reviews-per-day = 每天最多复习数 (张)
deck-options-new-cards = 新卡片
deck-options-options-group = 学习计划组
deck-options-replay-q-audio-in-answer = 显示答案时重播问题音频
deck-options-reset-all-settings-to-defaults = 将所有设置重置为默认值？
deck-options-restore-defaults = 恢复默认值
deck-options-steps = 步幅 (分钟/步)
