editing-bold = 粗体
editing-cancel-and-lose-any-unsaved-changes = 取消并丢失所有未保存的修改？
editing-cant-edit-original-image-data = 无法编辑 - 未找到原始图像数据。
editing-card-returned-to-new-card-queue = 卡片已返回新卡片队列。
editing-card-unsuspended = 保留卡片已放回
editing-from-camera = 照相机
editing-from-file = 文件
editing-from-photos = 照片
editing-italic = 斜体
editing-next-cloze = 下一空
editing-next-field = 下一字段
editing-note-deleted = 笔记已删除
editing-note-suspended = 笔记已保留
editing-note-type-prompt = 类型：
editing-note-unsuspended = 保留笔记已取出
editing-same-cloze = 同一空
editing-the-first-field-must-not-be = 首字段不能清空。
editing-unable-to-obtain-image = 无法载入图片
editing-unable-to-read-file = 无法读取文件
editing-underline = 下划线
editing-unexpected-file-extension = 不支持的文件扩展名：
editing-unexpected-rich-text-format-please = 文本格式不支持 - 请尝试复制和粘贴
editing-unexpected-status-code = 意外的状态代码：
editing-unsuspend-card = 放回保留的卡片
editing-unsuspend-note = 取出保留的笔记
