exporting-collection-saved-to-itunes = 集合已保存至iTunes。
exporting-export-to-itunes = 导出到 iTunes
exporting-export-to-share-sheet = 导出到…
exporting-exporting = 正在导出...
exporting-include-media2 = 包括媒体文件
exporting-media-files-exported-d = 导出媒体文件：{ $count }...
