preferences-about = 关于
preferences-always-duck-and-ignore-mute = 弱化其他媒体音量 + 无视系统静音
preferences-answer-keeps-zoom = 答案部分保持缩放比例
preferences-answer-side = 答案界面
preferences-audio-buttons = 显示音频按钮
preferences-auto-advance-answer-action = 回答操作
preferences-auto-advance-answer-seconds = 答案显示时间（秒）
preferences-auto-advance-auto-advance-to-start = 将「自动过卡」添加至快捷栏或手势中以快捷开启/关闭此功能。
preferences-auto-advance-do-nothing = 什么也不做
preferences-auto-advance-question-seconds = 问题显示时间（秒）
preferences-auto-advance-show-reminder = 显示提醒
preferences-auto-advance-wait-for-audio = 等待音频播放完毕
preferences-backup-available-backups = 可用的备份
preferences-backup-create-now = 立即创建
preferences-backup-maximum-backups = 最大备份数
preferences-backup-minutes-between-backups = 备份频率（分钟）
preferences-backup-revert-to-backup = 还原备份
preferences-backup-revert-to-backup-confirm = 还原到 { $backup }？自此备份以后的所有修改都将丢失。
preferences-backup-reverted-to-backup = 备份已还原。
preferences-bottom-bar-size = 底栏尺寸
preferences-bottom-center = 中下
preferences-bottom-left = 左下
preferences-bottom-right = 右下
preferences-button-d = 按钮 { $num }
preferences-collection-day-starts = 一天开始于
preferences-collection-learn-ahead-minutes = 提前学习（分钟）
preferences-collection-mix = 混合
preferences-collection-new-first = 先学新
preferences-collection-newreview-order = 学习/复习顺序
preferences-collection-reviews-first = 先复习
preferences-double-tap-prevention = 防止双击
preferences-drawing-screen-ignores-fingers = 绘图界面忽略手指
preferences-feedback-ticks = 显示对错符号
preferences-fine = 细
preferences-force-sync-confirm = 强制单向同步？本地和云端中有一方的数据将被覆盖。
preferences-full-sync = 完全同步
preferences-gamepad-button-mapping = 按钮映射
preferences-gamepad-menu-button = 菜单
preferences-gamepads = 游戏手柄
preferences-height = 大小
preferences-huge = 巨大
preferences-ignore-fingers = 禁用手指
preferences-interrupt-current-audio = 中断当前音频
preferences-large = 大
preferences-left = 左对齐
# gamepad
preferences-left-shoulder = 左肩键
# gamepad
preferences-left-thumbstick-button = 左摇杆
# gamepad
preferences-left-trigger = 左扳机键
preferences-logged-in-as = 登录为：
preferences-long = 长
preferences-mid-center = 正中
preferences-mid-left = 左中
preferences-mid-right = 右中
preferences-never-type-answer = 禁用键入答案
preferences-never-show-scratchpad = 从不显示草稿本
preferences-never-show-scratchpad-enabled = 「从不显示草稿本」已在设置中打开。
preferences-next-times = 下次答题时间
preferences-normal = 普通
preferences-notifications = 通知
preferences-notifications-alert-time = 提醒时间
preferences-notifications-alert-when-due = 每日提醒
preferences-notifications-app-icon-shows-due-count = 应用图标显示到期卡片数量
preferences-notifications-settings-app-enable-notifications = 请前往 iOS 设定，找到「Anki」，并允许通知、标记和提示。
preferences-pen-size = 笔迹粗细
preferences-question-side = 问题界面
preferences-remaining-count = 剩余卡片数
preferences-right = 右对齐
# gamepad
preferences-right-shoulder = 右肩键
# gamepad
preferences-right-thumbstick-button = 右摇杆
# gamepad
preferences-right-trigger = 右扳机键
preferences-scratchpad-below-buttons = 置于底栏下方
preferences-scratchpad-transparency = 手写板透明度
preferences-scratchpad-transparency-full = 全透明
preferences-scratchpad-transparency-medium = 中等
preferences-scratchpad-transparency-none = 无
preferences-scratchpad-transparency-slight = 细
preferences-shake-action = 摇⼀摇
preferences-short = 短
preferences-show-bottom-bar = 显示底栏
preferences-show-grid = 显示网格
preferences-show-top-bar = 显示顶栏
preferences-small = 小
preferences-swipe-down = 下滑
preferences-swipe-left = 左滑
preferences-swipe-right = 右滑
preferences-swipe-up = 上滑
preferences-swipes = 手势控制：滑动
preferences-swipes-must-begin-from-the-far = 请从屏幕最左侧或最右侧开始滑动。
preferences-sync-sounds-images = 同步声音和图像
preferences-syncing = 同步
preferences-tap-to-sync = 在牌组列表界面点击「同步」以开始。
preferences-taps = 手势控制：轻点
preferences-theme-bar-style = 栏样式
preferences-theme-black = 黑色
preferences-theme-dark-translucent = 深色半透明
preferences-theme-force-off = 强制关闭
preferences-theme-force-on = 强制开启
preferences-theme-light-translucent = 浅色半透明
preferences-theme-night-mode-desc = 夜间模式界面变暗，卡片以黑底白字显示。
preferences-theme-night-mode-same-as-system = 与系统保持一致
preferences-theme-slate = 深灰
preferences-thick = 粗
preferences-tools-overlay-button = 工具包按钮
preferences-tools-overlay-position = 工具包位置
preferences-top-center = 中上
preferences-top-left = 左上
preferences-top-right = 右上
preferences-undo-clears-all = 撤销清除全部
preferences-when-answer-shown = 显示答案界面时
preferences-when-question-shown = 显示问题界面时
preferences-you-have-been-logged-out = 您已退出登陆。
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = 图像最大尺寸（长边）
# whether to shrink images when pasting
preferences-editing-resize-on-paste = 粘贴时缩放图像
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = 自动标点转换
preferences-editing-crop-camera-photos = 裁剪相机照片
preferences-loop-video = 循环播放视频
preferences-show-video-controls = 显示视频控制
preferences-auto-capitalize = 输入字母时自动将句首字母大写
preferences-auto-correct = 自动更正
preferences-strip-hebrew-vowels = 去除希伯来语元音
