profiles-a-profile-with-that-name-already = 同名配置文件已存在。
profiles-add-profile = 添加配置文件
profiles-creating-backup = 正在创建备份...
profiles-finishing-backup = 正在完成备份...
profiles-please-provide-some-text-avoiding-symbols = 请提供一些文本，避免使用符号和下划线。
profiles-please-select-another-profile-first = 请先选用其他配置文件。
profiles-profile-name = 配置文件名
profiles-rename-profile = 重命名配置文件
profiles-unable-to-open-safari-please = 无法打开Safari - 请检查家长控制。
profiles-welcome = 欢迎！
