studying-answer-time-elapsed = 播放时间已过
studying-auto-advance-starting = 已开始自动播放卡片
studying-auto-advance-stopped = 已停止自动播放卡片
studying-have-ready-to-study = 你有 { $numCards }可供学习。
studying-please-run-empty-cards-on-the = 请在计算机版本运行“空白卡片”。
studying-replay-card = 回放卡片
studying-replay-voice = 重播音频
studying-rescheduled-card = 已重新安排卡片进度。
studying-type-in-the-answer = 输入答案
