actions-actions = Akcje
actions-add-new = Dodaj nową
actions-added-to-frequent-actions = Dodano do częstych działań.
actions-all-actions = Wszystkie działania
actions-already-in-frequent-actions = Już obecne w częstych działaniach.
actions-an-error-occurred = Wystąpił błąd: { $error }
actions-answer-again = Odpowiedz Powtórz
actions-answer-easy = Odpowiedz Łatwa
actions-answer-good = Odpowiedz Dobra
actions-answer-hard = Odpowiedz Trudna
actions-are-you-sure = Czy jesteś pewien?
actions-auto-advance = Auto-postęp
actions-bottom-bar = Dolny pasek
actions-browse = Przegląd
actions-card-buried = Karta zakopana
actions-card-suspended = Karta zawieszona
actions-card-template = Szablon karty
actions-confirm-delete = Potwierdź usunięcie
actions-create = Utwórz
actions-current-audio-minus-5s = Obecny dźwięk -5s
actions-current-audio-plus-5s = Obecny dźwięk +5s
actions-custom-study-cant-be-used-on = Nauka własna nie może zostać użyta w talii filtrowanej.
actions-deck-statistics = Statystyki talii
actions-delete-note-and-its-cards = Usunąć notatkę i powiązane z nią karty?
actions-discard-changes = Porzuć zmiany
actions-done = Gotowe
actions-downloading = Pobieranie...
actions-drag-here-to-remove = Przeciągnij tutaj, aby usunąć
actions-draw = Rysuj
actions-file-invalid-or-corrupt = Plik nieprawidłowy lub uszkodzony.
actions-filtercram = Filtruj/Zakuwaj
actions-filtered-deck = Filtrowana talia { $num }
actions-forgot-card = Zapomniano kartę
actions-frequent-actions = Częste działania
actions-leave-without-saving = Wyjść bez zapisywania?
actions-long-press-on-an-item-to = Przyciśnij dłużej na obiekcie, aby dostosować.
actions-mark = Wyróżnij
actions-mark-and-bury = Wyróżnij + Zakop
actions-mark-and-suspend = Wyróżnij + Zawieś
actions-marked = Wyróżniona
actions-no-current-card = Brak aktualnej karty.
actions-no-load-restore-backup = Twoja kolekcja nie mogła zostać załadowana. Przywróć automatyczną kopię zapasową poprzez ekran ustawień.
# (http://example.com) does not appear to be...
actions-not-valid-link = nie wydaje się być prawidłowym linkiem http/https.
actions-note-and-its-cards-deleted = Usunięto notatkę i jej { $count } kart(y)
actions-note-and-its-cards-suspended = Zawieszono notatkę i jej { $count } kart(y)
actions-note-buried = Notatka zakopana
actions-note-marked-and-buried = Notatka wyróżniona i zakopana
actions-nothing-to-undo = Nic do cofnięcia
actions-nothing-to-redo = Nic do ponowienia
actions-off = Wył.
actions-please-tap-the-in-the = Naciśnij „?” w lewym górnym rogu, aby rozpocząć.
actions-processing = Przetwarzanie...
actions-record-voice = Nagraj głos
actions-record-voice-menu = Menu nagrywania głosu
actions-reset-card = Resetuj kartę
actions-revert = Przywróć
actions-review-undone = Powtórka cofnięta
actions-scratchpad = Brudnopis
actions-scratchpad-size = Rozmiar brudnopisu
actions-select-deck = Wybierz talię
actions-select-note-type = Wybierz typ notatki
actions-show-answeranswer-good = Pokaż odp./odp. Dobra
actions-study-options = Opcje nauki
actions-tools = Narzędzia
actions-tools-overlay = Nakładka z narzędziami
actions-top-bar = Górny pasek
actions-unbury-deck = Odkop talię
actions-undo = Cofnij
actions-unmarked = Usunięto wyróżnienie
actions-you-can-only-empty-a-filtered = Możesz opróżnić tylko talię filtrowaną.
actions-you-can-only-rebuild-a-filtered = Możesz przebudować tylko talię filtrowaną.
actions-scroll-up = Przewiń w górę
actions-scroll-down = Przewiń w dół

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Opróżnij
# create a filtered deck
actions-filter-short = Filtruj
actions-add-short = Dodaj
actions-answer-again-short = Odp.P
actions-answer-easy-short = Odp.Ł
actions-answer-good-short = Odp.D
actions-answer-hard-short = Odp.T
actions-auto-advance-short = Auto-pos.
actions-bottom-bar-short = Dol.P
actions-browse-short = Przegląd
actions-bury-card-short = Zkp K.
actions-bury-note-short = Zkp N.
actions-card-info-short = K.Info
actions-card-template-short = Szablon
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Własna
actions-deck-statistics-short = Staty.T
actions-decks-short = Talie
actions-delete-note-short = Usń
actions-edit-short = Edytuj
actions-mark-and-bury-short = W&Zkp
actions-mark-and-suspend-short = W&Zaw
actions-mark-short = Wyróż.
actions-night-mode-short = Noc
actions-off-short = Wył.
actions-pause-audio-short = Pauza
actions-rebuild-short = Przebud.
actions-record-voice-short = Nagraj
actions-replay-voice-short = Odtw.G
actions-replay-audio-short = Odtwórz
actions-reset-card-short = Reset.K
actions-scratchpad-short = Brud.
actions-scratchpad-size-short = Roz.Brud.
actions-set-due-date-short = Ust.Ter
actions-show-answer-short = Pok.Odp.
actions-show-answeranswer-good-short = Pok./Dobra
actions-study-options-short = Opc.N
actions-suspend-card-short = Zaw.K
actions-suspend-note-short = Zaw.N
actions-tools-short = Narzędz.
actions-top-bar-short = G.pasek
actions-unbury-deck-short = Odkop
actions-undo-short = Cofnij
actions-redo-short = Ponów
actions-scroll-up-short = W górę
actions-scroll-down-short = W dół
