actions-actions = Akcje
actions-add-new = Dodaj nową
actions-added-to-frequent-actions = Dodano do częstych działań.
actions-all-actions = Wszystkie działania
actions-already-in-frequent-actions = Już obecne w częstych działaniach.
actions-an-error-occurred = Wystąpił błąd: { $error }
actions-answer-again = Odpowiedz Powtórz
actions-answer-easy = Odpowiedz Łatwa
actions-answer-good = Odpowiedz Dobra
actions-answer-hard = Odpowiedz Trudna
actions-are-you-sure = Czy jesteś pewien?
actions-auto-advance = Auto-postęp
actions-auto-advance-short = Auto-pos.
actions-bottom-bar = Dolny pasek
actions-bottom-bar-short = Dol.P
actions-browse = Przegląd
actions-bury-card-short = Zkp K.
actions-bury-note-short = Zkp N.
actions-card-buried = Karta zakopana
actions-card-info = Informacje o karcie
actions-card-info-short = K.Info
actions-card-suspended = Karta zawieszona
actions-card-template = Szablon karty
actions-confirm-delete = Potwierdź usunięcie
actions-create = Utwórz
actions-current-audio-minus-5s = Obecny dźwięk -5s
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s = Obecny dźwięk +5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-cant-be-used-on = Nauka własna nie może zostać użyta w talii filtrowanej.
actions-custom-study-short = Własna
actions-deck-statistics = Statystyki talii
actions-deck-statistics-short = Staty.T
actions-delete-note-and-its-cards = Usunąć notatkę i powiązane z nią karty?
actions-delete-note-short = Usń
actions-discard-changes = Porzuć zmiany
actions-done = Gotowe
actions-downloading = Pobieranie...
actions-drag-here-to-remove = Przeciągnij tutaj, aby usunąć
actions-draw = Rysuj
actions-file-invalid-or-corrupt = Plik nieprawidłowy lub uszkodzony.
actions-filtercram = Filtruj/Zakuwaj
actions-filtered-deck = Filtrowana talia { $num }
actions-flag-1 = Flaga 1
actions-flag-1-red = Flaga 1 (Czerwona)
actions-flag-2 = Flaga 2
actions-flag-2-orange = Flaga 2 (Pomarańcz)
actions-flag-3 = Flaga 3
actions-flag-3-green = Flaga 3 (Zielona)
actions-flag-4 = Flaga 4
actions-flag-4-blue = Flaga 4 (Niebieska)
actions-forgot-card = Zapomniano kartę
actions-frequent-actions = Częste działania
actions-how-many-days-in-the-future = Za ile dni?
actions-invalid-number-of-days = Niepoprawna liczba dni.
actions-leave-without-saving = Wyjść bez zapisywania?
actions-long-press-on-an-item-to = Przyciśnij dłużej na obiekcie, aby dostosować.
actions-mark = Wyróżnij
actions-mark-and-bury = Wyróżnij + Zakop
actions-mark-and-bury-short = W&Zkp
actions-mark-and-suspend = Wyróżnij + Zawieś
actions-mark-and-suspend-short = W&Zaw
actions-marked = Wyróżniona
actions-night-mode-short = Noc
actions-no-current-card = Brak aktualnej karty.
actions-no-load-restore-backup = Twoja kolekcja nie mogła zostać załadowana. Przywróć automatyczną kopię zapasową poprzez ekran ustawień.
actions-not-valid-link = nie wydaje się być prawidłowym linkiem http/https.
actions-note-and-its-cards-deleted = Usunięto notatkę i jej { $count } kart(y)
actions-note-and-its-cards-suspended = Zawieszono notatkę i jej { $count } kart(y)
actions-note-buried = Notatka zakopana
actions-note-marked-and-buried = Notatka wyróżniona i zakopana
actions-nothing-to-undo = Nic do cofnięcia
actions-off = Wył.
actions-pause-audio-short = Pauza
actions-please-tap-the-in-the = Naciśnij „?” w lewym górnym rogu, aby rozpocząć.
actions-processing = Przetwarzanie...
actions-record-voice = Nagraj głos
actions-record-voice-short = Nagraj
actions-replay-audio-short = Odtwórz
actions-reset-card = Resetuj kartę
actions-reset-card-short = Reset.K
actions-revert = Przywróć
actions-review-undone = Powtórka cofnięta
actions-scratchpad = Brudnopis
actions-scratchpad-short = Brud.
actions-scratchpad-size = Rozmiar brudnopisu
actions-scratchpad-size-short = Roz.Brud.
actions-select-deck = Wybierz talię
actions-select-note-type = Wybierz typ notatki
actions-set-due-date = Ustaw termin
actions-set-due-date-short = Ust.Ter
actions-show-answer-short = Pok.Odp.
actions-show-answeranswer-good = Pokaż odp./odp. Dobra
actions-show-answeranswer-good-short = Pok./Dobra
actions-study-options = Opcje nauki
actions-study-options-short = Opc.N
actions-suspend-card-short = Zaw.K
actions-suspend-note-short = Zaw.N
actions-tools = Narzędzia
actions-tools-overlay = Nakładka z narzędziami
actions-top-bar = Górny pasek
actions-unbury-deck = Odkop talię
actions-unbury-deck-short = Odkop
actions-undo = Cofnij
actions-unmarked = Usunięto wyróżnienie
actions-you-can-only-empty-a-filtered = Możesz opróżnić tylko talię filtrowaną.
actions-you-can-only-rebuild-a-filtered = Możesz przebudować tylko talię filtrowaną.
