browsing-append = Dołącz
browsing-append-negated = Dołącz negowane
browsing-card-updated = Aktualizacja karty
browsing-change-flag = Zmień flagę
browsing-clear-flag = Usuń flagę
browsing-column-1 = Kolumna 1
browsing-column-2 = Kolumna 2
browsing-confirm-reset = Potwierdź reset
browsing-dd-selected = %d/%d wybrano
browsing-due-dateorder = Oczekiwanie data/kolejność
browsing-due-reviews = Powtórki oczekujące
browsing-learning-cards = Uczone karty
browsing-no-cards-are-selected = Nie wybrano kart.
browsing-note-created = Utworzenie notatki
browsing-note-updated = Aktualizacja notatki
browsing-note2 = Notatka:
browsing-questionandanswer = Pytanie+Odpowiedź
browsing-repetitions = Powtórzenia
browsing-reset-cards = Resetuj karty
browsing-searching = Wyszukiwanie...
browsing-second-column-19 = Druga kolumna (1->9)
browsing-second-column-91 = Druga kolumna (9->1)
browsing-select-all = Zaz wszys.
browsing-sort = Sortowanie:
browsing-sort-order = Kolejność sortowania
browsing-tag = Etykieta:
