decks-a-deck-must-be-provided = Podaj talię.
decks-a-deck-named-already-exists = Talia o nazwie \"{ $name }\" już istnieje.
decks-a-deck-with-that-name-already = Talia o takiej nazwie już istnieje.
decks-add-deck = Dodaj talię
decks-add-empty-deck = Dodaj pustą talię
decks-addexport = Dodaj/Eksportuj
decks-cannot-delete = Nie można usunąć
decks-card-limit = Limit kart
decks-cards-in-a-filtered-deck-cant = Karty w talii filtrowanej nie mogą być przemieszczane.
decks-custom-steps = Własne kroki
decks-deck-exists = Talia istnieje
decks-deck-label = Talia:
decks-deck-name = Nazwa talii
decks-deck-options = Opcje talii
decks-download-link = Link do pobrania
decks-export-collection = Eksportuj kolekcję
decks-filtered-deck = Talia filtrowana
decks-import-from-itunes = Importuj z iTunes
decks-invalid-deck-name = Niepoprawna nazwa talii.
decks-link-to-apkg-file-to-import = Link do zaimportowania pliku .apkg:
decks-no-matches = Brak dopasowań
decks-return-by-delete = Aby zwrócić wszystkie karty na raz przeciągnij niebieską talię na ekranie z listą talii i usuń ją.
decks-shared-deck-list = Lista gotowych talii
decks-sync = Synchronizacja
decks-synchronize = Synchronizuj
decks-the-default-deck-cannot-be-deleted = Domyślna talia nie może zostać usunięta.
decks-the-provided-deck-does-not-exist = Talia nie istnieje.
decks-the-search-you-provided-did-not = Twoje wyszukiwanie nie odpowiada żadnej karcie.
decks-will-be-returned = Po odpowiedzi na karty powrócą one do talii początkowej.
