deck-options-add-options-group = Dodaj grupę opcji
deck-options-answer-time-cap = Czas na odpowiedź
deck-options-bury-related-new-cards = Zakop powiązane nowe karty
deck-options-bury-related-reviews = Zakop powiązane powtórki
deck-options-defaults = Domyślne
deck-options-delete-options-full-sync = Usunięcie tej grupy opcji uniemożliwi złączenie jakichkolwiek zmian z innych urządzeń podczas następnej synchronizacji. Kontynuować?
deck-options-display-in-order-added = Kolejność dodania
deck-options-display-in-random-order = Kolejność losowa
deck-options-full-sync-required = Wymagana pełna synchronizacja
deck-options-group-name = Nazwa grupy
deck-options-max-new-per-day = Maks. nowych dziennie
deck-options-max-reviews-per-day = Maks. powtórek dziennie
deck-options-new-cards = Nowe karty
deck-options-options-group = Grupa opcji
deck-options-replay-q-audio-in-answer = Powtórz dźwięk w odpowiedzi
deck-options-reset-all-settings-to-defaults = Czy chcesz przywrócić ustawienia domyślne?
deck-options-restore-defaults = Przywróć ustawienia domyślne
deck-options-steps = Kroki
