editing-bold = Pogrubienie
editing-cancel-and-lose-any-unsaved-changes = Anulować i utracić niezapisane zmiany?
editing-cant-edit-original-image-data = Nie można edytować - nie znaleziono źródłowych danych obrazu.
editing-card-returned-to-new-card-queue = Karta zwrócona do kolejki nowych kart.
editing-card-unsuspended = Karta odwieszona
editing-from-camera = Z aparatu
editing-from-file = Z pliku
editing-from-photos = Ze zdjęć
editing-italic = Kursywa
editing-next-cloze = Następna luka
editing-next-field = Następne pole
editing-note-deleted = Notatka usunięta
editing-note-suspended = Notatka zawieszona
editing-note-type-prompt = Typ:
editing-note-unsuspended = Notatka odwieszona
editing-same-cloze = Taka sama luka
editing-the-first-field-must-not-be = Pierwsze pole nie może być puste.
editing-unable-to-obtain-image = Nie można wczytać obrazu
editing-unable-to-read-file = Nie można odczytać pliku
editing-underline = Podkreślenie
editing-unexpected-file-extension = Nieoczekiwane rozszerzenie pliku:
editing-unexpected-rich-text-format-please = Nieoczekiwany wzbogacony format tekstowy (RTF) - spróbuj kopiować & wklejać.
editing-unexpected-status-code = Nieoczekiwany kod statusu:
editing-unsuspend-card = Odwieś kartę
editing-unsuspend-note = Odwieś notatkę
