preferences-about = O aplikacji
preferences-autoplay-in-silent-mode = Odtwarzaj automatycznie w trybie cichym
preferences-always-duck = Wyciszaj dźwięk z innych aplikacji
preferences-answer-keeps-zoom = Odpowiedź zachowuje przybliżenie
preferences-answer-side = Strona z odpowiedzią
preferences-audio-buttons = Przyciski dźwięku
preferences-auto-advance-answer-action = Reakcja odpowiedzi
preferences-auto-advance-answer-seconds = Sekund odpowiedzi
preferences-auto-advance-auto-advance-to-start = Aby automatycznie przechodzić do kolejnej karty, użyj opcji Auto-postęp.
preferences-auto-advance-do-nothing = Nie rób nic
preferences-auto-advance-question-seconds = Sekund pytania
preferences-backup-available-backups = Dostępne kopie zapasowe
preferences-backup-create-now = Utwórz teraz
preferences-backup-maximum-backups = Maks. liczba kopii zapasowych
preferences-backup-minutes-between-backups = Minuty między kopiami zapasowymi
preferences-backup-revert-to-backup = Przywróć kopię zapasową
preferences-backup-revert-to-backup-confirm = Przywrócić do { $backup }? Wszelkie zmiany dokonane od utworzenia tej kopii zapasowej zostaną utracone.
preferences-backup-reverted-to-backup = Przywrócono kopię zapasową.
preferences-bottom-bar-size = Rozmiar dolnego paska
preferences-bottom-center = Dolny środek
preferences-bottom-left = Dolne lewo
preferences-bottom-right = Dolne prawo
preferences-button-d = Przycisk { $num }
preferences-collection-day-starts = Początek dnia
preferences-collection-learn-ahead-minutes = Minut nauki z wyprzedzeniem
preferences-collection-mix = Mieszaj
preferences-collection-new-first = Najpierw nowe
preferences-collection-newreview-order = Kolejność nowych/powtórek
preferences-collection-reviews-first = Najpierw powtórki
preferences-double-tap-prevention = Zapobiegaj podwójnemu dotknięciu
preferences-open-links-externally = Otwieraj linki poza aplikacją
preferences-drawing-screen-ignores-fingers = Ignoruj palce na ekranie rysowania
preferences-feedback-ticks = Znaczniki odpowiedzi
preferences-spread-ticks = Rozmieszczaj znaczniki
preferences-fine = Cienkie
preferences-force-sync-confirm = Wymusić synchronizację w jedną stronę? Wszystkie zmiany dokonane po jednej ze stron zostaną utracone.
preferences-full-sync = Synchronizacja w jedną stronę
preferences-gamepad-button-mapping = Dostosowywanie przycisków
preferences-gamepad-menu-button = Menu
preferences-gamepads = Kontrolery do gier
preferences-gamepad-thumbpad-deadzone = Martwa strefa drążka (%)
preferences-height = Wysokość
preferences-huge = Ogromny
preferences-ignore-fingers = Ignoruj palce
preferences-interrupt-current-audio = Przerywaj odtwarzany dźwięk
preferences-large = Duży
preferences-left = Lewo
# gamepad
preferences-left-shoulder = Lewy bumper
# gamepad
preferences-left-thumbstick-button = Przycisk lewej gałki
# gamepad
preferences-left-trigger = Lewy spust
preferences-logged-in-as = Zalogowano jako:
preferences-long = Długie
preferences-mid-center = Środek
preferences-mid-left = Lewy środek
preferences-mid-right = Prawy środek
preferences-never-type-answer = Nigdy nie wpisuj odpowiedzi
preferences-never-show-scratchpad = Nigdy nie pokazuj brudnopisu
preferences-never-show-scratchpad-enabled = W opcjach wybrano Nigdy nie pokazuj brudnopisu.
preferences-next-times = Czas do następnej powtórki
preferences-normal = Domyślnie
preferences-notifications = Powiadomienia
preferences-notifications-alert-time = Czas alertu
preferences-notifications-alert-when-due = Alert, jeśli powtórki czekają
preferences-notifications-app-icon-shows-due-count = Liczba powtórek na ikonie apki
preferences-notifications-settings-app-enable-notifications = Przejdź do ustawień systemu iOS, znajdź sekcję Anki i włącz powiadomienia, plakietki oraz alerty.
preferences-pen-size = Rozmiar pisma
preferences-question-side = Strona z pytaniem
preferences-remaining-count = Liczba pozostałych kart
preferences-right = Prawo
# gamepad
preferences-right-shoulder = Prawy bumper
# gamepad
preferences-right-thumbstick-button = Przycisk prawej gałki
# gamepad
preferences-right-trigger = Prawy spust
preferences-scratchpad-below-buttons = Brudnopis pod przyciskami
preferences-scratchpad-transparency = Przezroczystość brudnopisu
preferences-scratchpad-transparency-full = Pełna
preferences-scratchpad-transparency-medium = Średnia
preferences-scratchpad-transparency-none = Brak
preferences-scratchpad-transparency-slight = Niewielka
preferences-shake-action = Reakcja na potrząśnięcie
preferences-short = Krótkie
preferences-show-bottom-bar = Pokaż dolny pasek
preferences-show-grid = Pokazuj kratkę
preferences-show-top-bar = Pokaż górny pasek
preferences-small = Mały
preferences-swipe-down = Przesunięcie w dół
preferences-swipe-left = Przesunięcie w lewo
preferences-swipe-right = Przesunięcie w prawo
preferences-swipe-up = Przesunięcie w górę
preferences-swipes = Gesty
preferences-swipes-must-begin-from-the-far = Przesunięcia muszą zaczynać się od lewej lub prawej strony ekranu.
preferences-sync-sounds-images = Synchronizuj dźwięki i obrazy
preferences-syncing = Synchronizacja
preferences-tap-to-sync = Aby aktywować synchronizację, naciśnij przycisk \"Synchronizuj\" na ekranie z listą talii.
preferences-taps = Dotyk
preferences-theme-bar-style = Typ paska
preferences-theme-black = Czarny
preferences-theme-dark-translucent = Ciemny prześwitujący
preferences-theme-force-off = Wymuś wyłączenie
preferences-theme-force-on = Wymuś włączenie
preferences-theme-light-translucent = Jasny prześwitujący
preferences-theme-night-mode-desc = Tryb nocny przyciemnia interfejs i wyświetla karty białą czcionką na czarnym tle.
preferences-theme-night-mode-same-as-system = Zgodnie z systemem
preferences-theme-slate = Popielaty
preferences-thick = Grube
preferences-tools-overlay-button = Przycisk nakładki z narzędziami
preferences-tools-overlay-position = Pozycja nakładki z narzędziami
preferences-top-center = Górny środek
preferences-top-left = Górne lewo
preferences-top-right = Górne prawo
preferences-undo-clears-all = Cofnij usuwa wszystko
preferences-when-answer-shown = Gdy widoczna odpowiedź
preferences-when-question-shown = Gdy widoczne pytanie
preferences-you-have-been-logged-out = Wylogowano.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Maks. rozmiar obrazu (długa krawędź)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Zmień rozmiar przy wklejaniu
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Konwertuj inteligentne cytaty i myślniki
preferences-editing-crop-camera-photos = Przycinaj zdjęcia z aparatu
preferences-loop-video = Zapętl wideo
preferences-show-video-controls = Pokaż przyciski sterowania wideo
preferences-high-quality-video = Wideo wysokiej jakości
preferences-auto-capitalize = Zaczynaj duża literą
preferences-auto-correct = Autokorekta
preferences-strip-hebrew-vowels = Usuń hebrajskie samogłoski
