profiles-a-profile-with-that-name-already = Profil o takiej nazwie już istnieje.
profiles-add-profile = Dodaj profil
profiles-creating-backup = Tworzenie kopii zapasowej...
profiles-finishing-backup = Kończenie kopii zapasowej...
profiles-please-provide-some-text-avoiding-symbols = Wpisz tekst unikając symboli i znaków podkreślenia.
profiles-please-select-another-profile-first = Najpierw wybierz inny profil.
profiles-profile-name = Nazwa profilu
profiles-rename-profile = Zmień nazwę profilu
profiles-unable-to-open-safari-please = Nie można otworzyć Safari - sprawdź ustawienia kontroli rodzicielskiej.
profiles-welcome = Witaj!
