studying-answer-time-elapsed = Czas na odpowiedź minął
studying-auto-advance-starting = Rozpoczynanie Auto-postępu
studying-auto-advance-stopped = Auto-postęp zatrzymany
studying-have-ready-to-study = Masz %@ do przejrzenia.
studying-please-run-empty-cards-on-the = Uruchom Puste karty w wersji komputerowej.
studying-replay-card = Odtwórz kartę
studying-replay-voice = Odtwórz głos
studying-rescheduled-card = Zmieniono plan karty.
studying-type-in-the-answer = Wpisz odpowiedź
