actions-actions = 동작
actions-add-new = 새로 추가
actions-added-to-frequent-actions = 자주 쓰는 동작에 추가됨.
actions-all-actions = 모든 동작
actions-already-in-frequent-actions = 이미 자주 쓰는 동작에 있음.
actions-an-error-occurred = 에러 발생: { $error }
actions-answer-again = 답 다시
actions-answer-easy = 답 쉬움
actions-answer-good = 답 괜찮음
actions-answer-hard = 답 어려움
actions-are-you-sure = 확실합니까?
actions-auto-advance = 자동 다음
actions-bottom-bar = 하단 바
actions-browse = 탐색
actions-card-buried = 카드 숨겨짐
actions-card-suspended = 카드 일시중단됨
actions-card-template = 카드 템플릿
actions-confirm-delete = 삭제 확인
actions-create = 추가
actions-current-audio-minus-5s = 현재 오디오 -5s
actions-current-audio-plus-5s = 현재 오디오 +5s
actions-custom-study-cant-be-used-on = 필터가 적용된 뭉치에서 커스텀 학습을 이용하실 수 없습니다.
actions-deck-statistics = 뭉치 통계
actions-delete-note-and-its-cards = 노트와 관련된 카드 모두 삭제하시겠습니까?
actions-discard-changes = 변경사항 삭제
actions-done = 완료
actions-downloading = 다운로드 중...
actions-drag-here-to-remove = 여기로 끌어놓아 삭제
actions-draw = 그리기
actions-file-invalid-or-corrupt = 손상되었거나 잘못된 파일.
actions-filtercram = 필터/복습
actions-filtered-deck = 필터된 뭉치 { $num }
actions-forgot-card = 카드 잊음
actions-frequent-actions = 자주 사용하는 동작
actions-leave-without-saving = 저장하지 않고 나가시겠습니까?
actions-long-press-on-an-item-to = 아이템을 길게 눌러서 편집하세요.
actions-mark = 표시
actions-mark-and-bury = 표시 + 숨기기
actions-mark-and-suspend = 표시 + 일시중단하기
actions-marked = 표시됨
actions-no-current-card = 현재 카드 없음.
actions-no-load-restore-backup = 컬랙션을 로드할 수 없습니다. 설정 화면에서 자동 백업을 복원해 주세요.
# (http://example.com) does not appear to be...
actions-not-valid-link = 는 유효한 http/https 링크가 아닌 것 같습니다.
actions-note-and-its-cards-deleted = 노트와 속한 카드 { $count }개가 삭제되었습니다.
actions-note-and-its-cards-suspended = 노트와 속한 카드 { $count }개가 일시중단됨.
actions-note-buried = 노트 숨겨짐
actions-note-marked-and-buried = 노트 표시 및 숨겨짐
actions-nothing-to-undo = 실행 취소할 사항 없음
actions-nothing-to-redo = 다시 실행할 사항 없음
actions-off = 끄기
actions-please-tap-the-in-the = 왼쪽 위에 '?'를 눌러 시작하세요.
actions-processing = 처리 중...
actions-record-voice = 음성 녹음
actions-record-voice-menu = 음성 녹음 메뉴
actions-reset-card = 카드 초기화
actions-revert = 되돌리기
actions-review-undone = 리뷰 취소
actions-scratchpad = 스크래치패드
actions-scratchpad-size = 스크래치패드 크기
actions-select-deck = 뭉치 선택
actions-select-note-type = 노트 타입 선택
actions-show-answeranswer-good = 답 보이기/답 좋음
actions-study-options = 학습 옵션
actions-tools = 툴들
actions-tools-overlay = 툴들 오버레이
actions-top-bar = 상단바
actions-unbury-deck = 뭉치 숨김 해제
actions-undo = 실행 취소
actions-unmarked = 표시 해제됨
actions-you-can-only-empty-a-filtered = 필터된 뭉치만 비울 수 있습니다.
actions-you-can-only-rebuild-a-filtered = 필터된 뭉치만 다시 만들 수 있습니다.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = 비어있음
# create a filtered deck
actions-filter-short = 필터
actions-add-short = 추가
actions-answer-again-short = 답.다시
actions-answer-easy-short = 답.쉬움
actions-answer-good-short = 답.좋음
actions-answer-hard-short = 답.어려움
actions-auto-advance-short = 자동 다음.
actions-bottom-bar-short = 하단.바
actions-browse-short = 탐색
actions-bury-card-short = 카드.숨기기
actions-bury-note-short = 노트.숨기기
actions-card-info-short = 카드.정보
actions-card-template-short = 템플릿
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = 커스텀
actions-deck-statistics-short = 뭉치.통계
actions-decks-short = 뭉치들
actions-delete-note-short = 삭제
actions-edit-short = 편집
actions-mark-and-bury-short = 표시및숨김
actions-mark-and-suspend-short = 표시 및 일시중단
actions-mark-short = 표시
actions-night-mode-short = 야간모드
actions-off-short = 끄기
actions-pause-audio-short = 일시중지
actions-rebuild-short = 다시빌드
actions-record-voice-short = 음성녹음
actions-replay-voice-short = 녹음듣기
actions-replay-audio-short = 다시듣기
actions-reset-card-short = 카드리셋
actions-scratchpad-short = 패드
actions-scratchpad-size-short = 작은패드
actions-set-due-date-short = 마감설정
actions-show-answer-short = 답표시
actions-show-answeranswer-good-short = 보이기/답
actions-study-options-short = 학습옵션
actions-suspend-card-short = 카드 일시중단
actions-suspend-note-short = 노트 일시중단
actions-tools-short = 툴들
actions-top-bar-short = 툴바
actions-unbury-deck-short = 뭉치보이기
actions-undo-short = 실행 취소
actions-redo-short = 다시 실행
