decks-a-deck-must-be-provided = 뭉치를 제공해야 합니다.
decks-a-deck-named-already-exists = '{ $name }'을 가진 뭉치가 이미 존재합니다.
decks-a-deck-with-that-name-already = 그 이름을 가진 뭉치가 이미 존재합니다.
decks-add-deck = 뭉치 추가
decks-add-empty-deck = 빈 뭉치 추가
decks-addexport = 추가/내보내기
decks-cannot-delete = 삭제할 수 없음
decks-card-limit = 카드 수 제한
decks-cards-in-a-filtered-deck-cant = 필터가 적용된 뭉치에서 카드를 이동할 수 없습니다.
decks-custom-steps = 커스텀 단계들
decks-deck-exists = 뭉치 존재함
decks-deck-label = 뭉치:
decks-deck-name = 뭉치 이름
decks-deck-options = 뭉치 옵션
decks-download-link = 다운로드 링크
decks-export-collection = 컬랙션 내보내기
decks-filtered-deck = 필터 된 뭉치
decks-import-from-itunes = iTunes에서 가져오기
decks-invalid-deck-name = 뭉치 이름 잘못됨.
decks-link-to-apkg-file-to-import = 가져올 .apkg 파일 선택하기:
decks-no-matches = 일치 사항 없음
decks-return-by-delete = 모든 카드를 한꺼번에 되돌리려면, 뭉치 목록에서 파란색 뭉치를 스와이프한 다음, 삭제하세요.
decks-shared-deck-list = 공유된 뭉치 목록
decks-sync = 동기화
decks-synchronize = 동기화
decks-the-default-deck-cannot-be-deleted = 기본 뭉치는 삭제하실 수 없습니다.
decks-the-provided-deck-does-not-exist = 제공된 뭉치가 존재하지 않습니다.
decks-the-search-you-provided-did-not = 검색이 아무런 카드와 맞지 않았습니다.
decks-will-be-returned = 대답하면서 카드들은 원래 뭉치로 돌아오게 됩니다.
