deck-options-add-options-group = 옵션 그룹 추가
deck-options-answer-time-cap = 응담 시간 제한
deck-options-defaults = 기본값
deck-options-delete-options-full-sync = 이 옵션 그룹을 삭제하면 다음 동기화 시 변경사항이 다른 기기와 합병되는 것을 막습니다. 계속하시겠습니까?
deck-options-display-in-order-added = 추가된 순서로 표시
deck-options-display-in-random-order = 랜덤 순서로 표시
deck-options-full-sync-required = 전체 동기화 필요
deck-options-group-name = 그룹 이름
deck-options-new-cards = 새 카드들
deck-options-reset-all-settings-to-defaults = 모든 설정을 기본값으로 복원하시겠습니까?
deck-options-restore-defaults = 기본값으로 복원
