editing-bold = 볼드체
editing-cancel-and-lose-any-unsaved-changes = 취소하고 저장되지 않은 변경사항을 지울까요?
editing-cant-edit-original-image-data = 편집할 수 없습니다 - 원본 이미지 정보를 찾을 수 없습니다.
editing-card-unsuspended = 카드 보류 해제됨
editing-from-camera = 카메라에서
editing-from-file = 파일에서
editing-from-photos = 사진에서
editing-italic = 기울임체
editing-next-field = 다음 필드
editing-note-deleted = 노트 삭제됨
editing-note-suspended = 노트 보류됨
# (Note) type: 
editing-note-type-prompt = 타입:
editing-note-unsuspended = 노트 보류 해제됨
editing-the-first-field-must-not-be = 첫째 필드는 필수 입력사항입니다.
editing-unable-to-obtain-image = 이미지 가져오기 실패
editing-unable-to-read-file = 파일 읽기 실패
editing-underline = 밑줄
editing-unexpected-file-extension = 알 수 없는 파일 확장자:
editing-unexpected-rich-text-format-please = 알 수 없는 리치 텍스트 포맷 - 복사 및 붙여넣기를 해보세요.
editing-unexpected-status-code = 알 수 없는 상태 코드:
editing-unsuspend-card = 카드 보류 해제
editing-unsuspend-note = 노트 보류 해제
editing-discard-changes-question = 변경사항 삭제?
editing-discard = 삭제
editing-keep-editing = 계속 편집
