importing-delete-imported-file = 가져오기한 파일 삭제?
importing-import-complete = 가져오기 완료.
importing-importing = 가져오는 중...
importing-no-apkg-or-colpkg-files-were = iTunes에서 .apkg 또는 .colpkg 파일들을 찾을 수 없었습니다
importing-overwrite-via-import = 모든 컬렉션을 가져온 파일로 덮어쓰기할까요? 이는 실행취소하실 수 없습니다.
importing-please-choose-a-file = 파일을 선택해주세요.
importing-processed-media-files-d = 처리된 미디어 파일들: { $count }...
importing-replace-collection = 컬렉션 대체하기
importing-file-not-downloaded = iCloud에서 파일을 다운로드 후, 다시 불러와주세요.
