preferences-about = 정보
preferences-answer-side = 답 면
preferences-audio-buttons = 오디오 버튼들
preferences-auto-advance-answer-action = 답 동작
preferences-auto-advance-answer-seconds = 답 초
preferences-auto-advance-auto-advance-to-start = 자동으로 다음으로 넘어가려면, '자동 넘어가기' 동작을 사용하세요.
preferences-auto-advance-do-nothing = 아무것도 하지 않음
preferences-auto-advance-question-seconds = 질문 초
preferences-auto-advance-show-reminder = 남은 시간 보이기
preferences-auto-advance-wait-for-audio = 오디오 기다리기
preferences-backup-available-backups = 사용 가능한 백업들
preferences-backup-create-now = 지금 백업하기
preferences-backup-maximum-backups = 최대 백업
preferences-backup-minutes-between-backups = 다음 백업까지 공백 (분)
preferences-backup-revert-to-backup = 백업으로 복원
preferences-backup-revert-to-backup-confirm = { $backup }으로 복원할까요? 백업을 만든 후의 변경사항은 모두 사라집니다.
preferences-backup-reverted-to-backup = 백업으로 복원했습니다.
preferences-bottom-bar-size = 하단 바 크기
preferences-bottom-center = 하단 중앙
preferences-bottom-left = 하단 왼쪽
preferences-bottom-right = 하단 오른쪽
preferences-button-d = 버튼 { $num }
preferences-collection-mix = 섞기
preferences-collection-new-first = 새로운 것 먼저
preferences-collection-reviews-first = 리뷰 먼저
preferences-double-tap-prevention = 더블 탭 방지
preferences-drawing-screen-ignores-fingers = 그리기 화면에서 손가락 무시하기
preferences-force-sync-confirm = 일방적 동기화를 강제로 진행하시겠습니까? 한 쪽의 모든 변경사항이 사라집니다.
preferences-full-sync = 전체 동기화
preferences-gamepad-button-mapping = 버튼 맵핑
preferences-gamepad-menu-button = 메뉴
preferences-gamepads = 게임패드
preferences-height = 높이
preferences-huge = 큼
preferences-ignore-fingers = 손가락 무시하기
preferences-large = 큼
preferences-left = 왼쪽
preferences-logged-in-as = 현재 로그인 정보:
preferences-long = 길게
preferences-mid-center = 정중앙
preferences-mid-left = 중앙 왼쪽
preferences-mid-right = 중앙 오른쪽
preferences-never-type-answer = 절대로 답 입력하지 않기
preferences-normal = 일반
preferences-notifications = 알림
preferences-notifications-alert-time = 알림 시간
preferences-pen-size = 펜 크기
preferences-question-side = 질문 면
preferences-remaining-count = 남은 갯수
preferences-right = 오른쪽
preferences-scratchpad-transparency-full = 전체
preferences-scratchpad-transparency-medium = 중간
preferences-scratchpad-transparency-none = 없음
preferences-scratchpad-transparency-slight = 살짝
preferences-shake-action = 흔들기 동작
preferences-short = 짧게
preferences-show-bottom-bar = 하단 바 보이기
preferences-show-grid = 그리드 표시하기
preferences-show-top-bar = 상단 바 보이기
preferences-small = 작음
preferences-syncing = 동기화
preferences-tap-to-sync = 동기화를 진행하려면, 뭉치 목록 화면에서 동기화 버튼을 누르시면 됩니다.
preferences-theme = 테마
preferences-theme-bar-style = 바 스타일
preferences-theme-black = 블랙
preferences-theme-dark = 다크
preferences-theme-dark-translucent = 어두운 반투명
preferences-theme-force-off = 강제 끔
preferences-theme-force-on = 강제 켬
preferences-theme-light-translucent = 밝은 반투명
preferences-theme-night-mode-desc = 밤 모드는 인터페이스를 어둡게 하고, 카드를 흰색 글씨를 검은색 배경 위에 표시합니다.
preferences-theme-night-mode-same-as-system = 시스템 따르기
preferences-you-have-been-logged-out = 로그아웃 되었습니다.
preferences-editing = 편집
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = 최대 이미지 크기 (긴 변)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = 붙여넣기할 때 크기 조정
preferences-editing-crop-camera-photos = 카메라 사진 자르기
