profiles-a-profile-with-that-name-already = 그 이름을 가진 프로필이 이미 존재합니다.
profiles-add-profile = 프로필 추가
profiles-creating-backup = 백업하는 중...
profiles-finishing-backup = 백업 완성하는 중...
profiles-please-provide-some-text-avoiding-symbols = 특수문자나 밑줄 문자(_)를 제외한 텍스트를 입력해 주세요.
profiles-please-select-another-profile-first = 먼저 다른 프로필을 선택해 주세요.
profiles-profile-name = 프로필 이름
profiles-rename-profile = 프로필 이름 변경
profiles-unable-to-open-safari-please = Safari를 열 수 없습니다. 보호자 설정을 확인해 주세요.
profiles-welcome = 환영합니다!
