actions-actions = Toiminnot
actions-add-new = Lisää uusi
actions-added-to-frequent-actions = Lisätty usein käytettyihin toimintoihin
actions-all-actions = Kaikki toiminnot
actions-already-in-frequent-actions = Tämä on jo usein käytetyissä toiminnoissa.
actions-an-error-occurred = Tapahtui virhe: { $error }
actions-answer-again = Vastaa uudelleen
actions-answer-easy = Vastaa Helppo
actions-answer-good = Vastaa Hyvä
actions-answer-hard = Vastaa Vaikea
actions-are-you-sure = Oletko varma?
actions-auto-advance = Autom. eteneminen
actions-bottom-bar = Alapalkki
actions-browse = Selaa
actions-card-buried = Kortti piilotettu
actions-card-suspended = Kortti hyllytetty
actions-card-template = Korttimalli
actions-confirm-delete = Vahvista poisto
actions-create = Luo
actions-current-audio-minus-5s = Nykyinen ääni -5s
actions-current-audio-plus-5s = Nykyinen ääni +5s
actions-custom-study-cant-be-used-on = Mukautettua opiskelua ei voi käyttää suodatetussa pakassa.
actions-deck-statistics = Pakan tilastot
actions-delete-note-and-its-cards = Poistetaanko muistiinpano ja sen kortit?
actions-discard-changes = Hylkää muutokset
actions-done = Valmis
actions-downloading = Ladataan...
actions-drag-here-to-remove = Vedä tänne poistaaksesi
actions-draw = Piirrä
actions-file-invalid-or-corrupt = Tiedosto on virheellinen tai korruptoitunut.
actions-filtercram = Suodata/Pänttää
actions-filtered-deck = Suodatettu pakka { $num }
actions-forgot-card = Unohda kortti
actions-frequent-actions = Usein käytetyt toiminnot
actions-leave-without-saving = Poistutaanko tallentamatta?
actions-long-press-on-an-item-to = Käytä pitkää painallusta mukauttaaksesi.
actions-mark = Merkitse
actions-mark-and-bury = Merkitse + Piilota
actions-mark-and-suspend = Merkitse + Hyllytä
actions-marked = Merkitty
actions-no-current-card = Ei nykyistä korttia.
actions-no-load-restore-backup = Kokoelmaasi ei voitu ladata. Palauta kokoelma automaattisesta varmuuskopiosta asetusnäkymän kautta.
# (http://example.com) does not appear to be...
actions-not-valid-link = ei näytä olevan kelvollinen http/https-linkki.
actions-note-and-its-cards-deleted = Muistiinpano ja sen { $count } kortti(a) poistettu
actions-note-and-its-cards-suspended = Muistiinpano ja sen { $count } kortti(a) hyllytetty
actions-note-buried = Muistiinpano piilotettu
actions-note-marked-and-buried = Muistiinpano merkitty ja piilotettu
actions-off = Pois
actions-please-tap-the-in-the = Aloita napauttamalla vasemmassa yläkulmassa olevaa '?' -painiketta.
actions-processing = Käsitellään...
actions-record-voice = Äänitä
actions-record-voice-menu = Äänitysvalikko
actions-reset-card = Nollaa kortti
actions-revert = Palauta
actions-review-undone = Kertaus peruttu
actions-scratchpad = Raaputusalusta
actions-scratchpad-size = Raaputusalustan koko
actions-select-deck = Valitse pakka
actions-select-note-type = Valitse muistiinpanotyyppi
actions-show-answeranswer-good = Näytä vastaus/Vastaa Hyvä
actions-study-options = Opiskeluvalinnat
actions-tools = Työkalut
actions-tools-overlay = Kelluva työkalupainike
actions-top-bar = Yläpalkki
actions-unbury-deck = Poista pakan piilotus
actions-undo = Peru
actions-unmarked = Merkitsemätön
actions-you-can-only-empty-a-filtered = Voit tyhjentää vain suodatetun pakan.
actions-you-can-only-rebuild-a-filtered = Voit rakentaa uudelleen vain suodatetun pakan.
actions-scroll-up = Vieritä ylös
actions-scroll-down = Vieritä alas

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Tyhjää
# create a filtered deck
actions-filter-short = Suod.
actions-add-short = Lisää
actions-answer-again-short = Uudest.
actions-answer-easy-short = Helppo
actions-answer-good-short = Hyvä
actions-answer-hard-short = Vaikea
actions-auto-advance-short = Aut.etnm.
actions-bottom-bar-short = Alaplk.
actions-browse-short = Selaa
actions-bury-card-short = Piil.K
actions-bury-note-short = Piil.M
actions-card-info-short = K.info
actions-card-template-short = Malli
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Mukaut.
actions-deck-statistics-short = P.tlst
actions-decks-short = Pakat
actions-delete-note-short = Poista
actions-edit-short = Muokkaa
actions-mark-and-bury-short = M&Piil
actions-mark-and-suspend-short = M&Hyl
actions-mark-short = Merk.
actions-night-mode-short = Tumma
actions-off-short = Pois
actions-pause-audio-short = Tauko
actions-rebuild-short = Rk.uud.
actions-record-voice-short = Äänitä
actions-replay-voice-short = T.ääni
actions-replay-audio-short = Toista
actions-reset-card-short = Noll.K
actions-scratchpad-short = Raap.
actions-scratchpad-size-short = Raap.K
actions-set-due-date-short = As.eräp
actions-show-answer-short = Näyt.V
actions-show-answeranswer-good-short = Näytä/Hyvä
actions-study-options-short = Op.val
actions-suspend-card-short = Hyl.K
actions-suspend-note-short = Hyl.M
actions-tools-short = Työk.
actions-top-bar-short = Yläplk.
actions-unbury-deck-short = PPiil
actions-undo-short = Peru
actions-redo-short = Tee uud.
actions-scroll-up-short = Ylös
actions-scroll-down-short = Alas
