decks-a-deck-must-be-provided = Pakka on annettava.
decks-a-deck-named-already-exists = Pakka nimeltä '{ $name }' on jo olemassa.
decks-a-deck-with-that-name-already = Tällä nimellä oleva pakka on jo olemassa.
decks-add-deck = Lisää pakka
decks-add-empty-deck = Lisää tyhjä pakka
decks-addexport = Lisää/Vie
decks-cannot-delete = Ei voida poistaa
decks-card-limit = Korttien raja
decks-cards-in-a-filtered-deck-cant = Suodatetun pakan kortteja ei voi siirtää.
decks-custom-steps = Mukautetut askeleet
decks-deck-exists = Pakka on olemassa
decks-deck-label = Pakka:
decks-deck-name = Pakan nimi
decks-deck-options = Pakan valinnat
decks-download-link = Latauslinkki
decks-export-collection = Vie kokoelma
decks-filtered-deck = Suodatettu pakka
decks-import-from-itunes = Tuo iTunesista
decks-invalid-deck-name = Virheellinen pakan nimi.
decks-link-to-apkg-file-to-import = Linkki tuotavaan .apkg-tiedostoon:
decks-no-matches = Ei hakutuloksia
decks-return-by-delete = Jos haluat palauttaa kaikki kortit kerralla, pyyhkäise sinistä pakkaa pakkaluettelossa ja poista se.
decks-shared-deck-list = Jaettujen pakkojen lista
decks-sync = Synkronoi
decks-synchronize = Synkronoi
decks-the-default-deck-cannot-be-deleted = Oletuspakkaa ei voi poistaa.
decks-the-provided-deck-does-not-exist = Annettua pakkaa ei ole olemassa.
decks-the-search-you-provided-did-not = Antamallasi haulla ei löytynyt yhtään korttia.
decks-will-be-returned = Kortit palautetaan alkuperäiseen pakkaan, kun vastaat niihin.
