deck-options-add-options-group = Lisää valintaryhmä
deck-options-answer-time-cap = Vastauksen enimmäisaika
deck-options-bury-related-new-cards = Piilota liittyvät uudet kortit
deck-options-bury-related-reviews = Piilota liittyvät kertaukset
deck-options-defaults = Oletukset
deck-options-delete-options-full-sync = Tämän valintaryhmän poistaminen estää muutosten yhdistämisen muista laitteista seuraavan synkronoinnin yhteydessä. Jatketaanko?
deck-options-display-in-order-added = Näytä lisäysjärjestyksessä
deck-options-display-in-random-order = Näytä satunnaisessa järjestyksessä
deck-options-full-sync-required = Täysi synkronointi vaaditaan
deck-options-group-name = Ryhmän nimi
deck-options-max-new-per-day = Uusien päivittäinen enimmäismäärä
deck-options-max-reviews-per-day = Kerrattavien päivittäinen enimmäismäärä
deck-options-new-cards = Uusia kortteja
deck-options-options-group = Valintaryhmä
deck-options-replay-q-audio-in-answer = Toista kys. ääni vastauksessa
deck-options-reset-all-settings-to-defaults = Nollataanko kaikki asetukset oletusasetuksiin?
deck-options-restore-defaults = Palauta oletukset
deck-options-steps = Askeleet
