preferences-about = Tietoja
preferences-always-duck-and-ignore-mute = Vaimenna tausta, älä huomioi mykistystä
preferences-answer-keeps-zoom = Vastaus säilyttää zoomauksen
preferences-answer-side = Vastauspuoli
preferences-audio-buttons = Äänipainikkeet
preferences-auto-advance-answer-action = Vastaustoiminto
preferences-auto-advance-answer-seconds = Vastauksen näyttöaika (sekunteja)
preferences-auto-advance-auto-advance-to-start = Jos haluat aloittaa automaattisen etenemisen, käytä toimintoa 'Automaattinen eteneminen'.
preferences-auto-advance-do-nothing = Älä tee mitään
preferences-auto-advance-question-seconds = Kysymyksen näyttöaika (sekunteja)
preferences-auto-advance-show-reminder = Näytä muistutus
preferences-auto-advance-wait-for-audio = Odota äänen päättymistä
preferences-backup-available-backups = Saatavilla olevat varmuuskopiot
preferences-backup-create-now = Luo varmuuskopio nyt
preferences-backup-maximum-backups = Varmuuskopoiden enimmäismäärä
preferences-backup-minutes-between-backups = Minuutteja varmuuskopoiden välillä
preferences-backup-revert-to-backup = Palauta varmuuskopio
preferences-backup-revert-to-backup-confirm = Palautetaanko { $backup }? Kaikki varmuuskopioinnin jälkeen tehdyt muutokset menetetään.
preferences-backup-reverted-to-backup = Varmuuskopio palautettiin.
preferences-bottom-bar-size = Alapalkin koko
preferences-bottom-center = Alhaalla keskellä
preferences-bottom-left = Alhaalla vasemmalla
preferences-bottom-right = Alhaalla oikealla
preferences-button-d = Painike { $num }
preferences-collection-day-starts = Päivä alkaa
preferences-collection-learn-ahead-minutes = Ennalta opiskelun minuuttimäärä
preferences-collection-mix = Sekoita
preferences-collection-new-first = Uudet ensin
preferences-collection-newreview-order = Uusien/kerrattavien järjestys
preferences-collection-reviews-first = Kerrattavat ensin
preferences-double-tap-prevention = Kaksoisnapautuksen esto
preferences-drawing-screen-ignores-fingers = Piirustusnäkymä ohittaa sormista tulevan syötteen
preferences-feedback-ticks = Näytä oikein-merkki palautteena
preferences-fine = Ohut
preferences-force-sync-confirm = Pakotetaanko synkronointi yhteen suuntaan? Kaikki toisen puolen muutokset menetetään.
preferences-full-sync = Täysi synkronointi
preferences-gamepad-button-mapping = Painikkeiden määritykset
preferences-gamepad-menu-button = Valikko
preferences-gamepads = Peliohjaimet
preferences-height = Korkeus
preferences-huge = Jätti
preferences-ignore-fingers = Ohita syöte sormista
preferences-interrupt-current-audio = Keskeytä nykyinen ääni
preferences-large = Iso
preferences-left = Vasen
# gamepad
preferences-left-shoulder = Vasen olkapainike
# gamepad
preferences-left-thumbstick-button = Vasemman ohjainsauvan painike
# gamepad
preferences-left-trigger = Vasen liipasin
preferences-logged-in-as = Kirjauduttu:
preferences-long = Pitkä
preferences-mid-center = Keskellä
preferences-mid-left = Keskellä vasemmalla
preferences-mid-right = Keskellä oikealla
preferences-never-type-answer = Älä pyydä kirjoittamaan vastausta
preferences-never-show-scratchpad = Älä näytä raaputusalustaa
preferences-never-show-scratchpad-enabled = "Älä näytä raaputusalustaa" on kytketty päälle asetuksissa.
preferences-next-times = Seuraavat kerrat
preferences-normal = Normaali
preferences-notifications = Ilmoitukset
preferences-notifications-alert-time = Ilmoituksen ajankohta
preferences-notifications-alert-when-due = Ilmoita erääntyvistä
preferences-notifications-app-icon-shows-due-count = Erääntyneiden määrä kuvakkeessa
preferences-notifications-settings-app-enable-notifications = Mene iOS:n Asetukset-sovellukseen, etsi Anki-osio ja ota ilmoitukset, merkit ja ilmoitusviestit käyttöön.
preferences-pen-size = Kynän koko
preferences-question-side = Kysymyspuoli
preferences-remaining-count = Jäljellä olevien määrä
preferences-right = Oikea
# gamepad
preferences-right-shoulder = Oikea olkapainike
# gamepad
preferences-right-thumbstick-button = Oikean ohjainsauvan painike
# gamepad
preferences-right-trigger = Oikea liipasin
preferences-scratchpad-below-buttons = Painikkeet alustan alla
preferences-scratchpad-transparency = Raaputusalustan läpinäkyvyys
preferences-scratchpad-transparency-full = Kokonaan
preferences-scratchpad-transparency-medium = Puoliksi
preferences-scratchpad-transparency-none = Ei läpinäkyvä
preferences-scratchpad-transparency-slight = Vähäinen
preferences-shake-action = Ravistuksen toiminto
preferences-short = Lyhyt
preferences-show-bottom-bar = Näytä alapalkki
preferences-show-grid = Näytä ruudukko
preferences-show-top-bar = Näytä yläpalkki
preferences-small = Pieni
preferences-swipe-down = Pyyhkäisy alas
preferences-swipe-left = Pyyhkäisy vasemmalle
preferences-swipe-right = Pyyhkäisy oikealle
preferences-swipe-up = Pyyhkäisy ylös
preferences-swipes = Pyyhkäisyt
preferences-swipes-must-begin-from-the-far = Pyyhkäisyjen on alettava näytön vasemmasta tai oikeasta reunasta.
preferences-sync-sounds-images = Synkronoi äänet ja kuvat
preferences-syncing = Synkronointi
preferences-tap-to-sync = Voit aktivoida synkronoinnin napauttamalla synkronoi-painiketta pakkojen luettelonäkymässä.
preferences-taps = Napautukset
preferences-theme = Teema
preferences-theme-bar-style = Palkin ulkoasu
preferences-theme-black = Musta
preferences-theme-dark-translucent = Tumma ja läpikuultava
preferences-theme-force-off = Aina pois
preferences-theme-force-on = Aina päällä
preferences-theme-light-translucent = Vaalea ja läpikuultava
preferences-theme-night-mode-desc = Tummassa tilassa käyttöliittymä on tumma ja korttien teksti on valkoista mustalla pohjalla.
preferences-theme-night-mode-same-as-system = Järjestelmän asetus
preferences-theme-slate = Liuskekivi
preferences-thick = Paksu
preferences-tools-overlay-button = Kelluva työkalupainike
preferences-tools-overlay-position = Työkalupainikkeen sijainti
preferences-top-center = Ylhäällä keskellä
preferences-top-left = Ylhäällä vasemmalla
preferences-top-right = Ylhäällä oikealla
preferences-undo-clears-all = Peruminen poistaa kaiken
preferences-when-answer-shown = Kun vastaus näytetään
preferences-when-question-shown = Kun kysymys näytetään
preferences-you-have-been-logged-out = Sinut on kirjattu ulos.
preferences-editing = Muokkaus
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Kuvan enimmäiskoko (pisin sivu)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Muuta kokoa liitettäessä
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Muunna älykkäät lainausmerkit ja viivat
preferences-editing-crop-camera-photos = Rajaa kameralla otettuja kuvia
