profiles-a-profile-with-that-name-already = Tällä nimellä oleva profiili on jo olemassa.
profiles-add-profile = Lisää profiili
profiles-finishing-backup = Viimeistellään varmuuskopiointia...
profiles-please-provide-some-text-avoiding-symbols = Kirjoita tekstiä, mutta vältä erikoismerkkejä ja alaviivoja.
profiles-please-select-another-profile-first = Valitse ensin toinen profiili.
profiles-profile-name = Profiilin nimi
profiles-rename-profile = Nimeä profiili uudelleen
profiles-unable-to-open-safari-please = Safarin avaaminen ei onnistunut - tarkista lapsilukko.
profiles-welcome = Tervetuloa!
