actions-actions = 操作
actions-add-new = 新規追加
actions-added-to-frequent-actions = よく使用するアクションに追加しました。
actions-all-actions = すべてのアクション
actions-already-in-frequent-actions = すでによく使用するアクションに登録されています。
actions-an-error-occurred = エラーが発生しました：{ $error }
actions-answer-again = 回答 (もう一度)
actions-answer-easy = 回答 (簡単)
actions-answer-good = 回答 (正解)
actions-answer-hard = 回答 (難しい)
actions-are-you-sure = 本当によろしいですか？
actions-auto-advance = カードの自動送り
actions-auto-advance-short = 自動送
actions-bottom-bar = ボトムバー
actions-bottom-bar-short = ボトム
actions-browse = 検索
actions-bury-card-short = カ延期
actions-bury-note-short = ノ延期
actions-card-buried = カードを延期しました
actions-card-info = カード情報
actions-card-info-short = カ情報
actions-card-suspended = カードを保留しました
actions-card-template = カード書式
actions-confirm-delete = 削除の確認
actions-create = 作成
actions-current-audio-minus-5s = 音声-5秒
actions-current-audio-minus-5s-short = -5秒
actions-current-audio-plus-5s = 音声+5秒
actions-current-audio-plus-5s-short = +5秒
actions-custom-study-cant-be-used-on = カスタム学習機能をフィルタデッキで使用することはできません。
actions-custom-study-short = カスタム
actions-deck-statistics = デッキの統計
actions-deck-statistics-short = 統計
actions-delete-note-and-its-cards = ノートとそれに関連するカードを削除しますか？
actions-delete-note-short = 削除
actions-discard-changes = 変更を破棄
actions-done = 完了
actions-downloading = ダウンロード中...
actions-drag-here-to-remove = 除去するにはここにドラッグ
actions-draw = 手書き
actions-file-invalid-or-corrupt = 無効なファイルです。
actions-filtercram = フィルタ/詰め込み
actions-filtered-deck = フィルタデッキ { $num }
actions-flag-1 = フラグ 1
actions-flag-1-red = フラグ 1 (赤)
actions-flag-2 = フラグ 2
actions-flag-2-orange = フラグ 2 (橙)
actions-flag-3 = フラグ 3
actions-flag-3-green = フラグ 3 (緑)
actions-flag-4 = フラグ 4
actions-flag-4-blue = フラグ 4 (青)
actions-forgot-card = カードをリセットしました
actions-frequent-actions = よく使用するアクション
actions-how-many-days-in-the-future = 何日後に学習しますか？
actions-invalid-number-of-days = 無効な日数です。
actions-leave-without-saving = 保存せずに終了しますか？
actions-long-press-on-an-item-to = カストマイズしたいアイテムを長押し
actions-mark = マークする
actions-mark-and-bury = マーク＋延期
actions-mark-and-bury-short = マ&延
actions-mark-and-suspend = マーク＋保留
actions-mark-and-suspend-short = マ&保
actions-marked = マークしました
actions-night-mode-short = 夜間
actions-no-current-card = カードがありません。
actions-no-load-restore-backup = コレクションを読み込めませんでした。「設定」→「バックアップ」より、コレクションを復元してください。
actions-not-valid-link = は、有効なhttp/httpsリンクではありません。
actions-note-and-its-cards-deleted = ノートと関連のカード{ $count }枚を削除しました
actions-note-and-its-cards-suspended = ノートと関連のカード{ $count }枚を保留しました
actions-note-buried = ノートを延期しました
actions-note-marked-and-buried = ノートをマーク＋延期しました
actions-nothing-to-undo = 元に戻すものがありません
actions-off = オフ
actions-pause-audio-short = 停止
actions-please-tap-the-in-the = 左上の？アイコンをタップするとAnkiMobileのウェブサイトを開きます。
actions-processing = 処理中...
actions-record-voice = 声を録音する
actions-record-voice-short = 録音
actions-replay-audio-short = 再生
actions-reset-card = カードをリセット
actions-reset-card-short = カ初期
actions-revert = 元に戻す
actions-review-undone = カードを戻しました
actions-scratchpad = 手書きパッド
actions-scratchpad-short = 手書
actions-scratchpad-size = 手書きサイズ
actions-scratchpad-size-short = 手書サ
actions-select-deck = デッキを選択
actions-select-note-type = ノートタイプを選択
actions-set-due-date = 期日設定
actions-set-due-date-short = 期日
actions-show-answer-short = 答表示
actions-show-answeranswer-good = 答表示/正解
actions-show-answeranswer-good-short = 表示/正解
actions-study-options = 学習設定
actions-study-options-short = 学習
actions-suspend-card-short = カ保留
actions-suspend-note-short = ノ保留
actions-tools = ツール
actions-tools-overlay = ツールアイコン
actions-top-bar = トップバー
actions-unbury-deck = デッキ内延期解除
actions-unbury-deck-short = 延解除
actions-undo = 元に戻す
actions-unmarked = マークを解除しました
actions-you-can-only-empty-a-filtered = 空にできるのはフィルタデッキのみです。
actions-you-can-only-rebuild-a-filtered = 再作成できるのはフィルタデッキのみです。
