browsing-append = 条件を追加
browsing-append-negated = 否定条件を追加
browsing-card-updated = カード上書き日
browsing-change-flag = フラグを変更
browsing-clear-flag = フラグを解除
browsing-column-1 = 列 1
browsing-column-2 = 列 2
browsing-confirm-reset = リセットの確認
browsing-dd-selected = { $part }/{ $total }件選択
browsing-due-dateorder = 学習日/順序
browsing-due-reviews = 復習期日のカード
browsing-learning-cards = 学習中カード
browsing-no-cards-are-selected = カードが選択されていません。
browsing-note-created = ノート作成日
browsing-note-updated = ノート上書き日
browsing-note2 = ノート：
browsing-questionandanswer = 問題＋答え
browsing-repetitions = 学習頻度
browsing-reset-cards = カードをリセット
browsing-searching = 検索中...
browsing-second-column-19 = コラム2 (1->9)
browsing-second-column-91 = コラム2 (9->1)
browsing-select-all = すべて選択
browsing-sort = ソート：
browsing-sort-order = ソート順
browsing-tag = タグ：
