deck-options-add-options-group = 設定グループを追加
deck-options-answer-time-cap = 回答時間の上限 (秒)
deck-options-bury-related-new-cards = 関連する新規カードを延期
deck-options-bury-related-reviews = 関連する復習カードを延期
deck-options-defaults = デフォルト
deck-options-delete-options-full-sync = この設定グループを削除すると、次に同期をする際、他のデバイス上で変更したことをご使用中のデバイスに統合できません。それでも削除しますか？
deck-options-display-in-order-added = 追加順にカードを表示
deck-options-display-in-random-order = ランダムにカードを表示
deck-options-full-sync-required = 完全同期が必要です
deck-options-group-name = グループ名
deck-options-max-new-per-day = 新規カードの一日の上限
deck-options-max-reviews-per-day = 復習カードの一日の上限
deck-options-new-cards = 新規カード
deck-options-options-group = 設定グループ
deck-options-replay-q-audio-in-answer = 解答表示時に質問音声再生
deck-options-reset-all-settings-to-defaults = すべての設定をデフォルトに戻しますか？
deck-options-restore-defaults = 初期設定に戻す
deck-options-steps = 習得ステップ (分)
