exporting-collection-saved-to-itunes = コレクションをiTunesに保存しました。
exporting-export-to-itunes = iTunes にエクスポート
exporting-export-to-share-sheet = 共有シートにエクスポート
exporting-exporting = エクスポート中...
exporting-include-media2 = メディアファイルを含める
exporting-media-files-exported-d = メディアファイルのエクスポート：{ $count }...
