preferences-about = Anki について
preferences-autoplay-in-silent-mode = 消音モードでも音声を自動再生する
preferences-always-duck = バックグラウンド音声の音量を常に下げる
preferences-answer-keeps-zoom = 解答表示時もズームを維持する
preferences-answer-side = 解答面
preferences-audio-buttons = 音声の再生ボタン
preferences-auto-advance-answer-action = 解答表示後の動作
preferences-auto-advance-answer-seconds = 解答の表示時間 (秒)
preferences-auto-advance-auto-advance-to-start = 自動進行を開始するには、[自動進行] を実行してください。
preferences-auto-advance-do-nothing = 何もしない
preferences-auto-advance-question-seconds = 問題の表示時間 (秒)
preferences-backup-available-backups = 利用可能なバックアップ
preferences-backup-create-now = 今すぐ作成
preferences-backup-maximum-backups = 保持するバックアップ数
preferences-backup-minutes-between-backups = バックアップ間隔 (分)
preferences-backup-revert-to-backup = バックアップへ戻す
preferences-backup-revert-to-backup-confirm = バックアップ “{ $backup }” へ戻しますか？バックアップ作成後の変更は失われます。
preferences-backup-reverted-to-backup = バックアップへ戻しました。
preferences-bottom-bar-size = 下部バーのサイズ
preferences-bottom-center = 下中央
preferences-bottom-left = 左下
preferences-bottom-right = 右下
preferences-button-d = ボタン { $num }
preferences-collection-day-starts = 翌日分のカードに切り替わる時刻
preferences-collection-learn-ahead-minutes = 学習カードの先取り時間 (分)
preferences-collection-mix = 復習カードと混ぜる
preferences-collection-new-first = 復習カードの前
preferences-collection-newreview-order = 新規カードと復習カードの表示順
preferences-collection-reviews-first = 復習カードの後
preferences-double-tap-prevention = ダブルタップの誤操作防止
preferences-open-links-externally = リンクを外部アプリで開く
preferences-drawing-screen-ignores-fingers = 描画画面で指の入力を無視する
preferences-feedback-ticks = 解答時に確認マークを表示する
preferences-spread-ticks = 確認マークを解答ボタンの位置に表示する
preferences-fine = 細い
preferences-force-sync-confirm = 一方向同期を強制しますか？片方の変更はすべて失われます。
preferences-full-sync = 一方向同期
preferences-gamepad-button-mapping = ボタン割り当て
preferences-gamepad-menu-button = メニュー
preferences-gamepads = ゲームパッド
preferences-gamepad-thumbpad-deadzone = スティックのデッドゾーン (%)
preferences-height = 高さ
preferences-huge = 最大
preferences-ignore-fingers = 指の入力を無視する
preferences-interrupt-current-audio = 解答時に再生中の音声を停止する
preferences-large = 大
preferences-left = 左
# gamepad
preferences-left-shoulder = 左ショルダー
# gamepad
preferences-left-thumbstick-button = 左スティック
# gamepad
preferences-left-trigger = 左トリガー
preferences-logged-in-as = ログイン中のユーザー:
preferences-long = 長い
preferences-mid-center = 中央
preferences-mid-left = 左中央
preferences-mid-right = 右中央
preferences-never-type-answer = 文字入力で解答しない
preferences-never-show-scratchpad = 手書きパッドを表示しない
preferences-never-show-scratchpad-enabled = 設定で「手書きパッドを表示しない」がオンになっています。
preferences-next-times = 次回の学習までの間隔
preferences-normal = 標準
preferences-notifications = 通知
preferences-notifications-alert-time = 通知時刻
preferences-notifications-alert-when-due = 定時に、課題があれば枚数を通知
preferences-notifications-app-icon-shows-due-count = アプリのアイコンに課題枚数を表示
preferences-notifications-settings-app-enable-notifications = iOS設定アプリからAnkiの項目へ進み、通知、バッジ、アラートを有効にしてください。
preferences-pen-size = ペンの太さ
preferences-question-side = 質問側
preferences-remaining-count = 残りのカード枚数
preferences-right = 右側
# gamepad
preferences-right-shoulder = 右ショルダー
# gamepad
preferences-right-thumbstick-button = 右スティック
# gamepad
preferences-right-trigger = 右トリガー
preferences-scratchpad-below-buttons = 手書きパッドをボトムバーの下に表示
preferences-scratchpad-transparency = 手書きパッドの透明度
preferences-scratchpad-transparency-full = 完全透明
preferences-scratchpad-transparency-medium = 透明（中）
preferences-scratchpad-transparency-none = 不透明
preferences-scratchpad-transparency-slight = 透明（少）
preferences-shake-action = シェイクアクション
preferences-short = 短い
preferences-show-bottom-bar = ボトムバーを表示
preferences-show-grid = グリッドを表示
preferences-show-top-bar = トップバーを表示
preferences-small = 小
preferences-swipe-down = 下にスワイプ
preferences-swipe-left = 左にスワイプ
preferences-swipe-right = 右にスワイプ
preferences-swipe-up = 上にスワイプ
preferences-swipes = スワイプ
preferences-swipes-must-begin-from-the-far = スワイプはスクリーンの左端・右端から行ってください。
preferences-sync-sounds-images = 音声と画像を同期
preferences-syncing = 同期
preferences-tap-to-sync = 同期を実行するには、デッキリスト画面の「同期」をタップしてください。
preferences-taps = タップ
preferences-theme-bar-style = バーの外観
preferences-theme-black = ブラック
preferences-theme-dark-translucent = ダーク & 半透明
preferences-theme-force-off = 強制オフ
preferences-theme-force-on = 強制オン
preferences-theme-light-translucent = ライト & 半透明
preferences-theme-night-mode-desc = ナイトモード（夜間モード）を使用すると、インターフェースが暗くなり、カードは黒い背景に白文字で表示されます。
preferences-theme-night-mode-same-as-system = システムに従う
preferences-theme-slate = グレー
preferences-thick = 太い
preferences-tools-overlay-button = ツールアイコンを表示
preferences-tools-overlay-position = ツールアイコンの配置
preferences-top-center = 中央上
preferences-top-left = 左上
preferences-top-right = 右上
preferences-undo-clears-all = 「元に戻す」アイコンですべて消去
preferences-when-answer-shown = 解答側も表示されているとき
preferences-when-question-shown = 質問側だけが表示されているとき
preferences-you-have-been-logged-out = ログアウトしました
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = 最大画像サイズ（長辺）
# whether to shrink images when pasting
preferences-editing-resize-on-paste = 貼り付けの際にリサイズ
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = スマート引用符とダッシュを自動変換
preferences-editing-crop-camera-photos = カメラで撮影した写真をクロップ（切り出し）
preferences-loop-video = 動画をループ再生
preferences-show-video-controls = 動画再生コントローラーを表示
preferences-high-quality-video = 動画を高画質で録画する
preferences-auto-capitalize = 英字入力時に文頭を自動で大文字にする
preferences-auto-correct = 自動修正
preferences-strip-hebrew-vowels = ヘブライ語の母音記号を除去する
