preferences-about = Ankiについて
preferences-always-duck-and-ignore-mute = BGM調整＋ミュート無視
preferences-answer-keeps-zoom = 答えのズームを保つ
preferences-answer-side = 答え側
preferences-audio-buttons = 音声ボタン
preferences-auto-advance-answer-action = 回答アクション
preferences-auto-advance-answer-seconds = 答えを表示する時間 (秒)
preferences-auto-advance-auto-advance-to-start = デッキ内の「カードの自動送り」アクションで、カードの自動送りが開始されます。
preferences-auto-advance-do-nothing = 何もしない
preferences-auto-advance-question-seconds = 問題を表示する時間 (秒)
preferences-auto-advance-show-reminder = リマインダーを表示
preferences-auto-advance-wait-for-audio = 音声再生終了を待つ
preferences-backup-available-backups = 保存中のバックアップ
preferences-backup-create-now = 今すぐ作成
preferences-backup-maximum-backups = バックアップの上限
preferences-backup-minutes-between-backups = バックアップの間隔 (分)
preferences-backup-revert-to-backup = バックアップの状態に戻す
preferences-backup-revert-to-backup-confirm = { $backup }の状態に戻しますか？それ以降に変更した内容はすべて失われますがよろしいですか？
preferences-backup-reverted-to-backup = バックアップの状態を復元しました。
preferences-bottom-bar-size = ボトムバーのサイズ
preferences-bottom-center = 中央下
preferences-bottom-left = 左下
preferences-bottom-right = 右下
preferences-button-d = ボタン{ $num }
preferences-collection-day-starts = 一日の始まり時間
preferences-collection-learn-ahead-minutes = 習得学習の先取り (分)
preferences-collection-mix = ミックス
preferences-collection-new-first = 新規カードが先
preferences-collection-newreview-order = 新規/復習カードの順序
preferences-collection-reviews-first = 復習カードが先
preferences-double-tap-prevention = ダブルタップ防止
preferences-drawing-screen-ignores-fingers = 手書きスクリーンの指タップを無視
preferences-feedback-ticks = 回答フィードバック
preferences-fine = 細い
preferences-force-sync-confirm = 一方の状態をもう片方に上書きしますか？実行した場合、片方で行われた変更はすべて失われます。
preferences-full-sync = 完全同期
preferences-gamepad-button-mapping = ボタン配置
preferences-gamepad-menu-button = メニュー
preferences-gamepads = ゲームパッド
preferences-height = パッドの大きさ
preferences-huge = 特大
preferences-ignore-fingers = 指タップを無視
preferences-interrupt-current-audio = 再生中の音声を中断する
preferences-large = 大
preferences-left = 左寄せ
# gamepad
preferences-left-shoulder = 左ショルダー
# gamepad
preferences-left-thumbstick-button = 左スティック
# gamepad
preferences-left-trigger = 左トリガー
preferences-logged-in-as = ログイン中のユーザ名:
preferences-long = 長い
preferences-mid-center = 中央
preferences-mid-left = 左中央
preferences-mid-right = 右中央
preferences-never-type-answer = 答えをタイプしない
preferences-never-show-scratchpad = スクラッチパッドを表示しない
preferences-never-show-scratchpad-enabled = 設定画面で「スクラッチパッドを表示しない」がオンになっています。
preferences-next-times = 次回のカード表示
preferences-normal = 標準
preferences-notifications = 通知
preferences-notifications-alert-time = 通知の設定時間
preferences-notifications-alert-when-due = 期日に通知する
preferences-notifications-app-icon-shows-due-count = アイコンにカード数を表示
preferences-notifications-settings-app-enable-notifications = iOS設定アプリからAnkiの項目へ進み、通知、バッジ、アラートを有効にしてください。
preferences-pen-size = ペンの太さ
preferences-question-side = 問題側
preferences-remaining-count = 残りのカード数
preferences-right = 右寄せ
# gamepad
preferences-right-shoulder = 右ショルダー
# gamepad
preferences-right-thumbstick-button = 右スティック
# gamepad
preferences-right-trigger = 右トリガー
preferences-scratchpad-below-buttons = 手書きパッドをボタン下に表示
preferences-scratchpad-transparency = 手書きパッドの透明度
preferences-scratchpad-transparency-full = 完全透明
preferences-scratchpad-transparency-medium = 透明（中）
preferences-scratchpad-transparency-none = 不透明
preferences-scratchpad-transparency-slight = 透明（少）
preferences-shake-action = シェイクアクション
preferences-short = 短い
preferences-show-bottom-bar = ボトムバーを表示
preferences-show-grid = グリッドを表示
preferences-show-top-bar = トップバーを表示
preferences-small = 小
preferences-swipe-down = 下にスワイプ
preferences-swipe-left = 左にスワイプ
preferences-swipe-right = 右にスワイプ
preferences-swipe-up = 上にスワイプ
preferences-swipes = スワイプ
preferences-swipes-must-begin-from-the-far = スワイプはスクリーンの左端・右端から行ってください。
preferences-sync-sounds-images = 音声と画像を同期
preferences-syncing = 同期
preferences-tap-to-sync = 同期を実行するには、デッキリスト表示スクリーンの「同期する」をタップしてください。
preferences-taps = タップ
preferences-theme-bar-style = バーの外観
preferences-theme-black = ブラック
preferences-theme-dark-translucent = ダーク & 半透明
preferences-theme-force-off = 強制オフ
preferences-theme-force-on = 強制オン
preferences-theme-light-translucent = ライト & 半透明
preferences-theme-night-mode-desc = 夜間モードを使用することで、インターフェースが暗くなり、黒い背景に白文字のカードが表示されます。
preferences-theme-night-mode-same-as-system = システムに従う
preferences-theme-slate = グレー
preferences-thick = 太い
preferences-tools-overlay-button = ツールアイコンの表示
preferences-tools-overlay-position = ツールアイコンの配置
preferences-top-center = 中央上
preferences-top-left = 左上
preferences-top-right = 右上
preferences-undo-clears-all = 元に戻すタップですべて消去
preferences-when-answer-shown = 答えが表示されるとき
preferences-when-question-shown = 問題が表示されるとき
preferences-you-have-been-logged-out = ログアウトしました
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = 最大画像サイズ（長辺）
# whether to shrink images when pasting
preferences-editing-resize-on-paste = ペースト時にリサイズ
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = スマート引用符とダッシュを自動変換
preferences-editing-crop-camera-photos = 写真をトリミング
