profiles-a-profile-with-that-name-already = 同じ名前のプロファイルがすでに存在します。
profiles-add-profile = プロファイルを追加
profiles-finishing-backup = バックアップを完了しています...
profiles-please-provide-some-text-avoiding-symbols = 記号とアンダースコアを使わずに名前を入力してください。
profiles-please-select-another-profile-first = 先に別のプロファイルを選択してください。
profiles-profile-name = プロファイル名
profiles-rename-profile = プロファイル名を変更
profiles-unable-to-open-safari-please = Safari を開けません。ペアレンタルコントロールを確認してください。
profiles-welcome = ようこそ！
