studying-answer-time-elapsed = 経過した回答時間
studying-auto-advance-starting = カードの自動送りを開始します
studying-auto-advance-stopped = カードの自動送りを停止しました
studying-have-ready-to-study = 学習するカードが{ $numCards }あります。
studying-please-run-empty-cards-on-the = コンピュータ版で空のカードを実行してください。
studying-replay-card = カードを再生
studying-replay-voice = 音声を再生
studying-rescheduled-card = カードのスケジュールを変更しました。
studying-type-in-the-answer = 答えを入力してください
