decks-a-deck-must-be-provided = Ní foláir paca a lua.
decks-a-deck-named-already-exists = Tá an t-ainm '{ $name }' ar phaca eile cheana féin.
decks-a-deck-with-that-name-already = Tá an t-ainm sin ar phaca eile cheana féin.
decks-add-deck = Cuir Paca leis
decks-add-empty-deck = Cuir Paca Folamh leis
decks-addexport = Iompórtáil/Easpórtáil
decks-cannot-delete = Ná Scriostar
decks-card-limit = Uasmhéid cártaí
decks-cards-in-a-filtered-deck-cant = Ní féidir an cárta atá i bpaca scagtha a bhogadh.
decks-custom-steps = Céimeanna Saincheaptha
decks-deck-exists = Tá an Paca Ann
decks-deck-label = Paca:
decks-deck-name = Ainm an Phaca
decks-deck-options = Sainroghanna Paca
decks-download-link = Nasc Íoslódála
decks-export-collection = Easpórtáil Cnuasach
decks-filtered-deck = Paca Scagtha
decks-import-from-itunes = Iompórtáil ó iTunes
decks-invalid-deck-name = Ainm paca neamhbhailí.
decks-link-to-apkg-file-to-import = Nasc le comhad .apkg chun iompórtáil:
decks-no-matches = Gan Toradh
decks-return-by-delete = Chun na cártaí go léir a chur abhaile, croith do mhéar ar an bpaca gorm ar liosta na bpacaí agus scrios é.
decks-shared-deck-list = Liosta Pacaí Roinnte
decks-sync = Sioncronaigh
decks-synchronize = Sioncronaigh
decks-the-default-deck-cannot-be-deleted = Ní féidir an bunphaca a scriosadh.
decks-the-provided-deck-does-not-exist = Níl an paca a luaigh tú ann.
decks-the-search-you-provided-did-not = Níl aon cárta ann a thagann leis an gcuardach a rinne tú.
decks-will-be-returned = Cuirfear na cártaí abhaile chuig a bpacaí faoi seach nuair a thabharfaidh tú freagra orthu.
