deck-options-add-options-group = Cuir Grúpa Sainroghanna leis
deck-options-answer-time-cap = Uasteorainn ar am freagartha
deck-options-bury-related-new-cards = Cuir cartaí nua gaolmhara i bhfolach
deck-options-bury-related-reviews = Cuir athbhreithnithe gaolmhara i bhfolach
deck-options-defaults = Réamhshocruithe
deck-options-delete-options-full-sync = Ní bheifear in ann pé athruithe a rinne tú ar ghléas ar bith eile a chumasc ar an gcéad sioncronú eile má scriostar an grúpa sainroghanna seo. Lean ar aghaidh?
deck-options-display-in-order-added = Taispeáin san ord inar cruthaíodh iad
deck-options-display-in-random-order = Taispeáin in ord randamach
deck-options-full-sync-required = Sioncronú Cuimsitheach ag Teastáil
deck-options-group-name = Ainm grúpa
deck-options-max-new-per-day = Uasmhéid nótaí nua sa lá
deck-options-max-reviews-per-day = Uasmhéid nótaí aitbhreithnithe sa lá
deck-options-new-cards = Cártaí nua
deck-options-options-group = Grúpa sainroghanna
deck-options-replay-q-audio-in-answer = Cas fuaim na ceiste arís ar thaobh an fhreagra
deck-options-reset-all-settings-to-defaults = Fill ar na socruithe réamhshocraithe go léir?
deck-options-restore-defaults = Fill ar Réamhshocruithe
deck-options-steps = Céimeanna
