exporting-collection-saved-to-itunes = Cnuasach sábháilte chuig iTunes.
exporting-export-to-itunes = Easpórtáil go hiTunes
exporting-export-to-share-sheet = Easpórtáil go Leathanach Roinnte
exporting-exporting = Ag easpórtáil...
exporting-include-media2 = Meáin san Áireamh
exporting-media-files-exported-d = Comhaid mheán a easpórtáladh: { $count }...
