preferences-about = Maidir Linn
preferences-always-duck-and-ignore-mute = Cas + Fón Balbhaithe/Ceol Air
preferences-answer-keeps-zoom = Coinnigh Zúmáil ar Thaobh an Fhreagra
preferences-answer-side = Taobh an Fhreagra
preferences-audio-buttons = Cnaipí Fuaime
preferences-auto-advance-answer-action = Gníomh 'Freagair'
preferences-auto-advance-answer-seconds = Soicind ar Thaobh an Fhreagra
preferences-auto-advance-auto-advance-to-start = Chun dul ar aghaidh go huathoibríoch, bain triail as an ngníomh 'Ar Aghaidh go hUathoibríoch'.
preferences-auto-advance-do-nothing = Ná Déantar Dada
preferences-auto-advance-question-seconds = Soicind ar Thaobh na Ceiste
preferences-backup-available-backups = Do chuid cóipeanna cúltaca
preferences-backup-create-now = Déan Cóip Chúltaca Anois
preferences-backup-maximum-backups = Uasmhéid Cóipeanna Cúltaca
preferences-backup-minutes-between-backups = Achar (i Nóiméid) idir Cóipeanna Cúltaca
preferences-backup-revert-to-backup = Fill ar Chóip Cúltaca
preferences-backup-revert-to-backup-confirm = Fill ar { $backup }? Caillfear athrú ar bith dá ndearnadh ó sábháladh an chóip chúltaca.
preferences-backup-reverted-to-backup = Filleadh ar chóip chúltaca.
preferences-bottom-bar-size = Méid an Bharra Íochtair
preferences-bottom-center = Íochtar sa Lár
preferences-bottom-left = Íochtar ar Chlé
preferences-bottom-right = Íochtar ar Dheis
preferences-button-d = Cnaipe { $num }
preferences-collection-day-starts = Tosaíonn an Lá ag
preferences-collection-learn-ahead-minutes = Foghlaim Roimh Am - Nóiméid
preferences-collection-mix = Meascán
preferences-collection-new-first = Nua i dtosach
preferences-collection-newreview-order = Ord na gCártaí Nua/Athbhreithnithe
preferences-collection-reviews-first = Athbhreithniú i dtosach
preferences-double-tap-prevention = Seachain an Tapáil Dhúbailte
preferences-drawing-screen-ignores-fingers = Neamhaird do Mhéara sa Bhloc Tarraingthe
preferences-feedback-ticks = Comharthaí Aiseolais
preferences-fine = Mín
preferences-force-sync-confirm = Déan sioncronú ón t-aon ghléas amháin? Caillfear aon athrú a rinneadh ar ghléas ar bith eile.
preferences-full-sync = Sioncronú Iomlán
preferences-gamepad-button-mapping = Mapáil Cnaipí
preferences-gamepad-menu-button = Roghchlár
preferences-gamepads = Gléas Cluichíochta
preferences-height = Airde
preferences-huge = An-mhór
preferences-ignore-fingers = Neamhaird do Mhéara
preferences-interrupt-current-audio = Bris Isteach ar Fhuaim Reatha
preferences-large = Mór
preferences-left = Clé
# gamepad
preferences-left-shoulder = Gualainn Chlé
# gamepad
preferences-left-thumbstick-button = Luamhán Clé
# gamepad
preferences-left-trigger = Truicear Clé
preferences-logged-in-as = Sínithe isteach mar:
preferences-long = Fada
preferences-mid-center = Díreach i Lár
preferences-mid-left = Lár ar Chlé
preferences-mid-right = Lár ar Dheis
preferences-never-type-answer = Ná Clóscríobhtar Freagraí
preferences-never-show-scratchpad = Ná Taispeántar Bloc Tarraingthe
preferences-never-show-scratchpad-enabled = Tá 'Ná Taispeántar Bloc Tarraingthe' roghnaithe sna Sainroghanna.
preferences-next-times = Achar Amach Anseo
preferences-normal = Gnáthmhéid
preferences-notifications = Fógraí
preferences-notifications-alert-time = Am an Rabhaidh
preferences-notifications-alert-when-due = Rabhadh agus rud éigin Le Staidéar
preferences-notifications-app-icon-shows-due-count = Méid Le Staidéar ar Deilbhín
preferences-notifications-settings-app-enable-notifications = Téigh chomh fada le iOS Settings agus aimsigh an chuid a bhaineann le hAnki. Déan na fógraí agus na rabhaidh a cheadú ansin.
preferences-pen-size = Méid an Phinn
preferences-question-side = Taobh na Ceiste
preferences-remaining-count = Méid atá Fágtha
preferences-right = Deis
# gamepad
preferences-right-shoulder = Gualainn Dheis
# gamepad
preferences-right-thumbstick-button = Luamhán Deis
# gamepad
preferences-right-trigger = Truicear Deis
preferences-scratchpad-below-buttons = Bloc faoi Bhun na gCnaipí
preferences-scratchpad-transparency = Trédhearcacht an Bhloic
preferences-scratchpad-transparency-full = Lán-trédhearcach
preferences-scratchpad-transparency-medium = So-thrédhearcach
preferences-scratchpad-transparency-none = Neamh-thrédhearcach
preferences-scratchpad-transparency-slight = Leath-thrédhearcach
preferences-shake-action = Croitheadh: Gníomh
preferences-short = Gearr
preferences-show-bottom-bar = Taispeán Barra Íochtair
preferences-show-grid = Taispeán Greille
preferences-show-top-bar = Taispeán Barra Uachtair
preferences-small = Beag
preferences-swipe-down = Cuimil Síos
preferences-swipe-left = Cuimil ar Chlé
preferences-swipe-right = Cuimil ar Dheis
preferences-swipe-up = Cuimil Suas
preferences-swipes = Cuimilt Mhéar
preferences-swipes-must-begin-from-the-far = Bítear ag cuimilt ón chuid i bhfad ar chlé nó ón chuid i bhfad ar dheis den scáileán.
preferences-sync-sounds-images = Sioncronaigh Fuaimeanna & Íomhánna
preferences-syncing = Sioncronú
preferences-tap-to-sync = Chun tús a chur leis an sioncronú, brúigh an cnaipe Sioncronaigh agus tú ag breathnú ar liosta na bpacaí.
preferences-taps = Brú an Scáileáin
preferences-theme-bar-style = Cuma an Bharra
preferences-theme-black = Dubh
preferences-theme-dark-translucent = Dorcha & Trédhearcach
preferences-theme-force-off = As i gCónaí
preferences-theme-force-on = Air i gCónaí
preferences-theme-light-translucent = Sorcha & Trédhearcach
preferences-theme-night-mode-desc = Bíonn an comhéadan dorcha sa Mhodh Oíche agus bíonn na cártaí dubh agus cló bán orthu.
preferences-theme-night-mode-same-as-system = Réir an Ghléis
preferences-theme-slate = Slinnliath
preferences-thick = Tiubh
preferences-tools-overlay-button = Cnaipe Forleagtha Uirlisí
preferences-tools-overlay-position = Suíomh an Chnaipe Uirlisí
preferences-top-center = Uachtar sa Lár
preferences-top-left = Uachtar ar Chlé
preferences-top-right = Uachtar ar Dheis
preferences-undo-clears-all = Scriosann 'Cealaigh' Gach Rud
preferences-when-answer-shown = Agus an freagra á thaispeáint
preferences-when-question-shown = Agus an cheist á taispeáint
preferences-you-have-been-logged-out = Síníodh amach thú.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Uasmhéid Íomhá (Ciumhais Fhada)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Athraigh Méid Tar Éis Greamú
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Tiontaigh Camóga agus Fleiscíní Cliste
preferences-editing-crop-camera-photos = Bearr Grianghraif Cheamara
