preferences-about = Maidir Linn
preferences-answer-keeps-zoom = Coinnítear an Zúmáil ar Thaobh an Fhreagra
preferences-answer-side = Taobh an Fhreagra
preferences-audio-buttons = Cnaipí Fuaime
preferences-auto-advance-answer-action = Gníomh 'Freagair'
preferences-auto-advance-answer-seconds = Soicind ar Thaobh an Fhreagra
preferences-auto-advance-auto-advance-to-start = Chun dul ar aghaidh go huathoibríoch, bain triail as an ngníomh 'Ar Aghaidh go hUathoibríoch'.
preferences-auto-advance-do-nothing = Ná Déantar Dada
preferences-auto-advance-question-seconds = Soicind ar Thaobh na Ceiste
preferences-auto-advance-show-reminder = Taispeáintear Meabhrúchán
preferences-auto-advance-wait-for-audio = Fantar leis an bhFuaim
preferences-backup-available-backups = Do chuid cóipeanna cúltaca
preferences-backup-create-now = Déan Cóip Chúltaca Anois
preferences-backup-maximum-backups = Uasmhéid Cóipeanna Cúltaca
preferences-backup-minutes-between-backups = Achar (i Nóiméid) idir Cóipeanna Cúltaca
preferences-backup-revert-to-backup = Fill ar Chóip Cúltaca
preferences-backup-revert-to-backup-confirm = Fill ar { $backup }? Caillfear athrú ar bith dá ndearnadh ó sábháladh an chóip chúltaca.
preferences-backup-reverted-to-backup = Filleadh ar chóip chúltaca.
preferences-bottom-bar-size = Méid an Bharra Íochtair
preferences-bottom-center = Lár Íochtair
preferences-bottom-left = Clé Íochtair
preferences-bottom-right = Deis Íochtair
preferences-button-d = Cnaipe { $num }
preferences-collection-day-starts = Tosaíonn an Lá ag
preferences-collection-mix = Meascán
preferences-collection-new-first = Nua i dtosach
preferences-collection-newreview-order = Ord na gCártaí Nua/Athbhreithnithe
preferences-collection-reviews-first = Athbhreithniú i dtosach
