actions-actions = Tác vụ
actions-add-new = Thêm vào
actions-added-to-frequent-actions = Đã thêm vào Tác vụ thường xuyên.
actions-all-actions = Tất cả Tác vụ
actions-already-in-frequent-actions = Đã có trong Tác vụ thường xuyên.
actions-an-error-occurred = Một lỗi đã xảy ra: { $error }
actions-answer-again = Trả lời lần nữa
actions-answer-easy = Trả lời Dễ
actions-answer-good = Trả lời Tốt
actions-answer-hard = Trả lời Khó
actions-are-you-sure = Bạn chắc không?
actions-auto-advance = Tự động Nâng cao
actions-bottom-bar = Thanh dưới
actions-browse = Duyệt
actions-card-buried = Đã hoãn thẻ
actions-card-suspended = Đã dừng thẻ
actions-card-template = Kiểu mẫu Mặt trước
actions-confirm-delete = Xác nhận xoá
actions-create = Tạo
actions-current-audio-minus-5s = Âm thanh hiện hành -5s
actions-current-audio-plus-5s = Âm thanh hiện hành +5s
actions-custom-study-cant-be-used-on = Tùy chỉnh học tập không thể sử dụng trên bộ thẻ đã lọc.
actions-deck-statistics = Thống kê Bộ thẻ
actions-delete-note-and-its-cards = Xóa Phiếu cùng Thẻ kèm theo?
actions-discard-changes = Hủy bỏ thay đổi
actions-done = Xong
actions-downloading = Đang tải xuống...
actions-drag-here-to-remove = Kéo vào đây để xoá
actions-draw = Vẽ
actions-file-invalid-or-corrupt = Tệp không hợp lệ hoặc bị hỏng.
actions-filtercram = Lọc/Gộp
actions-filtered-deck = Bộ thẻ đã Lọc { $num }
actions-forgot-card = Quên thẻ
actions-frequent-actions = Tác vụ thường xuyên
actions-leave-without-saving = Rời đi mà không lưu?
actions-long-press-on-an-item-to = Nhấn giữ vào một mục để tùy chỉnh.
actions-mark = Đánh dấu
actions-mark-and-bury = Đánh dấu + Hoãn
actions-mark-and-suspend = Đánh dấu + Dừng
actions-marked = Đã đánh dấu
actions-no-current-card = Không có thẻ gần đây.
actions-no-load-restore-backup = Không thể tải được bộ sưu tập của bạn. Vui lòng khôi phục từ bản sao lưu tự động qua màn hình ưu tiên.
# (http://example.com) does not appear to be...
actions-not-valid-link = liên kết http/https có vẻ không hợp lệ.
actions-note-and-its-cards-deleted = Phiếu cùng { $count } Thẻ của nó đã xóa
actions-note-and-its-cards-suspended = Phiếu cùng { $count } Thẻ của nó đã dừng
actions-note-buried = Phiếu đã tạm hoãn
actions-note-marked-and-buried = Phiếu được đánh dấu và bị hoãn
actions-nothing-to-undo = Không còn gì để hoàn tác
actions-nothing-to-redo = Không còn gì để làm lại
actions-off = Tắt
actions-please-tap-the-in-the = Vui lòng nhấn vào '?' ở trên cùng bên trái để bắt đầu.
actions-processing = Đang xử lý ...
actions-record-voice = Thu Tiếng
actions-record-voice-menu = Bảng chọn thu tiếng
actions-reset-card = Đặt lại Thẻ
actions-revert = Hoàn nguyên
actions-review-undone = Hoàn tác Ôn tập
actions-select-deck = Chọn thẻ
actions-tools = Công cụ
actions-undo = Hoàn tác

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

actions-add-short = Thêm vào
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Tùy chỉnh
actions-decks-short = Bộ thẻ
actions-delete-note-short = Xoá
actions-edit-short = Chỉnh sửa
actions-mark-and-bury-short = Đ&T.h
actions-mark-and-suspend-short = Đ&Ng
actions-mark-short = Đánh dấu
actions-night-mode-short = Đêm
actions-off-short = Tắt
actions-pause-audio-short = Tạm dừng
actions-rebuild-short = Tái tạo
actions-record-voice-short = Ghi.Â
actions-replay-voice-short = Plại.Â
actions-replay-audio-short = Phát lại
actions-reset-card-short = Đặt lại.T
actions-set-due-date-short = G.hạn
actions-show-answer-short = Xem.Đ'án
actions-show-answeranswer-good-short = Xem/T.lời
actions-study-options-short = H.Tchỉnh
actions-suspend-card-short = Dừng.T
actions-suspend-note-short = Dừng.P
actions-tools-short = Công cụ
actions-top-bar-short = T.Trên
actions-unbury-deck-short = Bỏ T.hoãn
actions-undo-short = Hoàn tác
actions-redo-short = Làm lại
