# add current row to existing search
browsing-append = Gắn thêm
browsing-card-updated = Thẻ đã cập nhật
browsing-change-flag = Đổi Cờ
browsing-clear-flag = Bỏ Cờ
browsing-column-1 = Cột 1
browsing-column-2 = Cột 2
browsing-confirm-reset = Xác nhận Đặt lại
browsing-dd-selected = { $part }/{ $total } đã chọn
browsing-due-reviews = Thẻ ôn tập đến hạn
browsing-learning-cards = Thẻ đang học
browsing-no-cards-are-selected = Chưa thẻ nào được chọn.
browsing-note-created = Phiếu đã tạo
browsing-note-updated = Phiếu đã cập nhật
browsing-note2 = Phiếu:
browsing-questionandanswer = Câu hỏi+Đáp án
browsing-repetitions = Lặp
browsing-reset-cards = Đặt lại Thẻ
browsing-searching = Đang tìm kiếm...
browsing-second-column-19 = Cột thứ (1->9)
browsing-second-column-91 = Cột thứ (9->1)
browsing-select-all = Chọn tất cả
browsing-sort = Sắp xếp:
browsing-sort-order = Thứ tự sắp xếp
browsing-tag = Nhãn:
