deck-options-add-options-group = Thêm nhóm tùy chọn
deck-options-answer-time-cap = Giới hạn thời gian trả lời
deck-options-bury-related-new-cards = Tạm hoãn các thẻ mới liên quan
deck-options-bury-related-reviews = Tạm hoãn các thẻ ôn tập liên quan
deck-options-defaults = Mặc định
deck-options-delete-options-full-sync = Xóa nhóm tùy chọn này sẽ ngăn mọi thay đổi được hợp nhất từ ​​các thiết bị khác trong lần đồng bộ tiếp theo. Tiếp tục?
deck-options-display-in-order-added = Hiển thị theo thứ tự đã thêm
deck-options-display-in-random-order = Hiển thị theo thứ tự ngẫu nhiên
deck-options-full-sync-required = Yêu cầu đồng bộ đầy đủ
deck-options-group-name = Tên nhóm
deck-options-max-new-per-day = Thẻ mới tối đa một ngày
deck-options-max-reviews-per-day = Thẻ ôn tập tối đa một ngày
deck-options-new-cards = Thẻ Mới
deck-options-options-group = Nhóm tùy chọn
deck-options-replay-q-audio-in-answer = Phát lại âm thanh trong câu trả lời
deck-options-reset-all-settings-to-defaults = Đặt lại tất cả cài đặt về mặc định?
deck-options-restore-defaults = Phục hồi mặc định
deck-options-steps = Bước
