decks-a-deck-must-be-provided = Một bộ thẻ phải được cung cấp
decks-a-deck-named-already-exists = Bộ thẻ có tên '{ $name }' đã tồn tại.
decks-a-deck-with-that-name-already = Một bộ thẻ với tên này đã tồn tại.
decks-add-deck = Thêm Bộ thẻ
decks-add-empty-deck = Thêm Bộ thẻ trống
decks-addexport = Thêm/Xuất
decks-cannot-delete = Không thể xóa
decks-card-limit = Thẻ giới hạn
decks-cards-in-a-filtered-deck-cant = Không thể di chuyển các thẻ trong bộ bài đã lọc.
decks-custom-steps = Bước tùy chỉnh
decks-deck-exists = Bộ thẻ tồn tại
decks-deck-label = Bộ thẻ:
decks-deck-name = Tên bộ thẻ
decks-deck-options = Tùy chọn Bộ thẻ
decks-download-link = Liên kết tải xuống
decks-export-collection = Xuất Bộ sưu tập
decks-filtered-deck = Bộ thẻ đã lọc
decks-import-from-itunes = Nhập từ iTunes
decks-invalid-deck-name = Tên bộ thẻ không hợp lệ.
decks-link-to-apkg-file-to-import = Liên kết đến tệp .apkg để nhập:
decks-return-by-delete = Để trả lại tất cả các thẻ cùng một lúc, hãy vuốt qua bộ bài màu xanh trong danh sách bộ bài và xóa nó.
decks-shared-deck-list = Danh sách bộ bài được chia sẻ
decks-sync = Đồng bộ
decks-synchronize = Đồng bộ hoá
decks-the-default-deck-cannot-be-deleted = Không thể xóa bộ thẻ mặc định.
decks-the-provided-deck-does-not-exist = Bộ bài được cung cấp không tồn tại.
decks-the-search-you-provided-did-not = Tìm kiếm bạn cung cấp không khớp với bất kỳ thẻ nào.
decks-will-be-returned = Thẻ sẽ được trả về bộ thẻ gốc khi bạn trả lời chúng.
