importing-delete-imported-file = Xoá file đã nhập vào?
importing-import-complete = Nhập hoàn tất.
importing-importing = Đang nhập...
importing-no-apkg-or-colpkg-files-were = Không tìm thấy file .apkg hay .colpkg trong iTunes
importing-overwrite-via-import = Ghi đè toàn bộ bộ sưu tập bằng tệp đã nhập? Hành động này không thể được hoàn tác.
importing-please-choose-a-file = Vui lòng chọn một file.
importing-processed-media-files-d = Tệp phương tiện đã xử lý: { $count }...
importing-replace-collection = Thay thế Bộ sưu tập
importing-file-not-downloaded = Hãy tải tài liệu từ iCloud và nhập nó lại.
