preferences-about = Giới thiệu
preferences-always-duck-and-ignore-mute = Luôn Ẩn + Bỏ qua Tắt tiếng
preferences-answer-keeps-zoom = Thu Phóng Đáp án
preferences-answer-side = Đáp án phụ
preferences-audio-buttons = Các nút Âm thanh
preferences-auto-advance-answer-action = Đáp án Tác vụ
preferences-auto-advance-answer-seconds = Đáp án Thứ cấp
preferences-auto-advance-auto-advance-to-start = Để bắt đầu tự động nâng cao cấp độ, hãy sử dụng tác vụ 'Tự động Nâng cao'.
preferences-auto-advance-do-nothing = Không còn gì
preferences-auto-advance-question-seconds = Câu hỏi thứ cấp
preferences-auto-advance-show-reminder = Hiển thị Lời nhắc
preferences-auto-advance-wait-for-audio = Chờ Âm thanh
preferences-backup-available-backups = Các bản sao lưu có sẵn
preferences-backup-create-now = Tạo ngay
preferences-backup-maximum-backups = Sao lưu tối đa
preferences-backup-minutes-between-backups = Khoảng thời gian giữa các lần sao lưu
preferences-backup-revert-to-backup = Hoàn nguyên về Sao lưu
preferences-backup-revert-to-backup-confirm = Hoàn nguyên về { $backup }{ $backup }? Mọi thay đổi được thực hiện kể từ sau khi sao lưu sẽ bị mất.
preferences-backup-reverted-to-backup = Hoàn nguyên về Sao lưu
preferences-bottom-bar-size = Kích thước Thanh dưới
preferences-bottom-center = Thanh Trung tâm
preferences-bottom-left = Thanh Trái
preferences-bottom-right = Thanh Phải
preferences-button-d = Nút { $num }
preferences-collection-day-starts = Ngày bắt đầu
preferences-collection-learn-ahead-minutes = Quãng Học Trước
preferences-collection-mix = Xáo trộn
preferences-collection-new-first = Mới đầu tiên
preferences-collection-newreview-order = Phiếu Mới/Ôn tập
preferences-collection-reviews-first = Ôn tập trước
preferences-double-tap-prevention = Chống Bấm Đúp
preferences-drawing-screen-ignores-fingers = Màn hình Vẽ Bỏ qua Ngón tay
preferences-feedback-ticks = Dấu Phản hồi
preferences-fine = Bình thường
preferences-force-sync-confirm = Buộc đồng bộ hóa một chiều? Tất cả các thay đổi một bên sẽ bị mất.
preferences-full-sync = Đồng bộ Hoàn toàn
preferences-gamepad-button-mapping = Liên kết Nút
preferences-gamepad-menu-button = Menu
preferences-gamepads = Bàn phím trò chơi
preferences-height = Độ cao
preferences-huge = Rất lớn
preferences-ignore-fingers = Bỏ qua ngón tay
preferences-interrupt-current-audio = Ngắt âm thanh hiện tại
preferences-large = Lớn
preferences-left = Trái
# gamepad
preferences-left-shoulder = Lề trái
# gamepad
preferences-left-thumbstick-button = Nút Thumbstick Trái
# gamepad
preferences-left-trigger = Bộ nhả bên trái
preferences-logged-in-as = Đăng nhập với tư cách:
preferences-long = Dài
preferences-mid-center = Giữa trung tâm
preferences-mid-left = Giữa bên trái
preferences-mid-right = Giữa bên phải
preferences-never-type-answer = Không nhập đáp án
preferences-next-times = Lần sau
preferences-normal = Bình thường
preferences-notifications = Thông báo
preferences-notifications-alert-time = Thời gian Báo
preferences-notifications-alert-when-due = Cảnh báo khi đến hạn
preferences-notifications-app-icon-shows-due-count = Icon App cho biết số Thẻ đến hạn
preferences-notifications-settings-app-enable-notifications = Vui lòng truy cập Cài đặt của iOS, tìm Anki và bật thông báo, biểu ngữ và cảnh báo.
preferences-pen-size = Kích thước bút
preferences-question-side = Câu hỏi phụ
preferences-remaining-count = Số lượng còn lại
preferences-right = Phải
# gamepad
preferences-right-shoulder = Lề phải
# gamepad
preferences-right-thumbstick-button = Nút Thumbstick Phải
# gamepad
preferences-right-trigger = Bộ nhả bên phải
preferences-scratchpad-below-buttons = Các nút bên dưới Vùng tạm
preferences-scratchpad-transparency = Độ trong của Vùng tạm
preferences-scratchpad-transparency-full = Đầy đủ
preferences-scratchpad-transparency-medium = Trung bình
preferences-scratchpad-transparency-none = Không
preferences-scratchpad-transparency-slight = Không đáng kể
preferences-shake-action = Tác vụ Lắc
preferences-short = Ngắn
preferences-show-bottom-bar = Hiển thị Thanh Dưới
preferences-show-grid = Hiển thị lưới
preferences-show-top-bar = Hiển thị Thanh Trên
preferences-small = Nhỏ
preferences-swipe-down = Vuốt xuống
preferences-swipe-left = Vuốt sang trái
preferences-swipe-right = Vuốt sang phải
preferences-swipe-up = Vuốt lên
preferences-swipes = Vuốt
preferences-swipes-must-begin-from-the-far = Các thao tác vuốt phải bắt đầu từ ngoài cùng bên trái hoặc bên phải của màn hình.
preferences-sync-sounds-images = Đồng bộ hóa Âm thanh & Hình ảnh
preferences-syncing = Đang đồng bộ...
preferences-tap-to-sync = Để kích hoạt đồng bộ hóa, hãy nhấn vào nút đồng bộ hóa trên màn hình danh sách bộ thẻ.
preferences-taps = Nhấn
preferences-theme = Giao diện
preferences-theme-bar-style = Kiểu Thanh chọn
preferences-theme-black = Đen
preferences-theme-dark = Tối
preferences-theme-dark-translucent = Tối & Mờ
preferences-theme-force-off = Buộc Tắt
preferences-theme-force-on = Buộc Bật
preferences-theme-light-translucent = Sáng & Mờ
preferences-theme-night-mode-desc = Chế độ ban đêm làm tối giao diện và hiển thị thẻ màu trắng trên nền đen.
preferences-theme-night-mode-same-as-system = Theo dõi Hệ thống
preferences-theme-slate = Xám đá
preferences-thick = Dày
preferences-tools-overlay-button = Nút Công cụ Phủ
preferences-tools-overlay-position = Vị trí Công cụ Phủ
preferences-top-center = Trên cùng ở giữa
preferences-top-left = Trên cùng bên trái
preferences-top-right = Trên cùng bên phải
preferences-undo-clears-all = Hoàn tác Xóa tất cả
preferences-when-answer-shown = Khi đáp án được hiển thị
preferences-when-question-shown = Khi câu hỏi được hiển thị
preferences-you-have-been-logged-out = Bạn đã được đăng xuất.
preferences-editing = Chỉnh sửa
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Kích thước hình ảnh tối đa (Cạnh dài)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Thay đổi kích thước khi dán
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Chuyển đổi Dấu ngoặc kép & Dấu gạch ngang Thông minh
preferences-editing-crop-camera-photos = Cắt ảnh camera
