preferences-about = Giới thiệu
preferences-always-duck-and-ignore-mute = Luôn Ẩn + Bỏ qua Tắt tiếng
preferences-answer-keeps-zoom = Thu Phóng Đáp án
preferences-answer-side = Đáp án sang Lề
preferences-audio-buttons = Các nút Âm thanh
preferences-auto-advance-answer-action = Đáp án Tác vụ
preferences-auto-advance-answer-seconds = Đáp án Thứ cấp
preferences-auto-advance-auto-advance-to-start = Để bắt đầu tự động nâng cao cấp độ, hãy sử dụng tác vụ 'Tự động Nâng cao'.
preferences-auto-advance-do-nothing = Không còn gì
preferences-auto-advance-question-seconds = Câu hỏi thứ cấp
preferences-auto-advance-show-reminder = Hiển thị Lời nhắc
preferences-auto-advance-wait-for-audio = Chờ Âm thanh
preferences-backup-available-backups = Các bản sao lưu có sẵn
preferences-backup-create-now = Tạo ngay
preferences-backup-maximum-backups = Sao lưu tối đa
preferences-backup-minutes-between-backups = Khoảng thời gian giữa các lần sao lưu
preferences-backup-revert-to-backup = Hoàn nguyên về Sao lưu
preferences-backup-revert-to-backup-confirm = Hoàn nguyên về { $backup }{ $backup }? Mọi thay đổi được thực hiện kể từ sau khi sao lưu sẽ bị mất.
preferences-backup-reverted-to-backup = Hoàn nguyên về Sao lưu
preferences-bottom-bar-size = Kích thước Thanh dưới
preferences-bottom-center = Thanh Trung tâm
preferences-bottom-left = Thanh Trái
preferences-bottom-right = Thanh Phải
preferences-button-d = Nút { $num }
preferences-collection-day-starts = Ngày bắt đầu
preferences-collection-learn-ahead-minutes = Quãng Học Trước
preferences-collection-mix = Xáo trộn
preferences-collection-new-first = Mới đầu tiên
preferences-collection-newreview-order = Phiếu Mới/Ôn tập
preferences-collection-reviews-first = Ôn tập trước
preferences-double-tap-prevention = Chống Bấm Đúp
preferences-drawing-screen-ignores-fingers = Màn hình Vẽ Bỏ qua Ngón tay
preferences-feedback-ticks = Dấu Phản hồi
preferences-fine = Bình thường
preferences-force-sync-confirm = Buộc đồng bộ hóa một chiều? Tất cả các thay đổi một bên sẽ bị mất.
preferences-full-sync = Đồng bộ Hoàn toàn
preferences-gamepad-button-mapping = Liên kết Nút
preferences-gamepad-menu-button = Menu
preferences-gamepads = Bàn phím trò chơi
preferences-height = Độ cao
preferences-huge = Rất lớn
preferences-ignore-fingers = Bỏ qua ngón tay
preferences-interrupt-current-audio = Ngắt âm thanh hiện tại
preferences-large = Lớn
preferences-left = Trái
# gamepad
preferences-left-shoulder = Lề trái
# gamepad
preferences-left-thumbstick-button = Nút Thumbstick Trái
# gamepad
preferences-left-trigger = Bộ nhả bên trái
preferences-normal = Bình thường
preferences-notifications = Thông báo
preferences-scratchpad-transparency-none = Không
preferences-editing-crop-camera-photos = Cắt ảnh camera
