actions-actions = Actions
actions-add-new = Ajouter Nouveau
actions-added-to-frequent-actions = Ajouté aux actions fréquentes.
actions-all-actions = Toutes les actions
actions-already-in-frequent-actions = Déjà en action fréquente.
actions-an-error-occurred = Une erreur s'est produite: { $error }
actions-answer-again = Répondre à revoir
actions-answer-easy = Réponse facile
actions-answer-good = Réponse correcte
actions-answer-hard = Réponse difficile
actions-are-you-sure = Êtes-vous sûr?
actions-auto-advance = Avance automatique
actions-auto-advance-short = Avance auto.
actions-bottom-bar = Barre du bas
actions-bottom-bar-short = BarreB
actions-browse = Parcourir
actions-bury-card-short = Dét.C
actions-bury-note-short = Dét.N
actions-card-buried = Carte enterrées
actions-card-info = Info carte
actions-card-info-short = Infos C
actions-card-suspended = Carte suspendue
actions-card-template = Modèle de carte
actions-confirm-delete = Confirmer la suppression
actions-create = Créer
actions-current-audio-minus-5s = Piste audio -5s
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s = Piste audio +5s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-cant-be-used-on = L'étude personnalisée ne peut pas être utilisée sur un paquet filtré.
actions-custom-study-short = Personnalisé
actions-deck-statistics = Statistiques du paquet
actions-deck-statistics-short = Stats P
actions-delete-note-and-its-cards = Supprimer la note et ses cartes?
actions-delete-note-short = Suppr
actions-discard-changes = Annuler les modifications
actions-done = Fait
actions-downloading = Téléchargement...
actions-drag-here-to-remove = Glissez ici pour enlever
actions-draw = Dessiner
actions-file-invalid-or-corrupt = Fichier invalide ou corrompu.
actions-filtercram = Filtrer/Étudier
actions-filtered-deck = Paquet filtré { $num }
actions-flag-1 = Drapeau 1
actions-flag-1-red = Drapeau 1 (Rouge)
actions-flag-2 = Drapeau 2
actions-flag-2-orange = Drapeau 2 (Orange)
actions-flag-3 = Drapeau 3
actions-flag-3-green = Drapeau 3 (vert)
actions-flag-4 = Drapeau 4
actions-flag-4-blue = Drapeau 4 (bleu)
actions-forgot-card = Carte oubliée
actions-frequent-actions = Actions fréquentes
actions-how-many-days-in-the-future = Combien de jours d'avance?
actions-invalid-number-of-days = Nombre de jours non valide.
actions-leave-without-saving = Quitter sans enregistrer ?
actions-long-press-on-an-item-to = Appui long sur un élément pour personnaliser.
actions-mark = Marquer
actions-mark-and-bury = Marquer+Enterrer
actions-mark-and-bury-short = M&B
actions-mark-and-suspend = Marquer+Suspendre
actions-mark-and-suspend-short = MetS
actions-marked = Marqué
actions-night-mode-short = Nuit
actions-no-current-card = Aucune carte actuellement.
actions-no-load-restore-backup = Votre collection n'a pas pu être chargée. Veuillez restaurer la collection à partir d'une sauvegarde automatisée, par le menu des préférences.
actions-not-valid-link = ne semble pas être un lien http/https valide.
actions-note-and-its-cards-deleted = La note et ses cartes { $count } ont été supprimées
actions-note-and-its-cards-suspended = Note et ses { $count } carte(s) ont été suspendues
actions-note-buried = Note enterrée
actions-note-marked-and-buried = Note marquée et enterrée
actions-nothing-to-undo = Rien à annuler
actions-off = Désactivé
actions-pause-audio-short = Arrêter
actions-please-tap-the-in-the = Appuyez sur le bouton '?' en haut à gauche pour commencer.
actions-processing = Traitement...
actions-record-voice = S’enregistrer
actions-record-voice-short = Enreg.
actions-replay-audio-short = Réentendre
actions-reset-card = Réinitialiser la carte
actions-reset-card-short = Reset
actions-revert = Rétablir
actions-review-undone = Révision annulée
actions-scratchpad = Bloc-notes
actions-scratchpad-short = Pavé
actions-scratchpad-size = Taille du bloc-notes
actions-scratchpad-size-short = Taille du pavé
actions-select-deck = Choisir le paquet
actions-select-note-type = Choisir un type de note
actions-set-due-date-short = Date due
actions-show-answer-short = Réponse
actions-show-answeranswer-good = Afficher la réponse/réponse correcte
actions-show-answeranswer-good-short = Montrer/Correct
actions-study-options = Options d'étude
actions-study-options-short = Option
actions-suspend-card-short = Susp.C
actions-suspend-note-short = Susp.N
actions-tools = Outils
actions-tools-overlay = Outils superposés
actions-top-bar = Barre du haut
actions-unbury-deck = Déterrer le paquet
actions-unbury-deck-short = Dét P
actions-undo = Annuler
actions-unmarked = Décocher
actions-you-can-only-empty-a-filtered = Vous ne pouvez vider qu'un paquet filtré.
actions-you-can-only-rebuild-a-filtered = Vous ne pouvez refondre qu'un paquet filtré.
