actions-actions = Actions
actions-add-new = Ajouter Nouveau
actions-added-to-frequent-actions = Ajouté aux actions fréquentes.
actions-all-actions = Toutes les actions
actions-already-in-frequent-actions = Déjà en action fréquente.
actions-an-error-occurred = Une erreur s'est produite: { $error }
actions-answer-easy = Réponse facile
actions-are-you-sure = Êtes-vous sûr?
actions-bottom-bar = Barre du bas
actions-browse = Parcourir
actions-card-buried = Carte enterrée
actions-card-suspended = Carte suspendue
actions-card-template = Modèle de carte
actions-confirm-delete = Confirmer la suppression
actions-create = Créer
actions-current-audio-minus-5s = Piste audio -5s
actions-current-audio-plus-5s = Piste audio +5s
actions-custom-study-cant-be-used-on = L'étude personnalisée ne peut pas être utilisée sur un paquet filtré.
actions-deck-statistics = Statistiques du paquet
actions-delete-note-and-its-cards = Supprimer la note et ses cartes?
actions-discard-changes = Annuler les modifications
actions-done = Fait
actions-downloading = Téléchargement...
actions-drag-here-to-remove = Glissez ici pour enlever
actions-draw = Dessiner
actions-file-invalid-or-corrupt = Fichier invalide ou corrompu.
actions-filtercram = Filtrer/Étudier
actions-filtered-deck = Paquet filtré { $num }
actions-frequent-actions = Actions fréquentes
actions-leave-without-saving = Quitter sans enregistrer ?
actions-long-press-on-an-item-to = Appui long sur un élément pour personnaliser.
actions-mark = Marquer
actions-mark-and-bury = Marquer+Enfouir
actions-mark-and-suspend = Marquer+Suspendre
actions-marked = Marqué
actions-no-current-card = Aucune carte actuellement.
actions-no-load-restore-backup = Votre collection n'a pas pu être chargée. Veuillez restaurer la collection à partir d'une sauvegarde automatisée, par le menu des préférences.
# (http://example.com) does not appear to be...
actions-not-valid-link = ne semble pas être un lien http/https valide.
actions-note-and-its-cards-deleted = La note et ses cartes { $count } ont été supprimées
actions-note-and-its-cards-suspended = Note et ses { $count } carte(s) ont été suspendues
actions-note-buried = Note enfouie
actions-note-marked-and-buried = Note marquée et enfouie
actions-off = Désactivé
actions-please-tap-the-in-the = Appuyez sur le bouton '?' en haut à gauche pour commencer.
actions-record-voice = S’enregistrer
actions-record-voice-menu = Menu d'enregistrement
actions-reset-card = Réinitialiser la carte
actions-revert = Rétablir
actions-review-undone = Révision annulée
actions-scratchpad = Bloc-notes
actions-scratchpad-size = Taille du bloc-notes
actions-select-deck = Choisir le paquet
actions-select-note-type = Choisir un type de note
actions-show-answeranswer-good = Afficher la réponse/réponse correcte
actions-study-options = Options d'étude
actions-tools = Outils
actions-tools-overlay = Outils superposés
actions-top-bar = Barre du haut
actions-unbury-deck = Déterrer le paquet
actions-undo = Annuler
actions-unmarked = Décocher
actions-you-can-only-empty-a-filtered = Vous ne pouvez vider qu'un paquet filtré.
actions-you-can-only-rebuild-a-filtered = Vous ne pouvez refondre qu'un paquet filtré.
actions-scroll-up = Faire défiler vers le haut
actions-scroll-down = Faire défiler vers le bas

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Vider
# create a filtered deck
actions-filter-short = Filter
actions-add-short = Ajouter
actions-answer-again-short = Rép. A
actions-answer-easy-short = Rép. E
actions-answer-good-short = Rép. G
actions-answer-hard-short = Rep. H
actions-auto-advance-short = Avance auto.
actions-bottom-bar-short = BarreB
actions-browse-short = Parcourir
actions-bury-card-short = Dét.C
actions-bury-note-short = Dét.N
actions-card-info-short = Infos C
actions-card-template-short = Modèle
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5 s
actions-custom-study-short = Personnalisé
actions-deck-statistics-short = Stats P
actions-decks-short = Paquets
actions-delete-note-short = Suppr
actions-edit-short = Modifier
actions-mark-and-bury-short = M&B
actions-mark-and-suspend-short = MetS
actions-mark-short = Marquer
actions-night-mode-short = Nuit
actions-off-short = Désactivé
actions-pause-audio-short = Arrêter
actions-rebuild-short = Reconstruire
actions-record-voice-short = Enreg.
actions-replay-voice-short = Rejouer
actions-replay-audio-short = Réentendre
actions-reset-card-short = Reset
actions-scratchpad-short = Pavé
actions-scratchpad-size-short = Taille du pavé
actions-set-due-date-short = Date due
actions-show-answer-short = Réponse
actions-show-answeranswer-good-short = Montrer/Correct
actions-study-options-short = Option
actions-suspend-card-short = Susp.C
actions-suspend-note-short = Susp.N
actions-tools-short = Outils
actions-top-bar-short = T.Bar
actions-unbury-deck-short = Dét P
actions-undo-short = Annuler
actions-redo-short = Rétablir
actions-scroll-up-short = Haut
actions-scroll-down-short = Bas
actions-back = Retour
