browsing-append = Ajouter
browsing-append-negated = Soustraire
browsing-card-updated = Carte mise à jour
browsing-change-flag = Changer de drapeau
browsing-clear-flag = Effacer le drapeau
browsing-column-1 = Colonne 1
browsing-column-2 = Colonne 2
browsing-confirm-reset = Confirmer la réinitialisation
browsing-dd-selected = %d/%d sélectionnés
browsing-due-dateorder = Date due/ordre
browsing-due-reviews = Révisions dues
browsing-learning-cards = Cartes apprises
browsing-no-cards-are-selected = Aucune carte sélectionnée.
browsing-note-created = Note créée
browsing-note-updated = Note mise à jour
browsing-note2 = Note :
browsing-questionandanswer = Question+Réponse
browsing-repetitions = Répétitions
browsing-reset-cards = Réinitialiser la carte
browsing-searching = Recherche...
browsing-second-column-19 = Colonne 2 (9->1)
browsing-second-column-91 = Colonne 2 (9->1)
browsing-select-all = Tout sélectionner
browsing-sort = Trier :
browsing-sort-order = Ordre de tri
browsing-tag = Tag:
