custom-study-any-tag = tous
custom-study-available = { $num } disponible
custom-study-cant-extend-limits-no-extra = Impossible d'augmenter la limite - aucune carte additionnelle n'est disponible.
custom-study-cram-seen-cards-with-certain-tags = Reporter les cartes révisées ayant certaines étiquettes (tags)
custom-study-days-to-look-ahead = Nombre de jours à devancer
custom-study-days-to-look-back = Nombre de jours passés à reprendre
custom-study-exclude-cards-with-tag = Exclure les cartes avec le tag
custom-study-extra-new-cards = Nouvelles cartes supplémentaires
custom-study-extra-review-cards = Cartes à réviser supplémentaires
custom-study-include-cards-with-tag = Inclure les cartes avec certains tags
custom-study-learn-new-cards-with-certain-tags = Apprendre des cartes inédites avec certains tags
custom-study-loading = Chargement...
custom-study-max-cards-to-gather = Cartes max à collecter
custom-study-no-tags = aucun
custom-study-no-tags-available = pas de tag disponible
custom-study-preview-all-cards-with-certain-tags = Aperçu des cartes avec certains tags
custom-study-review-due-cards-with-certain-tags = Revoir les cartes avec certains tags
custom-study-search-matches = Rechercher les correspondances { $num }
custom-study-study-type = Type d'étude
custom-study-the-selected-options-did-not-match = Les options sélectionnées ne correspondent à aucune carte.
