deck-options-add-options-group = Ajouter un groupe d'options
deck-options-answer-time-cap = Limite de temps de réponse
deck-options-bury-related-new-cards = Enterrer les cartes inédites associées
deck-options-bury-related-reviews = Enterrer les cartes associées
deck-options-defaults = Par défaut
deck-options-delete-options-full-sync = Supprimer ce groupe d'options empêchera la fusion de tout changement depuis d'autres périphériques lors de la prochaine synchronisation. Continuer ?
deck-options-display-in-order-added = Afficher dans l'ordre ajouté
deck-options-display-in-random-order = Afficher dans un ordre aléatoire
deck-options-full-sync-required = Synchronisation complète requise
deck-options-group-name = Nom du groupe
deck-options-max-new-per-day = Maximum de nouvelles cartes par jour
deck-options-max-reviews-per-day = Maximum de cartes révisées par jour
deck-options-new-cards = Cartes inédites
deck-options-options-group = Groupe d'options
deck-options-replay-q-audio-in-answer = Réentendre l'audio de la question sur le côté réponse
deck-options-reset-all-settings-to-defaults = Réinitialiser tous les paramètres par défaut ?
deck-options-restore-defaults = Paramètres par défaut
deck-options-steps = Étapes
