decks-a-deck-must-be-provided = Un paquet doit être indiqué.
decks-a-deck-named-already-exists = Un paquet nommé '{ $name }' existe déjà.
decks-a-deck-with-that-name-already = Un paquet portant ce nom existe déjà.
decks-add-deck = Ajouter un paquet
decks-add-empty-deck = Ajouter un paquet vide
decks-addexport = Ajouter/Exporter
decks-cannot-delete = Impossible de supprimer
decks-card-limit = Limite de carte
decks-cards-in-a-filtered-deck-cant = Les cartes d'un paquet filtré ne peuvent pas être déplacées.
decks-custom-steps = Étapes personnalisées
decks-deck-exists = Le paquet existe
decks-deck-label = Paquet :
decks-deck-name = Nom du paquet
decks-deck-options = Options du paquet
decks-download-link = Télécharger le lien
decks-export-collection = Exporter la collection
decks-filtered-deck = Paquet filtré
decks-import-from-itunes = Importer depuis iTunes
decks-invalid-deck-name = Nom du paquet invalide.
decks-link-to-apkg-file-to-import = Lien vers le fichier .apkg à importer :
decks-no-matches = Aucun résultat
decks-return-by-delete = Pour replacer les cartes dans leur paquet d’origine, supprimez le paquet filtré.
decks-shared-deck-list = Liste de paquets partagés
decks-sync = Synchronisation
decks-synchronize = Synchroniser
decks-the-default-deck-cannot-be-deleted = Le paquet par défaut ne peut pas être supprimé.
decks-the-provided-deck-does-not-exist = Le paquet indiqué n'existe pas.
decks-the-search-you-provided-did-not = La recherche indiquée ne correspond à aucune carte.
decks-will-be-returned = Replace les cartes dans leur paquet après y avoir répondu.
