editing-bold = Gras
editing-cancel-and-lose-any-unsaved-changes = Annuler et perdre toutes les modifications non sauvegardées?
editing-cant-edit-original-image-data = Impossible de modifier - l'image originale est introuvable.
editing-card-returned-to-new-card-queue = Carte replacée parmi les inédites.
editing-card-unsuspended = Carte non suspendue
editing-from-camera = Depuis la caméra
editing-from-file = Depuis Fichier
editing-from-photos = Depuis Photos
editing-italic = Italique
editing-next-cloze = Prochain texte à trous
editing-next-field = Prochain champ
editing-note-deleted = Note supprimée
editing-note-suspended = Note suspendue
editing-note-type-prompt = Type:
editing-note-unsuspended = Note non suspendue
editing-same-cloze = Même texte à trous
editing-the-first-field-must-not-be = Le champ ne doit pas être vide.
editing-unable-to-obtain-image = Impossible de récupérer l'image
editing-unable-to-read-file = Impossible de lire le fichier
editing-underline = Souligner
editing-unexpected-file-extension = Extension de fichier inattendue:
editing-unexpected-rich-text-format-please = Format de texte enrichi inattendu - veuillez essayer de copier et coller.
editing-unexpected-status-code = Code de statut inattendu :
editing-unsuspend-card = Enlever la suspension de la carte
editing-unsuspend-note = Enlever la suspension de la note
