exporting-collection-saved-to-itunes = Collection enregistrée sur iTunes.
exporting-export-to-itunes = Exporter vers iTunes
exporting-export-to-share-sheet = Exporter vers la feuille de partage
exporting-exporting = Exportation...
exporting-include-media2 = Inclure les médias
exporting-media-files-exported-d = Nombre de fichiers média exportés: { $count }...
