preferences-about = À propos
preferences-always-duck-and-ignore-mute = Toujours jouer l'audio et ignorer la sourdine
preferences-answer-keeps-zoom = Garder le zoom
preferences-answer-side = Côté réponse
preferences-audio-buttons = Boutons audio
preferences-auto-advance-answer-action = Bouton de réponse
preferences-auto-advance-answer-seconds = Nombre de secondes
preferences-auto-advance-auto-advance-to-start = Pour avancer automatiquement, utilisez l'action 'Avance automatique'.
preferences-auto-advance-do-nothing = Ne rien faire
preferences-auto-advance-question-seconds = Nombre de secondes par question
preferences-auto-advance-show-reminder = Afficher le rappel
preferences-auto-advance-wait-for-audio = Veuillez attendre l'audio
preferences-backup-available-backups = Sauvegardes disponibles
preferences-backup-create-now = Créer maintenant
preferences-backup-maximum-backups = Nombre maximum de sauvegardes
preferences-backup-minutes-between-backups = Nombre de minutes entre les copies de sécurité
preferences-backup-revert-to-backup = Rétablir la copie de sécurité
preferences-backup-revert-to-backup-confirm = Revenir à { $backup }? Toutes les modifications apportées depuis la sauvegarde seront perdues.
preferences-backup-reverted-to-backup = Copie de sécurité rétablie.
preferences-bottom-bar-size = Taille de la barre du bas
preferences-bottom-center = En bas au centre
preferences-bottom-left = En bas à gauche
preferences-bottom-right = En bas à droite
preferences-button-d = Bouton numéro { $num }
preferences-collection-day-starts = Début du jour
preferences-collection-learn-ahead-minutes = Apprendre en avance (minutes)
preferences-collection-mix = Mélanger
preferences-collection-new-first = Priorité aux nouvelles
preferences-collection-newreview-order = Ordre d'affichage des cartes nouvelles/révisées
preferences-collection-reviews-first = Révisions en premier
preferences-double-tap-prevention = Prévention du double coup
preferences-drawing-screen-ignores-fingers = Ignorer les doigts sur l’écran de dessin
preferences-feedback-ticks = Case de commentaire
preferences-fine = Fin
preferences-force-sync-confirm = Forcer une synchronisation à sens unique? Tous les changements d'un côté seront perdus.
preferences-full-sync = Forcer la synchronisation
preferences-gamepad-button-mapping = Mappage des boutons
preferences-gamepad-menu-button = Menu
preferences-gamepads = Manette de Jeu
preferences-height = Hauteur
preferences-huge = Très grande
preferences-ignore-fingers = Ignorer les doigts
preferences-interrupt-current-audio = Interrompre l’audio en cours
preferences-large = Grand
preferences-left = Gauche
preferences-left-shoulder = Gaucher
preferences-left-thumbstick-button = Bouton miniature à gauche
preferences-left-trigger = Déclencheur à gauche
preferences-logged-in-as = Logué en tant que:
preferences-long = Long
preferences-mid-center = Au milieu au centre
preferences-mid-left = Au milieu à gauche
preferences-mid-right = Au milieu à droite
preferences-never-type-answer = Ne jamais taper la réponse
preferences-next-times = Prochaines fois
preferences-normal = Normal
preferences-notifications = Notifications
preferences-notifications-alert-time = Heure d'alerte
preferences-notifications-alert-when-due = Alerte en cas de retard
preferences-notifications-app-icon-shows-due-count = L'icône de l'appli montre le compte de révision
preferences-notifications-settings-app-enable-notifications = Veuillez accéder aux paramètres d’iOS, puis à la section Anki et activez les notifications, badges et alertes.
preferences-pen-size = Taille du stylet
preferences-question-side = Côté question
preferences-remaining-count = Compte restant
preferences-right = Droite
preferences-right-shoulder = Droitier
preferences-right-thumbstick-button = Bouton miniature à droite
preferences-right-trigger = Déclencheur à droite
preferences-scratchpad-below-buttons = Bloc-notes sous les boutons
preferences-scratchpad-transparency = Transparence du bloc-notes
preferences-scratchpad-transparency-medium = Moyen
preferences-shake-action = Action « secouer »
preferences-short = Court
preferences-show-bottom-bar = Afficher la barre du bas
preferences-show-grid = Afficher la grille
preferences-show-top-bar = Afficher la Barre du Haut
preferences-small = Petit
preferences-swipe-down = Balayer en Bas
preferences-swipe-left = Balayer à Gauche
preferences-swipe-right = Balayer à Droite
preferences-swipe-up = Balayer en Haut
preferences-swipes = Balayer
preferences-swipes-must-begin-from-the-far = Les balayages doivent commencer à partir de l'extrême gauche ou droite de l'écran.
preferences-sync-sounds-images = Synchroniser les sons et les images
preferences-syncing = Synchronisation
preferences-tap-to-sync = Pour synchroniser, appuyez sur le bouton en bas de la liste des paquets.
preferences-taps = Toucher
preferences-theme = Thème
preferences-theme-bar-style = Style de la barre
preferences-theme-black = Noir
preferences-theme-dark = Sombre
preferences-theme-dark-translucent = Sombre et translucide
preferences-theme-force-off = Forcer la désactivation
preferences-theme-force-on = Forcer l'activation
preferences-theme-light-translucent = Clair et translucide
preferences-theme-night-mode-desc = Le mode nuit assombrit l'interface et affiche les cartes en blanc sur noir.
preferences-theme-night-mode-same-as-system = Suivre le système
preferences-theme-slate = Ardoise
preferences-thick = Épais
preferences-tools-overlay-button = Bouton outils superposés
preferences-tools-overlay-position = Position des outils superposés
preferences-top-center = En haut au centre
preferences-top-left = En haut à gauche
preferences-top-right = En haut à droite
preferences-undo-clears-all = ‘Annuler’ efface tout
preferences-when-answer-shown = Lorsque la réponse est affichée
preferences-when-question-shown = Lorsque la question est affichée
preferences-you-have-been-logged-out = Vous avez été déconnecté.
