actions-actions = פעולות
actions-add-new = הוסף חדש
actions-added-to-frequent-actions = נוסף לפעולות תכופות.
actions-all-actions = כל הפעולות
actions-already-in-frequent-actions = כבר בפעולות תכופות.
actions-an-error-occurred = התרחשה שגיאה: { $error }
actions-answer-again = ענה שוב
actions-answer-easy = תשובה קלה
actions-answer-good = תשובה טובה
actions-answer-hard = תשובה קשה
actions-are-you-sure = האם אתה בטוח?
actions-auto-advance = התקדמות אוטומטית
actions-bottom-bar = בר תחתון
actions-browse = דפדף
actions-card-buried = כרטיס טמון
actions-card-suspended = הכרטיס מושעה
actions-card-template = תבנית כרטיס
actions-confirm-delete = אשר את המחיקה
actions-create = ליצור
actions-current-audio-minus-5s = אודיו נוכחי -5שניות
actions-current-audio-plus-5s = אודיו נוכחי +5שניות
actions-custom-study-cant-be-used-on = לא ניתן להשתמש בלימוד מותאם אישית על חפיסה מסוננת.
actions-deck-statistics = סטטיסטיקות חפיסה
actions-delete-note-and-its-cards = למחוק את הפתק ואת הקלפים שלו?
actions-discard-changes = בטל שינויים
actions-done = בוצע
actions-downloading = מוריד...
actions-drag-here-to-remove = גרור לכאן כדי להסיר
actions-draw = צייר
actions-file-invalid-or-corrupt = קובץ לא חוקי או פגום.
actions-filtercram = סינון/דחיסה
actions-filtered-deck = { $num } חפיסות מסוננות
actions-forgot-card = שכח כרטיס
actions-frequent-actions = פעולות נפוצות
actions-leave-without-saving = לעזוב ללא שמירה?
actions-long-press-on-an-item-to = לחץ לחיצה ארוכה על פריט להתאמה אישית.
actions-mark = סמן
actions-mark-and-bury = סמן + קבור
actions-mark-and-suspend = סמן + השהה
actions-marked = מסומן
actions-no-current-card = אין כרטיס נוכחי.
actions-no-load-restore-backup = לא ניתן היה לטעון את האוסף שלך. נא לשחזר מגיבוי אוטומטי דרך מסך ההעדפות.
# (http://example.com) does not appear to be...
actions-not-valid-link = לא נראה כקישור http/https חוקי.
actions-note-and-its-cards-deleted = הפתקים והכרטיסים { $count } שלה נמחקו
actions-note-and-its-cards-suspended = הפתק והכרטיסים שלה { $count } הושעו
actions-note-buried = קבור פתק
actions-note-marked-and-buried = פתק מסומן ומוטמן
actions-nothing-to-undo = אין מה לבטל
actions-nothing-to-redo = אין מה לעשות מחדש
actions-off = כבוי
actions-please-tap-the-in-the = אנא הקש על '?' בפינה השמאלית העליונה כדי להתחיל.
actions-processing = מעבד...
actions-record-voice = הקלט קול
actions-record-voice-menu = תפריט הקלטת קול
actions-reset-card = אתחל כרטיס
actions-revert = לחזור
actions-review-undone = הלימוד בוטל
actions-select-deck = בחר חפיסה
actions-select-note-type = בחר סוג פתק
actions-show-answeranswer-good = הצג תשובה/תשובה טובה
actions-study-options = אפשרויות לימוד
actions-tools = כלים
actions-tools-overlay = שכבת על של כלים
actions-top-bar = בר עליון
actions-undo = בטל
actions-scroll-up = גלול למעלה
actions-scroll-down = גלול למטה

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

