actions-actions = פעולות
actions-add-new = הוסף חדש
actions-added-to-frequent-actions = נוסף לפעולות תכופות.
actions-all-actions = כל הפעולות
actions-already-in-frequent-actions = כבר בפעולות תכופות.
actions-an-error-occurred = התרחשה שגיאה: { $error }
actions-answer-easy = תשובה קלה
actions-are-you-sure = האם אתה בטוח?
actions-bottom-bar = בר תחתון
actions-browse = דפדף
actions-card-buried = כרטיס טמון
actions-card-suspended = הכרטיס מושעה
actions-card-template = תבנית כרטיס
actions-confirm-delete = אשר את המחיקה
actions-create = ליצור
actions-current-audio-minus-5s = אודיו נוכחי -5שניות
actions-current-audio-plus-5s = אודיו נוכחי +5שניות
actions-custom-study-cant-be-used-on = לא ניתן להשתמש בלימוד מותאם אישית על חפיסה מסוננת.
actions-deck-statistics = סטטיסטיקות חפיסה
actions-delete-note-and-its-cards = למחוק את הפתק ואת הקלפים שלו?
actions-discard-changes = בטל שינויים
actions-done = בוצע
actions-downloading = מוריד...
actions-drag-here-to-remove = גרור לכאן כדי להסיר
actions-draw = צייר
actions-file-invalid-or-corrupt = קובץ לא חוקי או פגום.
actions-filtercram = סינון/דחיסה
actions-filtered-deck = { $num } חפיסות מסוננות
actions-frequent-actions = פעולות נפוצות
actions-leave-without-saving = לעזוב ללא שמירה?
actions-long-press-on-an-item-to = לחץ לחיצה ארוכה על פריט להתאמה אישית.
actions-mark = סמן
actions-mark-and-bury = סמן + קבור
actions-mark-and-suspend = סמן + השהה
actions-marked = מסומן
actions-no-current-card = אין כרטיס נוכחי.
actions-no-load-restore-backup = לא ניתן היה לטעון את האוסף שלך. נא לשחזר מגיבוי אוטומטי דרך מסך ההעדפות.
# (http://example.com) does not appear to be...
actions-not-valid-link = לא נראה כקישור http/https חוקי.
actions-note-and-its-cards-deleted = הפתקים והכרטיסים { $count } שלה נמחקו
actions-note-and-its-cards-suspended = הפתק והכרטיסים שלה { $count } הושעו
actions-note-buried = קבור פתק
actions-note-marked-and-buried = פתק מסומן ומוטמן
actions-off = כבוי
actions-please-tap-the-in-the = אנא הקש על '?' בפינה השמאלית העליונה כדי להתחיל.
actions-record-voice = הקלט קול
actions-record-voice-menu = תפריט הקלטת קול
actions-reset-card = אתחל כרטיס
actions-revert = לחזור
actions-review-undone = הלימוד בוטל
actions-scratchpad = פנקס שרבוט
actions-scratchpad-size = גודל פנקס השרבוט
actions-select-deck = בחר חפיסה
actions-select-note-type = בחר סוג פתק
actions-show-answeranswer-good = הצג תשובה/תשובה טובה
actions-study-options = אפשרויות לימוד
actions-tools = כלים
actions-tools-overlay = שכבת על של כלים
actions-top-bar = בר עליון
actions-unbury-deck = הוצא חפיסה מהטמנה
actions-undo = בטל
actions-unmarked = לא מסומנים
actions-you-can-only-empty-a-filtered = אתה יכול לרוקן רק חפיסה מסוננת.
actions-you-can-only-rebuild-a-filtered = אתה יכול רק לבנות מחדש חפיסה מסוננת.
actions-scroll-up = גלול למעלה
actions-scroll-down = גלול למטה

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = רוקן
# create a filtered deck
actions-filter-short = מסנן
actions-add-short = הוספה
actions-answer-again-short = שוב
actions-answer-easy-short = קל
actions-answer-good-short = טוב
actions-answer-hard-short = קשה
actions-auto-advance-short = אוטו' מתק.
actions-bottom-bar-short = בר תחתון
actions-browse-short = דפדף
actions-bury-card-short = הטמן כ.
actions-bury-note-short = הטמן כ.
actions-card-info-short = מידע כ.
actions-card-template-short = תבנית
actions-current-audio-minus-5s-short = -5שנ'
actions-current-audio-plus-5s-short = +5שנ'
actions-custom-study-short = מותאם
actions-deck-statistics-short = סטט'.ח.
actions-decks-short = חפיסות
actions-delete-note-short = מחק
actions-edit-short = עריכה
actions-mark-and-bury-short = סמן.הטמן
actions-mark-and-suspend-short = סמן.השעה
actions-mark-short = סמן
actions-night-mode-short = לילה
actions-off-short = כבוי
actions-pause-audio-short = השהה
actions-rebuild-short = בנייה מחדש
actions-replay-audio-short = שחזור
actions-scratchpad-short = פנקס
actions-tools-short = כלים
actions-unbury-deck-short = הוצא טמון
actions-undo-short = בטל
actions-redo-short = בצע שוב
actions-scroll-up-short = למעלה
actions-scroll-down-short = למטה
actions-back = אחורה
