deck-options-add-options-group = הוסף קבוצת אפשרויות
deck-options-answer-time-cap = מגבלת זמן תשובה
deck-options-bury-related-new-cards = קלפים חדשים הקשורים להטמנה
deck-options-bury-related-reviews = קלפים חדשים הקשורים לסקירה
deck-options-defaults = ברירות המחדל
deck-options-delete-options-full-sync = מחיקת קבוצת אפשרויות זו תמנע מיזוג של שינויים ממכשירים אחרים בסנכרון הבא. להמשיך?
deck-options-display-in-order-added = נוספה תצוגה לפי סדר
deck-options-display-in-random-order = הצג בסדר אקראי
deck-options-full-sync-required = שם קבוצה
deck-options-group-name = שם קבוצה
deck-options-max-new-per-day = מקסימום ליום
deck-options-max-reviews-per-day = מקסימום סקירות ליום
deck-options-new-cards = קלפים חדשים
deck-options-options-group = קבוצת אפשרויות
deck-options-replay-q-audio-in-answer = נגן שמע שוב
deck-options-reset-all-settings-to-defaults = לאפס את כל ההגדרות לברירת המחדל?
deck-options-restore-defaults = שחזר ברירות מחדל
deck-options-steps = שלבים
