decks-a-deck-must-be-provided = חייבים לספק חפיסה.
decks-a-deck-named-already-exists = חפיסה בשם  ׳{ $name }׳ כבר קיימת
decks-a-deck-with-that-name-already = כבר קיים חפיסה עם שם זה.
decks-add-deck = הוסף חפיסה
decks-add-empty-deck = הוסף חפיסה ריקה
decks-addexport = הוסף/יצא
decks-cannot-delete = לא ניתן למחוק
decks-card-limit = מגבלת קלפים
decks-cards-in-a-filtered-deck-cant = לא ניתן להזיז קלפים בחפיסה מסוננת.
decks-custom-steps = שלבים מותאמים אישית
decks-deck-exists = חפיסה קיימת
decks-deck-label = חפיסה:
decks-deck-name = שם חפיסה
decks-deck-options = אפשרויות חפיסה
decks-download-link = קישור להורדה
decks-export-collection = יצא אוסף
decks-filtered-deck = חפיסה מסוננת
decks-import-from-itunes = יבא מ-iTunes
decks-invalid-deck-name = שם חפיסה שגוי.
decks-link-to-apkg-file-to-import = קישור לקובץ .apkg לייבוא:
decks-no-matches = אין התאמות
decks-return-by-delete = כדי להחזיר את כל הקלפים בבת אחת, החליקו מעל החפיסה הכחולה ברשימת החפיסות ומחקו אותה.
decks-shared-deck-list = רשימת חפיסות משותפות
decks-sync = סינכרון
decks-synchronize = לסנכרן
decks-the-default-deck-cannot-be-deleted = חפיסה ברירת המחדל לא ניתנת למחיקה.
decks-the-provided-deck-does-not-exist = החפיסה הנבחרת איננה קיימת.
decks-the-search-you-provided-did-not = החיפוש שסיפקת לא תאם לאף כרטיס.
decks-will-be-returned = הקלפים יוחזרו לחפיסה המקורית שלהם לאחר שתענו עליהם.
