editing-bold = מודגש
editing-cancel-and-lose-any-unsaved-changes = לבטל ולאבד את כל השינויים שלא נשמרו?
editing-cant-edit-original-image-data = לא ניתן לערוך - נתוני התמונה המקוריים לא נמצאו.
editing-card-returned-to-new-card-queue = הכרטיס הוחזר לתור הכרטיסים החדש.
editing-card-unsuspended = הכרטיס שוחזר
editing-from-camera = מהמצלמה
editing-from-file = מקובץ
editing-from-photos = מתמונה
editing-italic = נטוי
editing-next-field = שדה הבא
editing-note-deleted = הערה נמחקה
editing-note-suspended = הערה הוקפאה
# (Note) type: 
editing-note-type-prompt = סוג:
editing-note-unsuspended = הערה שוחזרה
editing-the-first-field-must-not-be = השדה הראשון חייב לא להיות ריק
editing-unable-to-obtain-image = לא מצליח להשיג תמונה
editing-unable-to-read-file = לא מצליח לקרוא קובץ
editing-underline = קו תחתי
editing-unexpected-file-extension = סיומת קובץ לא צפויה:
editing-unexpected-rich-text-format-please = פורמט טקסט עשיר לא צפוי - אנא נסה להעתיק ולהדביק.
editing-unexpected-status-code = קוד סטטוס לא צפוי:
editing-unsuspend-card = שחזר כרטיס
editing-unsuspend-note = שחזר הערה
editing-discard-changes-question = לבטל שינויים?
editing-discard = סגור מבלי לשמור
editing-keep-editing = המשך עריכה
