exporting-collection-saved-to-itunes = האוסף נשמר ב-iTunes.
exporting-export-to-itunes = ייצוא ל-iTunes
exporting-export-to-share-sheet = ייצוא לגיליון שיתוף
exporting-exporting = מייצא...
exporting-include-media2 = כלול מדיה
exporting-media-files-exported-d = קבצי מדיה יוצאו: { $count }...
