decks-a-deck-must-be-provided = Balíček musí být k dispozici.
decks-a-deck-named-already-exists = Balíček s názvem '{ $name }' již existuje.
decks-a-deck-with-that-name-already = Balíček s tímto názvem již existuje.
decks-add-deck = Přidat balíček
decks-add-empty-deck = Přidat prázdný balíček
decks-addexport = Přidat/Exportovat
decks-cannot-delete = Nelze smazat
decks-card-limit = Limit kartiček
decks-cards-in-a-filtered-deck-cant = Kartičky ve filtrovaném balíčku nelze přesouvat.
decks-custom-steps = Vlastní kroky
decks-deck-exists = Balíček existuje
decks-deck-label = Balíček:
decks-deck-name = Název balíčku
decks-deck-options = Možnosti balíčku
decks-download-link = Odkaz ke stažení
decks-export-collection = Exportovat kolekci
decks-filtered-deck = Filtrovaný balíček
decks-import-from-itunes = Importovat z iTunes
decks-invalid-deck-name = Neplatný název balíčku.
decks-link-to-apkg-file-to-import = Odkaz na soubor .apkg k importu:
decks-no-matches = Žádné shody
decks-return-by-delete = Chcete-li vrátit všechny karty najednou, přejeďte prstem přes modrý balíček v seznamu balíčků a smažte jej.
decks-shared-deck-list = Seznam sdílených balíčků
decks-sync = Synchronizace
decks-synchronize = Synchronizace
decks-the-default-deck-cannot-be-deleted = Výchozí balíček nelze smazat.
decks-the-provided-deck-does-not-exist = Zadaný balíček neexistuje.
decks-the-search-you-provided-did-not = Zadané hledání neodpovídá žádné kartičce.
decks-will-be-returned = Kartičky se po zodpovězení vrátí do původního balíčku.
