actions-actions = Дзеянні
actions-add-new = Дадаць новую
actions-added-to-frequent-actions = Дададзена ў частыя дзеянні.
actions-all-actions = Усе дзеянні
actions-already-in-frequent-actions = Ужо ў частых дзеяннях.
actions-an-error-occurred = Узнікла памылка: { $error }
actions-answer-again = Адказаць зноў
actions-answer-easy = Адказаць «лёгка»
actions-answer-good = Адказаць «добра»
actions-answer-hard = Адказаць «цяжка»
actions-are-you-sure = Вы ўпэўнены?
actions-bottom-bar = Ніжняя панэль
actions-browse = Прагляд
actions-card-buried = Картка адкладзена
actions-card-suspended = Картка прыпынена
actions-card-template = Шаблон карткі
actions-confirm-delete = Пацвердзіць выдаленне
actions-create = Стварыць
actions-current-audio-minus-5s = Бягучае аўдыя -5 с
actions-current-audio-plus-5s = Бягучае аўдыя +5 с
actions-deck-statistics = Статыстыка калоды
actions-delete-note-and-its-cards = Выдаліць нататку і яе карткі?
actions-discard-changes = Адхіліць змены?
actions-done = Гатова
actions-downloading = Спампоўванне...
actions-draw = Рысаваць
actions-filtered-deck = Фільтраваная калода { $num }
actions-forgot-card = Картка забыта
actions-mark = Пазначыць
actions-mark-and-bury = Пазначыць + адкласці
actions-mark-and-suspend = Пазначыць + прыпыніць
actions-marked = Пазначана
actions-no-current-card = Няма бягучай карткі.
actions-note-buried = Нататка адкладзена
actions-note-marked-and-buried = Нататка пазначана і адкладзена
actions-nothing-to-undo = Нечага адрабляць
actions-nothing-to-redo = Нечага ўзнаўляць
actions-off = Выкл.
actions-processing = Апрацоўка...
actions-record-voice = Запісаць голас
actions-reset-card = Скінуць картку
actions-scratchpad = Нататнік
actions-scratchpad-size = Памер нататніка
actions-select-deck = Выбраць калоду
actions-select-note-type = Выбраць тып нататкі
actions-show-answeranswer-good = Паказаць адк./адк. «добра»
actions-study-options = Параметры навучання
actions-tools = Інструменты
actions-top-bar = Верхняя панэль
actions-unbury-deck = Вярнуць калоду
actions-undo = Адрабіць
actions-you-can-only-rebuild-a-filtered = Вы можаце перасабраць толькі фільтраваную калоду.

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Ачысціць
# create a filtered deck
actions-filter-short = Фільтр
actions-add-short = Дадаць
actions-answer-again-short = Адказ З
actions-answer-easy-short = Адказ Л
actions-answer-good-short = Адказ Д
actions-answer-hard-short = Адказ Ц
actions-bottom-bar-short = Ніж.П
actions-browse-short = Прагляд
actions-bury-card-short = Адкл.К
actions-bury-note-short = Адкл.Н
actions-card-info-short = Звест.К
actions-card-template-short = Шаблон
actions-current-audio-minus-5s-short = -5с
actions-current-audio-plus-5s-short = +5с
actions-custom-study-short = Дапасаванае
actions-deck-statistics-short = Стат.К
actions-decks-short = Калоды
actions-delete-note-short = Выд.
actions-edit-short = Рэд.
actions-mark-and-bury-short = Паз&Адкл
actions-mark-and-suspend-short = Паз&Прып
actions-mark-short = Паз.
actions-night-mode-short = Ноч
actions-off-short = Выкл.
actions-pause-audio-short = Прып.
actions-rebuild-short = Перасаб.
actions-record-voice-short = Зап.Г.
actions-replay-voice-short = Паўт.Г
actions-replay-audio-short = Паўтор
actions-reset-card-short = Скін.К
actions-scratchpad-short = Натат-к
actions-scratchpad-size-short = Пам.Нат.
actions-set-due-date-short = Зад.Дату
actions-show-answer-short = Пак.Адк.
actions-show-answeranswer-good-short = Пак./Добра
actions-study-options-short = Пар.Нав
actions-suspend-card-short = Адкл.К
actions-suspend-note-short = Адкл.Н
actions-tools-short = Інстр.
actions-top-bar-short = В.Пан
actions-unbury-deck-short = Вярн.
actions-undo-short = Адрабіць
actions-redo-short = Узнавіць
