deck-options-add-options-group = Дадаць групу параметраў
deck-options-defaults = Перадвызначаныя
deck-options-display-in-order-added = Адлюстроўваць у парадку дадавання
deck-options-group-name = Назва групы
deck-options-new-cards = Новыя карткі
deck-options-options-group = Група параметраў
deck-options-replay-q-audio-in-answer = Паўтарыць гук у адказе
deck-options-reset-all-settings-to-defaults = Скінуць усе налады да перадвызначаных?
deck-options-restore-defaults = Аднавіць перадвызначаныя параметры
deck-options-steps = Крокі
