deck-options-add-options-group = Дадаць групу параметраў
deck-options-bury-related-reviews = Адкладваць звязаныя карткі да перагляду
deck-options-defaults = Прадвызначаныя
deck-options-display-in-order-added = Адлюстроўваць у парадку дадавання
deck-options-display-in-random-order = Паказваць у выпадковым парадку
deck-options-full-sync-required = Патрабуецца поўная сінхранізацыя
deck-options-group-name = Назва групы
deck-options-max-reviews-per-day = Макс. пераглядаў на дзень
deck-options-new-cards = Новыя карткі
deck-options-options-group = Група параметраў
deck-options-replay-q-audio-in-answer = Паўтарыць гук у адказе
deck-options-reset-all-settings-to-defaults = Скінуць усе налады да прадвызначаных?
deck-options-restore-defaults = Аднавіць прадвызначаныя параметры
deck-options-steps = Крокі
