decks-a-deck-must-be-provided = Павінна быць пададзена калода.
decks-a-deck-named-already-exists = Калода з назвай «{ $name }» ужо існуе.
decks-a-deck-with-that-name-already = Калода з гэтай назвай ужо існуе.
decks-add-deck = Дадаць калоду
decks-add-empty-deck = Дадаць пустую калоду
decks-addexport = Дадаць/Экспартаваць
decks-cannot-delete = Немагчыма выдаліць
decks-card-limit = Ліміт картак
decks-cards-in-a-filtered-deck-cant = Карткі ў фільтраванай калодзе не могуць быць перамешчаны.
decks-custom-steps = Наладжвальныя крокі
decks-deck-exists = Калода існуе
decks-deck-label = Калода:
decks-deck-name = Назва калоды
decks-deck-options = Параметры калоды
decks-download-link = Спасылка на спампаванне
decks-export-collection = Экспартаваць калекцыю
decks-filtered-deck = Фільтраваная калода
decks-import-from-itunes = Імпартаваць з iTunes
decks-invalid-deck-name = Памылковая назва калоды.
decks-link-to-apkg-file-to-import = Спасылка на файл .apkg для імпарту:
decks-no-matches = Няма супадзенняў
decks-shared-deck-list = Спіс абагуленых калод
decks-sync = Сінхранізацыя
decks-synchronize = Сінхранізаваць
decks-the-default-deck-cannot-be-deleted = Прадвызначаная калода не можа быць выдалена.
decks-the-provided-deck-does-not-exist = Дадзеная калода не існуе.
