preferences-about = Аб праграме
preferences-answer-side = Бок з адказам
preferences-audio-buttons = Кнопкі аўдыя
preferences-auto-advance-answer-action = Дзеянне адказу
preferences-auto-advance-answer-seconds = Секунд на адказ
preferences-auto-advance-auto-advance-to-start = Каб пачаць аўтаматычны пераход паміж карткамі, выкарыстайце дзеянне «Aўтапрасоўванне».
preferences-auto-advance-do-nothing = Не рабіць нічога
preferences-auto-advance-question-seconds = Секунд на пытанне
preferences-auto-advance-show-reminder = Паказваць напамін
preferences-auto-advance-wait-for-audio = Чакаць аўдыя
preferences-backup-available-backups = Даступныя рэзервовыя копіі
preferences-backup-create-now = Стварыць зараз
preferences-backup-maximum-backups = Макс. лічба рэзервовых копій
preferences-backup-minutes-between-backups = Хвілін паміж рэзервовымі копіямі
preferences-backup-revert-to-backup = Вярнуць да рэзервовай копіі
preferences-backup-reverted-to-backup = Вярнута да рэзервовай копіі.
preferences-bottom-bar-size = Памер ніжняй панэлі
preferences-bottom-center = Знізу па цэнтры
preferences-bottom-left = Знізу злева
preferences-bottom-right = Знізу справа
preferences-button-d = Кнопка { $num }
preferences-collection-day-starts = Пачатак дня
preferences-collection-mix = Змешваць
preferences-collection-new-first = Спачатку новыя
preferences-collection-newreview-order = Парадак новых/пераглядаў
preferences-collection-reviews-first = Спачатку перагляды
preferences-double-tap-prevention = Прадухіленне двайных націсканняў
preferences-full-sync = Поўная сінхранізацыя
preferences-gamepad-menu-button = Меню
preferences-gamepads = Геймпады
preferences-height = Вышыня
preferences-ignore-fingers = Ігнараваць пальцы
preferences-interrupt-current-audio = Перарваць бягучае аўдыя
preferences-left = Злева
preferences-logged-in-as = Выкананы ўваход як:
preferences-long = Доўгае
preferences-mid-center = У сярэдзіне па цэнтры
preferences-mid-left = У сярэдзіне злева
preferences-mid-right = У сярэдзіне справа
preferences-never-type-answer = Ніколі не ўводзіць адказ
preferences-never-show-scratchpad = Не паказваць нататнік
preferences-never-show-scratchpad-enabled = «Не паказваць нататнік» уключана на экране параметраў.
preferences-next-times = Наступныя разы
preferences-notifications = Апавяшчэнні
preferences-question-side = Бок з пытаннем
preferences-right = Справа
preferences-scratchpad-below-buttons = Нататнік пад кнопкамі
preferences-scratchpad-transparency = Празрыстасць нататніка
preferences-scratchpad-transparency-full = Поўная
preferences-scratchpad-transparency-medium = Сярэдняя
preferences-scratchpad-transparency-none = Няма
preferences-scratchpad-transparency-slight = Невялікая
preferences-shake-action = Дзеянне ўстрэсвання
preferences-short = Кароткае
preferences-show-bottom-bar = Паказваць ніжнюю панэль
preferences-show-grid = Паказваць сетку
preferences-show-top-bar = Паказваць верхнюю панэль
preferences-small = Маленькі
preferences-swipe-down = Чырканне ўніз
preferences-swipe-left = Чырканне ўлева
preferences-swipe-right = Чырканне ўправа
preferences-swipe-up = Чырканне ўверх
preferences-swipes = Жэсты чырканняў
preferences-sync-sounds-images = Сінхранізаваць гукі і відарысы
preferences-syncing = Сінхранізацыя
preferences-tap-to-sync = Каб актываваць сінхранізаванне, націсніце на кнопку сінхранізацыі на экране са спісам калод.
preferences-taps = Дотыкі
preferences-theme = Тэма
preferences-theme-bar-style = Стыль панэлі
preferences-theme-black = Чорны
preferences-theme-dark-translucent = Цёмная і паўпразрыстая
preferences-theme-light-translucent = Светлая і паўпразрыстая
preferences-theme-night-mode-desc = Начны рэжым зацямняе інтэрфейс і адлюстроўвае карткі белым шрыфтам на чорным фоне.
preferences-top-center = Зверху па цэнтры
preferences-top-left = Зверху злева
preferences-top-right = Зверху справа
preferences-undo-clears-all = «Адрабіць» ачышчае ўсё
preferences-when-answer-shown = Калі паказаны адказ
preferences-when-question-shown = Калі паказана пытанне
preferences-you-have-been-logged-out = Выкананы выхад.
preferences-editing = Рэдагаванне
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Макс. памер відарыса (доўгі край)
