preferences-about = Аб праграме
preferences-answer-keeps-zoom = Захоўваць маштабаванне пры адказе
preferences-answer-side = Бок з адказам
preferences-audio-buttons = Кнопкі аўдыя
preferences-auto-advance-answer-action = Дзеянне адказу
preferences-auto-advance-answer-seconds = Секунд на адказ
preferences-auto-advance-auto-advance-to-start = Для аўтаматычнага пераходу паміж карткамі выкарыстайце дзеянне «Aўтапрасоўванне».
preferences-auto-advance-do-nothing = Не рабіць нічога
preferences-auto-advance-question-seconds = Секунд на пытанне
preferences-backup-available-backups = Даступныя рэзервовыя копіі
preferences-backup-create-now = Стварыць зараз
preferences-backup-maximum-backups = Макс. лічба рэзервовых копій
preferences-backup-minutes-between-backups = Хвілін паміж рэзервовымі копіямі
preferences-backup-revert-to-backup = Вярнуць да рэзервовай копіі
preferences-backup-revert-to-backup-confirm = Вярнуцца да { $backup }? Любыя змены зробленыя пасля рэзервовага капіявання будуць страчаны.
preferences-backup-reverted-to-backup = Вярнута да рэзервовай копіі.
preferences-bottom-bar-size = Памер ніжняй панэлі
preferences-bottom-center = Знізу па цэнтры
preferences-bottom-left = Злева ўнізе
preferences-bottom-right = Справа ўнізе
preferences-button-d = Кнопка { $num }
preferences-collection-day-starts = Пачатак дня
preferences-collection-learn-ahead-minutes = Хвілін вывучэння з апярэджаннем
preferences-collection-mix = Змешваць
preferences-collection-new-first = Спачатку новыя
preferences-collection-newreview-order = Парадак новых/пераглядаў
preferences-collection-reviews-first = Спачатку перагляды
preferences-double-tap-prevention = Прадухіленне двайных націсканняў
preferences-fine = Тонкае
preferences-force-sync-confirm = Прымусіць да аднабаковай сінхранізацыі? Усе змены на адным з бакоў будуць страчаны.
preferences-full-sync = Поўная сінхранізацыя
preferences-gamepad-button-mapping = Супастаўленне кнопак
preferences-gamepad-menu-button = Меню
preferences-gamepads = Геймпады
preferences-height = Вышыня
preferences-huge = Вялізнае
preferences-ignore-fingers = Ігнараваць пальцы
preferences-interrupt-current-audio = Перарваць бягучае аўдыя
preferences-large = Буйное
preferences-left = Злева
# gamepad
preferences-left-shoulder = Левы бампер
# gamepad
preferences-left-trigger = Левы курок
preferences-logged-in-as = Выкананы ўваход як:
preferences-long = Доўгае
preferences-mid-center = У сярэдзіне па цэнтры
preferences-mid-left = У сярэдзіне злева
preferences-mid-right = У сярэдзіне справа
preferences-never-type-answer = Ніколі не ўводзіць адказ
preferences-never-show-scratchpad = Не паказваць нататнік
preferences-never-show-scratchpad-enabled = «Не паказваць нататнік» уключана на экране параметраў.
preferences-next-times = Наступныя разы
preferences-normal = Звычайнае
preferences-notifications = Апавяшчэнні
preferences-notifications-alert-time = Час абвесткі
preferences-notifications-alert-when-due = Абвестка, калі чакаюць карткі
preferences-notifications-app-icon-shows-due-count = К-ць перапраглядаў на значке
preferences-pen-size = Памер пяра
preferences-question-side = Бок з пытаннем
preferences-remaining-count = Колькасць застаўшыхся
preferences-right = Справа
# gamepad
preferences-right-shoulder = Правы бампер
# gamepad
preferences-right-trigger = Правы курок
preferences-scratchpad-below-buttons = Нататнік пад кнопкамі
preferences-scratchpad-transparency = Празрыстасць нататніка
preferences-scratchpad-transparency-full = Поўная
preferences-scratchpad-transparency-medium = Сярэдняя
preferences-scratchpad-transparency-none = Няма
preferences-scratchpad-transparency-slight = Невялікая
preferences-shake-action = Дзеянне ўстрэсвання
preferences-short = Кароткае
preferences-show-bottom-bar = Паказваць ніжнюю панэль
preferences-show-grid = Паказваць сетку
preferences-show-top-bar = Паказваць верхнюю панэль
preferences-small = Маленькае
preferences-swipe-down = Чырканне ўніз
preferences-swipe-left = Чырканне ўлева
preferences-swipe-right = Чырканне ўправа
preferences-swipe-up = Чырканне ўверх
preferences-swipes = Жэсты чырканняў
preferences-sync-sounds-images = Сінхранізаваць гукі і відарысы
preferences-syncing = Сінхранізацыя
preferences-tap-to-sync = Каб актываваць сінхранізаванне, націсніце на кнопку сінхранізацыі на экране са спісам калод.
preferences-taps = Дотыкі
preferences-theme-bar-style = Стыль панэлі
preferences-theme-black = Чорная
preferences-theme-dark-translucent = Цёмная і паўпразрыстая
preferences-theme-force-off = Прымусова выключыць
preferences-theme-force-on = Прымусова ўключыць
preferences-theme-light-translucent = Светлая і паўпразрыстая
preferences-theme-night-mode-desc = Начны рэжым зацямняе інтэрфейс і адлюстроўвае карткі белым шрыфтам на чорным фоне.
preferences-theme-night-mode-same-as-system = Прытрымлівацца сістэмнага
preferences-theme-slate = Цёмна-шэрая
preferences-thick = Тоўстае
preferences-tools-overlay-button = Кнопка накладкі з інструментамі
preferences-tools-overlay-position = Пазіцыя накладкі з інструментамі
preferences-top-center = Зверху па цэнтры
preferences-top-left = Злева ўверсе
preferences-top-right = Справа ўверсе
preferences-undo-clears-all = «Адрабіць» ачышчае ўсё
preferences-when-answer-shown = Калі паказаны адказ
preferences-when-question-shown = Калі паказана пытанне
preferences-you-have-been-logged-out = Выкананы выхад.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Макс. памер відарыса (доўгі край)
preferences-editing-crop-camera-photos = Абразаць здымкі з камеры
preferences-loop-video = Зацыкліваць відэа
preferences-show-video-controls = Паказваць кіраванне відэа
preferences-auto-correct = Аўтавыпраўленне
preferences-strip-hebrew-vowels = Прыбіраць галосныя ў іўрыце
