profiles-a-profile-with-that-name-already = Профіль з такім імем ужо існуе.
profiles-add-profile = Дадаць профіль
profiles-finishing-backup = Сканчэнне рэзервовага капіявання...
profiles-please-provide-some-text-avoiding-symbols = Увядзіце нейкі тэкст, пазбягаючы сімвалаў і падкрэсліванняў.
profiles-please-select-another-profile-first = Спачатку выберыце іншы профіль.
profiles-profile-name = Імя профілю
profiles-rename-profile = Перайменаваць профіль
profiles-unable-to-open-safari-please = Немагчыма адкрыць Safari - праверце налады бацькоўскага кантролю.
profiles-welcome = Вітаем!
