actions-actions = Ações
actions-add-new = Adicionar Novo
actions-added-to-frequent-actions = Adicionado às ações frequentes.
actions-all-actions = Todas as Ações
actions-already-in-frequent-actions = Já em ações frequentes.
actions-an-error-occurred = Um erro ocorreu: { $error }
actions-answer-again = Responder Novamente
actions-answer-easy = Resposta Fácil
actions-answer-good = Resposta Boa
actions-answer-hard = Resposta Difícil
actions-are-you-sure = Você tem certeza?
actions-auto-advance = Avanço Automático
actions-bottom-bar = Barra Inferior
actions-browse = Painel
actions-card-buried = Cartão ocultado
actions-card-suspended = Cartão suspenso
actions-card-template = Modelo do Cartão
actions-confirm-delete = Confirmar Exclusão
actions-create = Criar
actions-current-audio-minus-5s = Áudio Atual -5s
actions-current-audio-plus-5s = Áudio Atual +5s
actions-custom-study-cant-be-used-on = Estudo personalizado não pode ser usado num baralho filtrado.
actions-deck-statistics = Estatísticas do Baralho
actions-delete-note-and-its-cards = Excluir nota e seus cartões?
actions-discard-changes = Descartar Alterações
actions-done = Feito
actions-downloading = Baixando...
actions-drag-here-to-remove = Arraste aqui para remover
actions-draw = Desenhar
actions-file-invalid-or-corrupt = Arquivo inválido ou corrompido.
actions-filtercram = Filtrar/Agrupar
actions-filtered-deck = Baralho Filtrado { $num }
actions-forgot-card = Esquecer cartão
actions-frequent-actions = Ações Frequentes
actions-leave-without-saving = Sair sem salvar?
actions-long-press-on-an-item-to = Pressione e segure um item para personalizar.
actions-mark = Marcar
actions-mark-and-bury = Marcar + Ocultar
actions-mark-and-suspend = Marcar + Suspender
actions-marked = Marcado
actions-no-current-card = Não há cartão.
actions-no-load-restore-backup = Não foi possível carregar sua coleção. Restaure a partir de uma cópia de segurança automática por meio da tela de preferências.
# (http://example.com) does not appear to be...
actions-not-valid-link = não parece ser um link http/https válido.
actions-note-and-its-cards-deleted = Nota e seus { $count } cartões excluídos
actions-note-and-its-cards-suspended = Nota e seu(s) { $count } cartão(s) suspenso(s)
actions-note-buried = Nota ocultada
actions-note-marked-and-buried = Nota marcada e ocultada
actions-nothing-to-undo = Nada para desfazer
actions-nothing-to-redo = Nada para refazer
actions-off = Desativado
actions-please-tap-the-in-the = Por favor, toque no '?' no canto superior esquerdo para começar.
actions-processing = Processando...
actions-record-voice = Gravar Voz
actions-record-voice-menu = Menu de Gravação de Voz
actions-reset-card = Reiniciar Cartão
actions-revert = Reverter
actions-review-undone = Revisão desfeita
actions-scratchpad = Caderno de Rascunhos
actions-scratchpad-size = Tamanho do Caderno de Rascunhos
actions-select-deck = Selecionar Baralho
actions-select-note-type = Selecionar Tipo de Nota
actions-show-answeranswer-good = Mostrar Resposta Boa
actions-study-options = Opções de Estudo
actions-tools = Ferramentas
actions-tools-overlay = Sobreposição de Ferramentas
actions-top-bar = Barra Superior
actions-unbury-deck = Desocultar Baralho
actions-undo = Desfazer
actions-unmarked = Desmarcado
actions-you-can-only-empty-a-filtered = Você só pode esvaziar um baralho filtrado.
actions-you-can-only-rebuild-a-filtered = Você só pode reconstruir um baralho filtrado.
actions-scroll-up = Rolar para cima
actions-scroll-down = Rolar para baixo

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = Vazio
# create a filtered deck
actions-filter-short = Filtrar
actions-add-short = Adicionar
actions-answer-again-short = Resp. A
actions-answer-easy-short = Resp. E
actions-answer-good-short = Resp. B
actions-answer-hard-short = Resp. D
actions-auto-advance-short = Av. Aut.
actions-bottom-bar-short = Barra. Inf
actions-browse-short = Navegar
actions-bury-card-short = Ocul. C
actions-bury-note-short = Ocul. N
actions-card-info-short = Info. C
actions-card-template-short = Modelo
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-short = Personalizado
actions-deck-statistics-short = Estat. B
actions-decks-short = Baralhos
actions-delete-note-short = Excluir
actions-edit-short = Editar
actions-mark-and-bury-short = M&O
actions-mark-and-suspend-short = M&S
actions-mark-short = Marcar
actions-night-mode-short = Noturno
actions-off-short = Deslig.
actions-pause-audio-short = Pausar
actions-rebuild-short = Recons.
actions-record-voice-short = Gravar
actions-replay-voice-short = Rep. Á
actions-replay-audio-short = Repetir
actions-reset-card-short = Rein. C
actions-scratchpad-short = Caderno
actions-scratchpad-size-short = Cad. R
actions-set-due-date-short = Def. D
actions-show-answer-short = Most. R
actions-show-answeranswer-good-short = Most/R
actions-study-options-short = Opç. E
actions-suspend-card-short = Susp. C
actions-suspend-note-short = Susp. N
actions-tools-short = Ferram.
actions-top-bar-short = Bar. S
actions-unbury-deck-short = Revelar
actions-undo-short = Desf.
actions-redo-short = Ref.
actions-scroll-up-short = Cima
actions-scroll-down-short = Baixo
