actions-actions = Ações
actions-add-new = Adicionar Novo
actions-added-to-frequent-actions = Adicionado às ações frequentes.
actions-all-actions = Todas as Ações
actions-an-error-occurred = Um erro ocorreu: { $error }
actions-are-you-sure = Você tem certeza?
actions-browse = Painel
actions-card-buried = Cartão ocultado
actions-card-info = Informação do Cartão
actions-card-info-short = C.Info
actions-card-suspended = Cartão suspenso
actions-card-template = Modelo do Cartão
actions-confirm-delete = Confirmar Exclusão
actions-create = Criar
actions-current-audio-minus-5s-short = -5s
actions-current-audio-plus-5s-short = +5s
actions-custom-study-cant-be-used-on = Estudo personalizado não pode ser usado num baralho filtrado.
actions-custom-study-short = Personalizado
actions-deck-statistics = Estatísticas do Baralho
actions-delete-note-and-its-cards = Excluir nota e seus cartões?
actions-delete-note-short = Excl
actions-discard-changes = Descartar Alterações
actions-done = Feito
actions-downloading = Baixando...
actions-draw = Desenhar
actions-file-invalid-or-corrupt = Arquivo inválido ou corrompido.
actions-filtered-deck = Baralho Filtrado { $num }
actions-frequent-actions = Ações Frequentes
actions-how-many-days-in-the-future = Quantos dias no futuro?
actions-invalid-number-of-days = Número de dias inválido.
actions-mark-and-bury = Marcar + Ocultar
actions-mark-and-suspend = Marcar + Suspender
actions-marked = Marcado
actions-night-mode-short = Noturno
actions-no-load-restore-backup = Não foi possível carregar sua coleção. Restaure a partir de uma cópia de segurança automática por meio da tela de preferências.
actions-not-valid-link = não parece ser um link http/https válido.
actions-note-and-its-cards-deleted = Nota e seus { $count } cartões excluídos
actions-note-and-its-cards-suspended = Nota e seu(s) { $count } cartão(s) suspenso(s)
actions-note-buried = Nota ocultada
actions-pause-audio-short = Pausar
actions-processing = Processando...
actions-record-voice = Gravar Voz
actions-record-voice-short = Gravar
actions-replay-audio-short = Repetir
actions-reset-card = Reiniciar Cartão
actions-reset-card-short = Reiniciar.C
actions-revert = Reverter
actions-select-deck = Selecionar Baralho
actions-select-note-type = Selecionar Tipo de Nota
actions-study-options = Opções de Estudo
actions-tools = Ferramentas
actions-undo = Desfazer
actions-you-can-only-empty-a-filtered = Você só pode esvaziar um baralho filtrado.
