browsing-append = Acrescentar
browsing-card-updated = Cartão Atualizado
browsing-column-1 = Coluna 1
browsing-column-2 = Coluna 2
browsing-confirm-reset = Confirmar Redefinição
browsing-dd-selected = %d/%d selecionado
browsing-note-created = Nota Criada
browsing-note-updated = Nota Atualizada
browsing-note2 = Nota:
browsing-repetitions = Repetições
browsing-reset-cards = Reiniciar Cartões
browsing-second-column-19 = Segunda Coluna (1->9)
browsing-second-column-91 = Segunda Coluna (9->1)
browsing-select-all = Selecionar Tudo
browsing-tag = Etiqueta:
