deck-options-add-options-group = Adicionar Grupo de Opções
deck-options-answer-time-cap = Limite de tempo de resposta
deck-options-bury-related-new-cards = Ocultar novos cartões relacionados
deck-options-bury-related-reviews = Ocultar revisões relacionadas
deck-options-defaults = Padrões
deck-options-delete-options-full-sync = A exclusão deste grupo de opções impedirá que quaisquer alterações sejam mescladas de outros dispositivos na próxima sincronização. Continuar?
deck-options-display-in-order-added = Exibir na ordem de inclusão
deck-options-display-in-random-order = Exibir em ordem aleatória
deck-options-full-sync-required = Sincronização completa necessária
deck-options-group-name = Nome do grupo
deck-options-max-new-per-day = Máximo de novos por dia
deck-options-max-reviews-per-day = Máximo de revisões por dia
deck-options-new-cards = Novos cartões
deck-options-options-group = Grupo de opções
deck-options-replay-q-audio-in-answer = Repetir q. áudio em resposta
deck-options-reset-all-settings-to-defaults = Redefinir todas as configurações para as padrões?
deck-options-restore-defaults = Restaurar Padrões
deck-options-steps = Passos
