decks-a-deck-must-be-provided = Um baralho deve ser fornecido.
decks-a-deck-named-already-exists = Um baralho nomeado '%@' já existe.
decks-a-deck-with-that-name-already = Um baralho com esse nome já existe.
decks-add-deck = Adicionar Baralho
decks-add-empty-deck = Adicionar Baralho Vazio
decks-addexport = Adicionar/Exportar
decks-cannot-delete = Não pode Apagar
decks-card-limit = Limite do cartão
decks-cards-in-a-filtered-deck-cant = Cartões num baralho filtrado não podem ser movidos.
decks-deck-label = Baralho:
decks-deck-name = Nome do Baralho
decks-deck-options = Opções do Baralho
decks-export-collection = Exportar Coleção
decks-filtered-deck = Baralho Filtrado
decks-import-from-itunes = Importar do iTunes
decks-invalid-deck-name = Nome do baralho inválido.
decks-return-by-delete = Para retornar todos os cartões de uma vez, passe o dedo sobre o baralho azul na lista de baralhos e exclua-o.
decks-sync = Sincronizar
decks-synchronize = Sincronizar
decks-the-default-deck-cannot-be-deleted = O baralho padrão não pode ser excluído.
decks-the-provided-deck-does-not-exist = O baralho fornecido não existe.
decks-the-search-you-provided-did-not = A pesquisa que você forneceu não correspondeu a nenhum cartão.
decks-will-be-returned = Os cartões serão devolvidos ao seu baralho original conforme você os responde.
