editing-bold = Negrito
editing-cancel-and-lose-any-unsaved-changes = Cancelar e perder as alterações não salvas?
editing-cant-edit-original-image-data = Não é possível editar - dados da imagem original não encontrados.
editing-card-unsuspended = Cartão não suspenso
editing-from-camera = Da Câmera
editing-from-file = De Arquivo
editing-from-photos = De Fotos
editing-italic = Itálico
editing-next-field = Próximo Campo
editing-note-deleted = Nota excluída
editing-note-suspended = Nota suspensa
editing-note-type-prompt = Tipo:
editing-note-unsuspended = Nota não suspensa
editing-the-first-field-must-not-be = O primeiro campo não deve estar vazio.
editing-unable-to-obtain-image = Não é possível obter a imagem
editing-unable-to-read-file = Não é possível ler o arquivo
editing-underline = Sublinhado
editing-unexpected-file-extension = Extensão de arquivo inesperada:
editing-unexpected-status-code = Código de status inesperado:
editing-unsuspend-card = Cartão não Suspenso
editing-unsuspend-note = Nota não Suspensa
