exporting-collection-saved-to-itunes = Coleção salva no iTunes.
exporting-export-to-itunes = Exportar para o iTunes
exporting-export-to-share-sheet = Exportar para uma planilha compartilhada
exporting-exporting = Exportando...
exporting-include-media2 = Incluir Mídia
exporting-media-files-exported-d = Arquivos de mídia exportados: { $count }...
