preferences-about = Sobre
preferences-always-duck-and-ignore-mute = Sempre Abaixar + Ignorar Mudo
preferences-answer-keeps-zoom = A resposta mantém o Zoom
preferences-answer-side = Resposta
preferences-audio-buttons = Botões de áudio
preferences-auto-advance-answer-action = Ação de resposta
preferences-auto-advance-answer-seconds = Segundos de resposta
preferences-auto-advance-auto-advance-to-start = Para começar a avançar automaticamente, use a ação 'Auto Advance'.
preferences-auto-advance-do-nothing = Nada a fazer
preferences-auto-advance-question-seconds = Pergunta em segundos
preferences-backup-available-backups = Backups disponíveis
preferences-backup-create-now = Criar Agora
preferences-backup-maximum-backups = Máximo de Backups
preferences-backup-minutes-between-backups = Minutos entre backups
preferences-backup-revert-to-backup = Reverter para o Backup
preferences-backup-revert-to-backup-confirm = Reverter para { $backup }? Quaisquer alterações feitas desde o backup serão perdidas.
preferences-backup-reverted-to-backup = Revertido para o backup.
preferences-bottom-bar-size = Tamanho da barra inferior
preferences-bottom-center = Centro inferior
preferences-bottom-left = Inferior esquerdo
preferences-bottom-right = Inferior direito
preferences-button-d = Botão { $num }
preferences-collection-day-starts = Início do dia
preferences-collection-learn-ahead-minutes = Aprender além do limite (minutos)
preferences-collection-mix = Mix
preferences-collection-new-first = Novo primeiro
preferences-collection-newreview-order = Novo/Revisar Pedido
preferences-collection-reviews-first = Revisões primeiro
preferences-double-tap-prevention = Prevenção de toque duplo
preferences-drawing-screen-ignores-fingers = A tela de desenho ignora os dedos
preferences-feedback-ticks = Marcações de feedback
preferences-fine = Bem
preferences-force-sync-confirm = Forçar uma sincronização unidirecional? Todas as alterações em um lado serão perdidas.
preferences-full-sync = Sincronização Completa
preferences-gamepad-button-mapping = Mapeamento de botões
preferences-gamepad-menu-button = Menu
preferences-gamepads = Controles de jogo
preferences-height = Altura
preferences-huge = Enorme
preferences-ignore-fingers = Ignorar dedos
preferences-interrupt-current-audio = Interromper Áudio Atual
preferences-large = Grande
preferences-left = Esquerda
# gamepad
preferences-left-shoulder = Shoulder Esquerdo
# gamepad
preferences-left-thumbstick-button = Botão do polegar esquerdo
# gamepad
preferences-left-trigger = Gatilho esquerdo
preferences-logged-in-as = Logado como:
preferences-long = Grande
preferences-mid-center = Centro Médio
preferences-mid-left = Centro esquerdo
preferences-mid-right = Centro direito
preferences-never-type-answer = Nunca digite a resposta
preferences-never-show-scratchpad = Nunca mostrar o Scratchpad
preferences-never-show-scratchpad-enabled = Nunca mostrar o Scratchpad está ativado nas Preferências.
preferences-next-times = Próximas Vezes
preferences-normal = Normal
preferences-notifications = Notificações
preferences-notifications-alert-time = Horário de Alerta
preferences-notifications-alert-when-due = Alertar quando houver cartões pendentes
preferences-notifications-app-icon-shows-due-count = O ícone do aplicativo mostra a contagem que falta
preferences-notifications-settings-app-enable-notifications = Acesse as Configurações do aplicativo no iOS, localize a seção do Anki e ative as notificações, emblemas e alertas.
preferences-pen-size = Tamanho da caneta
preferences-question-side = Lado da pergunta
preferences-remaining-count = Contagem restante
preferences-right = Direita
# gamepad
preferences-right-shoulder = Shoulder Direito
# gamepad
preferences-right-thumbstick-button = Botão do polegar direito
# gamepad
preferences-right-trigger = Gatilho direito
preferences-scratchpad-below-buttons = Bloco de rascunho abaixo dos botões
preferences-scratchpad-transparency = Transparência do bloco de rascunho
preferences-scratchpad-transparency-full = Completo
preferences-scratchpad-transparency-medium = Médio
preferences-scratchpad-transparency-none = Nenhum
preferences-scratchpad-transparency-slight = Pouca
preferences-shake-action = Agitar
preferences-short = Baixo
preferences-show-bottom-bar = Mostrar barra inferior
preferences-show-grid = Mostrar grade
preferences-show-top-bar = Mostrar barra superior
preferences-small = Pequeno
preferences-swipe-down = Deslizar para Baixo
preferences-swipe-left = Deslizar para Esquerda
preferences-swipe-right = Deslizar para a Direita
preferences-swipe-up = Deslizar para Cima
preferences-swipes = Deslizar
preferences-swipes-must-begin-from-the-far = O deslizar devem começar na extremidade esquerda ou direita da tela.
preferences-sync-sounds-images = Sincronizar Sons & Imagens
preferences-syncing = Sincronizando
preferences-tap-to-sync = Para ativar a sincronização, toque no botão sincronizar na tela de lista de baralho.
preferences-taps = Toques
preferences-theme-bar-style = Estilo da Barra
preferences-theme-black = Preto
preferences-theme-dark-translucent = Escuro & Translúcido
preferences-theme-force-off = Forçar Desativado
preferences-theme-force-on = Forçar Ativado
preferences-theme-light-translucent = Leve e Translúcido
preferences-theme-night-mode-desc = O modo noturno escurece a interface e exibe os cartões em branco no preto.
preferences-theme-night-mode-same-as-system = Conforme o Sistema
preferences-theme-slate = Slate
preferences-thick = Grossura
preferences-tools-overlay-button = Botão de sobreposição de Ferramentas
preferences-tools-overlay-position = Posição de sobreposição de Ferramentas
preferences-top-center = Superior central
preferences-top-left = Superior Esquerdo
preferences-top-right = Superior Direito
preferences-undo-clears-all = Desfazer Limpar Tudo
preferences-when-answer-shown = Quando a resposta for mostrada
preferences-when-question-shown = Quando a pergunta for mostrada
preferences-you-have-been-logged-out = Você foi desconectado.
# a limit on the long edge of an image (eg 1024 pixels)
preferences-editing-max-image-size = Tamanho Máximo da Imagem (Borda Longa)
# whether to shrink images when pasting
preferences-editing-resize-on-paste = Redimensionar ao colar
# convert smart quotes and smart dashes to ASCII style
preferences-editing-convert-smart-quotes = Converter Citações e Travessões Inteligentes
preferences-editing-crop-camera-photos = Cortar Fotos da Câmera
preferences-loop-video = Vídeo em looping
preferences-show-video-controls = Mostrar controles do vídeo
preferences-high-quality-video = Vídeo de Alta Qualidade
preferences-auto-capitalize = Auto Capitalizar
preferences-auto-correct = Correção Automática
preferences-strip-hebrew-vowels = Remover Vogais Hebraicas
