preferences-about = Sobre
preferences-audio-buttons = Botões de áudio
preferences-auto-advance-do-nothing = Fazer Nada
preferences-auto-advance-wait-for-audio = Esperando pelo Áudio
preferences-backup-create-now = Criar Agora
preferences-backup-revert-to-backup = Reverter para a cópia de segurança
preferences-backup-reverted-to-backup = Revertido para a cópia de segurança.
preferences-button-d = Botão { $num }
preferences-collection-learn-ahead-minutes = Aprender além do limite (minutos)
preferences-collection-new-first = Novo primeiro
preferences-full-sync = Sincronização Completa
preferences-gamepad-menu-button = Menu
preferences-height = Altura
preferences-interrupt-current-audio = Interromper Áudio Atual
preferences-large = Grande
preferences-left = Esquerda
preferences-logged-in-as = Logado como:
preferences-normal = Normal
preferences-notifications = Notificações
preferences-notifications-alert-time = Horário de Alerta
preferences-notifications-alert-when-due = Alertar quando houver cartões pendentes
preferences-right = Direita
preferences-scratchpad-transparency-medium = Médio
preferences-scratchpad-transparency-none = Nenhum
preferences-small = Pequeno
preferences-sync-sounds-images = Sincronizar Sons & Imagens
preferences-syncing = Sincronizando
preferences-tap-to-sync = Para ativar a sincronização, toque no botão sincronizar na tela de lista de baralho.
preferences-theme = Tema
preferences-theme-bar-style = Estilo da Barra
preferences-theme-black = Preto
preferences-theme-dark = Escuro
preferences-theme-dark-translucent = Escuro & Translúcido
preferences-theme-night-mode-desc = O modo noturno escurece a interface e exibe os cartões em branco no preto.
preferences-when-answer-shown = Quando a resposta for mostrada
preferences-when-question-shown = Quando a pergunta for mostrada
preferences-you-have-been-logged-out = Você foi desconectado.
