profiles-a-profile-with-that-name-already = Um perfil com esse nome já existe.
profiles-add-profile = Adicionar Perfil
profiles-creating-backup = Criando cópia de segurança...
profiles-finishing-backup = Terminando cópia de segurança...
profiles-please-provide-some-text-avoiding-symbols = Forneça algum texto, evitando símbolos e sublinhados.
profiles-please-select-another-profile-first = Por favor, selecione outro perfil primeiro.
profiles-profile-name = Nome de perfil
profiles-rename-profile = Renomear Perfil
profiles-unable-to-open-safari-please = Não é possível abrir o Safari - verificar o controle dos pais.
profiles-welcome = Bem-vindo(a)!
