actions-actions = اعمال
actions-add-new = افزودن جدید
actions-added-to-frequent-actions = به اعمال مکرر اضافه شد.
actions-all-actions = همۀ اعمال
actions-already-in-frequent-actions = این عمل از قبل در لیست اعمال مکرر وجود دارد.
actions-an-error-occurred = خطایی رخ داد: { $error }
actions-answer-again = پاسخ دوباره
actions-answer-easy = پاسخ آسان
actions-answer-good = پاسخ خوب
actions-answer-hard = پاسخ سخت
actions-are-you-sure = مطمئنید؟
actions-auto-advance = پیشروی خودکار
actions-auto-advance-short = پیشروی خودکار
actions-bottom-bar = نوار پایین
actions-bottom-bar-short = نوار پایین
actions-browse = جستجو
actions-bury-card-short = دفن کارت
actions-bury-note-short = دفن یادداشت
actions-card-buried = کارت دفن شد
actions-card-info = مشخصات کارت
actions-card-info-short = مشخصات کارت
actions-card-suspended = کارت معلق شد
actions-card-template = قالب کارت
actions-confirm-delete = تأیید حذف
actions-create = ایجاد
actions-current-audio-minus-5s = -5 ثانیه از صدای فعلی
actions-current-audio-minus-5s-short = -5 ثانیه
actions-current-audio-plus-5s = +5 ثانیه به صدای فعلی
actions-current-audio-plus-5s-short = +5 ثانیه
actions-custom-study-cant-be-used-on = امکان مطالعۀ سفارشی دستۀ فیلتر شده وجود ندارد.
actions-custom-study-short = سفارشی
actions-deck-statistics = آمار دسته
actions-deck-statistics-short = آمار دسته
actions-delete-note-and-its-cards = حذف یادداشت و کارت‌هایش؟
actions-delete-note-short = حذف
actions-discard-changes = لغو تغییرات
actions-done = انجام شد
actions-downloading = در حال دانلود...
actions-drag-here-to-remove = برای زدودن به اینجا بکشید
actions-draw = رسم
actions-file-invalid-or-corrupt = فایل نامعتبر یا خراب است.
actions-filtercram = فیلتر/مطالعۀ با شتاب
actions-filtered-deck = دستۀ فیلتر شدۀ { $num }
actions-flag-1 = نشان 1
actions-flag-1-red = نشان 1 (قرمز)
actions-flag-2 = نشان 2
actions-flag-2-orange = نشان 2 (نارنجی)
actions-flag-3 = نشان 3
actions-flag-3-green = نشان 3 (سبز)
actions-flag-4 = نشان 4
actions-flag-4-blue = نشان 4 (آبی)
actions-forgot-card = کارت فراموش شده
actions-frequent-actions = اعمال مکرر
actions-how-many-days-in-the-future = چه تعداد روز آینده؟
actions-invalid-number-of-days = تعداد رو نامعتبر است.
actions-leave-without-saving = خروج بدون ذخیره؟
actions-long-press-on-an-item-to = برای شخصی‌سازی یک گزینه را برای مدت طولانی نگه دارید.
actions-mark = علامتگذاری
actions-mark-and-bury = علامت + دفن
actions-mark-and-bury-short = علامت و دفن
actions-mark-and-suspend = علامت + تعلیق
actions-mark-and-suspend-short = علامت و تعلیق
actions-marked = علامت زده شده
actions-night-mode-short = شب
actions-no-current-card = بدون کارت فعلی.
actions-no-load-restore-backup = بارگذاری مجموعۀ شما انجام نشد. لطفاً با استفاده از یکی از پشتیبان‌های خودکار در صفحۀ تنظیمات مجموعه را بازنشانی کنید.
actions-not-valid-link = لینک نامعتبر.
actions-note-and-its-cards-deleted = یادداشت و { $count } کارت آن حذف شدند
actions-note-and-its-cards-suspended = یادداشت و { $count } کارت آن معلق شدند
actions-note-buried = یادداشت دفن شد
actions-note-marked-and-buried = یادداشت علامت‌گذاری و دفن شد
actions-nothing-to-undo = عملی برای لغو وجود ندارد
actions-off = خاموش
actions-pause-audio-short = مکث
actions-please-tap-the-in-the = لطفاً روی '؟' در گوشۀ چپ بالا بزنید تا راهنما باز شود.
actions-processing = در حال پردازش...
actions-record-voice = ضبط صدا
actions-record-voice-short = ضبط
actions-replay-audio-short = پخش مجدد
actions-reset-card = بازنشانی کارت
actions-reset-card-short = بازنشانی کارت
actions-revert = برگرداندن
actions-review-undone = مرور لغو شد
actions-scratchpad = چرکنویس
actions-scratchpad-short = چرکنویس
actions-scratchpad-size = اندازۀ چرکنویس
actions-scratchpad-size-short = اندازۀ چرکنویس
actions-select-deck = انتخاب دسته
actions-select-note-type = انتخاب نوع یادداشت
actions-set-due-date-short = تنظیم موعد مرور
actions-show-answer-short = نمایش پاسخ
actions-show-answeranswer-good = نمایش پاسخ/پاسخ خوب
actions-show-answeranswer-good-short = نمایش/خوب
actions-study-options = تنظیمات مطالعه
actions-study-options-short = تنظیمات مطالعه
actions-suspend-card-short = تعلیق کارت
actions-suspend-note-short = تعلق یادداشت
actions-tools = ابزارها
actions-tools-overlay = زمینۀ ابزارها
actions-top-bar = نوار بالا
actions-unbury-deck = لغو دفن دسته
actions-unbury-deck-short = لغو دفن
actions-undo = لغو عمل
actions-unmarked = علامت پاک شد
actions-you-can-only-empty-a-filtered = خالی کردن فقط برای دسته‌های فیلتر شده ممکن است.
actions-you-can-only-rebuild-a-filtered = امکان بازسازی فقط برای دسته‌های فیلتر شده ممکن است.
