actions-actions = اقدامات
actions-add-new = افزودن جدید
actions-added-to-frequent-actions = به اعمال مکرر اضافه شد.
actions-all-actions = همۀ اعمال
actions-already-in-frequent-actions = این عمل از قبل در لیست اعمال مکرر وجود دارد.
actions-an-error-occurred = خطایی رخ داد: { $error }
actions-answer-easy = پاسخ آسان
actions-are-you-sure = مطمئنید؟
actions-bottom-bar = نوار پایین
actions-browse = جستجو
actions-card-buried = کارت دفن شد
actions-card-suspended = کارت معلق شد
actions-card-template = قالب کارت
actions-confirm-delete = تأیید حذف
actions-create = ایجاد
actions-current-audio-minus-5s = -5 ثانیه از صدای فعلی
actions-current-audio-plus-5s = +5 ثانیه به صدای فعلی
actions-custom-study-cant-be-used-on = امکان مطالعۀ سفارشی دستۀ فیلتر شده وجود ندارد.
actions-deck-statistics = آمار دسته
actions-delete-note-and-its-cards = حذف یادداشت و کارت‌هایش؟
actions-discard-changes = لغو تغییرات
actions-done = انجام شد
actions-downloading = در حال دانلود...
actions-drag-here-to-remove = برای زدودن به اینجا بکشید
actions-draw = رسم
actions-file-invalid-or-corrupt = فایل نامعتبر یا خراب است.
actions-filtercram = فیلتر/مطالعۀ با شتاب
actions-filtered-deck = دستۀ فیلتر شدۀ { $num }
actions-frequent-actions = اعمال مکرر
actions-leave-without-saving = خروج بدون ذخیره؟
actions-long-press-on-an-item-to = برای شخصی‌سازی یک گزینه را برای مدت طولانی نگه دارید.
actions-mark = علامتگذاری
actions-mark-and-bury = علامت + دفن
actions-mark-and-suspend = علامت + تعلیق
actions-marked = علامت زده شده
actions-no-current-card = بدون کارت فعلی.
actions-no-load-restore-backup = بارگذاری مجموعۀ شما انجام نشد. لطفاً با استفاده از یکی از پشتیبان‌های خودکار در صفحۀ تنظیمات مجموعه را بازنشانی کنید.
# (http://example.com) does not appear to be...
actions-not-valid-link = لینک نامعتبر.
actions-note-and-its-cards-deleted = یادداشت و { $count } کارت آن حذف شدند
actions-note-and-its-cards-suspended = یادداشت و { $count } کارت آن معلق شدند
actions-note-buried = یادداشت دفن شد
actions-note-marked-and-buried = یادداشت علامت‌گذاری و دفن شد
actions-off = خاموش
actions-please-tap-the-in-the = لطفاً روی '؟' در گوشۀ چپ بالا بزنید تا راهنما باز شود.
actions-record-voice = ضبط صدا
actions-record-voice-menu = منو ضبط صدا
actions-reset-card = بازنشانی کارت
actions-revert = برگرداندن
actions-review-undone = مرور لغو شد
actions-scratchpad = چرکنویس
actions-scratchpad-size = اندازۀ چرکنویس
actions-select-deck = انتخاب دسته
actions-select-note-type = انتخاب نوع یادداشت
actions-show-answeranswer-good = نمایش پاسخ/پاسخ خوب
actions-study-options = تنظیمات مطالعه
actions-tools = ابزارها
actions-tools-overlay = زمینۀ ابزارها
actions-top-bar = نوار بالا
actions-unbury-deck = نمایش دوبارهٔ دسته
actions-undo = لغو عمل
actions-unmarked = علامت پاک شد
actions-you-can-only-empty-a-filtered = خالی کردن فقط برای دسته‌های فیلتر شده ممکن است.
actions-you-can-only-rebuild-a-filtered = امکان بازسازی فقط برای دسته‌های فیلتر شده ممکن است.
actions-scroll-up = رفتن به بالا
actions-scroll-down = رفتن به پایین

## Short actions. These will be shown in the top bar, and should be kept to about
## 5-7 characters where possible.

# empty filtered deck
actions-empty-short = خالی
# create a filtered deck
actions-filter-short = فیلتر
actions-add-short = افزودن
actions-answer-again-short = دوباره
actions-answer-easy-short = آسان
actions-answer-good-short = خوب
actions-answer-hard-short = سخت
actions-auto-advance-short = پیشروی خودکار
actions-bottom-bar-short = نوار پایین
actions-browse-short = جستجو
actions-bury-card-short = دفن کارت
actions-bury-note-short = دفن یادداشت
actions-card-info-short = مشخصات کارت
actions-card-template-short = قالب
actions-current-audio-minus-5s-short = -5 ثانیه
actions-current-audio-plus-5s-short = +5 ثانیه
actions-custom-study-short = سفارشی
actions-deck-statistics-short = آمار دسته
actions-decks-short = دسته‌ها
actions-delete-note-short = حذف
actions-edit-short = ویرایش
actions-mark-and-bury-short = علامت و دفن
actions-mark-and-suspend-short = علامت و تعلیق
actions-mark-short = علامتگذاری
actions-night-mode-short = شب
actions-off-short = غیرفعال
actions-pause-audio-short = مکث
actions-rebuild-short = بازسازی
actions-record-voice-short = ضبط
actions-replay-voice-short = Repl.V
actions-replay-audio-short = پخش مجدد
actions-reset-card-short = بازنشانی کارت
actions-scratchpad-short = چرکنویس
actions-scratchpad-size-short = اندازۀ چرکنویس
actions-set-due-date-short = تنظیم موعد مرور
actions-show-answer-short = نمایش پاسخ
actions-show-answeranswer-good-short = نمایش/خوب
actions-study-options-short = تنظیمات مطالعه
actions-suspend-card-short = تعلیق کارت
actions-suspend-note-short = تعلق یادداشت
actions-tools-short = ابزارها
actions-top-bar-short = نواره بالا
actions-unbury-deck-short = نمایش
actions-undo-short = برگرداندن
actions-redo-short = انجام دوباره
actions-scroll-up-short = بالا
actions-scroll-down-short = پایین
actions-back = پشت
