browsing-append = الحاق
browsing-append-negated = الحاق معکوس
browsing-card-updated = کارت به‌روز شد
browsing-change-flag = تغییر نشان
browsing-clear-flag = پا کردن نشان
browsing-column-1 = ستون 1
browsing-column-2 = ستون 2
browsing-confirm-reset = تأیید بازنشانی
browsing-dd-selected = %d از %d انتخاب شد
browsing-due-dateorder = موعد مرور
browsing-due-reviews = مرور‌های بعدی
browsing-learning-cards = کارت‌های مرحلۀ یادگیری
browsing-no-cards-are-selected = هیچ کارتی انتخاب نشده است.
browsing-note-created = یادداشت ساخته شد
browsing-note-updated = یادداشت به‌روز شد
browsing-note2 = یادداشت:
browsing-questionandanswer = سوال+پاسخ
browsing-repetitions = تکرارها
browsing-reset-cards = بازنشانی کارت‌ها
browsing-searching = در حال جستجو...
browsing-second-column-19 = ستون دوم (1 -> 9)
browsing-second-column-91 = ستون دوم (9 -> 1)
browsing-select-all = انتخاب همه
browsing-sort = ترتیب:
browsing-sort-order = ترتیب نمایش
browsing-tag = برچسب:
