custom-study-any-tag = هرکدام
custom-study-available = %@ در دسترس
custom-study-cant-extend-limits-no-extra = حد قابل افزایش نیست - کارتی در دسترس نیست.
custom-study-cram-seen-cards-with-certain-tags = کارت‌های شتاب‌زده دارای برچسب‌های خاص
custom-study-days-to-look-ahead = تعداد روزهای بعدی
custom-study-days-to-look-back = تعداد روز‌های قبلی
custom-study-exclude-cards-with-tag = مستنثی کردن کارت‌های دارای برچسب
custom-study-extra-new-cards = کارت‌های جدید اضافی
custom-study-extra-review-cards = مرور‌های اضافی
custom-study-include-cards-with-tag = شامل کردن کارت‌های دارای برچسب
custom-study-learn-new-cards-with-certain-tags = یادگیری کارت‌های جدید دارای برچسب‌های خاص
custom-study-loading = درحال بارگذاری...
custom-study-max-cards-to-gather = حداکثر تعداد کارت‌ها
custom-study-no-tags = هیچکدام
custom-study-no-tags-available = برچسبی در دسترس نیست
custom-study-preview-all-cards-with-certain-tags = پیش‌نمایش همۀ کارت‌های دارای برچسب‌های خاص
custom-study-review-due-cards-with-certain-tags = مرور کارت‌های دارای برچسب‌های خاص
custom-study-search-matches = جستجوی مشابهات %@
custom-study-study-type = نوع مطالعه
custom-study-the-selected-options-did-not-match = گزینه‌های انتخابی با هیچ کارتی هم‌خوانی ندارد.
