deck-options-add-options-group = افزودن گروه اختیارات
deck-options-answer-time-cap = حداکثر زمان پاسخ
deck-options-bury-related-new-cards = دفن کارت‌های مرتبط جدید
deck-options-bury-related-reviews = دفن مرور‌های مرتبط
deck-options-defaults = پیش فرض‌ها
deck-options-delete-options-full-sync = حذف این گروه اختیارات در همگام‌سازی بعدی از یکسان‌سازی هر تغییری روی دستگاه‌های دیگر جلوگیری خواهد کرد. ادامه؟
deck-options-display-in-order-added = نمایش به ترتیبی که اضافه شده‌اند
deck-options-display-in-random-order = نمایش به‌صورت تصادفی
deck-options-full-sync-required = همگام‌سازی کامل لازم است
deck-options-group-name = نام گروه
deck-options-max-new-per-day = حداکثر تعداد کارت تازه در روز
deck-options-max-reviews-per-day = حداکثر تعداد مرور در روز
deck-options-new-cards = کارت‌های جدید
deck-options-options-group = گروه اختیارات
deck-options-replay-q-audio-in-answer = پخش صوت سوال در قسمت پاسخ
deck-options-reset-all-settings-to-defaults = بازنشانی همۀ تنظیمات به حالت پیش‌فرض؟
deck-options-restore-defaults = بازنشانی به پیش‌فرض
deck-options-steps = مراحل
