decks-a-deck-must-be-provided = یک دسته باید انتخاب شود.
decks-a-deck-named-already-exists = دسته‌ای با نام '{ $name }' از قبل وجود دارد.
decks-a-deck-with-that-name-already = دسته‌ای با این نام از قبل وجود دارد.
decks-add-deck = افزودن دسته
decks-add-empty-deck = افزودن دستۀ خالی
decks-addexport = افزودن/صادر کردن
decks-cannot-delete = غیرقابل حذف
decks-card-limit = حد کارت
decks-cards-in-a-filtered-deck-cant = امکان انتقال کارت‌های یک دستۀ فیلتر شده وجود ندارد.
decks-custom-steps = قدم‌های سفارشی
decks-deck-exists = دسته وجود دارد
decks-deck-label = دسته:
decks-deck-name = نام دسته
decks-deck-options = تنظیمات دسته
decks-download-link = لینک دانلود
decks-export-collection = صدور مجموعه
decks-filtered-deck = دستۀ فیلتر شده
decks-import-from-itunes = وارد کردن از iTunes
decks-invalid-deck-name = نام دسته نامعتبر است.
decks-link-to-apkg-file-to-import = لینک فایل .apkg برای وارد کردن:
decks-no-matches = موردی یافت نشد
decks-return-by-delete = برای بازگردانی همۀ کارت‌ها به‌صورت یکجا، روی دستۀ آبی در لیست دسته‌ها بکشید، و آن را حذف کنید.
decks-shared-deck-list = لیست دسته‌های اشتراکی
decks-sync = همگام‌سازی
decks-synchronize = همگام‌سازی
decks-the-default-deck-cannot-be-deleted = امکان حذف دستۀ پیش‌فرض وجود ندارد.
decks-the-provided-deck-does-not-exist = دستۀ انتخابی وجود ندارد.
decks-the-search-you-provided-did-not = موردی با این مشخصات یافت نشد.
decks-will-be-returned = کارت‌ها بعد از پاسخ به دستۀ اصلی خود بازگردانده می‌شوند.
