editing-bold = بولد
editing-cancel-and-lose-any-unsaved-changes = لغو و از دست دادن همۀ تغییرات ذخیره نشده؟
editing-cant-edit-original-image-data = غیرقابل ویرایش - داده‌های تصویر اصلی یافت نشد.
editing-card-returned-to-new-card-queue = کارت به ردیف کارت‌های جدید بازگردانده شد.
editing-card-unsuspended = تعلیق کارت لغو شد
editing-from-camera = از دوربین
editing-from-file = از فایل
editing-from-photos = از عکس‌ها
editing-italic = کج
editing-next-cloze = جاخالی بعدی
editing-next-field = فیلد بعدی
editing-note-deleted = یادداشت حذف شد
editing-note-suspended = یادداشت معلق شد
editing-note-type-prompt = نوع:
editing-note-unsuspended = تعلیق کارت لغو شد
editing-same-cloze = همان جاخالی
editing-the-first-field-must-not-be = فیلد اول نباید خالی باشد.
editing-unable-to-obtain-image = فراهم کردن تصویر ممکن نیست
editing-unable-to-read-file = خواندن فایل ممکن نیست
editing-underline = زیر خط
editing-unexpected-file-extension = پسوند فایل نامعبتر:
editing-unexpected-rich-text-format-please = فرمت متن نامعتبر - لطفاً از کپی/پیست استفاده کنید.
editing-unexpected-status-code = کد وضعیت نامعتبر:
editing-unsuspend-card = لغو تعلیق کارت
editing-unsuspend-note = لغو تعلیق یادداشت
