preferences-about = درباره
preferences-always-duck-and-ignore-mute = انکار همیشه + چشم‌پوشی از بی‌صدا
preferences-answer-keeps-zoom = حفظ بزرگنمایی بعد از پاسخ
preferences-answer-side = اسلاید پاسخ
preferences-audio-buttons = دکمه‌های صدا
preferences-auto-advance-answer-action = اَعمال پاسخ
preferences-auto-advance-answer-seconds = ثانیه‌های پاسخ
preferences-auto-advance-auto-advance-to-start = برای شروع پیشروی خودکار، از گزینۀ 'پیشروی خودکار' استفاده کنید.
preferences-auto-advance-do-nothing = کاری نکن
preferences-auto-advance-question-seconds = ثانیه‌های سوال
preferences-auto-advance-show-reminder = نمایش یادآور
preferences-auto-advance-wait-for-audio = توقف برای صوت
preferences-backup-available-backups = پشتیبان‌های در دسترس
preferences-backup-create-now = ایجاد
preferences-backup-maximum-backups = حداکثر تعداد پشتیبان
preferences-backup-minutes-between-backups = وقفۀ بین پشتیبان‌ها (دقیقه)
preferences-backup-revert-to-backup = بازگردانی به پشتیبان
preferences-backup-revert-to-backup-confirm = بازگردانی به { $backup }؟ هر تغییری که بعد از پشتیبان‌گیری انجام گرفته است از دست خواهد رفت.
preferences-backup-reverted-to-backup = بازگردانی به پشتیبان انجام شد.
preferences-bottom-bar-size = اندازۀ نوار پایین
preferences-bottom-center = مرکز پایین
preferences-bottom-left = چپ پایین
preferences-bottom-right = راست پایین
preferences-button-d = دکمه { $num }
preferences-collection-day-starts = شروع روز
preferences-collection-learn-ahead-minutes = صرف نظر از زمان‌های یادگیری کمتر از
preferences-collection-mix = ترکیب
preferences-collection-new-first = تازه‌ها اول
preferences-collection-newreview-order = ترتیب کارت‌های مرور/تازه
preferences-collection-reviews-first = اول مرورها
preferences-double-tap-prevention = منع ضربۀ دوتایی
preferences-drawing-screen-ignores-fingers = کار نکردن انگشت روی صفحۀ رسم
preferences-feedback-ticks = تیک‌های بازخورد
preferences-fine = خوب
preferences-force-sync-confirm = همگام‌سازی یک‌طرفه اجباری؟ همۀ تغییرات در یک سمت از دست خواهد رفت.
preferences-full-sync = همگام‌سازی کامل
preferences-gamepad-button-mapping = شخصی‌سازی دکمه‌ها
preferences-gamepad-menu-button = منو
preferences-gamepads = صفحه‌های بازی
preferences-height = ارتفاع
preferences-huge = بسیار بزرگ
preferences-ignore-fingers = نادیده گرفتن انگشت‌ها
preferences-interrupt-current-audio = قطع صدای فعلی
preferences-large = بزرگ
preferences-left = چپ
preferences-left-shoulder = زمانبندی چپ
preferences-left-thumbstick-button = دکمۀ انگشت شست راست
preferences-left-trigger = کلید چپ
preferences-logged-in-as = وارد شده به عنوان:
preferences-long = طولانی
preferences-mid-center = وسط مرکز
preferences-mid-left = وسط چپ
preferences-mid-right = وسط راست
preferences-never-type-answer = هیچ وقت پاسخ را تایپ نکن
preferences-next-times = زمان‌های بعدی
preferences-normal = عادی
preferences-notifications = اعلان‌ها
preferences-notifications-alert-time = زمان هشدار
preferences-notifications-alert-when-due = هشدار هنگامی که بازۀ زمانی
preferences-notifications-app-icon-shows-due-count = نمایش تعداد مرورد بر روی آیکون برنامه
preferences-notifications-settings-app-enable-notifications = لطفاً به تنظیمات مراجعه کرده، آنکی را پیدا کرده، و اعلان‌ها، نشانک‌ها و هشدارها را برای آنکی فعال کنید.
preferences-pen-size = اندازۀ قلم
preferences-question-side = طرف سوال
preferences-remaining-count = تعداد باقی‌مانده
preferences-right = راست
preferences-right-shoulder = سمت راست
preferences-right-thumbstick-button = دکمۀ انگشت شست چپ
preferences-right-trigger = کلید راست
preferences-scratchpad-below-buttons = چرکنویس پایین دکمه‌ها
preferences-scratchpad-transparency = شفافیت چرکنویس
preferences-scratchpad-transparency-full = کامل
preferences-scratchpad-transparency-medium = متوسط
preferences-scratchpad-transparency-none = هیچکدام
preferences-scratchpad-transparency-slight = جزئی
preferences-shake-action = عملکرد تکان دادن
preferences-short = کوتاه
preferences-show-bottom-bar = نمایش نوار پایین
preferences-show-grid = نمایش خطوط راهنما
preferences-show-top-bar = نمایش نوار بالا
preferences-small = کوچک
preferences-swipe-down = کشیدن به پایین
preferences-swipe-left = کشیدن به چپ
preferences-swipe-right = کشیدن به راست
preferences-swipe-up = کشیدن به بالا
preferences-swipes = کشیدن‌ها
preferences-swipes-must-begin-from-the-far = کشیدن‌ها باید از از چپ‌ترین یا راست‌ترین نقطۀ صفحه شروع شوند.
preferences-sync-sounds-images = همگام‌سازی صدا‌ها و تصاویر
preferences-syncing = در حال همگام‌سازی
preferences-tap-to-sync = برای فعال‌سازی همگام‌سازی، بر روی دکمۀ همگام‌سازی در لیست دسته‌ها بزنید.
preferences-taps = ضربه‌ها
preferences-theme = طرح
preferences-theme-bar-style = سبک نوار
preferences-theme-black = سیاه
preferences-theme-dark = تاریک
preferences-theme-dark-translucent = تاریک و مات
preferences-theme-force-off = خاموشی اجباری
preferences-theme-force-on = روشن کردن اجباری
preferences-theme-light-translucent = روشن و مات
preferences-theme-night-mode-desc = حالت شب رابط کاربری را تیره می‌کند، و کارت‌ها را به‌صورت سفید روی سیاه نشان می‌دهد.
preferences-theme-night-mode-same-as-system = مثل دستگاه
preferences-theme-slate = لوح
preferences-thick = ضخیم
preferences-tools-overlay-button = دکمۀ زمینۀ ابزارها
preferences-tools-overlay-position = موقعیت زمینۀ ابزارها
preferences-top-center = مرکز بالا
preferences-top-left = چپ بالا
preferences-top-right = راست بالا
preferences-undo-clears-all = لغو عمل همه را پاک کند
preferences-when-answer-shown = هنگامی که پاسخ نشان داده شده
preferences-when-question-shown = هنگامی که سوال نشان داده شده
preferences-you-have-been-logged-out = شما خارج شدید.
