studying-answer-time-elapsed = زمان طی شدۀ پاسخ
studying-auto-advance-starting = شروع پیشروی خودکار
studying-auto-advance-stopped = پیشروی خودکار متوقف شد
studying-have-ready-to-study = شما %@ آماده مطالعه دارید.
studying-please-run-empty-cards-on-the = لطفاً در نسخۀ کامپیوتر از گزینۀ کارت‌های خالی استفاده کنید.
studying-replay-card = پخش مجدد کارت
studying-replay-voice = پخش کجدد صدا
studying-rescheduled-card = کارت‌های مجدداً زمان‌بندی شده.
studying-type-in-the-answer = تایپ کردن پاسخ
